### ISSUE TITLE
Trigger "HandshakeException: Connection terminated during handshake" error

### ISSUE THREAD

**Issue by bigbirdhzp** [shamblett/mqtt_client#101]
I use mqtt_client plugins to connect my mqtt server, with wss in flutter.I find the it trigger the "HandshakeException: Connection terminated during handshake" error.
Please help me.
![image](https://user-images.githubusercontent.com/22903159/62198411-26537680-b3b4-11e9-98ed-3f700a1eb68e.png)

**Comment by shamblett** [comment]
There could be many reasons for this, how are you initialising the client? What wss protocols are you using?

**Comment by bigbirdhzp** [comment]
I did not specify wss protocols.The test example i use this plugin example.Just add "client.usewebsocket = true", change broker and add ".authenticateAs" with my username and password

**Comment by shamblett** [comment]
OK, try this 

client .websocketProtocols = MqttWsConnection.protocolsSingleDefault;

you can also set it to a null list using [].

Some ws servers don't like more than one entry in the protocol header.
Failing this if you can get to your mqtt server logs they may shed light on whats happening.
