### ISSUE TITLE
MqttConnectPayload::Client id exceeds spec value of 23

### ISSUE THREAD

**Issue by bigbirdhzp** [shamblett/mqtt_client#102]
I try to connect mqtt server with tcp.Now I set the clientId is "1000/app/" + uuid.When I connect Server, the command tell me "MqttConnectPayload::Client id exceeds spec value of 23"
![image](https://user-images.githubusercontent.com/22903159/62612727-9163f680-b93a-11e9-8486-5212a8c91470.png)
Is the plugin limit the client ID length?
How can I undo the client ID length limit?

**Comment by bigbirdhzp** [comment]
Now I find the source code,you wirte the limit
![image](https://user-images.githubusercontent.com/22903159/62613379-ece2b400-b93b-11e9-8311-632927aee149.png)

**Comment by shamblett** [comment]
This is printed out purely as a warning that you are not in accordance with the MQTT specification which says the client id  should have a length of 23, its not enforced, you can have any length you want, its just logged.

**Comment by bigbirdhzp** [comment]
Thanks for your guidance，I will close this issue
