### ISSUE TITLE
fail to build in flutter 1.8.5

### ISSUE THREAD

**Issue by liaoweiguo** [shamblett/mqtt_client#103]
Compiler message:
../../.pub-cache/hosted/pub.flutter-io.cn/mqtt_client-5.5.3/lib/src/connectionhandling/mqtt_client_mqtt_ws2_connection.dart:11:7: Error: '_DetachedSocket' can't implement both 'Stream<List<int>>' and 'Stream<Uint8List>'
 - 'Stream' is from 'dart:async'.
 - 'List' is from 'dart:core'.
 - 'Uint8List' is from 'dart:typed_data'.
class _DetachedSocket extends Stream<List<int>> implements Socket {
      ^

**Comment by liaoweiguo** [comment]
Dart VM version: 2.5.0-dev.1.0.flutter-f29f41f1a5

**Comment by shamblett** [comment]
I'm no flutter expert but this looks like issue 99, which should only be for Dart 2.5.0 so I've not released the package yet. As a test you could replace your mqtt_client inclusion in your pubspec.yaml with 

mqtt_client:
    git: 
         url: https://github.com/shamblett/mqtt_client.git
         ref: development
this will pick up the change in my development branch and see if it works.

**Comment by Tumbler0809** [comment]
I also encountered the same problem.，How did you solve it?

**Comment by shamblett** [comment]
The fix(maybe!) is in my development branch as said above, you will have to pull this and try it.

**Comment by Tumbler0809** [comment]
Yes, the development branch has been resolved

**Comment by ali-mahdavi** [comment]
in pubspec.yaml file change :
mqtt_client: 5.4.4
to
mqtt_client: '<=5.0.0'
