### ISSUE TITLE
in android send message,disconnected immediately

### ISSUE THREAD

**Issue by zhaoxiafeigithub** [shamblett/mqtt_client#105]
I don't know why my client can send and receive mqtt messages normally on Apple devices, but on Android, once the message is sent, mqtt will disconnect, and it will probably be repeated many times before it can receive and receive messages normally once in a while.

**Comment by shamblett** [comment]
Your better asking this on an android/flutter list, it looks as though its an android/flutter environment problem, as you say the client is OK on ios and its also OK on the VM.
