### ISSUE TITLE
Is it possible to connect like "tcp://192.168.0.101"?

### ISSUE THREAD

**Issue by v2kb2l** [shamblett/mqtt_client#108]
Hi 
My server url format is like this "tcp://192.168.0.101".  In order to run in local hardware device also.

Is it possible to connect tcp like "tcp://192.168.0.101"? using this library. 

Thanks,
Vijay

**Comment by shamblett** [comment]
No I don't think so unless "tcp://192.168.0.101" resolves to an IP address, why can't you just use "192.168.0.101" ?

**Comment by v2kb2l** [comment]
I tried both ways but not connecting..., 
where as it is working in old project (Kotlin Android) Please see logs below:

 MQTT client connecting....
2019-08-16 14:25:39.966 19325-19363/ndonate./flutter: 2019-08-16 14:25:39.956419 -- SynchronousMqttConnectionHandler::internalConnect entered
2019-08-16 14:25:39.966 19325-19363/ndonate./flutter: 2019-08-16 14:25:39.966111 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 0
2019-08-16 14:25:39.966 19325-19363/ndonate./flutter: 2019-08-16 14:25:39.966700 -- SynchronousMqttConnectionHandler::internalConnect - websocket selected
2019-08-16 14:25:40.023 19325-19363/ndonate./flutter: mqtt-client::NoConnectionException: MqttWsConnection::The URI supplied for the WS has an incorrect scheme - 202.153.34.59
2019-08-16 14:25:40.025 19325-19363/ndonate./flutter: 2019-08-16 14:25:40.025517 -- SynchronousMqttConnectionHandler::disconnect
2019-08-16 14:25:40.031 19325-19363/ndonate./flutter: 2019-08-16 14:25:40.031665 -- MqttConnectionHandler::sendMessage - MQTTMessage of type MqttMessageType.disconnect
    Header: MessageType = MqttMessageType.disconnect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
2019-08-16 14:25:40.032 19325-19363/ndonate./flutter: 2019-08-16 14:25:40.032173 -- MqttConnectionHandler::sendMessage - not connected
2019-08-16 14:25:40.044 19325-19363/ndonate./flutter: MQTT client disconnected
2019-08-16 14:25:40.044 19325-19363/ndonate./flutter: MQTT client disconnected

**Comment by shamblett** [comment]
This line 

NoConnectionException: MqttWsConnection::The URI supplied for the WS has an incorrect scheme - 202.153.34.59

means you are trying to connect to a ws MQTT server, your url must start with 'ws://' or 'wss://'

**Comment by xhidnoda** [comment]
Hi, i get the error:
**The URI supplied for the WS has an incorrect scheme**

My ip has **wss://202.153.34.59**
Also test like this **ws://202.153.34.59**
Use mqtt_browser_client for web Flutter.
Use mqtt_client_client for iOS/Android Flutter with not ws:// or wss:// and work.
 
But the problem still, can you help me?

**Comment by shamblett** [comment]
If you look at the mqtt_server_client_websocket.dart example in the examples directory it uses test.mosquitto.org as the broker, if I use the IP address , i.e. do this -
```
MqttServerClient('ws://5.196.95.208', '');
```
it works fine. Are you saying you are just seeing this on the browser client only?

**Comment by xhidnoda** [comment]
This is my code for Web:

```
import 'package:mqtt_client/mqtt_client.dart';
import 'package:mqtt_client/mqtt_browser_client.dart';

class MqttConnection {
  String mBrokerUrl;
  String mClientId;
  String mUsername;
  String mPassword;
  String mUserPhoneId;
  String publishTopic;
  static MqttBrowserClient mClient;
  var uuid = new Uuid();

  MqttConnection(
      {this.mBrokerUrl,
      this.mClientId,
      this.mUsername,
      this.mPassword,
      this.publishTopic,
      this.mUserPhoneId});

  Future connectToMqtt() async {
    eventBus.on<PublishData>().listen((event) {
      publishTopic = event.topic;
      if (mClient.connectionStatus.state == MqttConnectionState.connected) {
        print(
            "PUBLISH REQUEST EN TÓPICO: ${event.topic}\n\n CON MENSAJE: ${event.jsonData}");

        print(
            'ESTADO OK mClient.connectionStatus.state ---------------------------------');
        print(mClient.connectionStatus.state);
        print(
            'ESTADO OK MqttConnectionState.connected ---------------------------------');
        print(MqttConnectionState.connected);

        MqttClientPayloadBuilder builder = MqttClientPayloadBuilder();
        builder.addString(event.jsonData);

        mClient.publishMessage(
            event.topic, MqttQos.exactlyOnce, builder.payload);
      } else {
        print(
            'ESTADO NOT OK mClient.connectionStatus.state ---------------------------------');
        print(mClient.connectionStatus.state);
        print(
            'ESTADO NOT OK MqttConnectionState.connected ---------------------------------');
        print(MqttConnectionState.connected);
        connectBroker();
      }

      //connectBroker();
    });

    connectBroker();
  }

  void connectBroker() {
    mUserPhoneId = uuid.v1();
    mClient = MqttBrowserClient(mBrokerUrl, mClientId);
    mClient.logging(on: true);
    mClient.keepAlivePeriod = 180;
    mClient.onConnected = onConnected;
    mClient.onDisconnected = onDisconnected;
    mClient.onSubscribed = onSubscribed;
    final MqttConnectMessage connMess = MqttConnectMessage()
        .withClientIdentifier(mClientId)
        .keepAliveFor(
            180) // Must agree with the keep alive set above or not set
        //.withWillTopic('willtopic') // If you set this you must set a will message
        //.withWillMessage('My Will message')
        .authenticateAs(mUsername, mPassword)
        //.startClean() // Non persistent session for testing
        .withWillQos(MqttQos.atMostOnce);
    mClient.connectionMessage = connMess;

    try {
      mClient.connect();
    } on Exception catch (e) {
      print(e.toString());
      mClient.disconnect();
    }
      ...
}
```

My connections:

```
if (!MqttConnection().connectionStatus()) {
          MqttConnection(
                  mUsername: ApiConnect.username,
                  mPassword: ApiConnect.password,
                  mBrokerUrl: ApiConnect.serverIp,
                  mClientId: deviceID.substring(0, 20))
              .connectToMqtt();
 }
```
Try this:
`serverIp = "wss://202.153.34.59";`
`serverIp = "ws://202.153.34.59";`

This exact code is for Android/iOS but, with the **mqtt_server_client.dart** and **serverIp = "202.153.34.59";**

The error still appearing :(

**Comment by shamblett** [comment]
Turn on logging on the client, and post it here,  at the top of the log it will print out the exact url string it is trying to connect with.

**Comment by xhidnoda** [comment]
Output:

```
MqttBrowserClient es: Instance of 'MqttBrowserClient'
2-2021-03-17 10:18:33.506 -- MqttConnectionHandlerBase::connect - server ws://202.153.34.59, port 1883
2-2021-03-17 10:18:33.507 -- SynchronousMqttBrowserConnectionHandler::internalConnect entered
2-2021-03-17 10:18:33.507 -- SynchronousMqttBrowserConnectionHandler::internalConnect - initiating connection try 0, auto reconnect in progress false
2-2021-03-17 10:18:33.507 -- SynchronousMqttBrowserConnectionHandler::internalConnect - calling connect
2-2021-03-17 10:18:33.508 -- MqttBrowserWsConnection::connect - entered
2-2021-03-17 10:18:33.509 -- MqttBrowserWsConnection::connect -  WS URL is ws://202.153.34.59:1883
2-2021-03-17 10:18:33.512 -- MqttBrowserWsConnection::connect - connection is waiting
2-2021-03-17 10:19:04.651 -- MqttBrowserWsConnection::connect - websocket has erred
```

And after a while...this log appear:

`Error: mqtt-client::NoConnectionException: The maximum allowed connection attempts ({3}) were exceeded. The broker is not responding to the connection`

**Comment by shamblett** [comment]
Your connection is failing -
```
2-2021-03-17 10:19:04.651 -- MqttBrowserWsConnection::connect - websocket has erred
```
Your URL looks OK -
```
2-2021-03-17 10:18:33.509 -- MqttBrowserWsConnection::connect -  WS URL is ws://202.153.34.59:1883
```
This is not the error you reported above which was 'The URI supplied for the WS has an incorrect scheme'

Your using the default port of 1883, most brokers don't use websockets on port 1883, its more normal to use 8080 or 8081, please check your port number or look at your broker logs to see why its refusing the connection.

**Comment by xhidnoda** [comment]
But this port 1883 works on iOS/Android, i have to manage other port for web?

**Comment by shamblett** [comment]
I don't know, usually the server side clients don't use websockets, 1883 is the standard MQTT port in this case, it could be different for websockets, the mosquitto test broker for example uses the following -
```
1883 : MQTT, unencrypted
8883 : MQTT, encrypted
8884 : MQTT, encrypted, client certificate required
8887 : MQTT, encrypted, server certificate deliberately expired
8080 : MQTT over WebSockets, unencrypted
8081 : MQTT over WebSockets, encrypted
```
This has nothing to do with the client, it doesn't matter if you use the browser client or the server client, you have to use whatever port your broker uses for websockets. Also check your broker logs.

**Comment by aytunch** [comment]
@shamblett I am stuck in the same place with OP. I know this is not related to the package but if you can help, that would be great.
In my iOS app, I use
```
MqttClient setup(String serverAddress, String uniqueID, int port) {
  return MqttServerClient.withPort(serverAddress, uniqueID, port)
    ..secure = true;
}
```
And in the web app, I use;
```
MqttClient setup(String serverAddress, String uniqueID, int port) {
  return MqttBrowserClient.withPort(serverAddress, uniqueID, port)
    ..websocketProtocols = MqttClientConstants.protocolsSingleDefault;  //don't know what this is. saw it in the issues
}
```
My question is why do we need to prepend `ws://` or `wss://` just for `MqttBrowserClient` and use the naked URI for `MqttServerClient`?

Does the server treat a web and mobile client differently? Why are the endpoints have to be different uris?

```
    _mqttClient = mqttsetup.setup(
      '${kIsWeb ? "wss://" : ""}${_configController.mqttHost}',
      clientId,
      _configController.mqttPort,
    );
```
`MQTT client disconnected, MqttDisconnectionOrigin.solicited`

**Comment by shamblett** [comment]
Your question -
```
My question is why do we need to prepend ws:// or wss:// just for MqttBrowserClient and use the naked URI for MqttServerClient?
```

Is imposed by the Dart HTML library API [websocket implementation](https://api.dart.dev/stable/2.19.2/dart-html/WebSocket-class.html) you have to prefix the url with ws or wss. If you don't do this you will get a scheme exception, this is raised by Dart, not the package. This is not the case with the Dart IO library API.

However you want to do this is up to you but you will have to do it somehow.
