### ISSUE TITLE
flutter: type '(MessageReceived) => void' is not a subtype of type '(dynamic) => void'

### ISSUE THREAD

**Issue by arden** [shamblett/mqtt_client#11]
when i'm use mqtt_client in flutter 0.4.4 beta version，and when call connect method, and there some errors:

flutter: type '(MessageReceived) => void' is not a subtype of type '(dynamic) => void'

**Comment by benbehringer** [comment]
had the same error. forked the repo and added a workaround (casting explicitly). you can get the fixed mqtt_client by adding the following lines to your pubspec.yaml:

  #mqtt_client: "^1.7.2"
  mqtt_client:
    git:
      url: https://github.com/benbehringer/mqtt_client.git

**Comment by shamblett** [comment]
Thanks, however I don't think 'casting' is supported in Dart 1, If I adopt this now it will only run in Dart 2(which includes Flutter), when Google finally release Dart 2 into production I'll update the code as you suggest, then I guess we need to somehow tell people up to what versions of a package are Dart 1, hopefully Google have a plan for this.

**Comment by fabricio-godoi** [comment]
Hello everyone,
Firstly, @benbehringer thank you for the workaround! It helped me a lot. There is any chance that you keeping this repository updated with the changes in the mainline?

I'm having the same issue with the version 1.9.0 of the mqtt_client. There is any way to correct this to support both dart1 and dart2?

Thank you,
Best regards!

**Comment by benbehringer** [comment]
@fabricio-godoi : updated with the changes in the mainline. Yet, required a quick workaround and thus you need to subscribe as follows:

`import 'package:observable/observable.dart' as observe;
import 'package:mqtt_client/mqtt_client.dart' as mqtt;

    final observe.ChangeNotifier<observe.ChangeRecord> cn = client.subscribe(topic, mqtt.MqttQos.exactlyOnce).observable;
    cn.changes.listen((List<observe.ChangeRecord> c) {
      mqtt.MqttReceivedMessage myMessage = c[0] as mqtt.MqttReceivedMessage;
      final mqtt.MqttPublishMessage recMess = myMessage.payload as mqtt.MqttPublishMessage;
      final String pt =
      mqtt.MqttPublishPayload.bytesToStringAsString(recMess.payload.message);
      print("EXAMPLE::Change notification:: payload is <$pt> for topic <$topic>");
    });
`

**Comment by shamblett** [comment]
Fixed under other issues, see latest client(3.2.1)
