### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by iCiki** [shamblett/mqtt_client#112]
Error: '_DetachedSocket' can't implement both 'Stream<List<int>>' and 'Stream<Uint8List>'
 - 'Stream' is from 'dart:async'.
 - 'List' is from 'dart:core'.
 - 'Uint8List' is from 'dart:typed_data'.
class _DetachedSocket extends Stream<List<int>> implements Socket {

**Comment by Ailoli** [comment]
I also encountered such a problem.

**Comment by Ailoli** [comment]
I have solved this problem, please switch to the development branch

**Comment by iCiki** [comment]
> I have solved this problem, please switch to the development branch

It took no effect.How it could be?
Contact me, Wechat: iXuqiangXiao
THX~

**Comment by Ailoli** [comment]
Did it quote it correctly?

**Comment by Ailoli** [comment]
> > I have solved this problem, please switch to the development branch
> 
> It took no effect.How it could be?
> Contact me, Wechat: iXuqiangXiao
> THX~

Did it quote it correctly?

**Comment by iCiki** [comment]
> > > I have solved this problem, please switch to the development branch
> > 
> > 
> > It took no effect.How it could be?
> > Contact me, Wechat: iXuqiangXiao
> > THX~
> 
> Did it quote it correctly?

看你主页，你是大陆的。
切换到开发环境，一样编译不过，同样的错误，所以我很好奇你是怎么通过的，如果可以，可以微信交流一下，ID：iXuqiangXiao

**Comment by kalkotekedar** [comment]
> I have solved this problem, please switch to the development branch

Switch to the development branch of mqtt clinet

**Comment by shamblett** [comment]
Updated in Release 5.4.4 of the client

**Comment by ali-mahdavi** [comment]
in pubspecs.yaml file 
change 
 mqtt_client:5.5.4
to
 mqtt_client: '<=5.0.0'
