### ISSUE TITLE
OS Error: nodename nor servname provided, or not known, errno = 8

### ISSUE THREAD

**Issue by dingzuhua** [shamblett/mqtt_client#114]
flutter: 2019-09-09 14:19:45.803731 -- MqttConnection::_onError - calling disconnected callback
flutter: SocketException: Failed host lookup: 'tls://172.16.0.28:8883' (OS Error: nodename nor servname provided, or not known, errno = 8)
flutter: ERROR: MQTT client connection failed - disconnecting, state is MqttConnectionState.faulted

**Comment by shamblett** [comment]
Remove the 'tls://' from the hostname, the client won't resolve this, if you need tls use the clients secure socket option.

**Comment by dingzuhua** [comment]
What is clients secure socket option？Any examples?

**Comment by dingzuhua** [comment]
How to set the InsecureSkipVerify?

**Comment by shamblett** [comment]
See the iot-core.dart file in the examples directory, or browse the API for the package on pub, you can only set what google allow you to set in the standard SecurityContext class.
