### ISSUE TITLE
Build Error - After updating to dart 2.5

### ISSUE THREAD

**Issue by larslundh** [shamblett/mqtt_client#116]
Hello,(I opened this issue too quickly...)
you can use development branch to avoid that error...
if you are a noob like me then refer to picture as to how to use development branch.
![import development branch](https://user-images.githubusercontent.com/40725321/64586235-cf4bb300-d3ef-11e9-9a87-ddc33cc8130f.png)

I am getting this error after updating dart to version 2.5

Error: '_DetachedSocket' can't implement both 'Stream<List<int>>' and 'Stream<Uint8List>'
 - 'Stream' is from 'dart:async'.
 - 'List' is from 'dart:core'.
 - 'Uint8List' is from 'dart:typed_data'.

I am certain it has to do with mqtt client.

Anybody else have this?
or solved this?
Kind Regards

**Comment by e-body** [comment]
I also met this problem,but no solution yet

**Comment by e-body** [comment]
Have you solved this problem?

**Comment by shamblett** [comment]
The latest client fixes this problem if it is the client please update
