### ISSUE TITLE
Get old state from mqtt when app is destroyed

### ISSUE THREAD

**Issue by guitar9** [shamblett/mqtt_client#119]
Hello first thank you for this beautiful library. 
I build a app where I can show a state of my lamp. I connect to mqtt broker when I start the app an subscripe to the topic light. When I close the app an open it again and and the state of the lamp changed when i closed the app. Everything works fine. But when I destroy the app and connect again to mqtt broker, I dont get the new state. Only when I publish a new message. The state of the lamp changes again. Sombody can help me?

**Comment by shamblett** [comment]
Ok, can you turn on logging and post the log from when you reconnect again, remember that when you have reconnected you have to subscribe again, when the client is destroyed it loses its subscriptions, you shouldn't have to publish anything though.

**Comment by guitar9** [comment]
I think it is because it tested it with flutter run. I think it is like a new application when I rerun the application. But when I build the apk I get the error permisson denied when I want to connec to mqtt server. Do you know why?

**Comment by guitar9** [comment]
I found the error. 
I must publish the message with retained on. I tested it with mqtt.fx.
Can I somehow publish the message with this library with retained on?

**Comment by shamblett** [comment]
There's a retain option flag on the publishMessage client method, set this to true when you publish. You can also reset the startClean() option on the connect message if you need it.
