### ISSUE TITLE
mqtt_client is support dart2 now, why doesn't support flutter 0.4.4 beta?

### ISSUE THREAD

**Issue by arden** [shamblett/mqtt_client#12]
mqtt_client is support dart2 now, why doesn't support flutter 0.4.4 beta?

**Comment by shamblett** [comment]
I'm not sure what you mean by 'mqtt-client support dart2 now', mqtt-client has had some updates to make it Dart2 ready but it is still a Dart1 package and will be until Google release a production version of Dart2. When that happens I'll update all my packages to Dart2. I don't want to do this now as things may change between now and whenever Dart2 is released and I don't want to do it twice. The pub page for mqtt_client gives the following analysis : 

_We analyzed this package on May 28, 2018, and provided a score, details, and suggestions below. Analysis was completed with status completed using:

Dart: 2.0.0-dev.58.0
pana: 0.11.3

Detected platforms: Flutter, other

Primary library: package:mqtt_client/mqtt_client.dart with components: io._

So it says no errors and that its flutter compatible. I suggest you refer this to the flutter guys. If it helps I've noticed that these errors seem to change as flutter is upgraded, maybe this will stop eventually.

**Comment by shamblett** [comment]
As far as I know the latest client(3.2.1) is now OK with flutter, refer to other maybe closed issues, the client has been updated to Dart 2.0
