### ISSUE TITLE
connecting to mqtt server permission denied (release.apk)

### ISSUE THREAD

**Issue by guitar9** [shamblett/mqtt_client#120]
When I want to connect to mqtt client with this library with flutter run or flutter build apk --debug, everything works fine. But when I build the release app with flutter build apk. I get error permission denied when I want to connect to Mqtt Broker. Somebody know why?

**Comment by shamblett** [comment]
This sounds like  a flutter problem, you may be better also posting on a flutter dev list.

**Comment by genovoxx** [comment]
Exactly experienced the same problem - when installing the debug APK, it works like a charme. I think this might be a permission setting problem?
