### ISSUE TITLE
mqtt5

### ISSUE THREAD

**Issue by uwejan** [shamblett/mqtt_client#123]
Is there any plans for implementing mqtt5, my use case will require user properties, which is added on mqtt5, i wonder if there is a plan for it, or is it already on dev repo which i can test?

**Comment by shamblett** [comment]
Nothing immediate but this does sound like an update the client will need, I'll have a look at the work involved and update this issue.

**Comment by uwejan** [comment]
Any update on this? Time frame maybe please.

**Comment by ffbfh** [comment]
Is there a time frame to bring this enhancement? Is there any dev version which I could test?
I'm working on a project where we need a mqtt client in flutter which supports protocol version 5.

**Comment by shamblett** [comment]
I am starting to look at this but there is no time frame as of yet

**Comment by shamblett** [comment]
OK, I think what I'll do is implement MQTT 5 in chunks rather than all at once, this will lower the time frame to a working albeit not fully compliant MQTT 5 client. beside the addition of message properties and the new message structure what other functionality do you need for a first release?

**Comment by ffbfh** [comment]
> OK, I think what I'll do is implement MQTT 5 in chunks rather than all at once, this will lower the time frame to a working albeit not fully compliant MQTT 5 client. beside the addition of message properties and the new message structure what other functionality do you need for a first release?

oh grat, that sounds really good.
I would say that the enhanced authentication would be great to have in a first release.
But I will check that in detail and will come back to this.

**Comment by ffbfh** [comment]
> > OK, I think what I'll do is implement MQTT 5 in chunks rather than all at once, this will lower the time frame to a working albeit not fully compliant MQTT 5 client. beside the addition of message properties and the new message structure what other functionality do you need for a first release?
> 
> oh grat, that sounds really good.
> I would say that the enhanced authentication would be great to have in a first release.
> But I will check that in detail and will come back to this.

I checked the needed featues for my project.
It would be great when the first release would have the enhanced authentication feature and also includes the two properties 'Authentication Method' and 'Authentication Data' from the MQTTv5 Standard (https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901027).

**Comment by shamblett** [comment]
Yep OK, I'll add the enhanced auth method, still can't give you a timeframe here but at least I've started and we have an end goal. If you want to keep an eye on things the updates will be in the mqtt5 branch

**Comment by shamblett** [comment]
OK, forget the branch idea, there's going to be a lot of change so for now I've made this its own client [here](https://github.com/shamblett/mqtt5_client). This allows me to develop more freely without worrying about breaking existing functionality and littering the code with class renames and 'if version ===' statements. In the long run it may stay like this with maybe the addition of a common support package for both clients.  Use this [issue](https://github.com/shamblett/mqtt5_client/issues/1) to track progress and raise concerns/suggestions etc.

**Comment by shamblett** [comment]
The mqtt5_client is now published at version 1.0.0, closing this issue.
