### ISSUE TITLE
Error: '_DetachedSocket' can't implement both 'Stream<Uint8List>' and 'Stream<List<int>>'

### ISSUE THREAD

**Issue by dingzuhua** [shamblett/mqtt_client#125]
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Compiler message:
    file:///Users/dingzuhua/.pub-cache/hosted/pub.flutter-io.cn/mqtt_client-5.5.4/lib/src/connectionhandling/mqtt_client_mqtt_ws2_connection.dart:11:7: Error: '_DetachedSocket' can't implement both 'Stream<Uint8List>' and 'Stream<List<int>>'
     - 'Stream' is from 'dart:async'.
     - 'Uint8List' is from 'dart:typed_data'.
     - 'List' is from 'dart:core'.
    class _DetachedSocket extends Stream<Uint8List> implements Socket {
      ^
    file:///Users/dingzuhua/.pub-cache/hosted/pub.flutter-io.cn/mqtt_client-5.5.4/lib/src/connectionhandling/mqtt_client_mqtt_ws2_connection.dart:204:35: Error: The argument type 'Null Function(Uint8List)' can't be assigned to the parameter type 'void Function(List<int>)'.
     - 'Uint8List' is from 'dart:typed_data'.
     - 'List' is from 'dart:core'.
    Try changing the type of the parameter, or casting the argument to 'void Function(List<int>)'.
        _subscription = socket.listen((Uint8List data) {
                                      ^
    Compiler failed on /Users/dingzuhua/go/src/code.izhaohu.com/dolphin/ecare/lib/main.dart
    Failed to package /Users/dingzuhua/go/src/code.izhaohu.com/dolphin/ecare.

**Comment by shamblett** [comment]
If you are using client 5.5.4 you need to use Dart 2.5, if you can't use Dart 2.5 you need to use client 5.5.3 as the changelog says.

**Comment by dingzuhua** [comment]
> If you are using client 5.5.4 you need to use Dart 2.5, if you can't use Dart 2.5 you need to use client 5.5.3 as the changelog says.

thank you
