### ISSUE TITLE
Unsubscribe fixed header is wrong

### ISSUE THREAD

**Issue by alvistar** [shamblett/mqtt_client#128]
Hi,
unless I missed something I found a bug in the unsubscribe fixed header.

I noticed that I got immediately disconnected from VerneMQ broker when unsubscribing and it was complaining with bad header. Mosquito was more tolerant it was ok.

After wiresharking a bit and looking at specs of MQTT 3.1.1 the fixed header of unsubscribe must always BE 
1 | 0 | 1 | 0 | 0 | 0 | 1 | 0
or 162 in decimal.

The specification requires to disconnect a client with bad header.

I patched the code as quick fix and I will ask a pull request

**Comment by shamblett** [comment]
In the MQTT 3.1 spec the bits 3,2,1,0 of the Unsubscribe header are marked as reserved and as you say must be set to 0,0,1,0, however in the 3.1 spec these are the DUP flag(set to 0), the Qos level(set to 0,1) and the RETAIN flag which is marked as Not Used, so we need to check the version the client has been set to before forcing, or maybe if we can force the QOS to 01 and set the retain to 0, as its not used it shouldn't matter.

**Comment by alvistar** [comment]
Perhaps checking version protocol would be the best, is one line of code more and I don't see drawbacks.

**Comment by shamblett** [comment]
Client updated as per comment on associated pull request, re-published at 5.6.1
