### ISSUE TITLE
setting a secure connection to broker (question)

### ISSUE THREAD

**Issue by madtocc** [shamblett/mqtt_client#13]
Hi,
I'm trying to make a secure connection to my broker, but I'm not being able to establish a connection to my server. Usually I need to set it up through my client certificate, my client key and the CA cert. Can you give me a direction on how can achieve it? Thank you!

**Comment by shamblett** [comment]
Hi,
Have look at the iot_core.dart file in the examples directory, this shows you how to set up your trusted cert path along with your key file path and passphrase. You can also set a certificate chain path if needed.

Note these parameters are simply passed to the secure socket implementation in Dart, for more information on what these mean in the security layer go [here](https://api.dartlang.org/stable/1.24.3/dart-io/SecurityContext-class.html).

**Comment by shamblett** [comment]
Closing this as no further comments received.
