### ISSUE TITLE
Connect Google IOT mqtt demo

### ISSUE THREAD

**Issue by bhagujava** [shamblett/mqtt_client#136]
I am newbie on google IOT. do you have any documentation to connect Google IOT mqtt client using private key and pem file ?. I tried [https://github.com/BitKnitting/flutter_adafruit_mqtt](https://github.com/BitKnitting/flutter_adafruit_mqtt ) but it has half information and the jsonfile expecting username and key which i don't have.

I have folowing params to connect
1) private key
2) client_id
3) client_x509_cert_url
4) auth_provider_x509_cert_url
5) auth_uri
6) private_key_id
7) project_id

as long as i know mqtt is protocol which follows the certain standard. Looking for to connect mqtt client using above parameter.

**Comment by DhavalRKansara** [comment]
I am also facing the same issue.

**Comment by shamblett** [comment]
Ok, yes I have some examples, I use Googles cloud IOT core and have sent some sensor data to it using the client, your first port of call is the iot_core.dart file in the examples directory of the client, this shows what you need to do to connect to IOT core, there's also [this](https://github.com/shamblett/iot-home) project I've put together, this does the same thing but is a bit more real in that it generates the JWT token, connects to IOT core and sends some data, there's a write up for it [here](https://medium.com/@stevehamblett/dart-in-the-iot-world-a-practical-example-601f036212c7).

**Comment by bhagujava** [comment]
> Ok, yes I have some examples, I use Googles cloud IOT core and have sent some sensor data to it using the client, your first port of call is the iot_core.dart file in the examples directory of the client, this shows what you need to do to connect to IOT core, there's also [this](https://github.com/shamblett/iot-home) project I've put together, this does the same thing but is a bit more real in that it generates the JWT token, connects to IOT core and sends some data, there's a write up for it [here](https://medium.com/@stevehamblett/dart-in-the-iot-world-a-practical-example-601f036212c7).

@shamblett Thanks for reply. I have seen your code but sound confused me. I am looking  straightforward integration with the parameter which i have mentioned above. In your example there is no such parameter mentioned. am i in right direction ?

**Comment by shamblett** [comment]
I take it you have looked [here](https://cloud.google.com/iot/docs/how-tos/mqtt-bridge), which explains how google says you should connect to its MQTT service, which is basically what the iot-home project does.

**Comment by bhagujava** [comment]
@shamblett Thanks for your prompt reply.... 
````

  final MqttConnectMessage connMess = MqttConnectMessage()
      .withClientIdentifier('Mqtt_MyClientUniqueId')
      .keepAliveFor(20) // Must agree with the keep alive set above or not set
      .withWillTopic('willtopic') // If you set this you must set a will message
      .withWillMessage('My Will message')
      .startClean() // Non persistent session for testing
      .withWillQos(MqttQos.atLeastOnce);
  print('EXAMPLE::Mosquitto client connecting....');
  client.connectionMessage = connMess;

  /// Connect the client, any errors here are communicated by raising of the appropriate exception. Note
  /// in some circumstances the broker will just disconnect us, see the spec about this, we however eill
  /// never send malformed messages.
  try {
    await client.connect();
  } on Exception catch (e) {
    print('EXAMPLE::client exception - $e');
    client.disconnect();
  }

```` 

This is the snapshot which i have observed to connect from the lib but as per  [link](https://cloud.google.com/iot/docs/how-tos/mqtt-bridge) which you have shared has  expose some parameters which is ...


````

const connectionArgs = {
  host: mqttBridgeHostname,
  port: mqttBridgePort,
  clientId: mqttClientId,
  username: 'unused',
  password: createJwt(projectId, privateKeyFile, algorithm),
  protocol: 'mqtts',
  secureProtocol: 'TLSv1_2_method',
};

// Create a client, and connect to the Google MQTT bridge.
const iatTime = parseInt(Date.now() / 1000);
const client = mqtt.connect(connectionArgs);


````


Do we have such way to expose and assign value in same way the node.js did ?

**Comment by shamblett** [comment]
You don't need all the values above, the protocol and secureprotocol options don't exist in Dart/mqtt-client, the iot-core.dart file shows you how to do all this in Dart world, there's no direct mapping from nodejs, its done slightly differently. What part of the iot-core.dart example are you having trouble with? You should be able to edit the file and substitute your specific parameters such as projectId etc.
