### ISSUE TITLE
Mqtt publish issue

### ISSUE THREAD

**Issue by devUsama** [shamblett/mqtt_client#137]
Iam facing issue to publish message.
Right after connection with mqtt broker, message publish successfully, but if i try to publish any message after sometime of connection with broker it fails to publish any message, may be it get disconnected from broker.
I tested on both secured and unsecured tcp ports, but getting the same issue.

**Comment by shamblett** [comment]
You need to turn on logging and post the output so I can see whats happening, ta.

**Comment by devUsama** [comment]
You want to see the output when i publish any message? or the complete output right after connection with broker?

**Comment by shamblett** [comment]
Complete output please up to the point of disconnection.

**Comment by devUsama** [comment]
Sure, i will upload the complete output i a while. The attached output is at the point of publishing the message i debug using breakpoints.
Code snapshot:
![Code ](https://user-images.githubusercontent.com/57903749/69125609-01e8ea80-0ac8-11ea-9468-7953a08a7c1a.png)

Output snapshot when try to publish the message:
![Output](https://user-images.githubusercontent.com/57903749/69125711-47a5b300-0ac8-11ea-8bf1-389e11360b42.png)

**Comment by devUsama** [comment]
Complete output in sequence, kindly review it.

![output1](https://user-images.githubusercontent.com/57903749/69127923-0e237680-0acd-11ea-8a2c-b0d63c19c395.png)
![output2](https://user-images.githubusercontent.com/57903749/69127954-209db000-0acd-11ea-87dc-3299c0a92e70.png)
![out3](https://user-images.githubusercontent.com/57903749/69128332-de28a300-0acd-11ea-8afe-a302f02a608e.png)
![Output4](https://user-images.githubusercontent.com/57903749/69128375-f8fb1780-0acd-11ea-8a37-6b796d5eaee3.png)

**Comment by shamblett** [comment]
Seemingly at 12:48:23.591978 the client logged a disconnection, yet the very next message sent was a subscription, followed by another subscription, both were acked, then a publish was received, which we acked, we then published a message which was acked at 12:48:24.771967 we then go into a ping/pong sequence. I can't see any other attempt to publish from our side.

So I'm not sure why you think you are disconnecting on publish, I can't however explain the disconnect logging earlier.

**Comment by devUsama** [comment]
Its not publishing any message to broker.
As  i mentioned earlier whenever i try to publish the message the message my code dont go into this if body where the publish method is called. I verified it by debugging using breakpoints
![Code ](https://user-images.githubusercontent.com/57903749/69216634-80a85b00-0b8e-11ea-9b0d-55bb64f8195c.png)
At that point my console output is this and you can see connection state is **null**.
![Output](https://user-images.githubusercontent.com/57903749/69216848-03311a80-0b8f-11ea-908f-11cbb9452071.png)

**Comment by shamblett** [comment]
You don't show how you set the connection state, you should be using connectionStatus now, what version of the client are you using?

**Comment by devUsama** [comment]
**Iam using version:   mqtt_client: ^5.6.0**

**Here is the complete code to having all the methods,** Iam calling the publish method in another dart file
import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:iot_core/Dashboard.dart';
import 'package:iot_core/HomePage.dart';
import 'package:mqtt_client/mqtt_client.dart' as mqtt;
import 'package:mqtt_client/mqtt_client.dart';
import 'package:http/http.dart' as http;
import 'DBHelper.dart';
import 'Urls_for_APIs.dart';
import 'package:logger/logger.dart';

class mqtt_connection extends StatefulWidget {
  static var temprature;
  String broker = Mqtt_Broker_URL;
  int port = 8883;

  String username = Broker_user_name;
  String passwd = Broker_password;
  String clientIdentifier = 'android';
  mqtt.MqttClient client;
  mqtt.MqttConnectionState connectionState;
  StreamSubscription subscription;

  List<Devices_data> devices = [];

  String dev_to_subs;
  var logger = Logger();

  void publishToTopic(String topic, String message) {
    final MqttClientPayloadBuilder builder = MqttClientPayloadBuilder();
    builder.addString(message);
    //  print(connectionState);

    logger.d(connectionState);

    // client.publishMessage(topic, mqtt.MqttQos.exactlyOnce, builder.payload);

    if (connectionState == mqtt.MqttConnectionState.connected) {
      client.publishMessage(topic, mqtt.MqttQos.exactlyOnce, builder.payload);
      // print('published');
    }
  }

  void _disconnect() {
    client.disconnect();
    _onDisconnected();
  }

  void _onDisconnected() {
    connectionState = client.connectionState;
    client = null;
    subscription.cancel();
    subscription = null;
    print('MQTT client disconnected');
  }

  void connect() async {
    client = mqtt.MqttClient(broker, '');
    client.port = port;
    client.logging(on: true);
    client.keepAlivePeriod = 30;
    client.secure = true;
    // client.useWebSocket = true;

    logger.d("Connection type:", client.secure);
    client.onDisconnected = _onDisconnected;

    final mqtt.MqttConnectMessage connMess = mqtt.MqttConnectMessage()
        .withClientIdentifier(clientIdentifier)
        .startClean() // Non persistent session for testing
        .keepAliveFor(30)
        .withWillQos(mqtt.MqttQos.atMostOnce);
    client.connectionMessage = connMess;

    try {
      await client.connect(username, passwd); //username, passwd
      print(
          '\n************************************connected************************************\n');
    } catch (e) {
      logger.e(e);
      _disconnect();
    }

    if (client.connectionState == mqtt.MqttConnectionState.connected) {
      connectionState = client.connectionState;
      logger.d(connectionState);

    } else {
      _disconnect();
    }

    subscription = client.updates.listen(onMessage);
  }

  void subscribeToTopic(String topic) {
    if (connectionState == mqtt.MqttConnectionState.connected) {
      logger.d(client.subscribe(topic, mqtt.MqttQos.exactlyOnce));
    }
  }

  List status = new List();
  List dev_serial = new List();

  // List<Device_status_list> deviceStatusList;

  void onMessage(List<mqtt.MqttReceivedMessage> event) {
    final mqtt.MqttPublishMessage recMess =
        event[0].payload as mqtt.MqttPublishMessage;

    message_from_mqtt =
        mqtt.MqttPublishPayload.bytesToStringAsString(recMess.payload.message);

    if (message_from_mqtt != null) {
      for (var i = 0; i < devices.length; i++) {
        if (event[0].topic ==
            'd/' + devices[i].device_id.toString() + '/status') {
          var raw_data = json.decode(message_from_mqtt);

          var dev_status = raw_data["status"];
        }
      }

      for (var i = 0; i < devices.length; i++) {
        if (event[0].topic ==
            'd/' + devices[i].device_id.toString() + '/gs/set') {
          var raw_data = json.decode(message_from_mqtt);

          temprature = raw_data['t'];

          print(temprature);
        }
      }
    }
  }

  @override
  _mqtt_connectionState createState() => _mqtt_connectionState();
}

class _mqtt_connectionState extends State<mqtt_connection> {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

**Comment by devUsama** [comment]
**Iam using version: mqtt_client: ^5.6.0

Here is the complete code file having all the methods and connection initiating, Iam calling the publish method of this file in another dart file**
[code.txt](https://github.com/shamblett/mqtt_client/files/3869456/code.txt)

**Comment by shamblett** [comment]
OK, don't use connectionState its deprecated as the API docs say, 
```
 if (client.connectionState == mqtt.MqttConnectionState.connected) {
      connectionState = client.connectionState;
      logger.d(connectionState);
    } else {
```

Use the MqttClientConnectionStatus getter instead, see if that makes a difference.

**Comment by devUsama** [comment]
Thank you man for your response, I tried that solution but getting the same results.
Connection state is again null at this point:

![code](https://user-images.githubusercontent.com/57903749/69314556-47d3b900-0c56-11ea-8f87-94484ef5eec4.png)

Here is the code file attached i tried what you told me. Thanks again for your cooperation, kindly guide me to get out of this problem. 
[Code (1).txt](https://github.com/shamblett/mqtt_client/files/3873241/Code.1.txt)

**Comment by shamblett** [comment]
OK, so it looks as though its is disconnected, going back to my previous comment above('Seemingly at 12:48:23.591978 the client logged a disconnection,......') did you find out why this occurred?

**Comment by devUsama** [comment]
No, i couldn't find out the reason that why the client disconnected itself. I am looking for your help in this issue.I think there is no such thing from my side in code that made the client disconnected.

**Comment by shamblett** [comment]
The client can disconnect if the broker disconnects it for any reason, you need to get your broker logs and see if it says why it disconnected the client at that time.

**Comment by devUsama** [comment]
OK i'll find the reason, it seems like after the disconnection from broker publish is not working but if i publish any message before client get disconnected then it works fine

**Comment by shamblett** [comment]
No further updates, closing.
