### ISSUE TITLE
error for v5.6.2

### ISSUE THREAD

**Issue by zhanghaigang666** [shamblett/mqtt_client#140]
When I use mqtt_client: ^ 5.6.2, executing the packages get command will prompt the following error, how can I solve it?
Because mqtt_client> = 5.6.2 depends on meta ^ 1.1.8 and every version of flutter from sdk depends on meta 1.1.7, mqtt_client> = 5.6.2 is incompatible with flutter from sdk.
So, because robot_master_project depends on both flutter any from sdk and mqtt_client ^ 5.6.2, version solving failed.
pub get failed (1)

**Comment by shamblett** [comment]
You could try a higher flutter version that bumps the meta package, or wait for flutter to catch up, you may be better asking on a flutter list. You could of course use 5.6.1 or lower of the client.
