### ISSUE TITLE
Connection status

### ISSUE THREAD

**Issue by hyagush** [shamblett/mqtt_client#141]
When get to this part of the code `await client.connect();` nothing happens, and `client.connectionStatus.state` stays into "connecting" forever. It doesn't report me any error at all. Can someone help me please?
![image](https://user-images.githubusercontent.com/58311378/69831429-18015400-1208-11ea-9348-c1ac8d358d5f.png)

**Comment by shamblett** [comment]
You need to turn logging on on the client to see where its hanging, it looks as though the broker is connecting but not responding

**Comment by hyagush** [comment]
When I turn logging on, i've tried to connect and got this message
![image](https://user-images.githubusercontent.com/58311378/69963331-c9490800-14ee-11ea-8e49-9e17376efae8.png)

**Comment by shamblett** [comment]
Yes the client is trying to connect but getting no response, this is usually a network/firewall issue of some kind.

**Comment by hyagush** [comment]
I'll try to find and fix it, thanks for now!

**Comment by hyagush** [comment]
I solved it! Thanks a lot
