### ISSUE TITLE
Error while connecting to Greengrass core ip. 

### ISSUE THREAD

**Issue by Usama455** [shamblett/mqtt_client#143]
Connecting to AWS-END-POINT properly but when I tried connecting to Greengrass core using local network ip. I get this error. 

E/flutter (12349): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter (12349):      CERTIFICATE_VERIFY_FAILED: Hostname mismatch(handshake.cc:352))

I have already checked the greengrass core. it's working fine . 
I think there might be some issue of using ip address instead of URL address. but i am not sure. Can anyone help please? 

The Code I am running is
import 'dart:async';
import 'dart:io';
import 'package:mqtt_client/mqtt_client.dart';

import 'dart:convert' show utf8;
import 'dart:convert';

Future main() async {

const String url =
'192.168.8.102';
const int port = 8883;
const String clientId =
'Flutter_tmfacility_0_1';

MqttClient client = MqttClient.withPort(url,clientId,port);

client.secure = true;
// Set the security context as you need, note this is the standard Dart SecurityContext class.

final SecurityContext context = new SecurityContext(withTrustedRoots: true); context.setTrustedCertificatesBytes(utf8.encode('GREEN GRASS CORE CERT HERE'));
context.useCertificateChainBytes(utf8.encode(' CLIENT CERT HERE'));
context.usePrivateKeyBytes(utf8.encode(' MY PRIVATE KEY HERE '));

client.securityContext = context;
client.setProtocolV311();
// logging if you wish
client.logging(on: false);
print('Before Connecting');

await client.connect(url);

print('After Connecting');
if (client.connectionStatus.state == MqttConnectionState.connected) {
print('iotcore client connected');
} else {
print(
'ERROR iotcore client connection failed - disconnecting, state is ${client.connectionStatus.state}');
client.disconnect();
}
const String topic = '$aws/things/Pi_tmfacility_0_1/shadow/update';
String payload = '{'state':{'desired': {'name' : 'usama'}} }';

    final MqttClientPayloadBuilder builder = MqttClientPayloadBuilder();
  builder.addString(json.encode(payload));

  print('into the publish to get single device shadow ');
  client.publishMessage(topic, MqttQos.atMostOnce, builder.payload);
print('Sleeping....');
await MqttUtilities.asyncSleep(10);
print('Disconnecting');
client.disconnect();
return 0;
}`

![Screenshot from 2019-12-11 12-03-48](https://user-images.githubusercontent.com/29920285/70599163-533f5200-1c0e-11ea-9268-072cfc9f75f5.png)

**Comment by shamblett** [comment]
The error is 
```
E/flutter (12349): CERTIFICATE_VERIFY_FAILED: Hostname mismatch(handshake.cc:352))
```
A Hostname mismatch, you need to update your cert to allow it use the ip address.

**Comment by Usama455** [comment]
Thanks for your reply. 
I have used mqttfx client using same certs, client ID and ip and i was able to connect successfully with same credentials. 
But in flutter , it gives this error for core ip. 
AWS endpoint is connected successfully using same things .

**Comment by shamblett** [comment]
Yes, flutter/Dart uses its own TLS implementation, it uses Boring SSL, see[ here](https://dart-lang.github.io/server/tls-ssl.html) which is probably set up differently to your mqtffx client environment, your better asking on a flutter list, the mqtt_client can't really affect any of this except through the secure context/socket api Dart provides if supported.
