### ISSUE TITLE
Can set socket timeout, and get onDisconnected when timeout is exceeded?

### ISSUE THREAD

**Issue by stuz5000** [shamblett/mqtt_client#146]
I'd like to be able to detect disconnections sooner. The current behavior I see is that:

 - if set keepAlivePeriod to 5 seconds
 - I register a pong callback
 - I connect,
 - then I unplug the network

... I don't see a way to be notified that the keepAilive message has failed. The pong callback simply stops being called. onDisconnect is called only when the network is plugged back in.

Typically with TCP, when you send a message, you can specify a "socket timeout" (e.g. 10 seconds) - if no response or TCP ACK is received, then the socket can assumed to be disconnected. Ideally, we'd get an onDisconnected event whever the socket timeout is exceeded.

This is handy, for example, to grey out a UI, to let the user know their inputs aren't being captured by the server (google docs does something similar when a connection is lost).

Is it possible to set the socket timeout and trigger client.disconnect in this case?

**Comment by shamblett** [comment]
As you are probably aware the client can only do what the Dart API allows it, currently the only [socket option](https://api.dartlang.org/stable/2.7.0/dart-io/SocketOption-class.html) I can see is for TCP no delay, a quick search in the API docs doesn't turn up anything else in this area.

I'm surprised however that onDisconnect is called only when the network cable is plugged back in, this is triggered directly from the onDone event on the socket stream, there may be another event I can hook into here, I'll have a more detailed look at this.

**Comment by stuz5000** [comment]
Thanks - I'll poke the Dart people for answers, and possibly a feature request.

**Comment by stuz5000** [comment]
Also, it occurs to me I can (inefficiently) setup an mqtt ping topic to resolve this:

```
 subscribe to ping
 checkConnected():
     Future({
        publish(magic number)
     }).then.delayed(timeout)({
         if (not received magic number) client.disconnect()
         else checkConnected();
    })
```

**Comment by stuz5000** [comment]
Its looks like what was recommended was to wrap requests with Future.timeout:

```
import 'dart:async';
import 'dart:io';

Future<T> disconnectOnTimeout<T>(Future<T> fut, Duration duration) =>
    fut.timeout(Duration(seconds: 1)).catchError((e) {
      print("TIMEOUT -- disconnect"); // Disconnect here
      throw e;
    }, test: (e) => e is TimeoutException);

f() async {
  var client = new HttpClient();
  Future request = client.getUrl(Uri.parse('http://8.8.8.9')); // host without response

  request = disconnectOnTimeout(request, Duration(seconds: 2));
  request = await request;
}

```

I think the above is the only solution. Dart peeps only implement a timeout for connect.

https://github.com/dart-lang/sdk/commit/86fdbde70a0d22cdf03612ce2d5a3f38ded71634

**Comment by shamblett** [comment]
Yes I see what you mean but there aren't 'requests'as such, the client connects to the broker and listens for data, if you subscribe to a topic that has no data you will receive nothing until it has something, this could be any time after subscription, you can't say 'subscribe to this topic and wait x seconds for a response', its up to the broker, not the client. This is why MQTT uses the ping/pong mechanism for keep alive I guess.

What we could do however is if we don't get a pong callback we could disconnect, then onDisconnect would be called, this would need to be configurable on the client, some users may not want this behaviour. I'll still have a look for a better disconnected event also.

**Comment by stuz5000** [comment]
I think that sound like a good idea.

**Comment by stuz5000** [comment]
Also, is it possible to turn the MQTT keepalive on/off dynamically (and perhaps also set the timeout dynamically)? 
It might be useful to change this depending on the status of the app, for example, if the user is away, you might want a longer keep ailive, or if we're expecting to receive a message, we might want a short keep ailive (to more quickly notify about a disconnection).

**Comment by shamblett** [comment]
The keepalive period is set by the client in the connect message and as far as I know can't be changed after this without disconnecting from the broker and reconnecting, you can disable this however and do your own keepalive, if you set the keepalive to zero it disables it on the broker, and from the MQTT spec :-
```
The Client can send PINGREQ at any time, irrespective of the Keep Alive value, and use the PINGRESP to determine that the network and the Server are working.
```
So the client could implement its own keepalive. I wouldn't expect this however to be able support times of lower than say 2 seconds, maybe one second say, there are reported issues with some MQTT brokers when the keepalive value is set to 1 second.
