### ISSUE TITLE
'_DetachedSocket' can't implement both 'Stream<List<int>>' and 'Stream<Uint8List>'

### ISSUE THREAD

**Issue by YXYCareFree** [shamblett/mqtt_client#147]
Error: '_DetachedSocket' can't implement both 'Stream<List<int>>' and 'Stream<Uint8List>'
 - 'Stream' is from 'dart:async'.
 - 'List' is from 'dart:core'.
 - 'Uint8List' is from 'dart:typed_data'.
class _DetachedSocket extends Stream<List<int>> implements Socket {
      ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.

**Comment by shamblett** [comment]
This has been fixed, see previous issues, you need to use dart > 2.6 and the latest client.

**Comment by YXYCareFree** [comment]
> This has been fixed, see previous issues, you need to use dart > 2.6 and the latest client.

I have used dart 2.7.0 and mqtt_clinet 5.5.3, but the error keep coming up

**Comment by YXYCareFree** [comment]
> This has been fixed, see previous issues, you need to use dart > 2.6 and the latest client.

Thanks！
