### ISSUE TITLE
Is there Clear Session option?

### ISSUE THREAD

**Issue by ZionPi** [shamblett/mqtt_client#148]
I do not to want to resubscribe topics after  mqtt  client `reconnect`.It seems  that to comment out this `.startClean() ` line does not help.And I'm not sure if not to call `startClean` is equivalent to call `ClearSession(false)` as the demo code shows below.
```
 /// Create a connection message to use or use the default one. The default one sets the
  /// client identifier, any supplied username/password, the default keepalive interval(60s)
  /// and clean session, an example of a specific one below.
  final MqttConnectMessage connMess = MqttConnectMessage()
      .withClientIdentifier('Mqtt_MyClientUniqueId')
      .keepAliveFor(20) // Must agree with the keep alive set above or not set
      .withWillTopic('willtopic') // If you set this you must set a will message
      .withWillMessage('My Will message')
      .startClean() // Non persistent session for testing
      .withWillQos(MqttQos.atLeastOnce);
```
Do I have to subscribe topics one by one that have been subscribed after `reconnect`?Btw,`reconnect` is a user defined function that was put inside `OnDisconnect` callback.

**Comment by shamblett** [comment]
The start clean option selects either a persistent or no-persistent session with the broker, see [here](http://www.steves-internet-guide.com/mqtt-clean-sessions-example/), looks as though you want a persistent(durable) session so you do not want to call startClean().

Note that the docs say 
```
In order for the broker to store session information for a client a client id must be used.
```
so you must connect with a clientId.

Not sure what the ClearSession() you are referring to is.

**Comment by ZionPi** [comment]
Yes , persistent  session.Sorry for the confusion of `ClearSession()` ,it is a function that I have seen in other language implemented for keeping persistent session. I do set a `unique clientId` by using
`mqttConnectMessage.withClientIdentifier('Mqtt_MyClientUniqueId')` ,and not call `.startClean()` ,but when I trying to turn off network and turn it on again,and the subscriptions that I have subscribed  seems gone.

**Comment by shamblett** [comment]
I see what you mean, the client does clear its subscriptions on disconnect, you would have to re-instate them manually. I'm sure this has been raised before maybe as part of auto reconnect functionality which has not yet been implemented. That said the broker should still send you publish messages for the subscriptions you set up prior to the disconnect(for a persistent session that is), is this not happening?

**Comment by ZionPi** [comment]
> I see what you mean, the client does clear its subscriptions on disconnect, you would have to re-instate them manually. I'm sure this has been raised before maybe as part of auto reconnect functionality which has not yet been implemented. That said the broker should still send you publish messages for the subscriptions you set up prior to the disconnect(for a persistent session that is), is this not happening?

Yes ,it is not happening, that's exactly what I mean.

**Comment by shamblett** [comment]
Yes, could you try starting a persistent session and turn logging on, when you pull the network cable and reconnect with the same clientid(don't resubscrbe anything) you should see publish messages in the log for your already subscribed subcriptions, the client may be discarding these at this point, if you don't see any then your broker is not behaving as I think it should.
