### ISSUE TITLE
Secure websocket support?

### ISSUE THREAD

**Issue by gokr** [shamblett/mqtt_client#15]
From mobile applications and in general, using MQTT over WSS is ideal. It works well through firewalls and so on. In Canoe (getcanoe.io) which is a crypto wallet we use this to communicate effortlessly from the app, and it even works great from inside China. Is support for WSS hard to add? Has it been considered?

**Comment by shamblett** [comment]
In theory it should just work by changing the URL, from the Dart API docs 

---
connect(String url, { Iterable<String> protocols, Map<String, dynamic> headers, CompressionOptions compression: CompressionOptions.DEFAULT }) → Future<WebSocket>
Create a new WebSocket connection. The URL supplied in url must use the scheme ws or wss.
---

Notice it says ws or wss. I can't find any more info on this so presumably it should just work. I've not tried nor tested with this, please try this and see what mileage you get if you can.

**Comment by gokr** [comment]
Oh, nice! I will try it out and get back.

**Comment by shamblett** [comment]
The wss scheme is now fully supported and tested in the latest client(3.2.1), please update to this version.
