### ISSUE TITLE
Connection to 'https://app.fflux.cn/mqtt#' was not upgraded to websocket

### ISSUE THREAD

**Issue by zhaoxiafeigithub** [shamblett/mqtt_client#150]
When I link to mqtt server, I get this error report. My account is: server, password is:^&&&09@~...!8g681, server address is wss://alitest.fflux.tech/mqtt. Can you write a demo ? Thank you!

**Comment by shamblett** [comment]
Sorry I don't really understand your issue, there are plenty of examples in the examples directory, if you can't find what you are looking for please update this issue with log output.
