### ISSUE TITLE
Error subscribing to Topic with `application/#/status` when wildcard is in middle.

### ISSUE THREAD

**Issue by magillus** [shamblett/mqtt_client#152]
Hello I run into issue when trying to subscribe to:
`/application/#/status` - or similar topic that have `#` wildcard in middle of topic name.

Error output:
```Subscriptionsmanager::createNewSubscription exception raised, text is Exception: mqtt_client::SubscriptionTopic: The rawTopic wildcard # can only be present at the end of a topic```

Which seems like expected - I think it should work (at least other MQTT clients support that notation).

**Comment by shamblett** [comment]
From the spec:
```
4.7.1.2 Multi-level wildcard
The number sign (‘#’ U+0023) is a wildcard character that matches any number of levels within a topic. The multi-level wildcard represents the parent and any number of child levels. The multi-level wildcard character MUST be specified either on its own or following a topic level separator. In either case it MUST be the last character specified in the Topic Filter [MQTT-4.7.1-2].

Non normative comment

For example, if a Client subscribes to “sport/tennis/player1/#”, it would receive messages published using these topic names:

·         “sport/tennis/player1”

·         “sport/tennis/player1/ranking”

·         “sport/tennis/player1/score/wimbledon”

 
Non normative comment

·         “sport/#” also matches the singular “sport”, since # includes the parent level.

·         “#” is valid and will receive every Application Message

·         “sport/tennis/#” is valid

·         “sport/tennis#” is not valid

·         “sport/tennis/#/ranking” is not valid
```
We don't allow this because the spec disallows it, what other clients do support this BTW?

I could add a flag to disallow strict topic checking however the user would need to be careful using things like this.

**Comment by magillus** [comment]
Thank you, I think assumed wrong, one of clients I use (java) worked with it so that why I got this wrong assumption.
