### ISSUE TITLE
publish mode not working

### ISSUE THREAD

**Issue by Kalyanb447-github** [shamblett/mqtt_client#153]
the app work nice on debug mode 
but after build apk the app is not connecting 
please help

**Comment by shamblett** [comment]
This sounds like a flutter problem, I'm sure there have been other users that have raised issues in this area and this has turned out to be a flutter/platform problem. If the client works in for you in debug mode its a packaging/deployment problem.

**Comment by lucacasonato** [comment]
> the app work nice on debug mode
> but after build apk the app is not connecting
> please help

Does your app the android.permission.INTERNET in its manifest? Your //android/app/src/main/AndroidManifest.xml should contain `<uses-permission android:name="android.permission.INTERNET"/>`.
