### ISSUE TITLE
not good support Chinese characters

### ISSUE THREAD

**Issue by zzdota** [shamblett/mqtt_client#158]
static String bytesToStringAsString(typed.Uint8Buffer message) {
    final StringBuffer sb = StringBuffer();
    message.forEach(sb.writeCharCode);
    return sb.toString();
}
There is no good support for Chinese characters,
We use the following method to solve this problem

  static String bytesToStringAsString(typed.Uint8Buffer message) {
//    final StringBuffer sb = StringBuffer();
////    message.forEach(sb.writeCharCode);
////    return sb.toString();
    String messageTxt = Utf8Decoder().convert(message);
    return messageTxt;
  }

**Comment by shamblett** [comment]
Yes, the client only supplies a payload builder class to help you build payloads, only you know what is in your received payloads and thus how to decode them.
