### ISSUE TITLE
type 'List<ChangeRecord>' is not a subtype of type 'List<MqttReceivedMessage<dynamic>>

### ISSUE THREAD

**Issue by LuLeRoemer** [shamblett/mqtt_client#16]
Unfortunately, I get the following error running the example code:
```
E/flutter (16017): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (16017): type 'List<ChangeRecord>' is not a subtype of type 'List<MqttReceivedMessage<dynamic>>'
E/flutter (16017): #0      ChangeNotifier.deliverChanges (package:observable/src/change_notifier.dart:63:20)
E/flutter (16017): #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (16017): #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```
It seems, there is a problem regarding publish messages.
I'm using flutter v0.5.1.

**Comment by shamblett** [comment]
Yes, this looks like a Dart 2 problem, flutter users have been reporting this type of breakage in various parts of the client, it seems to change depending on the flutter version being used. When Google release Dart 2 into production I'll update and fix the client accordingly, until then there's not much I can do.

**Comment by benbehringer** [comment]
I added a workaround in my repo:

pubspec.yaml:

#mqtt_client: "^1.7.2"
mqtt_client:
git:
url: https://github.com/benbehringer/mqtt_client.git

subscribe as follows:
import 'package:observable/observable.dart' as observe;
import 'package:mqtt_client/mqtt_client.dart' as mqtt;

final observe.ChangeNotifier<observe.ChangeRecord> cn = client.subscribe(topic, mqtt.MqttQos.exactlyOnce).observable;
cn.changes.listen((List<observe.ChangeRecord> c) {
mqtt.MqttReceivedMessage myMessage = c[0] as mqtt.MqttReceivedMessage;
final mqtt.MqttPublishMessage recMess = myMessage.payload as mqtt.MqttPublishMessage;
final String pt =
mqtt.MqttPublishPayload.bytesToStringAsString(recMess.payload.message);
print("EXAMPLE::Change notification:: payload is <$pt> for topic <$topic>");
});

**Comment by shamblett** [comment]
Ok looks as though Dart 2 has hit stable, im just finishing my hols at the mo Ill update the package late this week/early next and see where we are then

**Comment by shamblett** [comment]
Dart 2.0 updates are now tracked on issue 24

**Comment by shamblett** [comment]
I believe the latest client(3.2.1) and flutter are now OK together, can you verify this.

**Comment by shamblett** [comment]
Believe this is now fixed.

**Comment by excode** [comment]
Can we use Mqtt_client for chatting app which will run both on IOS and Android. Please suggest. Thanks a lot

**Comment by shamblett** [comment]
I believe some users do use the client for stuff like this using flutter so you can run it on IOS or Android, some users use it as a general purpose pub/sub mechanism, you will of course need your own MQTT broker somewhere, the mqtt_client is as it says only a client.

**Comment by ddkoin** [comment]
> I believe some users do use the client for stuff like this using flutter so you can run it on IOS or Android, some users use it as a general purpose pub/sub mechanism, you will of course need your own MQTT broker somewhere, the mqtt_client is as it says only a client.

Thanks.

Do you have any reference link /  example for code which implement the mqtt_client  for chat or pub/sub.
Thanks in advance.
