### ISSUE TITLE
onDisconnect being called on null, but the function exists

### ISSUE THREAD

**Issue by BRO3886** [shamblett/mqtt_client#160]
`Exception has occurred. NoSuchMethodError (NoSuchMethodError: The setter 'onDisconnected=' was called on null. Receiver: null Tried calling: onDisconnected=Closure: () => void from Function 'internalDisconnect':.)
`
I am unable to connect to cloudmqtt service to subscribe to a topic to read temperature

**Comment by BRO3886** [comment]
**Code**

```
void connect() async {
    mqttClient.port = port;
    mqttClient.logging(on: true);
    mqttClient.keepAlivePeriod = 20;
    mqttClient.onConnected = _onConnected;
    mqttClient.onDisconnected = _onDisconnected;
    mqttClient.onSubscribed = _onSubscribed;
    MqttConnectionState state;
    String topic = "temperature";
    final MqttConnectMessage connMess = MqttConnectMessage()
        .withClientIdentifier(clientIdentifier)
        .keepAliveFor(20) // Must agree with the keep alive set above or not set
        .startClean() // Non persistent session for testing
        .withWillQos(MqttQos.atLeastOnce);
    print("----client connecting----");
    mqttClient.connectionMessage = connMess;
    try {
      await mqttClient.connect();
    } on Exception catch (e) {
      print('----EXC $e----');
      mqttClient.disconnect();
      return;
    }
    if (mqttClient.connectionStatus.state == MqttConnectionState.connected) {
      print("----client connected----");
    } else {
      print("----unable to connect----");
      setState(() {
        state = mqttClient.connectionStatus.state;
      });
      print("----connection state is $state----");
      print("----disconnecting----");
      mqttClient.disconnect();
      return;
    }
    print("----subscribing to topic \"$topic\"----");
    mqttClient.subscribe(topic, MqttQos.atMostOnce);

    mqttClient.updates.listen((List<MqttReceivedMessage<MqttMessage>> c) {
      final MqttPublishMessage recMess = c[0].payload;
      final String pt =
          MqttPublishPayload.bytesToStringAsString(recMess.payload.message);
      print("----topic is ${c[0].topic} and payload is $pt----");
    });

    print("----sleeping----");
    await MqttUtilities.asyncSleep(120);

    print("----unsubscribing----");
    mqttClient.unsubscribe(topic);

    await MqttUtilities.asyncSleep(2);

    print("----disconnecting----");
    mqttClient.disconnect();
    return;
  }

  void _onDisconnected() {
    print("----_onDisconnected callback, client disconnection----");
    if (mqttClient.connectionStatus.returnCode ==
        MqttConnectReturnCode.solicited) {
      print("----_onDisconnected callback solicitated, correct!----");
    }
  }

  void _onConnected() {
    print("----connection from _onConnected successful----");
  }

  void _onSubscribed(String topic) {
    print("----subscribed to topic $topic from _onSubscribed----");
  }

```

**Comment by BRO3886** [comment]
AAAH nvm, got it
 try {
      await mqttClient.connect(username, password); <--this was missing
    } on Exception catch (e) {
      print('----EXC $e----');
      mqttClient.disconnect();
      return;
    }

**Comment by shamblett** [comment]
Please check you are using MqttServerClient or MqttBRowserClient as the changelog says you should not be using the MqttClient class withe the latest package vwrsion

**Comment by BRO3886** [comment]
void internalDisconnect() {
    **// Only call disconnect if we are connected, i.e. a connection to
    // the broker has been previously established.**
    if (connectionStatus.state == MqttConnectionState.connected) {
      _disconnect(unsolicited: true);
    } else {
      _disconnect(unsolicited: false);
    }
  }

Seems to be some issue here
I am using MqttServerClient, yes. But onDisconnect is being called before the connection is established.

**Comment by BRO3886** [comment]
Unhandled Exception: NoSuchMethodError: The setter 'onDisconnected=' was      
called on null.
[  +10 ms] E/flutter (11000): Receiver: null
[   +2 ms] E/flutter (11000): Tried calling: onDisconnected=Closure: () => void from Function 'internalDisconnect':.

**Comment by shamblett** [comment]
internalDisconnect is only used before you have an established connection, this just calls _disconnect which itself does this 
```
if (onDisconnected != null) {
      onDisconnected();
    }
```
so the onDisconnected call is checked for null.

Presumably the hit or miss means it doesn't fail if it connects, I really need to see all ypur code here.
