### ISSUE TITLE
Bind listening to an IP

### ISSUE THREAD

**Issue by Fiono11** [shamblett/mqtt_client#171]
Hello! With this library, can you make a mqtt_client listen to messages that only come from a specific IP adress? Thank you!

**Comment by shamblett** [comment]
Not sure what you mean, just specify the host name either as a name e.g. 'test.mosquitto,org', or as an IP '123.123.123.123'.

**Comment by Fiono11** [comment]
I mean from another client, not the broker.

A sexta, 10/04/2020, 12:37, Steve Hamblett <notifications@github.com>
escreveu:

**Comment by shamblett** [comment]
No, its a standard MQTT client that connects to an MQTT broker, what use case do you have for it to accept messages from another client?

**Comment by Fiono11** [comment]
I was confusing the concepts a little bit. I need to setup a private topic between clients through the mqtt broker.

**Comment by shamblett** [comment]
Yes OK, in that case you can use the client for this.

**Comment by Fiono11** [comment]
Ok, thanks!
