### ISSUE TITLE
Failed MQTT connections always end with Missing Connection Acknowledgement error

### ISSUE THREAD

**Issue by lucacasonato** [shamblett/mqtt_client#172]
Currently there is no way of detecting which error code a connect failed with. It always just throws `The maximum allowed connection attempts (3) were exceeded. The broker is not responding to the connection request message (Missing Connection Acknowledgement` even if the broker responded with a connection acknowledgement, just with a non 0 return code.

What I would expect to happen on for example a connection attempt where the broker refuses with a `5` return code (not authorized) is for the connect not to throw, but rather return a `MqttClientConnectionStatus` with `state` set to `MqttConnectionState.disconnected` and the `returnCode` set to `MqttConnectReturnCode.notAuthorized`. Instead the connect method just throws with a incorrect message now. The message says that there was a `missing connection acknowledgement` which is incorrect as the `Connect Ack` was sent by the broker.

**Comment by shamblett** [comment]
After the three connection attempts have failed if you read the connection status is this correct, i.e. does it correctly reflect the status of the last attempt being not authorized with just the exception message being wrong, or is the connection status wrong also?

**Comment by lucacasonato** [comment]
First of all, thanks for the quick response :smiley:. Super awesome that you develop this library!

The `connectionStatus` property on the client is also incorrect: it has a `status` of `MqttConnectionState.disconnected` but a return code of `MqttConnectReturnCode.solicited`. No mention of the actual return code. `MqttConnectReturnCode.solicited` and `MqttConnectReturnCode.unsolicited` are not even part of the spec right?

**Comment by shamblett** [comment]
OK, yes I added these but your right they are not part of the spec, I'll do something about this while I'm looking at the issue.

**Comment by shamblett** [comment]
Client updated and re published at 7.0.0. The solicited/unsolicited codes have now been move into their own status field so as not to overwrite broker returned codes. The exception has been updated to better indicate whether a connection ack has been received or not and what the broker return code is. The real broker return code should now always be available.

**Comment by lucacasonato** [comment]
Oh that is super awesome! I'll try it out later today. Thanks a lot :smile:
