### ISSUE TITLE
 problem when using autoReconnect = true; with usewebsoket = true

### ISSUE THREAD

**Issue by alanfg120** [shamblett/mqtt_client#173]
E/flutter (23545): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: Class '_WebSocketImpl' has no instance method 'destroy'.
E/flutter (23545): Receiver: Instance of '_WebSocketImpl'
E/flutter (23545): Tried calling: destroy()
[38;5;244mE/flutter (23545): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)[39;49m
[38;5;248mE/flutter (23545): #1      MqttConnectionBase._disconnect[39;49m
[38;5;248mE/flutter (23545): #2      MqttConnectionBase.onDone[39;49m
[38;5;244mE/flutter (23545): #3      _rootRun  (dart:async/zone.dart:1122:38)[39;49m
[38;5;244mE/flutter (23545): #4      _CustomZone.run  (dart:async/zone.dart:1023:19)[39;49m
[38;5;244mE/flutter (23545): #5      _CustomZone.runGuarded  (dart:async/zone.dart:925:7)[39;49m
[38;5;244mE/flutter (23545): #6      _BufferingStreamSubscription._sendDone.sendDone  (dart:async/stream_impl.dart:391:13)[39;49m
[38;5;244mE/flutter (23545): #7      _BufferingStreamSubscription._sendDone  (dart:async/stream_impl.dart:401:15)[39;49m
[38;5;244mE/flutter (23545): #8      _BufferingStreamSubscription._close  (dart:async/stream_impl.dart:285:7)[39;49m
[38;5;244mE/flutter (23545): #9      _SyncStreamControllerDispatch._sendDone  (dart:async/stream_controller.dart:774:19)[39;49m
[38;5;244mE/flutter (23545): #10     _StreamController._closeUnchecked  (dart:async/stream_controller.dart:631:7)[39;49m
[38;5;244mE/flutter (23545): #11     _StreamController.close  (dart:async/stream_controller.dart:624:5)[39;49m
[38;5;244mE/flutter (23545): #12     new _WebSocketImpl._fromSocket.<anonymous closure>  (dart:_http/websocket_impl.dart:1155:19)[39;49m
[38;5;244mE/flutter (23545): #13     _rootRunBinary  (dart:async/zone.dart:1146:38)[39;49m
[38;5;244mE/flutter (23545): #14     _CustomZone.runBinary  (dart:async/zone.dart:1039:19)[39;49m
[38;5;244mE/flutter (23545): #15     _CustomZone.runBinaryGuarded  (dart:async/zone.dart:941:7)[39;49m
[38;5;244mE/flutter (23545): #16     _BufferingStreamSubscription._sendError.sendError  (dart:async/stream_impl.dart:357:15)[39;49m
[38;5;244mE/flutter (23545): #17     _BufferingStreamSubscription._sendError  (dart:async/stream_impl.dart:372:18)[39;49m
[38;5;244mE/flutter (23545): #18     _BufferingStreamSubscription._addError  (dart:async/stream_impl.dart:274:7)[39;49m
[38;5;244mE/flutter (23545): #19     _SinkTransformerStreamSubscription._addError  (dart:async/stream_transformers.dart:84:11)[39;49m
[38;5;244mE/flutter (23545): #20     _EventSinkWrapper.addError  (dart:async/stream_transformers.dart:21:11)[39;49m
[38;5;244mE/flutter (23545): #21     _WebSocketProtocolTransformer.addError  (dart:_http/websocket_impl.dart:118:16)[39;49m
[38;5;244mE/flutter (23545): #22     _SinkTransformerStreamSubscription._handleError  (dart:async/stream_transformers.dart:130:24)[39;49m
[38;5;244mE/flutter (23545): #23     _rootRunBinary  (dart:async/zone.dart:1146:38)[39;49m
[38;5;244mE/flutter (23545): #24     _CustomZone.runBinary  (dart:async/zone.dart:1039:19)[39;49m
[38;5;244mE/flutter (23545): #25     _CustomZone.runBinaryGuarded  (dart:async/zone.dart:941:7)[39;49m
[38;5;244mE/flutter (23545): #26     _BufferingStreamSubscription._sendError.sendError  (dart:async/stream_impl.dart:357:15)[39;49m
[38;5;244mE/flutter (23545): #27     _BufferingStreamSubscription._sendError  (dart:async/stream_impl.dart:375:16)[39;49m
[38;5;244mE/flutter (23545): #28     _BufferingStreamSubscription._addError  (dart:async/stream_impl.dart:274:7)[39;49m
[38;5;244mE/flutter (23545): #29     _SyncStreamControllerDispatch._sendError  (dart:async/stream_controller.dart:770:19)[39;49m
[38;5;244mE/flutter (23545): #30     _StreamController._addError  (dart:async/stream_controller.dart:650:7)[39;49m
[38;5;244mE/flutter (23545): #31     _StreamController.addError  (dart:async/stream_controller.dart:602:5)[39;49m
[38;5;244mE/flutter (23545): #32     _Socket._onError  (dart:io-patch/socket_patch.dart:1874:19)[39;49m
[38;5;244mE/flutter (23545): #33     _rootRunBinary  (dart:async/zone.dart:1146:38)[39;49m
[38;5;244mE/flutter (23545): #34     _CustomZone.runBinary  (dart:async/zone.dart:1039:19)[39;49m
[38;5;244mE/flutter (23545): #35     _CustomZone.runBinaryGuarded  (dart:async/zone.dart:941:7)[39;49m
[38;5;244mE/flutter (23545): #36     _BufferingStreamSubscription._sendError.sendError  (dart:async/stream_impl.dart:357:15)[39;49m
[38;5;244mE/flutter (23545): #37     _BufferingStreamSubscription._sendError  (dart:async/stream_impl.dart:372:18)[39;49m
[38;5;244mE/flutter (23545): #38     _BufferingStreamSubscription._addError  (dart:async/stream_impl.dart:274:7)[39;49m
[38;5;244mE/flutter (23545): #39     _SyncStreamControllerDispatch._sendError  (dart:async/stream_controller.dart:770:19)[39;49m
[38;5;244mE/flutter (23545): #40     _StreamController._addError  (dart:async/stream_controller.dart:650:7)[39;49m
[38;5;244mE/flutter (23545): #41     _StreamController.addError  (dart:async/stream_controller.dart:602:5)[39;49m
[38;5;244mE/flutter (23545): #42     new _RawSocket.<anonymous closure>  (dart:io-patch/socket_patch.dart:1412:23)[39;49m
[38;5;244mE/flutter (23545): #43     _rootRunBinary  (dart:async/zone.dart:1150:13)[39;49m
[38;5;244mE/flutter (23545): #44     _CustomZone.runBinary  (dart:async/zone.dart:1039:19)[39;49m
[38;5;244mE/flutter (23545): #45     _CustomZone.runBinaryGuarded  (dart:async/zone.dart:941:7)[39;49m
[38;5;244mE/flutter (23545): #46     _CustomZone.bindBinaryCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:976:33)[39;49m
[38;5;244mE/flutter (23545): #47     _NativeSocket.reportError  (dart:io-patch/socket_patch.dart:1160:32)[39;49m
[38;5;244mE/flutter (23545): #48     _NativeSocket.multiplex  (dart:io-patch/socket_patch.dart:998:13)[39;49m
E/flutter (23545): #49

It only happens when I configure websocket if I use tcp this error does not happen excuse my english

Thank you

your package is very good and works well, in flutter and thanks for the updates.

**Comment by shamblett** [comment]
Yes well spotted, the Websocket class either server or browser side doesn't have a destroy method. I've changed this to a close method in these cases and re published the package at 6.2.1 please re test if you get chance.
