### ISSUE TITLE
Socket handling pauses

### ISSUE THREAD

**Issue by gokr** [shamblett/mqtt_client#18]
There is something wrong in the socket code because I can see two variants of "pauses". Here is a log from a little test program:

```
INFO: 2018-06-26 11:01:27.275563: Connecting to localhost
INFO: 2018-06-26 11:01:32.316929: Connected
INFO: 2018-06-26 11:01:32.317333: Connected
INFO: 2018-06-26 11:01:32.317969: Subscribing to #
INFO: 2018-06-26 11:01:32.354016: idioter: hey2
INFO: 2018-06-26 11:01:52.343208: mulor: hey3
```
We can see that it takes exactly 5 seconds to connect. We can also see it takes exactly 20 seconds between "hey2" and "hey3" - both are retained messages on two different topics. Neither of these pauses should be here, using mosquitto_sun for example, all happens instantly.

Exactly the same behavior for Mosquitto or VerneMQ, I tested both to be sure.

**Comment by shamblett** [comment]
OK, I'll have a look at this, there may be an unnecessary wait somewhere, could you post your test peogram and./or test it again with logging enabled in the client.

**Comment by shamblett** [comment]
The asyncwait in the sync connection handler needs looking at here, no need to wait the full 5 seconds if we are connected.

**Comment by shamblett** [comment]
The testing that caused this was 'multiple retained, and then subscribe to "#"'

**Comment by shamblett** [comment]
The 5 second connection issue is now fixed by Issue 35, package re-published at 3.2.0

**Comment by shamblett** [comment]
Please retest with package 3.2.2

**Comment by shamblett** [comment]
Believe this is now fixed.
