### ISSUE TITLE
Unhandled Exception: type '(X509Certificate) => bool' is not a subtype of type '(dynamic) => bool' of 'value'

### ISSUE THREAD

**Issue by 0x2f0713** [shamblett/mqtt_client#181]
Hi, I am using mqtt_client package version 6.2.1. When I set property `onBadCertificate`, my app throw error with message: `Unhandled Exception: type '(X509Certificate) => bool' is not a subtype of type '(dynamic) => bool' of 'value'`
My code:
```dart
    var certificate =
        (await rootBundle.load("resources/certs/ca.crt")).buffer.asInt8List();
    print(certificate.toString());
    var key = (await rootBundle.load("resources/certs/server.key"))
        .buffer
        .asInt8List();
    var serverCert = (await rootBundle.load("resources/certs/server.crt"))
        .buffer
        .asInt8List();
    print(key.toString());
    securityContext.setTrustedCertificatesBytes(certificate);
    securityContext.usePrivateKeyBytes(key);
    securityContext.useCertificateChainBytes(serverCert);
    client.securityContext = this.securityContext;
    client.logging(on: true);
    client.onBadCertificate = (_) => true;
    client.secure = true;
    client.port = 8883;
```
I am waiting for help. Thanks!

**Comment by shamblett** [comment]
Change your dad certificate line to 
```
client.onBadCertificate = (dynamic a) => true;
```
Its expecting a certificate parameter, I'll annotate this better in the secure client example.

**Comment by 0x2f0713** [comment]
> Change your dad certificate line to
> 
> ```
> client.onBadCertificate = (dynamic a) => true;
> ```
> 
> Its expecting a certificate parameter, I'll annotate this better in the secure client example.

Thank you, it worked! I think you should update the documentation at https://pub.dev/documentation/mqtt_client/latest/mqtt_server_client/MqttServerClient-class.html. Because of this documentation, I catched this bugs.
Sorry for my bad English.

**Comment by shamblett** [comment]
Client updated and re published at 7.0.0.

**Comment by RicardoRB** [comment]
This error is still in the version ^7.1.0

@shamblett

**Comment by shamblett** [comment]
Not sure what you mean, you need to update your code as described above.

**Comment by RicardoRB** [comment]
Yes. I thought it should be without dynamic
