### ISSUE TITLE
what is wrong?

### ISSUE THREAD

**Issue by qq643316017** [shamblett/mqtt_client#189]
there has a wrong with linking ssl server in android, but ios is ok.

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/foundation/stack_frame.dart': Failed assertion: line 113 pos 12: 'match != null': Expected  to match RegExp: pattern=^(.+) (\d+):(\d+)\s+(.+)$ flags=.

**Comment by shamblett** [comment]
I'm not a flutter user so I have no idea what this means, however it has nothing to do with the client, I'd ask on a flutter/Dart list.
