### ISSUE TITLE
Wildcard topic subscriptions

### ISSUE THREAD

**Issue by shamblett** [shamblett/mqtt_client#19]
Currently the client allows subscriptions to wildcard topics(my/topic/#) and receives publications for these , e.g we would get my/topic/fred, mytopic/bill etc however on reception these are not propagated through the client as /my/topic/fred doesn't match my/topic/# exactly. The client has code to ascertain whether an incoming publish topic does in fact match a subscription topic taking into account wildcards and should use this, not an exact match.

For compatibility with existing behaviour this should be selectable on the client when implemented.

**Comment by gokr** [comment]
The PR I made fixes this, but not selectable on the client. Personally I consider it a "bug" to not propagate if you do use wildcards in your subscription.

**Comment by shamblett** [comment]
Yep Ok, I'm being a little to cautious here, I don't like introducing surprises if people are relying on  certain beahviour(even if that behaviour is wrong), guess we don't really need to be worried about this yet.

**Comment by shamblett** [comment]
Wildcard topics now supported in release 1.9
