### ISSUE TITLE
Last Will Testament. 

### ISSUE THREAD

**Issue by Lokhozt** [shamblett/mqtt_client#193]
Hello, 
It'll be interesting to implement LWT in your library as it is an important aspect of the mqtt protocol.
I've haven't found anything in the API doc and the only issue related has been closed without any information.
Thank you.

**Comment by shamblett** [comment]
The will related settings are on the [connect message](https://pub.dev/documentation/mqtt_client/latest/mqtt_client/MqttConnectMessage-class.html), this allows the setting of the topic, qos, retain and message will related parameters. IIRC some users have reported problems with some brokers where you have to be careful what you send here, other than that I don't think any faults have been reported. If you encounter any problems please log them on this issue.

**Comment by Lokhozt** [comment]
My bad, Should have read the [example](https://github.com/shamblett/mqtt_client/blob/master/example/mqtt_server_client.dart) more carefully.
```dart
final connMess = MqttConnectMessage()
      .withClientIdentifier('Mqtt_MyClientUniqueId')
      .keepAliveFor(20) // Must agree with the keep alive set above or not set
      .withWillTopic('willtopic') // If you set this you must set a will message
      .withWillMessage('My Will message')
      .startClean() // Non persistent session for testing
      .withWillQos(MqttQos.atLeastOnce);
  print('EXAMPLE::Mosquitto client connecting....');
  client.connectionMessage = connMess;
```
Thank for your help.
Cheers.

**Comment by talksik** [comment]
@Lokhozt @shamblett would y'all know why it accepts string instead of byte buffer (which is what publish requires)?

I am using protobuf with dart and trying to make sure that the serialization is consistent for messages on a topic.

Thank you!

**Comment by shamblett** [comment]
From the spec -
```
3.1.3.3 Will Message
If the Will Flag is set to 1 the Will Message is the next field in the payload. The Will Message defines the Application Message that is to be published to the Will Topic as described in Section 3.1.2.5. This field consists of a two byte length followed by the payload for the Will Message expressed as a sequence of zero or more bytes. The length gives the number of bytes in the data that follows and does not include the 2 bytes taken up by the length itself.
```
So it can be a byte buffer, I assumed that usage of the word message implies an ASCII string. I can add this to the client if you wish.

**Comment by talksik** [comment]
aha thanks @shamblett . This was due to my lack of knowledge of the protocol, sorry for the noise. I assume most people using this package know MQTT well; I am just new to MQTT.

Now that I look at it, I think you did a great job making this as un-opinionated as possible, and a lightweight wrapper.
