### ISSUE TITLE
Reconnect exponential backoff

### ISSUE THREAD

**Issue by chrisdrobison** [shamblett/mqtt_client#195]
Is there a way to implement exponential backoff for auto reconnection?

**Comment by shamblett** [comment]
If you mean when going into auto reconnect if we fail we wait say 30 seconds, then try again, if we fail again we wait 120 seconds then try again etc. I can't see why no, I'll have a look at this.t

**Comment by chrisdrobison** [comment]
Yep, that's exactly what I mean.

**Comment by r3flow** [comment]
this is a parameterizable solution for reference: https://github.com/google/dart-neats/tree/master/retry

**Comment by shamblett** [comment]
Thinking about this its not that useful, autoreconnect once started continues until a connection is achieved or the client is manually disconnected, exponentially backing off in this process doesn't really add anything that I can see.
