### ISSUE TITLE
Flutter Web Error :(Unsupported operation: default SecurityContext getter)

### ISSUE THREAD

**Issue by kumarmohan7** [shamblett/mqtt_client#197]
Hi,

I got error in Flutter Web in mqtt_client, How to solve this issue.

Please give fix / solution quickly.

![image](https://user-images.githubusercontent.com/7358397/85862856-f12bf000-b7df-11ea-9510-9ea6319b1038.png)

Thank You
Mohankumar

**Comment by shamblett** [comment]
Your trying to use mqtt_server_client in a Flutter web app, this won't work, you need to use mqtt_browser_client in browser based apps.

**Comment by bilalhq** [comment]
Even after using mqtt_browser_client I am getting the same error `Unsupported operation: default SecurityContext getter`

**Comment by shamblett** [comment]
As per the comment above, you are trying to use the server client in a web app, you have to use mqtt_browser_client, not mqtt_server_client.

**Comment by amazingye** [comment]
> As per the comment above, you are trying to use the server client in a web app, you have to use mqtt_browser_client, not mqtt_server_client.

this helped, thanks

**Comment by SiliconEmpire** [comment]
i was having same error would it work on mobile

**Comment by JonathanIvyCR** [comment]
I wish chatgpt could've found this... or gemini.. or any of them... this worked. I replaced the MqttServerClient with MqttBrowserClient and it worked...
