### ISSUE TITLE
Is there a way to use MQTT over TLS

### ISSUE THREAD

**Issue by ldemyanenko** [shamblett/mqtt_client#199]
I didn't find a way yo use MQTT over TLS.

I'm getting error 
mqtt connect error: SocketException: Failed host lookup: 'mqtt://yyy.xxx.net/mqtt' (OS Error: No address associated with hostname, errno = 7)

I'm able to connect to the MQTT server through MQTT Explorer app with TLS encryption but wasn't able to connect from flutter using mqtt_client.

Please help me with this issue

**Comment by shamblett** [comment]
Not sure what you mean by 'over TLS', the mqtt_server_client supports connecting over secure sockets, see the example mqtt_server_client_secure.dart in the examples directory. The browser client supports only secure webcockets(wss).

**Comment by ldemyanenko** [comment]
I mean something like this 

MQTT and TLS
MQTT relies on the TCP transport protocol. By default, TCP connections do not use an encrypted communication. To encrypt the whole MQTT communication, many MQTT brokers (such as HiveMQ) allow use of TLS instead of plain TCP. If you use the username and password fields of the MQTT CONNECT packet for authentication and authorization mechanisms, you should strongly consider using TLS.

Port 8883 is standardized for a secured MQTT connection. The standardized name at IANA is “secure-mqtt”. Port 8883 is exclusively reserved for MQTT over TLS.

https://www.hivemq.com/blog/mqtt-security-fundamentals-tls-ssl/

**Comment by ldemyanenko** [comment]
![Screenshot 2020-07-08 at 10 00 18](https://user-images.githubusercontent.com/22637733/86888187-724d8600-c102-11ea-833d-8064f4a9c915.png)
I'm able to set the connection with MQTT Explorer using TLS setting. But didn't find this option in mqtt_client. I'm trying to use mqtt_client in mobile app

**Comment by shamblett** [comment]
Yes, then you need to use the mqtt_server_client configured to use secure sockets as I said above.

**Comment by ldemyanenko** [comment]
Do you have an example for this case?

**Comment by shamblett** [comment]
Yes, as I've said above ' see the example mqtt_server_client_secure.dart in the examples directory'.

**Comment by ldemyanenko** [comment]
Was able to connect with 
```
secure  = true
no certificate
port 8883

```

**Comment by lyxia** [comment]
> Was able to connect with
> 
> ```
> secure  = true
> no certificate
> port 8883
> ```

I have the same problem, can you give me a demo address or code snippet? Thank you

**Comment by lyxia** [comment]
> Was able to connect with
> 
> ```
> secure  = true
> no certificate
> port 8883
> ```

@ldemyanenko  I have the same problem, can you give me a demo address or code snippet? Thank you
