### ISSUE TITLE
Using polish character in topic

### ISSUE THREAD

**Issue by Pawel-Pluta** [shamblett/mqtt_client#201]
Hi,
I have problem when I want to use polish characters like: "ś", "ć", "ó"... in MQTT topic. When using WebSoket with [HiveMQ](http://www.hivemq.com/demos/websocket-client/) everything works fine. 

When subscribing to major topic where one of sub topic contains polish sign the MQTT client stops working. 

e.g. I subscribe to 'test/#' and there is topic 'test/świeca' on the broker and MQTT client is breaking. 

Can you help me resolve this problem?

**Comment by shamblett** [comment]
The client should be able to process these kinds of topics, the spec says 'Topic Names and Topic Filters are UTF-8 encoded strings, they MUST NOT encode to more than 65535 bytes'. I'll look at this.

**Comment by shamblett** [comment]
I think this may be a version issue, UTF8 topic strings are only fully supported on MQTT V311, could you check you are setting the version correctly on your client, i.e do a -
```
client.setProtocolV311();
```
If you are doing this I can't see it wouldn't work, could you turn logging on and attach a log output showing the breakage please.
