### ISSUE TITLE
Connection state is not being updated on loss of Internet connectivity

### ISSUE THREAD

**Issue by akshg05** [shamblett/mqtt_client#202]
I am trying to check if the client is still connected to broker by :
```
if (client != null &&
        client.connectionStatus.state == MqttConnectionState.connected) 
```
However, the client shows connected when there is a loss of internet connectivity on the device.
How is the connection state being updated for the client? I assume that if the ping pong calls fail then the client's connection state is changed to disconnected. Please correct me.
My keepAlive is set to 10 seconds currently.

Please help!

**Comment by shamblett** [comment]
Connection state is driven from an onDone or onError event from the socket itself if this does not happen the client will keep the connection state as connected not matter wht the state of your keep alive.

It looks as though whatever is causing the internet disconnection is not being reflected back jnto the Dart runtime.

You can monitor keep alive yourself using the pong callback, plese see the api docs for the client.

**Comment by akshg05** [comment]
Thank you for clarifying. I noticed the onDisconnect callback is being fired on loss of internet connectivity though. Could you suggest me the cleanest way of being aware of the client connection to the broker?

**Comment by shamblett** [comment]
If onDisconnected is being called then if you check the connection status post this event it should not say its connected(unless of course you have set auto-reconnect and its reconnected, which I assume you haven't), if it is its an error, I'll need a log of your connection session to see what's going on.
