### ISSUE TITLE
Security Alert: Your app contains embedded private keys or keystore files

### ISSUE THREAD

**Issue by chiragmittal19** [shamblett/mqtt_client#204]
For connecting to AWS IOT, we need private key which is put in assets. When we build the apk and upload it on Play Store, following warning is issued -

Security Alert: Your app contains embedded private keys or keystore files

This app contains one or more private keys or keystore files embedded in its published apk as listed at the end of this message. These embedded items can be accessed by third parties, which can raise a variety of different security concerns depending on what the key is used for. For example, if the private key is the signing key for your application, a third party could sign and distribute apps that replace your authentic apps or corrupt them. Such a party could also sign and distribute apps under your identity.

As a general security practice, we strongly recommend against embedding private keys and keystore files in apps, even if the keys are password protected or obfuscated. The most effective way to protect your private key and keystore files are not to circulate them.

Please remove your private keys and keystore files from your app at your earliest convenience. For more information about keeping your keys secure, please see https://developer.android.com/tools/publishing/app-signing.html.

You have a responsibility as a developer to secure your private key properly, at all times. Please note, applications with vulnerabilities that expose users to risk of compromise may be considered in violation of our "Malicious Behavior" policy and section 4.4 of the Developer Distribution Agreement.

    assets/flutter_assets/assets/private_key.pem

There has to be another way of adding a private key then.

**Comment by Deepak-GP** [comment]
Is there any solution for this issue?
