### ISSUE TITLE
protobuff issue

### ISSUE THREAD

**Issue by a22349** [shamblett/mqtt_client#205]
hi , how to publish  the protobuff object ? 

i use this but server side parse error for the protobuf object . 
request = new SomeProtobufObject()
builder = MqttClientPayloadBuilder();
Uint8List list = request.writeToBuffer();
var buffer = Uint8Buffer(list.length);
buffer.addAll(list);
builder.addBuffer(buffer);
client.publishMessage(topic, MqttQos.atLeastOnce, builder.payload);

is this client usage correct ? 

thanks

**Comment by a22349** [comment]
the error in server side is "Protocol message contained an invalid tag (zero)."

**Comment by shamblett** [comment]
I think this is wrong -
```
var buffer = Uint8Buffer(list.length);
buffer.addAll(list);
```
Your sizing a buffer then adding to it, so you'll end up with a buffer twice the size you need with only the second half filled. Try -
```
var buffer = Uint8Buffer();
buffer.addAll(list);
```
or 

```
final buffer = Uint8Buffer()..addAll(list);
```

**Comment by a22349** [comment]
thanks , now it works . 👍 

> I think this is wrong -
> 
> ```
> var buffer = Uint8Buffer(list.length);
> buffer.addAll(list);
> ```
> 
> Your sizing a buffer then adding to it, so you'll end up with a buffer twice the size you need with only the second half filled. Try -
> 
> ```
> var buffer = Uint8Buffer();
> buffer.addAll(list);
> ```
> 
> or
> 
> ```
> final buffer = Uint8Buffer()..addAll(list);
> ```
