### ISSUE TITLE
[How To] Set Retain flag to message to store it?

### ISSUE THREAD

**Issue by pranjal-joshi** [shamblett/mqtt_client#207]
I want to publish the message with `RETAIN = true` flag on the MQTT broker so whenever another client connects, they will get the message.
I have the following code to publish a message:
```
void publish({@required String topic, @required String message}) {
    final MqttClientPayloadBuilder builder = MqttClientPayloadBuilder();
    builder.addString(message);
    client.publishMessage(topic, MqttQos.exactlyOnce, builder.payload);
  }
```
**How to modify it so that I can set a RETAIN flag whenever necessary?**

**Comment by shamblett** [comment]
Retain is an optional parameter on the publish method
```
client.publishMessage(topic, MqttQos.exactlyOnce, builder.payload, retain = true);

```

**Comment by pranjal-joshi** [comment]
Thank you! Resolved 👍
