### ISSUE TITLE
How to set connect timeout?

### ISSUE THREAD

**Issue by Gintasz** [shamblett/mqtt_client#214]
How to set a timeout for connect? I get `SocketException: OS Error: Connection timed out, errno = 110, address = ...., port = ....`, however, it takes quite a long time to receive that, I need to shorten that period.

**Comment by shamblett** [comment]
There isn't one as such, there's a retry count which you can change, this defaults to 3, there's also a time between re tries which is 5 seconds, this is not changeable at the mo. So out of the box you should be seeing a maximum of 3*5 seconds time period before the client gives up. If you are seeing longer periods you may be getting hung on the network layer, its difficult to see without a log.
