### ISSUE TITLE
Background service.

### ISSUE THREAD

**Issue by uwejan** [shamblett/mqtt_client#216]
Hi, at some point am going to use flutter, and i will require the client to be working on the background. was wondering what would be the best approach on doing so.
Many thanks.

**Comment by shamblett** [comment]
This is more of a flutter issue than anything to do with the client, it has however been asked before, see #194 for more information. 
Your probably better asking on flutter lists than here.

**Comment by uwejan** [comment]
@shamblett Hi, i saw it there, but no solution provided, and i have no idea to message someone on github. thought someone here has a solution would bring it up. However feel free to close it if you think it should not be open.

**Comment by shamblett** [comment]
Its a fair question and it has been asked before unfortunately I can't really help you with this.
