### ISSUE TITLE
[bug] Quick unsub/sub could cause no sub

### ISSUE THREAD

**Issue by robertsLando** [shamblett/mqtt_client#220]
Two consecutive calls to unsubscribe - subscribe could result in no subscription. To avoid this you have to wait for unsubscribe callback to retrigger a new subscribe. Is this expected?

**Comment by shamblett** [comment]
Sort of, when you subscribe you get a subscription object back, when you unsubscribe you can do as you are doing and wait for the unsubscribe callback to be activated for that subscription or call unsubscribe then  continually check the subscriptions status, when it becomes not active then you can resubscribe. 

Unsubscription triggers a message exchange with the broker, until the broker confirms you are unsubscribed then you are not, so re subscribing will not cause a new subscription as you are still already subscribed if you take my meaning.

**Comment by robertsLando** [comment]
> Sort of, when you subscribe you get a subscription object back

Yes but I think this could be an issue, in my case I have some widgets that on creation subscribe to a topic, on dispose they unsubscribe, I wasn't able to understand why on hot reloads sometimes some widgets where empty and others not and I found this, I have implemented a workaround by creating a `List<string> unsubscribing` that contains topics that are waiting for unsubscribe callback and when I subscribe I check if that topic is waiting and in that case I don't immediatily subscribe but I remove that from unsubscribing and if I don't find that topic once unsubscribe triggers It means I have to resubscribe that. 

I'm not sure if this is expected or not, anyway you can close this for now if you think it's ok

**Comment by shamblett** [comment]
You seem to be doing the right thing i.e. waiting for the unsubscription somehow before re subscribing so this is OK.
