### ISSUE TITLE
why my MQTT auto disconnect

### ISSUE THREAD

**Issue by tongyangsheng** [shamblett/mqtt_client#226]
I found the connected of MQTT seems like always disconnect, and is it correct? I have done nothing but the connect has disconnect after a while

**Comment by shamblett** [comment]
Not sure what you mean by 'after a while' the client will only disconnect if you call disconnect, the broker disconnects or the network fails. I will need a log of the disconnect and the client version number to help you further.

**Comment by tongyangsheng** [comment]
I have found my problem, thanks bro! It's because I send false param to client

**Comment by KaranRajPradhan** [comment]
@tongyangsheng Hi! I seem to be facing the same problem. How did you solve this? What do you mean by "I send false param to client"?
