### ISSUE TITLE
Inverted if condition in mqtt_client_byte_buffer

### ISSUE THREAD

**Issue by coletz** [shamblett/mqtt_client#230]
DISCLAIMER: I could be totally wrong on my assumption

Hi, I was debugging an issue with this library and found something that seems pretty strange [here](https://github.com/shamblett/mqtt_client/blob/93b0cc31a79096001c7adbf8c42f0331798680aa/lib/src/utility/mqtt_client_byte_buffer.dart#L171). Seems like the if/else branches are inverted in my opinion. 
Anyway since this code isn't changed since a lot of time ago and I haven't found any other bug mentioning this, maybe I'm just wrong

**Comment by shamblett** [comment]
You are totally right! Well spotted,  updated this now the fix will be in the next release of the package.

**Comment by shamblett** [comment]
Fix in version 8.1.0
