### ISSUE TITLE
connect server whith path

### ISSUE THREAD

**Issue by chals1258** [shamblett/mqtt_client#235]
How could I connect to the following server with path?

ws://xxxxxx.com:8083/mqtt

Thanks

**Comment by shamblett** [comment]
Just use it as your server hostname, i.e 
```
MqttServerClient('ws://xxxxxx.com:8083/mqtt', '');
```
should work, or if you prefer leave out the port specification and use the withPort constructor to specify it.
If you do this and it fails please turn on logging, at the top of the log you should see the actual connection string in use, if you have any problems just post the log output.
