### ISSUE TITLE
How to connect to local network broker.

### ISSUE THREAD

**Issue by sureace** [shamblett/mqtt_client#236]
Hi,
     I am trying to connect MQTT broker which runs local network. when try to connect, i am not able to connect and getting errors. Could you please tell us how to connect broker locally. I am able to connect when i user some other apps or MQTT client to the same. Some apps are using tcp:// before the ip. i tried in that way but failed.

MqttServerClient client = MqttServerClient.withPort("192.168.1.7:8888", "Mobile 1", 1883);
try{
      await client.connect();
    }catch(err){
      print("Exception : $err");
      client.disconnect();
    }

Thanks
Suresh

**Comment by shamblett** [comment]
Your mixing the url port specifier with the withPort constructor, you can use this '192.168.1.7:8888' without the 1883 port specified or use '192.168.1.7' and specify the port as you have done, if you are using 1883 you don't need to bother, its the default for standard MQTT non secure use.

You shouldn't need 'tcp://' however this is passed straight to your networking layer so may work.

**Comment by sureace** [comment]
Hi Shamblett,
           Thanks for the prompt response. I tried as you said but no success. Could you check my code and logs
Code
-------
`MqttServerClient client = MqttServerClient.withPort("192.168.1.7", "Mobile 1", 1883);
    client.logging(on: true);
    client.onConnected = onConnected;
    client.onDisconnected = onDisconnected;
    client.onSubscribed = onSubscribed;
    client.onSubscribeFail = onSubscribeFail;
    client.onUnsubscribed = onUnsubscribed;
    client.pongCallback = onPing;

    final connMessage = MqttConnectMessage()
      .keepAliveFor(60)
      .withWillTopic("sensors/drone01/altitude")
      .withWillMessage("Hello this is from message connected")
      .startClean()
      .withWillQos(MqttQos.atLeastOnce);

    client.connectionMessage = connMessage;

    try{
      await client.connect();
    }catch(err){
      print("Exception : $err");
      client.disconnect();
    }
    print("Connect state : ${client.connectionStatus.state}");
    if(client != null && client.connectionStatus.state ==  MqttConnectionState.connected) {
      client.updates.listen((List<MqttReceivedMessage<MqttMessage>> c) {
        final MqttPublishMessage message = c[0].payload;
        final payload = MqttPublishPayload.bytesToStringAsString(message.payload.message);
        print('Received message:$payload from topic: ${c[0].topic}>');
      });
    }
void onConnected(){
    print("%%%Connected");
  }

  void onDisconnected(){
    print("%%%Disconnected");
  }

  void onSubscribed(String topic){
    print("Subscribed Topic : $topic");
  }

  void onSubscribeFail(String topic){
    print("Subscribe failed : $topic");
  }

  void onUnsubscribed(String topic){
    print("Unsubscribed : $topic");
  }

  //PING response received
  void onPing(){
    print('Ping response client callback invoked');
  }
`

Logs
---------
`I/ViewRootImpl@bd01521[MainActivity]( 2157): ViewPostIme pointer 0
I/ViewRootImpl@bd01521[MainActivity]( 2157): ViewPostIme pointer 1
I/flutter ( 2157): 2-2020-12-11 16:47:48.124088 -- MqttConnectionHandlerBase::connect - server 192.168.1.7, port 1883
I/flutter ( 2157): 2-2020-12-11 16:47:48.124325 -- SynchronousMqttServerConnectionHandler::internalConnect entered
I/flutter ( 2157): 2-2020-12-11 16:47:48.124402 -- SynchronousMqttServerConnectionHandler::internalConnect - initiating connection try 0, auto reconnect in progress false
I/flutter ( 2157): 2-2020-12-11 16:47:48.124477 -- SynchronousMqttServerConnectionHandler::internalConnect - insecure TCP selected
I/flutter ( 2157): 2-2020-12-11 16:47:48.124549 -- SynchronousMqttServerConnectionHandler::internalConnect - calling connect
I/flutter ( 2157): 2-2020-12-11 16:47:48.124619 -- MqttNormalConnection::connect - entered
I/flutter ( 2157): 2-2020-12-11 16:47:48.323667 -- MqttServerConnection::_startListening
I/flutter ( 2157): 2-2020-12-11 16:47:48.324410 -- SynchronousMqttServerConnectionHandler::internalConnect - connection complete
I/flutter ( 2157): 2-2020-12-11 16:47:48.324864 -- SynchronousMqttServerConnectionHandler::internalConnect sending connect message
I/flutter ( 2157): 2-2020-12-11 16:47:48.325140 -- MqttConnectionHandlerBase::sendMessage - MQTTMessage of type MqttMessageType.connect
I/flutter ( 2157): Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
I/flutter ( 2157): Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=true, WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=false, UserNameFlag=false, KeepAlive=60
I/flutter ( 2157): MqttConnectPayload - client identifier is : 
I/flutter ( 2157): 2-2020-12-11 16:47:48.327540 -- SynchronousMqttServerConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
I/flutter ( 2157): 2-2020-12-11 16:47:48.502441 -- MqttConnectionBase::_onError - calling disconnected callback
I/flutter ( 2157): 2-2020-12-11 16:47:48.502866 -- MqttConnectionBase::_onDone - calling disconnected callback
E/flutter ( 2157): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: SocketException: OS Error: Connection reset by peer, errno = 104, address = 192.168.1.7, port = 57124
E/flutter ( 2157): 
I/flutter ( 2157): 2-2020-12-11 16:47:53.336726 -- SynchronousMqttServerConnectionHandler::internalConnect - post sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
I/flutter ( 2157): 2-2020-12-11 16:47:53.337124 -- SynchronousMqttServerConnectionHandler::internalConnect - initiating connection try 1, auto reconnect in progress false
I/flutter ( 2157): 2-2020-12-11 16:47:53.337540 -- SynchronousMqttServerConnectionHandler::internalConnect - insecure TCP selected
I/flutter ( 2157): 2-2020-12-11 16:47:53.337609 -- SynchronousMqttServerConnectionHandler::internalConnect - calling connect
I/flutter ( 2157): 2-2020-12-11 16:47:53.337665 -- MqttNormalConnection::connect - entered
I/flutter ( 2157): 2-2020-12-11 16:47:53.453220 -- MqttServerConnection::_startListening
I/flutter ( 2157): 2-2020-12-11 16:47:53.454620 -- SynchronousMqttServerConnectionHandler::internalConnect - connection complete
I/flutter ( 2157): 2-2020-12-11 16:47:53.454978 -- SynchronousMqttServerConnectionHandler::internalConnect sending connect message
I/flutter ( 2157): 2-2020-12-11 16:47:53.455654 -- MqttConnectionHandlerBase::sendMessage - MQTTMessage of type MqttMessageType.connect
I/flutter ( 2157): Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 78
I/flutter ( 2157): Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=true, WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=false, UserNameFlag=false, KeepAlive=60
I/flutter ( 2157): MqttConnectPayload - client identifier is : 
I/flutter ( 2157): 2-2020-12-11 16:47:53.458621 -- SynchronousMqttServerConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
I/flutter ( 2157): 2-2020-12-11 16:47:53.459767 -- MqttConnectionBase::_onError - calling disconnected callback
I/flutter ( 2157): 2-2020-12-11 16:47:53.460455 -- MqttConnectionBase::_onDone - calling disconnected callback
E/flutter ( 2157): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: SocketException: Write failed (OS Error: Connection reset by peer, errno = 104), address = 192.168.1.7, port = 57126
E/flutter ( 2157): #0      _NativeSocket.write (dart:io-patch/socket_patch.dart:968:34)
E/flutter ( 2157): #1      _RawSocket.write (dart:io-patch/socket_patch.dart:1643:15)
E/flutter ( 2157): #2      _Socket._write (dart:io-patch/socket_patch.dart:2076:18)
E/flutter ( 2157): #3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:1824:26)
E/flutter ( 2157): #4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:1798:11)
E/flutter ( 2157): #5      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 2157): #6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 2157): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 2157): #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter ( 2157): #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter ( 2157): #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
E/flutter ( 2157): #11     _StreamController._add (dart:async/stream_controller.dart:682:7)
E/flutter ( 2157): #12     _StreamController.add (dart:async/stream_controller.dart:624:5)
E/flutter ( 2157): #13     _StreamSinkImpl.add (dart:io/io_sink.dart:156:17)
E/flutter ( 2157): #14     _Socket.add (dart:io-patch/socket_patch.dart:1923:38)
E/flutter ( 2157): #15     MqttServerConnection.send (package:mqtt_client/src/connectionhandling/server/mqtt_client_mqtt_server_connection.dart:97:13)
E/flutter ( 2157): #16     MqttConnectionHandlerBase.sendMessage (package:mqtt_client/src/connectionhandling/mqtt_client_mqtt_connection_handler_base.dart:168:18)
E/flutter ( 2157): #17     SynchronousMqttServerConnectionHandler.internalConnect (package:mqtt_client/src/connectionhandling/server/mqtt_client_synchronous_mqtt_server_connection_handler.dart:97:7)
E/flutter ( 2157): <asynchronous suspension>
E/flutter ( 2157): #18     MqttConnectionHandlerBase.connect (package:mqtt_client/src/connectionhandling/mqtt_client_mqtt_connection_handler_base.dart:102:13)
E/flutter ( 2157): #19     MqttClient.connect (package:mqtt_client/src/mqtt_client.dart:251:30)
E/flutter ( 2157): #20     MqttServerClient.connect (package:mqtt_client/src/mqtt_server_client.dart:83:24)
E/flutter ( 2157): #21     _MQTTDemoState.connect (package:flutter_dev_new/mqtt/MQTTDemo.dart:61:20)
E/flutter ( 2157): #22     _MQTTDemoState.build.<anonymous closure> (package:flutter_dev_new/mqtt/MQTTDemo.dart:115:53)
E/flutter ( 2157): #23     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter ( 2157): #24     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter ( 2157): #25     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 2157): #26     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter ( 2157): #27     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 2157): #28     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter ( 2157): #29     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter ( 2157): #30     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter ( 2157): #31     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 2157): #32     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 2157): #33     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 2157): #34     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 2157): #35     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter ( 2157): #36     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter ( 2157): #37     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter ( 2157): #38     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter ( 2157): #39     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter ( 2157): #40     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter ( 2157): #41     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 2157): #42     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 2157): #43     
I/flutter ( 2157): 2-2020-12-11 16:47:58.464684 -- SynchronousMqttServerConnectionHandler::internalConnect - post sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
I/flutter ( 2157): 2-2020-12-11 16:47:58.465341 -- SynchronousMqttServerConnectionHandler::internalConnect - initiating connection try 2, auto reconnect in progress false
I/flutter ( 2157): 2-2020-12-11 16:47:58.465661 -- SynchronousMqttServerConnectionHandler::internalConnect - insecure TCP selected
I/flutter ( 2157): 2-2020-12-11 16:47:58.466230 -- SynchronousMqttServerConnectionHandler::internalConnect - calling connect
I/flutter ( 2157): 2-2020-12-11 16:47:58.466604 -- MqttNormalConnection::connect - entered
I/flutter ( 2157): 2-2020-12-11 16:47:58.513357 -- MqttServerConnection::_startListening
I/flutter ( 2157): 2-2020-12-11 16:47:58.515747 -- SynchronousMqttServerConnectionHandler::internalConnect - connection complete
I/flutter ( 2157): 2-2020-12-11 16:47:58.516568 -- SynchronousMqttServerConnectionHandler::internalConnect sending connect message
I/flutter ( 2157): 2-2020-12-11 16:47:58.517431 -- MqttConnectionHandlerBase::sendMessage - MQTTMessage of type MqttMessageType.connect
I/flutter ( 2157): Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 78
I/flutter ( 2157): Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=true, WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=false, UserNameFlag=false, KeepAlive=60
I/flutter ( 2157): MqttConnectPayload - client identifier is : 
I/flutter ( 2157): 2-2020-12-11 16:47:58.522873 -- SynchronousMqttServerConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
I/flutter ( 2157): 2-2020-12-11 16:47:58.551306 -- MqttConnectionBase::_onError - calling disconnected callback
I/flutter ( 2157): 2-2020-12-11 16:47:58.552226 -- MqttConnectionBase::_onDone - calling disconnected callback
E/flutter ( 2157): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: SocketException: OS Error: Connection reset by peer, errno = 104, address = 192.168.1.7, port = 57128
E/flutter ( 2157): 
I/flutter ( 2157): 2-2020-12-11 16:48:03.530800 -- SynchronousMqttServerConnectionHandler::internalConnect - post sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
I/flutter ( 2157): 2-2020-12-11 16:48:03.531126 -- SynchronousMqttServerConnectionHandler::internalConnect failed
I/flutter ( 2157): Exception : mqtt-client::NoConnectionException: The maximum allowed connection attempts ({3}) were exceeded. The broker is not responding to the connection request message (Missing Connection Acknowledgement?
I/flutter ( 2157): 2-2020-12-11 16:48:03.533337 -- MqttConnectionHandlerBase::disconnect - entered
I/flutter ( 2157): 2-2020-12-11 16:48:03.533864 -- MqttConnectionHandlerBase::_performConnectionDisconnect entered
I/flutter ( 2157): %%%Disconnected
I/flutter ( 2157): Connect state : MqttConnectionState.disconnected
I/flutter ( 2157): Cool!!!!`

Thanks,
Suresh

**Comment by sureace** [comment]
Hi shamblett,
                     Thanks for your prompt response. I updated my code as said and removed connectionMessage code then it is connecting to broker.
Code
--------
`MqttServerClient client = MqttServerClient.withPort("192.168.1.7", "Mobile 1", 1883);
    client.logging(on: true);
    client.onConnected = onConnected;
    client.onDisconnected = onDisconnected;
    client.onSubscribed = onSubscribed;
    client.onSubscribeFail = onSubscribeFail;
    client.onUnsubscribed = onUnsubscribed;
    client.pongCallback = onPing;try{
      await client.connect();
    }catch(err){
      print("Exception : $err");
      client.disconnect();
    }
    print("Connect state : ${client.connectionStatus.state}");
    if(client != null && client.connectionStatus.state ==  MqttConnectionState.connected) {
      client.updates.listen((List<MqttReceivedMessage<MqttMessage>> c) {
        final MqttPublishMessage message = c[0].payload;
        final payload = MqttPublishPayload.bytesToStringAsString(message.payload.message);
        print('Received message:$payload from topic: ${c[0].topic}>');
      });
    }`

Thanks
Suresh.

**Comment by sureace** [comment]
Thanks for your support. Now i am exploring the api. it will be very helpful if you provide the examples or documentation for this plugin.

**Comment by shamblett** [comment]
There are many examples in the examples directory of the git repo, the documentation is as per standard dart packages, see[ here](https://pub.dev/packages/mqtt_client)
