### ISSUE TITLE
mqtt_client service not working when screen lock or app killed

### ISSUE THREAD

**Issue by Husnain-Asharf** [shamblett/mqtt_client#237]
Hi, first of all I want to thank for a great package that helped me a lot. Really thanks for that.
- I found that when screen is lock or app killed mqtt service not work. It disconnect from broker.
- I am trying use it for background location.
- Is there any work around for this issue ?

**Comment by shamblett** [comment]
You could look through the closed issues, there have been a number of issues on running the client in background on flutter, I'm not a flutter user so I can't help here. I believe some flutter users did end up with workarounds.
