### ISSUE TITLE
issu in the connection to server (flutter web)

### ISSUE THREAD

**Issue by ShalevCohen2112** [shamblett/mqtt_client#238]
I am trying to connect to the mqtt server and receiving an error
SynchronousMqttBrowserConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none

log:
1-2020-12-28 11:39:40.667 -- MqttConnectionHandlerBase::connect - server ws://$url, port 9001
1-2020-12-28 11:39:40.669 -- SynchronousMqttBrowserConnectionHandler::internalConnect entered
1-2020-12-28 11:39:40.671 -- SynchronousMqttBrowserConnectionHandler::internalConnect - initiating connection try 0, auto reconnect in progress false
1-2020-12-28 11:39:40.673 -- SynchronousMqttBrowserConnectionHandler::internalConnect - calling connect
1-2020-12-28 11:39:40.675 -- MqttBrowserWsConnection::connect - entered
1-2020-12-28 11:39:40.678 -- MqttBrowserWsConnection::connect -  WS URL is ws://$url:9001
1-2020-12-28 11:39:40.686 -- MqttBrowserWsConnection::connect - connection is waiting
1-2020-12-28 11:39:40.986 -- MqttBrowserWsConnection::connect - websocket has erred
1-2020-12-28 11:39:40.988 -- SynchronousMqttBrowserConnectionHandler::internalConnect - connection complete
1-2020-12-28 11:39:40.989 -- SynchronousMqttBrowserConnectionHandler::internalConnect sending connect message
1-2020-12-28 11:39:40.991 -- MqttConnectionHandlerBase::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=true, WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=true, UserNameFlag=true, KeepAlive=60
MqttConnectPayload - client identifier is : 

1-2020-12-28 11:39:40.998 -- SynchronousMqttBrowserConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none

my code `
import 'dart:io';

import 'package:mqtt_client/mqtt_browser_client.dart';
import 'package:mqtt_client/mqtt_client.dart';
import 'package:mqtt_client/mqtt_server_client.dart';

class MQTTManager {

  Future<MqttBrowserClient> connect() async {
    MqttBrowserClient client = MqttBrowserClient.withPort('ws://$url', 'flutter_client', 9001);

    client.logging(on: true);
    client.onConnected = onConnected;
    client.onDisconnected = onDisconnected;
    client.onUnsubscribed = onUnsubscribed;
    client.onSubscribed = onSubscribed;
    client.onSubscribeFail = onSubscribeFail;
    client.pongCallback = pong;

    final connMessage = MqttConnectMessage()
        .authenticateAs('$user_name', '$password!!')
        .keepAliveFor(60)
        .withWillTopic('willtopic')
        .withWillMessage('Will message')
        .startClean()
        .withWillQos(MqttQos.atLeastOnce);
    client.connectionMessage = connMessage;
    try {
      await client.connect();
    } catch (e) {
      print('Exception: $e');
      client.disconnect();
    }

    client.updates.listen((List<MqttReceivedMessage<MqttMessage>> c) {
      final MqttPublishMessage message = c[0].payload;
      final payload =
      MqttPublishPayload.bytesToStringAsString(message.payload.message);

      print('Received message:$payload from topic: ${c[0].topic}>');
    });

    return client;
  }
  // connection succeeded
  void onConnected() {
    print('Connected');
  }

// unconnected
  void onDisconnected() {
    print('Disconnected');
  }

// subscribe to topic succeeded
  void onSubscribed(String topic) {
    print('Subscribed topic: $topic');
  }

// subscribe to topic failed
  void onSubscribeFail(String topic) {
    print('Failed to subscribe $topic');
  }

// unsubscribe succeeded
  void onUnsubscribed(String topic) {
    print('Unsubscribed topic: $topic');
  }

// PING response received
  void pong() {
    print('Ping response client callback invoked');
  }

}`

**Comment by shamblett** [comment]
From the log -
```
1-2020-12-28 11:39:40.678 -- MqttBrowserWsConnection::connect - WS URL is ws://$url:9001
1-2020-12-28 11:39:40.686 -- MqttBrowserWsConnection::connect - connection is waiting
1-2020-12-28 11:39:40.986 -- MqttBrowserWsConnection::connect - websocket has erred
```
Your not connecting to the server, your hostname looks odd, what does ' ws://$url:9001' resolve to, i.e. what does '$url' mean?

**Comment by ShalevCohen2112** [comment]
$url =my server URL, it's a production server and I have been told not to provide it.
do you need more logs or someone else?

**Comment by shamblett** [comment]
OK in that case it may be that your server doesn't like the default headers sent as part of the protocol, look at the websocketProtocols setting in the mqtt_client API. Initially try the MqttClientConstants.protocolsSingleDefault, if this doesn't work try no headers i.e. '[]'.
