### ISSUE TITLE
Dart 2.0

### ISSUE THREAD

**Issue by josvos** [shamblett/mqtt_client#24]
Dart 2.0 is now a stable release.  Please support it (and with that Flutter).

**Comment by shamblett** [comment]
Yep, starting this now, I'll track progress on this issue.

**Comment by shamblett** [comment]
Ok, an update, the client is now clean as far as dart 2 is concerned, except there is still a problem with observable, documented [here](https://github.com/dart-lang/observable/issues/54) with a fix. I've bumped the issue, see if we get a response in the short term

**Comment by daadu** [comment]
The package's requirement are _SDK version >=2.0.0 <3.0.0_ 
Flutter's current version is linked with  _Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760_

That is why getting version solving error while doing `flutter packages upgrade` for the HEAD of this repo.

```Running "flutter packages upgrade" in flutter_app...               
The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.

Because flutter_app depends on mqtt_client from git which requires SDK version >=2.0.0 <3.0.0, version solving failed.
```

**Comment by daadu** [comment]
does any of previous version support flutter? i would like to give that a try.

**Comment by shamblett** [comment]
You could try this fork

url: https://github.com/benbehringer/mqtt_client.git

Its what the flutter guys are currently using, I may relax the constraints to 

sdk: ">=2.0.0-dev <3.0.0"

when I get back round to this.

**Comment by josvos** [comment]
FWIW: @benbehringer's package also does not work anymore with an up-to-date Flutter package/tree due to an event_bus upgrade (the on() method does not accept parameters anymore...) :-(.

**Comment by shamblett** [comment]
Yep, I fixed this a while back I think, the client is now using event_bus 1.0.1.

**Comment by shamblett** [comment]
OK, to allow us to progress with this I've pulled what I need from observable into the client for now and fixed the above problem. This may also help with issue 25 ultimately.

**Comment by shamblett** [comment]
OK, re-published the client at 3.0.0(to make a nice break) for Dart 2.0, please pull this and report any breakages, note this is fine on the VM, no analyzer warnings, unit test + integration tests run OK.

**Comment by josvos** [comment]
Great!  I can confirm that this works with Flutter dev 0.7.1, Dart version 2.1.0-dev.1.0.flutter-ccb16f7282, now without overriding Observable.

**Comment by benbehringer** [comment]
> Great! I can confirm that this works with Flutter dev 0.7.1, Dart version 2.1.0-dev.1.0.flutter-ccb16f7282, now without overriding Observable.

+1! Works without modification now! Thanks!
