### ISSUE TITLE
TCP sticky/unpacking  Problem

### ISSUE THREAD

**Issue by luuillu** [shamblett/mqtt_client#240]
TCP is a stream protocol, When receive data from server,  the data may be  incomplete MQTT package,  if it happened, the client should wait remain data and then make a completed MQTT package。It seems that this library just throw exception。

**Comment by shamblett** [comment]
As far as I know the client does this, it builds incomplete packets and does not decode them until it has received the message length bytes as specified in the header. Please turn logging on and post me a log output of what you are seeing.

**Comment by luuillu** [comment]
Yes, You are Right,  I  misunderstand the code, Thank you for your answer。
