### ISSUE TITLE
Null Safety Updates

### ISSUE THREAD

**Issue by shamblett** [shamblett/mqtt_client#241]

**Comment by shamblett** [comment]
Null safety updates on the null safety branch, needs unit testing before merge.

**Comment by SaeDocas** [comment]
Any updates on this?

**Comment by shamblett** [comment]
Yes, coincidently just doing this now, maybe out later today or tomorrow.

**Comment by shamblett** [comment]
Complete, package re-released at version 9.0.0

**Comment by SaeDocas** [comment]
Thanks man, really appreciate it.
