### ISSUE TITLE
autoReconnect

### ISSUE THREAD

**Issue by rh-08** [shamblett/mqtt_client#243]
class：MqttConnectionHandlerBase
method： autoReconnect

After the connection is successful, you need to add a line of code：connection.onDisconnected = onDisconnected;

otherwise will not reconnect if disconnect again.

**Comment by rh-08** [comment]
I want to add timeout when connecting to the socket

**Comment by shamblett** [comment]
Your right about the fault you reported above, this is a good spot, it also fixes #231 so I've applied the fix tested it and re published the package at 8.2.0, thanks again.

**Comment by shamblett** [comment]
As for your second point we are really at the mercy of the Dart implementation here, as far as I can see you can't set a timeout on a socket, see [SocketOption](https://api.dart.dev/stable/2.10.5/dart-io/SocketOption-class.html). If you mean some other timeout please specify what is needed with more detail.

**Comment by rh-08** [comment]
Socket.connect(server, port, timeout: new Duration(seconds: 5)).then((dynamic socket) {

}）

**Comment by shamblett** [comment]
Yes OK, I didn't see this, it only seems to be on TCP sockets, not web sockets so we can only do this in the server client. I've raised #245 so we can track this separately as its nothing to do with auto reconnect.
