### ISSUE TITLE
How to connect mqtt broker which runs local wifi network.

### ISSUE THREAD

**Issue by sureace** [shamblett/mqtt_client#249]
Hi,
    I am running MQTT broker locally in Linux system which has ip address of 192.168.1.7. And i am trying to connect and  subscribe a topic from client with in the local wifi network which has ip as 192.168.1.3. When i try it, i am getting error like connection refused. SocketException: OS Error: Connection refused, errno = 111, address = 192.168.1.3, port = 45474. Could you please tell me, is it possible to connect local wifi network from one system to another system ? . No web server is installed at broker system. MQTT server is up and running directly.
Thanks,
Sureace

**Comment by shamblett** [comment]
Yes, your connection is being refused at the network level, check your firewall settings for the address and whatever MQTT port you are using, e.g. 1883

**Comment by sureace** [comment]
Thanks @shamblett. Every time i get prompt response from you. I am running MQTT broker on default port i.e 1883. I turned off router firewall as well. But still i am getting same error.
Thanks,
Sureace

**Comment by shamblett** [comment]
This error is being reported by the network layer in flutter, the package is only really printing it out for you. It is saying it can't connect to 192.168.1.7 from the host you are running it on, you need to look at your local network setup, can you ping your server from your client device?

**Comment by Jazzykhan** [comment]
i am having the same issue i can ping too and i can connect form mobile devices and latptop too but not from flutter. i changed the port and tried manythings. @shamblett  Thanks
