### ISSUE TITLE
Using Observable vs. plain Streams

### ISSUE THREAD

**Issue by josvos** [shamblett/mqtt_client#25]
I'm wondering if there is a good reason to use the Observable package, instead of providing a "plain" Dart Stream.

In case of using mqtt_client in complex programs (e.g. Flutter with in my case also rxdart, having its own Observable class), it's less easy to integrate (mixing up objects from several external packages).

**Comment by shamblett** [comment]
Refer to issue 24, the observable package is now internal to the client allow a local fix up, we may bea bale to do more here now if needed.

**Comment by shamblett** [comment]
The integration of Observeable seems to be working OK on flutter and elsewhere.  I'll close this issue for now.
