### ISSUE TITLE
SocketException: Failed host lookup: 'wss://xyz.com/mqtt' (OS Error: nodename nor servname provided, or not known, errno = 8)

### ISSUE THREAD

**Issue by 97loser** [shamblett/mqtt_client#250]
Hey,
 I'm unable to connect MQTT Box using wss 
 
what I have tried =>
            MqttServerClient client = MqttServerClient("wss://xyz.com/mqtt", 'Client_'+             DateTime.now().millisecondsSinceEpoch.toString(),maxConnectionAttempts: 100);

      client.logging(on: true);
      /// Set secure working
      client.secure = true;
      client.port = 443; // Secure port number for mosquitto, no client certificate required
      client.useWebSocket=true;
      client.autoReconnect=true;
      client.keepAlivePeriod = 30;
      client.onDisconnected = onDisconnected;
      final connMess = MqttConnectMessage()
          .withClientIdentifier('Client_'+ DateTime.now().millisecondsSinceEpoch.toString())
          .keepAliveFor(30)
          .startClean() // Non persistent session for testing
          .withWillQos(MqttQos.atMostOnce);
      print('Mosquitto client connecting....');
      client.connectionMessage = connMess;
      try {
        await client.connect();
      } on Exception catch (e) {
        print('client exception - $e');
        //mqttDisconnect();
        isConnected = false;
      }
      /// Check we are connected
      if(client.connectionStatus.state == MqttConnectionState.connected) {
        print('Mosquitto client connected : TOPIC $topic');
        isConnected = true;
      }
      else {
        print(
            'ERROR Mosquitto client connection failed - disconnecting, state is ${client.connectionStatus.state}');
       // mqttDisconnect();
        isConnected = false;
      }

what I have got =>

   flutter: Mosquitto client connecting....
flutter: 1-2021-02-09 10:31:00.239415 -- MqttConnectionHandlerBase::connect - server wss://xyz.com/mqtt, port 443
flutter: 1-2021-02-09 10:31:00.244005 -- SynchronousMqttServerConnectionHandler::internalConnect entered
flutter: 1-2021-02-09 10:31:00.244261 -- SynchronousMqttServerConnectionHandler::internalConnect - initiating connection try 0, auto reconnect in progress false
flutter: 1-2021-02-09 10:31:00.245081 -- SynchronousMqttServerConnectionHandler::internalConnect - secure selected
flutter: 1-2021-02-09 10:31:00.246108 -- SynchronousMqttServerConnectionHandler::internalConnect - calling connect
flutter: 1-2021-02-09 10:31:00.247043 -- MqttSecureConnection::connect - entered
flutter: 1-2021-02-09 10:31:00.641875 -- MqttConnectionBase::_onError - calling disconnected callback
flutter: client exception - SocketException: Failed host lookup: 'wss://xyz.com/mqtt' (OS Error: nodename nor servname provided, or not known, errno = 8)
flutter: ERROR Mosquitto client connection failed - disconnecting, state is MqttConnectionState.faulted

**Comment by shamblett** [comment]
You are failing to resolve your hostname -
```
flutter: client exception - SocketException: Failed host lookup: 'wss://xyz.com/mqtt' (OS Error: nodename nor servname provided, or not known, errno = 8)
```
hence the client disconnects.

**Comment by 97loser** [comment]
@shamblett 
 How can I resolve hostname issue bcz I able to connect same url Using MQTT-Box.
 Thank you for reply .

**Comment by shamblett** [comment]
I don't know what an MQTT-Box is, hostname resolution has nothing to do with the client, its the flutter environment you are running it in on whatever host you are using, use standard networking commands to find out why the hostname isn't being resolved on your platform.

**Comment by pengzhenkun** [comment]
使用 ws:// 需要使用 MqttBrowserClient 来进行连接，不然连接无效，现我遇到的问题是 MqttBrowserClient 进行 ws:// 还是无法成功

**Comment by shamblett** [comment]
You don't need to use MqttBrowserClient to use ws, MwttServerClient also supports ws by setting the useWebSocket property, also no matter which client you use you may have to set the protocol headers depending on what your broker expects, see the websocketProtocolString api. Please read the API docs completely and check your broker logs to see why its refusing the connection, the client is doing nothing wrong here.
