### ISSUE TITLE
How to use this lib Android + iOS + Web?

### ISSUE THREAD

**Issue by ganeshshirole** [shamblett/mqtt_client#255]
Getting this error

../../.pub-cache/hosted/pub.dartlang.org/mqtt_client-8.2.0/lib/mqtt_browser_client.dart:11:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^

**Comment by shamblett** [comment]
Your using the browser client, this only works in the browser, if you  are using the VM or flutter you need mqtt_server_client.

**Comment by ganeshshirole** [comment]
> Your using the browser client, this only works in the browser, if you are using the VM or flutter you need mqtt_server_client.

I am using both mqtt_browser_client and mqtt_client and also added platform conditions still getting this error

../../.pub-cache/hosted/pub.dartlang.org/mqtt_client-8.2.0/lib/mqtt_browser_client.dart:11:8: Error: Not found: 'dart:html'
import 'dart:html';

**Comment by shamblett** [comment]
You should be using just the server client, your imports should be -
```
import 'package:mqtt_client/mqtt_client.dart';
import 'package:mqtt_client/mqtt_server_client.dart';
```

Don't import the browser client.

**Comment by ganeshshirole** [comment]
> You should be using just the server client, your imports should be -
> 
> ```
> import 'package:mqtt_client/mqtt_client.dart';
> import 'package:mqtt_client/mqtt_server_client.dart';
> ```
> 
> Don't import the browser client.

How can I write conditional import like if I want to import browser client for web and mqtt_server_client for mobile?

**Comment by ganeshshirole** [comment]
> > You should be using just the server client, your imports should be -
> > ```
> > import 'package:mqtt_client/mqtt_client.dart';
> > import 'package:mqtt_client/mqtt_server_client.dart';
> > ```
> > 
> > 
> > Don't import the browser client.
> 
> How can I write conditional import like if I want to import browser client for web and mqtt_server_client for mobile?

But why you are not manage platforms in library only so I will use common client for web and mobile both

**Comment by shamblett** [comment]
I haven't got round to doing it, when this package was written I'm not sure conditional imports existed, if you want this urgently please submit a pull request. Conditional  imports are described [here](https://dart.dev/guides/libraries/create-library-packages) in the Dart docs.

**Comment by alamsz** [comment]
> > You should be using just the server client, your imports should be -
> > ```
> > import 'package:mqtt_client/mqtt_client.dart';
> > import 'package:mqtt_client/mqtt_server_client.dart';
> > ```
> > 
> > 
> > Don't import the browser client.
> 
> How can I write conditional import like if I want to import browser client for web and mqtt_server_client for mobile?

I do have this problem since I want to use the lib both in app and web, my solution to solve the problem was

```
import import 'app.dart' if (dart.library.html) 'web.dart' as mqttsetup;

...

var client = mqttsetup.setup(serverAddress, uniqueID, port);
```
where app.dart will contain such as the following

```
MqttClient setup(String serverAddress, String uniqueID, int port) {
  return MqttServerClient.withPort(serverAddress, uniqueID, port);
}

```

and web.dart 

```
MqttClient setup(String serverAddress, String uniqueID, int port) {
  return MqttBrowserClient.withPort(serverAddress, uniqueID, port);
}
```

**Comment by shamblett** [comment]
Ok thanks for this, I'll put it in the examples directory, may be of use to other users.

**Comment by ganeshshirole** [comment]
Thank you for your response

**Comment by shamblett** [comment]
Complete, package re published at version 9.1.0.

**Comment by ganeshshirole** [comment]
Thank you so much

**Comment by adojang** [comment]
A few years late to the party, but can confirm this works properly. Would love to see some kind of autoselect/autoimport feature built into the library if it is still being maintained.
