### ISSUE TITLE
MqttBrowserClient web 连接失败

### ISSUE THREAD

**Issue by pengzhenkun** [shamblett/mqtt_client#257]
使用 MqttServerClient 在客户端可成功连接，
使用 MqttBrowserClient 连接在web平台上连接失败，连接用的是 ws:// ， ws:// 连接在测试工具上测试通过
报错信息如下：
mqtt-client::NoConnectionException: The maximum allowed connection attempts ({3}) were exceeded. The broker is not responding to the connection request message (Missing Connection Acknowledgement?

**Comment by shamblett** [comment]
What is the problem you are reporting exactly? Your broker is not responding to the connection message from the client. Whys are you using both MqttServerClient and MqttBrowserClient?

**Comment by pengzhenkun** [comment]
我没有同时使用MqttServerClient和MqttBrowserClient，我的项目一直使用MqttServerClient，一切正常，现想适应Web端，无法成功连接时使用MqttBrowserClient。
报错信息如下：
................................................................................
mqtt-client::NoConnectionException: The maximum allowed connection attempts ({1}) were exceeded. The broker is not responding to the connection request message (Missing Connection Acknowledgement?
................................................................................
使用 MqttBrowserClient的区别在于需要加 "ws://" 前缀和跟换端口，但这还是无法让我连接成功

**Comment by pengzhenkun** [comment]
在使用 "ws://" 我的服务器有一个子路径 ws://xxx.xxx.xxx.xxx:9093/mqtt 请问 "/mqtt" 这个路径是怎么填？

**Comment by shamblett** [comment]
Yes, but the problem being reported is that your broker is not responding to the connect message you are sending, not that you are doing anything wrong with the client, you need to look at your broker logs to find out why.

**Comment by pengzhenkun** [comment]
https://www.emqx.cn/blog/using-mqtt-in-flutter
我使用的 emqx 官方推荐的本开源项目地址测试

**Comment by pengzhenkun** [comment]
测试连接报错400：
html_dart2js.dart:31719 WebSocket connection to 'ws://broker.emqx.io:8083/mqtt' failed: Error during WebSocket handshake: Unexpected response code: 400

使用在线测试工具可以连接
http://tools.emqx.io
