### ISSUE TITLE
HandshakeException: Handshake error in client (OS Error:   	CERTIFICATE_VERIFY_FAILED:)  on ios simulator. but working fine on android and ios device

### ISSUE THREAD

**Issue by prabha024** [shamblett/mqtt_client#259]

**Comment by prabha024** [comment]
_client = MqttServerClient(Constants.host, clientIdentifier);
 _client.port = 8883;
    _client.keepAlivePeriod = 20;
    _client.logging(on: true);
    _client.secure = true;
      /// Add the connection callback
    _client.onConnected = onConnected;
    _client.onSubscribed = onSubscribed;
    _client.onUnsubscribed = onUnsubscribed;
    _client.onDisconnected = onDisconnected;
final ByteData crtData = await rootBundle.load('assets/ca.crt');

     final securityContext = SecurityContext.defaultContext;
    securityContext.setTrustedCertificatesBytes(crtData.buffer.asUint8List());

    _client.securityContext = securityContext;
    _client.setProtocolV311();


    final MqttConnectMessage connMess = MqttConnectMessage()
        .withClientIdentifier(clientIdentifier)
        .withWillTopic(
            'willtopic') // If you set this you must set a will message
        .withWillMessage('0')
        .startClean() // Non persistent session for testing
        .withWillQos(MqttQos.atLeastOnce);
    print('EXAMPLE::Mqtt client connecting....');
    _client.connectionMessage = connMess;

this is my initialize method

**Comment by shamblett** [comment]
If it works OK on Android and IOS then it looks like its the IOS Simulator at fault, the package doesn't know where its running, it doesn't do anything different in this respect. Do you have your certs installed on the simulator?

**Comment by prabha024** [comment]
no, i haven't installed certificate on simulator like mobile. so do i need to install??

**Comment by shamblett** [comment]
Well, seeing as the fault you have reported is a certification error it may be  a good idea to install the certs on the simulator and see what happens next.

**Comment by prabha024** [comment]
Sorry for late response .. i found a way to solve this issue by adding the bad certificate function.
