### ISSUE TITLE
why is there so much "!" in the version 9?

### ISSUE THREAD

**Issue by baloyou** [shamblett/mqtt_client#262]
in example(example/mqtt_server_client.dart)

<img width="634" alt="image" src="https://user-images.githubusercontent.com/5190664/112457140-6c81f880-8d96-11eb-8020-58426ff6edd7.png">

on line(94) `if (client.connectionStatus!.state == MqttConnectionState.connected) {`

Many files have this problem

**Comment by shamblett** [comment]
These are null checks, they were added by the Dart NNBD migration tool. I'm sure you are right in that going through all the code you could reduce these, maybe drastically, however on a package this size I haven't had time to do this.  I'll gladly accept pull requests in this area.

**Comment by baloyou** [comment]
> These are null checks, they were added by the Dart NNBD migration tool. I'm sure you are right in that going through all the code you could reduce these, maybe drastically, however on a package this size I haven't had time to do this. I'll gladly accept pull requests in this area.

Ah!! I see! Thank you (i just started to learn flutter)
