### ISSUE TITLE
Unable to connect using mdns name

### ISSUE THREAD

**Issue by sureace** [shamblett/mqtt_client#264]
Hi @shamblett ,
                        I am trying to establish connection using mdns name. But it is giving me error like @MQTT mybroker.local: Exception : SocketException: Failed host lookup: 'mybroker.local' (OS Error: No address associated with hostname, errno = 7)

It connects fine when i try with ip address like 192.168.1.6. When i tried using third party mqtt clients like MQTT fx or mosquito_pub or _sub it connects successfully with both ip and mdns name. Could you please guide me how to resolve this issue.

Code
-----
client = MqttServerClient.withPort("mybroker.local", "4eb49ca055194de7aa16a335bd333c9c", 1883, maxConnectionAttempts: 3);
await client.connect("xxxxx", "password").timeout(Duration(seconds: 15));

**Comment by shamblett** [comment]
The client doesn't resolve the hostname, this is done by the Dart network layer runtime. Suggest tou ask on a Dart list as to how to get name resolution working with mdns.

**Comment by sureace** [comment]
> The client doesn't resolve the hostname, this is done by the Dart network layer runtime. Suggest tou ask on a Dart list as to how to get name resolution working with mdns.

Thank you @shamblett

**Comment by raphasauer** [comment]
@sureace were you able to connect to the broker with mdns?
