### ISSUE TITLE
not connecting to the aws endpoint

### ISSUE THREAD

**Issue by ashleshp** [shamblett/mqtt_client#265]
W/IInputConnectionWrapper(19012): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(19012): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(19012): getTextAfterCursor on inactive InputConnection
I/flutter (19012): EXAMPLE::Mosquitto start client connecting....
I/flutter (19012): 2021-04-07 18:30:03.190576 -- SynchronousMqttServerConnectionHandler::internalConnect entered
I/flutter (19012): 2021-04-07 18:30:03.194777 -- SynchronousMqttServerConnectionHandler::internalConnect - initiating connection try 0
I/flutter (19012): 2021-04-07 18:30:03.195153 -- SynchronousMqttServerConnectionHandler::internalConnect - secure selected
I/flutter (19012): 2021-04-07 18:30:03.197825 -- MqttSecureConnection::connect
I/flutter (19012): EXAMPLE::Mosquitto client connecting....
I/flutter (19012): 2021-04-07 18:30:05.712594 -- MqttSecureConnection::connect - securing socket
I/flutter (19012): 2021-04-07 18:30:05.714934 -- MqttSecureConnection::connect - start listening
I/flutter (19012): 2021-04-07 18:30:05.716122 -- MqttServerConnection::_startListening
I/flutter (19012): 2021-04-07 18:30:05.724299 -- SynchronousMqttServerConnectionHandler::internalConnect - connection complete
I/flutter (19012): 2021-04-07 18:30:05.724968 -- SynchronousMqttServerConnectionHandler::internalConnect sending connect message
I/flutter (19012): 2021-04-07 18:30:05.731167 -- MqttConnectionHandlerBase::sendMessage - MQTTMessage of type MqttMessageType.connect
I/flutter (19012): Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
I/flutter (19012): Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=false, WillQos=MqttQos.atMostOnce, WillRetain=false, PasswordFlag=false, UserNameFlag=false, KeepAlive=60
I/flutter (19012): MqttConnectPayload - client identifier is : Flutter_Android
I/flutter (19012): 2021-04-07 18:30:05.750538 -- SynchronousMqttServerConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
I/flutter (19012): 2021-04-07 18:30:08.063978 -- MqttConnectionBase::_onDone - calling disconnected callback
I/flutter (19012): EXAMPLE::OnDisconnected client callback - Client disconnection
I/flutter (19012): 2021-04-07 18:30:10.760714 -- SynchronousMqttServerConnectionHandler::internalConnect - post sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
I/flutter (19012): 2021-04-07 18:30:10.762585 -- SynchronousMqttServerConnectionHandler::internalConnect - initiating connection try 1
I/flutter (19012): 2021-04-07 18:30:10.763335 -- SynchronousMqttServerConnectionHandler::internalConnect - secure selected
I/flutter (19012): 2021-04-07 18:30:10.763856 -- MqttSecureConnection::connect
I/flutter (19012): 2021-04-07 18:30:11.725857 -- MqttSecureConnection::connect - securing socket
I/flutter (19012): 2021-04-07 18:30:11.726797 -- MqttSecureConnection::connect - start listening
I/flutter (19012): 2021-04-07 18:30:11.727213 -- MqttServerConnection::_startListening
I/flutter (19012): 2021-04-07 18:30:11.727885 -- SynchronousMqttServerConnectionHandler::internalConnect - connection complete
I/flutter (19012): 2021-04-07 18:30:11.728161 -- SynchronousMqttServerConnectionHandler::internalConnect sending connect message
I/flutter (19012): 2021-04-07 18:30:11.728683 -- MqttConnectionHandlerBase::sendMessage - MQTTMessage of type MqttMessageType.connect
I/flutter (19012): Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 29
I/flutter (19012): Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=false, WillQos=MqttQos.atMostOnce, WillRetain=false, PasswordFlag=false, UserNameFlag=false, KeepAlive=60
I/flutter (19012): MqttConnectPayload - client identifier is : Flutter_Android
I/flutter (19012): 2021-04-07 18:30:11.731332 -- SynchronousMqttServerConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
I/flutter (19012): 2021-04-07 18:30:14.074418 -- MqttConnectionBase::_onDone - calling disconnected callback
I/flutter (19012): EXAMPLE::OnDisconnected client callback - Client disconnection
I/flutter (19012): 2021-04-07 18:30:16.738657 -- SynchronousMqttServerConnectionHandler::internalConnect - post sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
I/flutter (19012): 2021-04-07 18:30:16.739748 -- SynchronousMqttServerConnectionHandler::internalConnect - initiating connection try 2
I/flutter (19012): 2021-04-07 18:30:16.740390 -- SynchronousMqttServerConnectionHandler::internalConnect - secure selected
I/flutter (19012): 2021-04-07 18:30:16.740898 -- MqttSecureConnection::connect
I/flutter (19012): 2021-04-07 18:30:17.764957 -- MqttSecureConnection::connect - securing socket
I/flutter (19012): 2021-04-07 18:30:17.765793 -- MqttSecureConnection::connect - start listening
I/flutter (19012): 2021-04-07 18:30:17.765998 -- MqttServerConnection::_startListening
I/flutter (19012): 2021-04-07 18:30:17.766517 -- SynchronousMqttServerConnectionHandler::internalConnect - connection complete
I/flutter (19012): 2021-04-07 18:30:17.766744 -- SynchronousMqttServerConnectionHandler::internalConnect sending connect message
I/flutter (19012): 2021-04-07 18:30:17.767098 -- MqttConnectionHandlerBase::sendMessage - MQTTMessage of type MqttMessageType.connect
I/flutter (19012): Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 29
I/flutter (19012): Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=false, WillQos=MqttQos.atMostOnce, WillRetain=false, PasswordFlag=false, UserNameFlag=false, KeepAlive=60
I/flutter (19012): MqttConnectPayload - client identifier is : Flutter_Android
I/flutter (19012): 2021-04-07 18:30:17.768971 -- SynchronousMqttServerConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
I/flutter (19012): 2021-04-07 18:30:20.115883 -- MqttConnectionBase::_onDone - calling disconnected callback
I/flutter (19012): EXAMPLE::OnDisconnected client callback - Client disconnection
I/flutter (19012): 2021-04-07 18:30:22.776764 -- SynchronousMqttServerConnectionHandler::internalConnect - post sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
I/flutter (19012): 2021-04-07 18:30:22.779191 -- SynchronousMqttServerConnectionHandler::internalConnect failed
I/flutter (19012): EXAMPLE::client exception - mqtt-client::NoConnectionException: The maximum allowed connection attempts ({3}) were exceeded. The broker is not responding to the connection request message (Missing Connection Acknowledgement?
I/flutter (19012): Disconnected
I/flutter (19012): EXAMPLE::OnDisconnected client callback - Client disconnection
I/flutter (19012): EXAMPLE::OnDisconnected callback is solicited, this is correct

**Comment by shamblett** [comment]
Which means the broker is not accepting your connection. Its tricky connecting to AWS, have a look at issues #246 and #260 amongst others

**Comment by ruchith696** [comment]
even i am facing same issue

**Comment by ashleshp** [comment]
Now its connected to cloud and I can send strings to it.
But please can you tell me how do I connect it to a thing shadow in aws IoT.

**Comment by shamblett** [comment]
There is no shadow handler function, this would be too specific to AWS., there's no concept of this in MQTT. I don't use AWS so don't know how to do this but IIRC it has been brought up before, look through the closed issues for AWS and shadow.

**Comment by ruchith696** [comment]
@ashleshp  can you share your code or can you explain what changes you made to make it work

**Comment by ruchith696** [comment]
class MQTTManager {
  // Private instance of client

  // LocationToJsonConverter locationToJsonConverter = LocationToJsonConverter();
  JsonToLocationConverter jsonToLocationConverter = JsonToLocationConverter();
  Keys data = Keys();
  LocationData streamLocation;

  final MQTTAppState _currentState;
  MqttServerClient _client;

  MQTTManager({@required MQTTAppState state}) : _currentState = state;
  void prepareMqttClient() async {
    // await data.fetchkeys();
    initializeMQTTClient(data);
    await connect();
  }

  void initializeMQTTClient(Keys data) async {
    _client = MqttServerClient.withPort(data.serverUri, 'cli', data.port);
    _client.secure = true;
    final context = SecurityContext.defaultContext;

    final clientAuth =
        await rootBundle.loadString('assets/aws/ruchith-root-ca.pem');
    context.setClientAuthoritiesBytes(clientAuth.codeUnits);

    final trustedCer =
        await rootBundle.loadString('assets/aws/ruchith-certificate.pem.crt');
    context.useCertificateChainBytes(trustedCer.codeUnits);

    final privatekey =
        await rootBundle.loadString('assets/aws/ruchith-private.pem.key');
    context.usePrivateKeyBytes(privatekey.codeUnits);

    _client.keepAlivePeriod = 20;
    _client.logging(on: true);
    _client.onConnected = onConnected;
    _client.onSubscribed = onSubscribed;
    _client.onDisconnected = onDisconnected;

    _client.setProtocolV311();

    final MqttConnectMessage connMess = await MqttConnectMessage();
    _client.connectionMessage = connMess;
  }

  // Connect to the host
  Future<void> connect() async {
    assert(_client != null);
    try {
      print('EXAMPLE::Mosquitto start client connecting....');
      _currentState.setAppConnectionState(MQTTAppConnectionState.connecting);
      await _client.connect();

      if (_client.connectionStatus.state == MqttConnectionState.connected) {
        _currentState.setAppConnectionState(MQTTAppConnectionState.connected);
        print('EXAMPLE::Mosquitto client connected....');

          _client.subscribe(data.topicName, MqttQos.atLeastOnce);
          print('subscribed');
          _client.updates.listen((List<MqttReceivedMessage<MqttMessage>> c) {
            final MqttPublishMessage recMess = c[0].payload;
            final String newLocation =
                MqttPublishPayload.bytesToStringAsString(recMess.payload.message);
            final Map<String, dynamic> newLocationJson = jsonDecode(newLocation);
            print(newLocationJson);
            print(jsonToLocationConverter.convert(newLocation).latitude);
            _currentState
                .setReceivedText(jsonToLocationConverter.convert(newLocation));
          });
      }
    } on Exception catch (e) {
      print('EXAMPLE::client exception - $e');
      disconnect();
    }
  }

  void disconnect() {
    print('Disconnected');
    _client.disconnect();
  }

  void publish(String message) {
    final MqttClientPayloadBuilder builder = MqttClientPayloadBuilder();
    builder.addString(message);
    _client.publishMessage(
        data.topicName, MqttQos.exactlyOnce, builder.payload);
  }

  /// The subscribed callback
  void onSubscribed(String topic) {
    print('EXAMPLE::Subscription confirmed for topic $topic');
  }

  /// The unsolicited disconnect callback
  void onDisconnected() {
    print('EXAMPLE::OnDisconnected client callback - Client disconnection');
    if (_client.connectionStatus.returnCode ==
        MqttConnectReturnCode.noneSpecified) {
      print('EXAMPLE::OnDisconnected callback is solicited, this is correct');
    }
    _currentState.setAppConnectionState(MQTTAppConnectionState.disconnected);
  }

  /// The successful connect callback
  void onConnected() {
    print("yoooooo");
    _currentState.setAppConnectionState(MQTTAppConnectionState.connected);
    print('EXAMPLE::Mosquitto client connected....');
    _client.subscribe(data.topicName, MqttQos.atLeastOnce);
    _client.updates.listen((List<MqttReceivedMessage<MqttMessage>> c) {
      final MqttPublishMessage recMess = c[0].payload;
      final String newLocationJson =
          MqttPublishPayload.bytesToStringAsString(recMess.payload.message);
      _currentState
          .setReceivedText(jsonToLocationConverter.convert(newLocationJson));
      print(
          'EXAMPLE::Change notification:: topic is <${c[0].topic}>, payload is <-- $newLocationJson -->');
      print('');
    });

    print(
        'EXAMPLE::OnConnected client callback - Client connection was sucessful');
  }
}





when trying to listen to a MQTT topic by connecting to aws iot core, onConnected call back is not working. if  code under onConnected callback is written inside connect() function it is able to subcribe succesfully and listen when a message is published to topic.
Also i am unable to publish to topic, client is getting disconnected when trying to publish.

**Comment by ruchith696** [comment]
if this package works perfectly with Google IoT Core, i am open to switch from aws and any example on how to use with Google IoT  would be great.

**Comment by shamblett** [comment]
There is an example in the examples directory called iot_core.dart

**Comment by ruchith696** [comment]
_client.subscribe(data.topicName, MqttQos.atLeastOnce);
      print('subscribed');
      _client.updates.listen((List<MqttReceivedMessage<MqttMessage>> c) {
        final MqttPublishMessage recMess = c[0].payload;
        final String newLocation =
            MqttPublishPayload.bytesToStringAsString(recMess.payload.message);
        final Map<String, dynamic> newLocationJson = jsonDecode(newLocation);
        print(newLocationJson);
        print(jsonToLocationConverter.convert(newLocation).latitude);
        _currentState
            .setReceivedText(jsonToLocationConverter.convert(newLocation));
      });

is the above code enough to receive message ??
