### ISSUE TITLE
multiple client connections to same endpoint(AWS IoT)

### ISSUE THREAD

**Issue by ashleshp** [shamblett/mqtt_client#268]
Is it a problem if we connect many devices to a same endpoint?
Because when Iam connecting and subscribing to same endpoint and topic ,one of the device is automatically disconnecting.

**Comment by shamblett** [comment]
I don't know what you mean by 'device', assuming you mean separate instantiations of the client whether they be on the same or different hosts then yes this is possible. Each client must use a different client id so the broker(endpoint) knows who the client is, if the clients are being disconnected its probably the broker doing this, you need to look at the disconnection reason in the log output.

Unless you are doing load balancing in an MQTT5 set up, which your not, there is no reason to to use more than one client on one host device, unless of course you are attaching to multiple different brokers. A single client can handle 1000's of subscriptions with no problem, you do not need to use more than one.

Other users have raised this as a workaround in a flutter environment whereby they seem to use a separate client for each subscription, this is not the way to go, in all of these cases they eventually worked out how to use one client in flutter, please look through the closed issues for examples.

**Comment by ashleshp** [comment]
Thanks alot,
You were right I was not using unique client id's , which called disconnect .
So I figured out this
`    Future<String> _getId() async {
      var deviceInfo = DeviceInfoPlugin();
      if (Platform.isIOS) { // import 'dart:io'
        var iosDeviceInfo = await deviceInfo.iosInfo;
        return iosDeviceInfo.identifierForVendor; // unique ID on iOS
      } else {
        var androidDeviceInfo = await deviceInfo.androidInfo;
        return androidDeviceInfo.androidId; // unique ID on Android
      }
    }
`
