### ISSUE TITLE
How to listen disconnect event after connection successful.

### ISSUE THREAD

**Issue by sureace** [shamblett/mqtt_client#270]
Hi @shamblett ,
                           When connecting to mqtt broker, if i call client.disconnect(), it is triggering client.onDisconnected method that is working fine. But after successfully connected, if any reason mqtt broker is disconnected, i am not getting any event. Could you please tell me how can listen connect and disconnect events after connected successfully.

code
------
client = MqttServerClient.withPort(ip,identifier,port, maxConnectionAttempts: 3);
client.autoReconnect = true;
client.onConnected = onConnected;
client.onDisconnected = onDisconnected;

Thanking you,
Sureace.

**Comment by shamblett** [comment]
You have autoReconnect set to true, onDisconnect will not be called unless you invoke it like you have done, see the API docs [here](https://pub.dev/documentation/mqtt_client/latest/mqtt_client/MqttClient/onDisconnected.html).

**Comment by sureace** [comment]
Hi @shamblett ,
                   Thanks for the prompt response. Could you please tell, when and how autoReconnect works ? and when to use client.doAutoReconnect(force: true);. Can we set any time for auto reconnect check.

Code
---------
client.autoReconnect = true;
client.onAutoReconnected = onAutoReconnected;

Thanking you,
Sureace

**Comment by shamblett** [comment]
How auto reconnect works should be clear from the API documentation, if not please point out to me what you don't understand and I'll update it. There is no time interval, once auto reconnect is triggered it will try forever until you stop it or it re connects.

You wouldn't normally call client.doAutoReconnect, just setting client.autoReconnect = true; is sufficient, the client handles the auto reconnect sequence for you. The example doesn't use client.doAutoReconnect, it is provided only if for some reason you wish to force an auto reconnect from your code.

**Comment by sureace** [comment]
Thank you @shamblett

**Comment by mars000** [comment]
how can i detect the status of the connection when using autoreconnect ? (i.e. what api call can I use)
Also - how do I change the time window that autoreconnect attempts to reconnect ?

**Comment by shamblett** [comment]
As I've said above see the API docs [here](https://pub.dev/documentation/mqtt_client/latest/mqtt_client/MqttClient/onDisconnected.html). 
Also check the example https://github.com/shamblett/mqtt_client/blob/master/example/mqtt_server_client_autoreconnect.dart for callback usage.
Also as I've already said above there is no time interval, once auto reconnect is triggered it will try forever until you stop it or it re connects.
