### ISSUE TITLE
Upgrade to websocket

### ISSUE THREAD

**Issue by boks21** [shamblett/mqtt_client#274]
Hi,
when connecting to some websockets I got: "was not upgraded to websocket"
It happens always, only to some websockets.

[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 1.22.6 at D:\FlutterSDK\flutter
    • Framework revision 9b2d32b605 (3 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

Thanks.

**Comment by shamblett** [comment]
Some brokers are particular about the protocol header, others not so, look at the client API for websocket protocols -
```
 List<String>? websocketProtocolString;

  /// User definable websocket protocols. Use this for non default websocket
  /// protocols only if your broker needs this. There are two defaults in
  /// MqttWsConnection class, the multiple protocol is the default. Some brokers
  /// will not accept a list and only expect a single protocol identifier,
  /// in this case use the single protocol default. You can supply your own
  /// list, or to disable this entirely set the protocols to an
  /// empty list , i.e [].
```
