### ISSUE TITLE
How to create password encoded JWT token to connect google IOT Core

### ISSUE THREAD

**Issue by sureace** [shamblett/mqtt_client#276]
Hi @shamblett ,
                         Could you please tell us, how to generate password encoded JWT token to connect google IOT Core.
I am following this example.
https://github.com/shamblett/mqtt_client/blob/master/example/iot_core.dart

Thanking you,
Sureace.

**Comment by shamblett** [comment]
Have a look at this example [project](https://github.com/shamblett/iot-home). This uses the MQTT client to connect to IOT Core. It shows how to generate a JWT token and generates basic sensor test data to test with. 

I'll update the example to point to this.

**Comment by shamblett** [comment]
Example updated. Package re published at version 9.3.0.

**Comment by sureace** [comment]
Hi @shamblett ,
                       What a great and prompt response.
Thank you
