### ISSUE TITLE
MqttPublishPayload.bytesToStringAsString is missing null safety support?

### ISSUE THREAD

**Issue by handicanam** [shamblett/mqtt_client#287]
Hi,
I am using 3.9.1 mqtt_client version.
And I noticed that "message" property that's part of MqttPublishPayload has null safety support therefore MqttPublishPayload.bytesToStringAsString needs to support null safety as well, from my understanding.

Thank you very much.

**Comment by shamblett** [comment]
I think this is being handled under #286, I'll update this issue when this is complete.

**Comment by shamblett** [comment]
Complete, package re published at version 9.3.2
