### ISSUE TITLE
Example in pub.dev is missing (opinion)

### ISSUE THREAD

**Issue by guyluz11** [shamblett/mqtt_client#288]
When opening the [example tab](https://pub.dev/packages/mqtt_client/example) in pub.dev (to someone new to this package/me) it looks like this package is new and the example was not inserted yet as all the code is commented.
  

![image](https://user-images.githubusercontent.com/9304740/122247906-5e90cf00-ced0-11eb-9f31-325aece06844.png)

I understand that it have comments where every type of example can be found and developers need to search for it and I think alone it is bad practice.

My suggestion is to add in the bottom simple code example for the most common use case, and add links (only without the url) inside the comments to the examples locations if it is possible.

**Comment by shamblett** [comment]
Complete, package re published at version 9.3.2
