### ISSUE TITLE
How to get onDisconnected callback for when software abort occurs

### ISSUE THREAD

**Issue by Tejas-MD** [shamblett/mqtt_client#291]
On my app, if the internet is unstable and MQTT disconnects, I would like to inform my user. 
But unfortunately, disconnection due to common issues like internet does not call `OnDisconnected()` but rather prints out:
`Unhandled Exception: SocketException: OS Error: Software caused connection abort, errno = 103, address = test.mosquitto.org, port = 55451` on the console. 

How do I fix this? I don't think there's a way I can catch this exception in my code?

**Comment by shamblett** [comment]
This has cropped up before, see #231 , there are others, its more a Dart runtime issue than anything the client is doing. You could try an exception handler in your code but this doesn't always work. I'll check the browser code again just in case but there may be nothing I can do here. If you find anything please post a fix here all pull requests gladly accepted.

Are you using autoreconnect? You may be better enabling this and hooking into an appropriate callback.

**Comment by Tejas-MD** [comment]
I do have autoreconnect enabled.

So in short, a good workaround would be to use the `OnAutoReconnect` method.

Thanks for your help and work into the package.

**Comment by shamblett** [comment]
Yes, I believe there are two callbacks., one when auto reconnect is started and one when it completes, take your pick, either way if these are called you have lost connection and are reconnecting, onDisconnect isn't used if auto reconnect is enabled.

**Comment by Tejas-MD** [comment]
Thanks for your time. I will try this out and reopen the issue if something goes wrong.
