### ISSUE TITLE
Question how to use MqttClient subscribe

### ISSUE THREAD

**Issue by lgLindstrom** [shamblett/mqtt_client#294]
Hi

This code is part of the MqttClient:

 ```
 /// Initiates a topic subscription request to the connected broker
  /// with a strongly typed data processor callback.
  /// The topic to subscribe to.
  /// The qos level the message was published at.
  /// Returns the subscription or null on failure
  Subscription? subscribe(String topic, MqttQos qosLevel) {
    if (connectionStatus!.state != MqttConnectionState.connected) {
      throw ConnectionException(connectionHandler?.connectionStatus?.state);
    }
    return subscriptionsManager!.registerSubscription(topic, qosLevel);
  }
```

I am trying to understand how to use it. Cant find any examples in the repository. 
As I read the documentation you should be able to subscribe to specific topics without filtering.
I would be a neat feature to have.

**Comment by shamblett** [comment]
When you say you can't find any examples in the repository presumably you have looked in the examples directory. The mqtt_server_client.dart example clearly shows the usage of client.subscribe and also the usage of its associated onSubscribed callback. There are many other examples in this directory.

Filtering is not used on subscription, you just subscribe to your topic at your QoS level, filtering is used to filter out topics of interest from the client.updates stream interface, i.e. from received publish messages.

**Comment by lgLindstrom** [comment]
Sorry if I not express myself clearly enough.

client.subscribe  returns a variable of class Subscription.

My interpretation of the documentation is that Subscription contains a Stream that of subscribed topic data.

I am not able to get this to work so I started to look for examples simular this:

```
Subscription sub = client.subscribe("topic",qos);
..
..
```

Maybe I don't understand the documentation correctly?

**Comment by shamblett** [comment]
The API says -
```
/// Returns the subscription or null on failure
``
If you look at Subscription you are correct in that it contains a changes stream, this however is incorrect, there is no reason now this class should be inherited from observeable, the returned value is for your own use. I will update the package to remove this.

As I say above you have to listen on client.updates and filter topics as you wish.

**Comment by lgLindstrom** [comment]
Okay,
Thanks for the fast update on the subject. 
I will close the issue.
