### ISSUE TITLE
How do I listen for MqttClient's connectionStatus changes?(keep alive enabled)

### ISSUE THREAD

**Issue by yullg** [shamblett/mqtt_client#295]
I want to get instant notification when the connection is not available

**Comment by shamblett** [comment]
Attach a function to the onDisconnected callback, if you are using auto reconnect use the onAutoReconnect or onAutoReconnected callbacks.

**Comment by yullg** [comment]
> Attach a function to the onDisconnected callback, if you are using auto reconnect use the onAutoReconnect or onAutoReconnected callbacks.

Thinks, I understand  what should I do.
