### ISSUE TITLE
Can you make MqttClientPayloadBuilder a Builder?

### ISSUE THREAD

**Issue by thomasbeauvais** [shamblett/mqtt_client#296]
Love your project, great help!

It would be cool if `MqttClientPayloadBuilder` was an actual builder based on the "builder pattern" where it returns itself to string statements. 

Shouldn't really break anything since it's all `void` returns anyway.

Cheers.

**Comment by shamblett** [comment]
I take your point, can't think of any good reason not to do this. I'll update the package.

**Comment by shamblett** [comment]
This update is now in the development branch and will be in the next release.

**Comment by shamblett** [comment]
This is in the 9.5.0 release.
