### ISSUE TITLE
mqtt_client dont work in flutter web

### ISSUE THREAD

**Issue by sinasaeedi8013** [shamblett/mqtt_client#297]
hello
i want too use mqtt in my flutter web project but web i click on "Connect" button i received this error:

════════ Exception caught by gesture ═══════════════════════════════════════════
Unsupported operation: default SecurityContext getter
══════════════════════════════════════════════════════════════════════

why???

**Comment by shamblett** [comment]
Looks as though you are using MqttServerClient, for web/browser applications you should be using MqttBrowserClient.

**Comment by sinasaeedi8013** [comment]
> Looks as though you are using MqttServerClient, for web/browser applications you should be using MqttBrowserClient.

Ooo,thanks it works.🌹

**Comment by rpungin** [comment]
You need to use `MqttBrowserClient` on the web and `MqttServerClient` on mobile. I did it like [this](https://github.com/shamblett/mqtt_client/issues/442#issuecomment-2342619674).
