### ISSUE TITLE
Is there a way to get last msg of topic only once without subscribeing to it?

### ISSUE THREAD

**Issue by guyluz11** [shamblett/mqtt_client#300]
Searching for a way to get the last msg that was sent in specific topic.
I need to get it only once each time (not a stream) and even if the value didn't changed so subscribe to the topic is not the wanted functionality.

Is there a built in method like that?,
`getLastMsgFromTopic(topicString)`

**Comment by shamblett** [comment]
In answer to your question no there isn't, how do you know its the last message? Do you mean you unsubscribe and get the message that came in last? Youcan't get anythin from a topic unless you subscribe to it.

**Comment by guyluz11** [comment]
Yep, I meant 

> unsubscribe and get the message that came in last

I understand that this is not possible. 
Thanks.
