### ISSUE TITLE
publish Persian character

### ISSUE THREAD

**Issue by sgsm74** [shamblett/mqtt_client#307]
Hey guys
When I want to publish a message in Persian language, the Response is kinda like this
this is what I sent : سلام دنیا
and response:
3 D ' E  / F Ì '

**Comment by shamblett** [comment]
When you say response where are you getting this from? If you mean the payload then its probably in UTF8 so you will need to to convert it, see the [payload convertor](url) classes and/or the [payload builder ](https://github.com/shamblett/mqtt_client/blob/master/lib/src/utility/mqtt_client_payload_builder.dart)class.

**Comment by sgsm74** [comment]
`_subscribeToTopic(String topicName) {
    print('MQTTClientWrapper::Subscribing to the $topicName topic');
    client.subscribe(topicName, MqttQos.atMostOnce);

    client.updates!.listen((List<MqttReceivedMessage<MqttMessage>> c) {
      final recMess = c[0].payload as MqttPublishMessage;

      final pt =
          MqttPublishPayload.bytesToStringAsString(recMess.payload.message);

      saveResponse(pt);
      print("MQTTClientWrapper::GOT A NEW MESSAGE $pt");
    });
  }`
exactly when I subscribing to topic, it occured
line `print("MQTTClientWrapper::GOT A NEW MESSAGE $pt");`

**Comment by sgsm74** [comment]
I added UTF8String() function to  builder in publish method, but when I subscribe to topic, what I got is something like this:
Ø³ÙØ§Ù

**Comment by shamblett** [comment]
OK I'll have look at this and try and see what's going on.

**Comment by sgsm74** [comment]
I got it, by adding: 
```
final recMess = c[0].payload as MqttPublishMessage;
String message = MqttPublishPayload.bytesToStringAsString(recMess.payload.message);
Utf8Decoder().convert(message.codeUnits);
```
third line fixed the issue

**Comment by sgsm74** [comment]
I got it, by adding: 
```
final recMess = c[0].payload as MqttPublishMessage;
String message = MqttPublishPayload.bytesToStringAsString(recMess.payload.message);
Utf8Decoder().convert(message.codeUnits);
```
third line fixed the issue
