### ISSUE TITLE
Topic subscription issues: receiving messages from other topics

### ISSUE THREAD

**Issue by benbehringer** [shamblett/mqtt_client#31]
Using mqtt_client 3.1.0 with

```
Flutter 0.7.5 • channel dev • https://github.com/flutter/flutter.git
Framework • revision eab5cd9853 (7 days ago) • 2018-08-30 14:47:04 -0700
Engine • revision dc7b5eb89d
Tools • Dart 2.1.0-dev.3.0.flutter-760a9690c2
```

The mqtt example code doesn't work as expected in a new flutter project, since I receive change notifications from other topics as well:

```
I/flutter (15268): EXAMPLE::Change notification:: topic is <test/lol>, payload is <-- test 3 -->
I/flutter (15268): EXAMPLE::Change notification:: topic is <ebcon/cinder/TicToc/JSON>, payload is <-- {"Node": "cinder", "Title": "TicToc", "Data": "1536237360 2018/09/06 05:36:00 -0700"} -->
```

Notice that the mqtt example code doesn't subscribe to these topics.

**Comment by shamblett** [comment]
Which example do you mean? The mqtt_client_wildcard example does subscribe to these topics

**Comment by shamblett** [comment]
Actually your right, there's something odd going on here, I'll have a look.

**Comment by cbenhagen** [comment]
The example was missing `.startClean()`. @benbehringer I suppose you did not change the client id in the example. So you were resuming the session of someone else who might have subscribed himself to those topics. The example was changed to include `.startClean()'. So this should not confuse new users again.

**Comment by shamblett** [comment]
Yes, I thought it might be connected to sessions, I added startClean() to both the normal and wildcard examples and changed the client ids. Funny thing is I can't remember seeing this until I did the Dart 2.0 updates, not to worry, closing this now.
