### ISSUE TITLE
Does the package has support connect MQTT using Username, Password, and TLS-PSK?

### ISSUE THREAD

**Issue by wickyou23** [shamblett/mqtt_client#310]
Currently, My company's device using the mosquitto for brokers and verify clients by Username, Password, and PSK. I don’t know how to connect to a broker using PSK in Dart? Does the package has support for the case?

**Comment by shamblett** [comment]
The client supports secure sockets(TLS) if you are on the server side, see the mqtt_server_client_secure.dart example in the examples directory.  You can pass a username and password in the connect method, this will be sent to the broker in the connect message. This client is for MQTT 3 and 3.1, if you need more specialist authentication MQTT5 may be a better choice, see the [mqtt5_client](https://pub.dev/packages/mqtt5_client) package.

**Comment by thangphungverik** [comment]
Hello @shamblett 

Thanks for your support. I am working on the mobile using flutter. Your package supported TLS for the CA files, but with TLS-PSK I didn't found. You can refer to this link for my case.

https://mosquitto.org/man/mosquitto_sub-1.html

**Comment by shamblett** [comment]
This has nothing to do with the client, the client uses the Dart runtime security context [here](https://api.dart.dev/stable/2.13.4/dart-io/SecurityContext-class.html), you can only do what the runtime supports here, this would be the same with the mqtt5_client.

**Comment by wickyou23** [comment]
Thanks @shamblett, I had clarified my case. I will close the thread.
