### ISSUE TITLE
Can't use mqtt browser client, always throwing Error: Not found: 'dart:html'

### ISSUE THREAD

**Issue by saravanans55** [shamblett/mqtt_client#315]
Full Error Log:

Launching lib\main.dart on Redmi Note 8 Pro in debug mode...
Running Gradle task 'assembleDebug'...
Invalid depfile: E:\workspace\flutter\boodskap_flutter_mqtt_app\.dart_tool\flutter_build\de1de6b3bbabb6e2ded9ade2778bb606\kernel_snapshot.d
Invalid depfile: E:\workspace\flutter\boodskap_flutter_mqtt_app\.dart_tool\flutter_build\de1de6b3bbabb6e2ded9ade2778bb606\kernel_snapshot.d
/E:/tools/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/mqtt_client-9.6.0/lib/mqtt_browser_client.dart:11:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
/E:/tools/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/mqtt_client-9.6.0/lib/src/connectionhandling/browser/mqtt_client_mqtt_browser_ws_connection.dart:52:16: Error: The method 'WebSocket' isn't defined for the class 'MqttBrowserWsConnection'.
 - 'MqttBrowserWsConnection' is from 'package:mqtt_client/mqtt_browser_client.dart' ('/E:/tools/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/mqtt_client-9.6.0/lib/mqtt_browser_client.dart').
Try correcting the name to the name of an existing method, or defining a method named 'WebSocket'.
      client = WebSocket(uriString, protocols);
               ^^^^^^^^^
/E:/tools/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/mqtt_client-9.6.0/lib/src/connectionhandling/browser/mqtt_client_mqtt_browser_ws_connection.dart:117:16: Error: The method 'WebSocket' isn't defined for the class 'MqttBrowserWsConnection'.
 - 'MqttBrowserWsConnection' is from 'package:mqtt_client/mqtt_browser_client.dart' ('/E:/tools/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/mqtt_client-9.6.0/lib/mqtt_browser_client.dart').
Try correcting the name to the name of an existing method, or defining a method named 'WebSocket'.
      client = WebSocket(uriString, protocols);
               ^^^^^^^^^
/E:/tools/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/mqtt_client-9.6.0/lib/src/connectionhandling/browser/mqtt_client_mqtt_browser_connection.dart:44:32: Error: 'MessageEvent' isn't a type.
      client.onMessage.listen((MessageEvent e) {
                               ^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:599:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:738:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:558:9)
<asynchronous suspension>
#4      starter (package:flutter_frontend_server/server.dart:180:12)
<asynchronous suspension>
#5      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
<asynchronous suspension>

FAILURE: Build failed with an exception.

* Where:
Script 'E:\tools\flutter_windows_2.0.6-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\tools\flutter_windows_2.0.6-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by shamblett** [comment]
You need to use flutter web for the web client -
```
/E:/tools/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/mqtt_client-9.6.0/lib/mqtt_browser_client.dart:11:8: Error: Not found: 'dart:html'
```

dart:html is not available on the server side, if you want to use flutter use mqtt_server_client.dart.

**Comment by saravanans55** [comment]
Oops... I think I'm doing the wrong one. currently, I'm trying to connect my flutter app and our private secured server. Can you please assist me with which example I should check?

**Comment by shamblett** [comment]
If you are using normal flutter i is a server side framework as far as Dart is concerned, so you need  mqtt_server_client.dart.

**Comment by saravanans55** [comment]
Thanks @shamblett
