### ISSUE TITLE
Unhandled Exception: WebSocketException: Connection to 'https://xyz.com/mqtt#' was not upgraded to websocket

### ISSUE THREAD

**Issue by saravanans55** [shamblett/mqtt_client#316]
It's working for non secured version (ws://) but throwing error for secured version (wss://). Below I mentioned my code and log details. I want to know it's server site configuration issue or flutter_app site issue. Please help me.

My Code:
----------

```
String MQTT_BASE = "xyz.com/mqtt";
var clientSessionId = "WEB_${DateTime.now().millisecondsSinceEpoch}";
final client = MqttServerClient('wss://$MQTT_BASE', clientSessionId);

Future<int> main() async {

  runApp(MyApp());

  /// A websocket URL must start with ws:// or wss:// or Dart will throw an exception, consult your websocket MQTT broker
  /// for details.
  /// To use websockets add the following lines -:
  /// client.useWebSocket = true;
  /// client.port = 80;  ( or whatever your WS port is)
  /// There is also an alternate websocket implementation for specialist use, see useAlternateWebSocketImplementation
  /// Note do not set the secure flag if you are using wss, the secure flags is for TCP sockets only.
  /// You can also supply your own websocket protocol list or disable this feature using the websocketProtocols
  /// setter, read the API docs for further details here, the vast majority of brokers will support the client default
  /// list so in most cases you can ignore this.
  /// Set logging on if needed, defaults to off
  client.logging(on: true);
  client.useWebSocket = true;
  client.port = 443;
  /// If you intend to use a keep alive you must set it here otherwise keep alive will be disabled.
  client.keepAlivePeriod = 20;

  /// Add the unsolicited disconnection callback
  client.onDisconnected = onDisconnected;

  /// Add the successful connection callback
  client.onConnected = onConnected;

  /// Add a subscribed callback, there is also an unsubscribed callback if you need it.
  /// You can add these before connection or change them dynamically after connection if
  /// you wish. There is also an onSubscribeFail callback for failed subscriptions, these
  /// can fail either because you have tried to subscribe to an invalid topic or the broker
  /// rejects the subscribe request.
  client.onSubscribed = onSubscribed;

  /// Set a ping received callback if needed, called whenever a ping response(pong) is received
  /// from the broker.
  client.pongCallback = pong;

  /// Create a connection message to use or use the default one. The default one sets the
  /// client identifier, any supplied username/password and clean session,
  /// an example of a specific one below.
  final connMess = MqttConnectMessage()
      .withClientIdentifier(clientSessionId)
      .withWillTopic('willtopic') // If you set this you must set a will message
      .withWillMessage('My Will message')
      .startClean() // Non persistent session for testing
      .authenticateAs("WEB_$API_TOKEN", API_KEY)// Non persistent session for testing
      .withWillQos(MqttQos.atLeastOnce);
  print('EXAMPLE::Mosquitto client connecting....');
  client.connectionMessage = connMess;

  /// Connect the client, any errors here are communicated by raising of the appropriate exception. Note
  /// in some circumstances the broker will just disconnect us, see the spec about this, we however will
  /// never send malformed messages.
  try {
    await client.connect();
  } on NoConnectionException catch (e) {
    // Raised by the client when connection fails.
    print('EXAMPLE::client exception - $e');
    client.disconnect();
  } on SocketException catch (e) {
    // Raised by the socket layer
    print('EXAMPLE::socket exception - $e');
    client.disconnect();
  }

  /// Check we are connected
  if (client.connectionStatus!.state == MqttConnectionState.connected) {
    print('EXAMPLE::Mosquitto client connected');
  } else {
    /// Use status here rather than state if you also want the broker return code.
    print(
        'EXAMPLE::ERROR Mosquitto client connection failed - disconnecting, status is ${client.connectionStatus}');
    client.disconnect();
    exit(-1);
  }

  /// Ok, lets try a subscription
  print('EXAMPLE::Subscribing to the test/lol topic');
  const topic = 'test/lol'; // Not a wildcard topic
  client.subscribe(topic, MqttQos.atMostOnce);

  /// The client has a change notifier object(see the Observable class) which we then listen to to get
  /// notifications of published updates to each subscribed topic.
  client.updates!.listen((List<MqttReceivedMessage<MqttMessage?>>? c) {
    final recMess = c![0].payload as MqttPublishMessage;
    final pt =
    MqttPublishPayload.bytesToStringAsString(recMess.payload.message);

    /// The above may seem a little convoluted for users only interested in the
    /// payload, some users however may be interested in the received publish message,
    /// lets not constrain ourselves yet until the package has been in the wild
    /// for a while.
    /// The payload is a byte buffer, this will be specific to the topic
    print(
        'EXAMPLE::Change notification:: topic is <${c[0].topic}>, payload is <-- $pt -->');
    print('');
  });

  /// If needed you can listen for published messages that have completed the publishing
  /// handshake which is Qos dependant. Any message received on this stream has completed its
  /// publishing handshake with the broker.
  client.published!.listen((MqttPublishMessage message) {
    print(
        'EXAMPLE::Published notification:: topic is ${message.variableHeader!.topicName}, with Qos ${message.header!.qos}');
  });

  /// Lets publish to our topic
  /// Use the payload builder rather than a raw buffer
  /// Our known topic to publish to
  const pubTopic = 'Dart/Mqtt_client/testtopic';
  final builder = MqttClientPayloadBuilder();
  builder.addString('Hello from mqtt_client');

  /// Subscribe to it
  print('EXAMPLE::Subscribing to the Dart/Mqtt_client/testtopic topic');
  client.subscribe(pubTopic, MqttQos.exactlyOnce);

  /// Publish it
  print('EXAMPLE::Publishing our topic');
  client.publishMessage(pubTopic, MqttQos.exactlyOnce, builder.payload!);

  /// Ok, we will now sleep a while, in this gap you will see ping request/response
  /// messages being exchanged by the keep alive mechanism.
  print('EXAMPLE::Sleeping....');
  await MqttUtilities.asyncSleep(120);

  /// Finally, unsubscribe and exit gracefully
  print('EXAMPLE::Unsubscribing');
  client.unsubscribe(topic);

  /// Wait for the unsubscribe message from the broker if you wish.
  await MqttUtilities.asyncSleep(2);
  print('EXAMPLE::Disconnecting');
  client.disconnect();
  return 0;
}

/// The subscribed callback
void onSubscribed(String topic) {
  print('EXAMPLE::Subscription confirmed for topic $topic');
}

/// The unsolicited disconnect callback
void onDisconnected() {
  print('EXAMPLE::OnDisconnected client callback - Client disconnection');
  if (client.connectionStatus!.disconnectionOrigin ==
      MqttDisconnectionOrigin.solicited) {
    print('EXAMPLE::OnDisconnected callback is solicited, this is correct');
  }
  exit(-1);
}

/// The successful connect callback
void onConnected() {
  print(
      'EXAMPLE::OnConnected client callback - Client connection was sucessful');
}

/// Pong callback
void pong() {
  print('EXAMPLE::Ping response client callback invoked');
}
```

Logs:
=======
Performing hot restart...
Syncing files to device Redmi Note 8 Pro...
Restarted application in 2,263ms.
I/flutter (16577): EXAMPLE::Mosquitto client connecting....
I/flutter (16577): 1-2021-08-31 17:32:59.557601 -- MqttClient::connect - keep alive is enabled with a value of 20 seconds
I/flutter (16577): 1-2021-08-31 17:32:59.565438 -- MqttConnectionKeepAlive:: Initialised with a keep alive value of 20 seconds
I/flutter (16577): 1-2021-08-31 17:32:59.565624 -- MqttConnectionKeepAlive:: Disconnect on no ping response is disabled
I/flutter (16577): 1-2021-08-31 17:32:59.567641 -- MqttConnectionHandlerBase::connect - server wss://xyz.com/mqtt, port 443
I/flutter (16577): 1-2021-08-31 17:32:59.571043 -- SynchronousMqttServerConnectionHandler::internalConnect entered
I/flutter (16577): 1-2021-08-31 17:32:59.571493 -- SynchronousMqttServerConnectionHandler::internalConnect - initiating connection try 0, auto reconnect in progress false
I/flutter (16577): 1-2021-08-31 17:32:59.572082 -- SynchronousMqttServerConnectionHandler::internalConnect - websocket selected
I/flutter (16577): 1-2021-08-31 17:32:59.572909 -- SynchronousMqttServerConnectionHandler::internalConnect - calling connect
I/flutter (16577): 1-2021-08-31 17:32:59.575110 -- MqttWsConnection::connect - entered
I/flutter (16577): 1-2021-08-31 17:32:59.593261 -- MqttWsConnection::connect - WS URL is wss://xyz.com:443/mqtt, protocols are [mqtt, mqttv3.1, mqttv3.11]
I/GED     (16577): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
I/flutter (16577): 1-2021-08-31 17:33:02.547761 -- MqttConnectionBase::_onError - calling disconnected callback
E/flutter (16577): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: WebSocketException: Connection to 'https://xyz.com/mqtt#' was not upgraded to websocket
E/flutter (16577): 
I/flutter (16577): 1-2021-08-31 17:33:19.575349 -- MqttConnectionKeepAlive::pingRequired
I/flutter (16577): 1-2021-08-31 17:33:19.579152 -- MqttConnectionKeepAlive::pingRequired - NOT sending ping - not connected
I/flutter (16577): 1-2021-08-31 17:33:19.580151 -- MqttConnectionKeepAlive::pingRequired - restarting ping timer
I/flutter (16577): 1-2021-08-31 17:33:39.583420 -- MqttConnectionKeepAlive::pingRequired
I/flutter (16577): 1-2021-08-31 17:33:39.584440 -- MqttConnectionKeepAlive::pingRequired - NOT sending ping - not connected
I/flutter (16577): 1-2021-08-31 17:33:39.584929 -- MqttConnectionKeepAlive::pingRequired - restarting ping timer
I/flutter (16577): 1-2021-08-31 17:33:59.588130 -- MqttConnectionKeepAlive::pingRequired
I/flutter (16577): 1-2021-08-31 17:33:59.589201 -- MqttConnectionKeepAlive::pingRequired - NOT sending ping - not connected
I/flutter (16577): 1-2021-08-31 17:33:59.589784 -- MqttConnectionKeepAlive::pingRequired - restarting ping timer
I/flutter (16577): 1-2021-08-31 17:34:19.594101 -- MqttConnectionKeepAlive::pingRequired
I/flutter (16577): 1-2021-08-31 17:34:19.595232 -- MqttConnectionKeepAlive::pingRequired - NOT sending ping - not connected
I/flutter (16577): 1-2021-08-31 17:34:19.595726 -- MqttConnectionKeepAlive::pingRequired - restarting ping timer

**Comment by shamblett** [comment]
Whatever it is if its working with ws then its not the client, its something to do with switching to wss, why does this appear in the log -
```
E/flutter (16577): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: WebSocketException: Connection to 'https://xyz.com/mqtt#' was not upgraded to websocket
```
Where has wss gone? It seems to have switched to https for some reason. Are you sure your wss port is 433? Just because its secure doesn't mean it will automatically use that port.

**Comment by saravanans55** [comment]
@shamblett Thanks for the help. I resolved the problem, there are two things I changed in my code. 

The first one I set the correct WebsocketProtocol. 
**client.websocketProtocols = ['mqttv3.1'];**

For the second one, I removed the port:443 option.

After those two things, it's working properly and I can able to receive messages.

Below I added my workable code. 

`Future<int> initMqtt() async {

    /// A websocket URL must start with ws:// or wss:// or Dart will throw an exception, consult your websocket MQTT broker
    /// for details.
    /// To use websockets add the following lines -:
    /// client.useWebSocket = true;
    /// client.port = 80;  ( or whatever your WS port is)
    /// There is also an alternate websocket implementation for specialist use, see useAlternateWebSocketImplementation
    /// Note do not set the secure flag if you are using wss, the secure flags is for TCP sockets only.
    /// You can also supply your own websocket protocol list or disable this feature using the websocketProtocols
    /// setter, read the API docs for further details here, the vast majority of brokers will support the client default
    /// list so in most cases you can ignore this.
    /// Set logging on if needed, defaults to off
    client.logging(on: true);
    client.useWebSocket = true;
    client.port = 443;
    /// If you intend to use a keep alive you must set it here otherwise keep alive will be disabled.
    client.keepAlivePeriod = 20;

    /// Add the unsolicited disconnection callback
    client.onDisconnected = onDisconnected;

    /// Add the successful connection callback
    client.onConnected = onConnected;

    /// Add a subscribed callback, there is also an unsubscribed callback if you need it.
    /// You can add these before connection or change them dynamically after connection if
    /// you wish. There is also an onSubscribeFail callback for failed subscriptions, these
    /// can fail either because you have tried to subscribe to an invalid topic or the broker
    /// rejects the subscribe request.
    client.onSubscribed = onSubscribed;

    /// Set a ping received callback if needed, called whenever a ping response(pong) is received
    /// from the broker.
    client.pongCallback = pong;

    /// Create a connection message to use or use the default one. The default one sets the
    /// client identifier, any supplied username/password and clean session,
    /// an example of a specific one below.
    final connMess = MqttConnectMessage()
        .withClientIdentifier(clientSessionId)
    // .withWillTopic('willtopic') // If you set this you must set a will message
    // .withWillMessage('My Will message')
        .startClean() // Non persistent session for testing
        .authenticateAs("WEB_$API_TOKEN", API_KEY)// Non persistent session for testing
        .withWillQos(MqttQos.atLeastOnce);
    print('EXAMPLE::Mosquitto client connecting....');
    client.connectionMessage = connMess;
    client.websocketProtocols = ['mqttv3.1'];

    /// Connect the client, any errors here are communicated by raising of the appropriate exception. Note
    /// in some circumstances the broker will just disconnect us, see the spec about this, we however will
    /// never send malformed messages.
    try {
      await client.connect();
    } on NoConnectionException catch (e) {
      // Raised by the client when connection fails.
      print('EXAMPLE::client exception - $e');
      client.disconnect();
    } on SocketException catch (e) {
      // Raised by the socket layer
      print('EXAMPLE::socket exception - $e');
      client.disconnect();
    }

    /// Check we are connected
    if (client.connectionStatus!.state == MqttConnectionState.connected) {
      print('EXAMPLE::Mosquitto client connected');
    } else {
      /// Use status here rather than state if you also want the broker return code.
      print(
          'EXAMPLE::ERROR Mosquitto client connection failed - disconnecting, status is ${client.connectionStatus}');
      client.disconnect();
      exit(-1);
    }

    /// Ok, lets try a subscription
    print('EXAMPLE::Subscribing to the test/lol topic');
    var topic = '/$DOMAIN_KEY/log/#'; // Not a wildcard topic
    client.subscribe(topic, MqttQos.atMostOnce);

    /// The client has a change notifier object(see the Observable class) which we then listen to to get
    /// notifications of published updates to each subscribed topic.
    client.updates!.listen((List<MqttReceivedMessage<MqttMessage?>>? c) {
      final recMess = c![0].payload as MqttPublishMessage;
      final pt =
      MqttPublishPayload.bytesToStringAsString(recMess.payload.message);

      /// The above may seem a little convoluted for users only interested in the
      /// payload, some users however may be interested in the received publish message,
      /// lets not constrain ourselves yet until the package has been in the wild
      /// for a while.
      /// The payload is a byte buffer, this will be specific to the topic
      print(
          'EXAMPLE::Change notification:: topic is <${c[0].topic}>, payload is <-- $pt -->');
      print('');
    });

    /// If needed you can listen for published messages that have completed the publishing
    /// handshake which is Qos dependant. Any message received on this stream has completed its
    /// publishing handshake with the broker.
    client.published!.listen((MqttPublishMessage message) {
      print(
          'EXAMPLE::Published notification:: topic is ${message.variableHeader!.topicName}, with Qos ${message.header!.qos}');
    });

    /// Lets publish to our topic
    /// Use the payload builder rather than a raw buffer
    /// Our known topic to publish to
    const pubTopic = 'Dart/Mqtt_client/testtopic';
    final builder = MqttClientPayloadBuilder();
    builder.addString('Hello from mqtt_client');

    /// Subscribe to it
    print('EXAMPLE::Subscribing to the Dart/Mqtt_client/testtopic topic');
    client.subscribe(pubTopic, MqttQos.exactlyOnce);

    /// Publish it
    // print('EXAMPLE::Publishing our topic');
    // client.publishMessage(pubTopic, MqttQos.exactlyOnce, builder.payload!);

    /// Ok, we will now sleep a while, in this gap you will see ping request/response
    /// messages being exchanged by the keep alive mechanism.
    print('EXAMPLE::Sleeping....');
    await MqttUtilities.asyncSleep(120);

    /// Finally, unsubscribe and exit gracefully
    // print('EXAMPLE::Unsubscribing');
    // client.unsubscribe(topic);

    /// Wait for the unsubscribe message from the broker if you wish.
    await MqttUtilities.asyncSleep(2);
    print('EXAMPLE::Disconnecting');
    // client.disconnect();
    return 0;
  }`

**Comment by shamblett** [comment]
Ok, good, the websocket protocol string crops up a lot, brokers tend to differ on what they need.
