### ISSUE TITLE
Unsubscribe when the page exits, but updates. Listen is not destroyed  

### ISSUE THREAD

**Issue by jahnli** [shamblett/mqtt_client#319]
MqttUtil.getInstance().mqttClient?.subscribe(_settingResponseTopic, MqttQos.atMostOnce);
    final _clientTopicFilter = MqttClientTopicFilter(_settingResponseTopic, MqttUtil.getInstance().mqttClient!.updates);
    _clientTopicFilter.updates.listen((List<MqttReceivedMessage> res) {
      final message = res[0].payload as MqttPublishMessage;
      final payload = utf8.decode(message.payload.message);
      if (json.decode(payload)['cal_setting_ok'] == 0) {
        Utils.showToast('changeError'.tr);
      }
      print(payload);

Unsubscribe when the page exits, but updates. Listen is not destroyed  ,Multiple duplicate messages will be received if multiple exits are caused

**Comment by shamblett** [comment]
I'm not a flutter user so I don't really know what you mean by 'page exits' and 'multiple exits', updates.listen is only destroyed when the client is destroyed, it has to stay alive while the client is connected, regardless of what pages you are on.
You maybe better asking flutter users.

**Comment by jahnli** [comment]
So you mean if I have multiple feeds, （ updates. Listen   I only need to set it in one place?  ）

**Comment by jahnli** [comment]
Do you need to write one (updates. listen) after each subscription topic, or write a global (updates. listen) and then modify it separately for each topic

**Comment by shamblett** [comment]
There is only one updates.listen, every subscribed topic will appear on it, if you want to filter these use [topic filtering](https://pub.dev/documentation/mqtt_client/latest/mqtt_client/MqttClientTopicFilter-class.html), see the mqtt_client_wildcard_filtered.dart example.

**Comment by jahnli** [comment]
The current situation is that I subscribed to one topic on page A and wrote an MqttClientTopicFilter updates.    Listen.    When I destroyed page A, I cancelled the subscription and re-subscribed to the topic when I entered page A again ，This resulted in repeated messages being returned multiple times in update.listen

**Comment by jahnli** [comment]
In the current situation, I wrote multiple updates. Listen, and the page was destroyed without destroying updates. Listen, resulting in duplicate messages

**Comment by shamblett** [comment]
Why are you unsubscribing and resubscribing again? This just causes unnecessary overhead, you are only changing pages, not going into background or exiting the app. Again you are better asking flutter users about this.

**Comment by jahnli** [comment]
OK， I see. Thank you for your advice

**Comment by jahnli** [comment]
I have a question， What's the difference between using res[0]. Topic in updaten.listen and MqttClientTopicFilter

**Comment by shamblett** [comment]
Topic filtering allows you to listen for multiple topics, you can attach a topic filter to client.updates, listen on it for your topic, then attach another filter to client.updates for another topic and so on. If you are only interested in a single topic there's no difference.

**Comment by jahnli** [comment]
client.updates!.listen((List<MqttReceivedMessage<MqttMessage?>>? c) {
    final topic= c![0].topic 
if(topic == 'topicA'){
}else if(topic == 'topicB){
}


Is this also possible if there are multiple topics?  Is it different from MqttClientTopicFilter?

**Comment by shamblett** [comment]
Not in essence, you can do it that way if you wish, its up to you.

**Comment by jahnli** [comment]
Ok, thank you for your advice

**Comment by jahnli** [comment]
final _topicAFilter = MqttClientTopicFilter("topicA", MqttUtil.getInstance().mqttClient!.updates);
      _topicAFilter .updates.listen((List<MqttReceivedMessage> res) {
        final message = res[0].payload as MqttPublishMessage;
        final payload = utf8.decode(message.payload.message);
      });


final _topicBFilter = MqttClientTopicFilter("topicB", MqttUtil.getInstance().mqttClient!.updates);
      _topicBFilter .updates.listen((List<MqttReceivedMessage> res) {
        final message = res[0].payload as MqttPublishMessage;
        final payload = utf8.decode(message.payload.message);
      });


If you are using multiple MQTTClienttopicFilters, is it possible to write it this way? It looks a bit too much code. Is there an easier way to write it

**Comment by shamblett** [comment]
No, that looks OK.

**Comment by JacoFourie** [comment]
You should subscribe to all the toppics on a onconnect event.
Then Use Provider with MQTT and as the data arrives on a topic pass it to a method that updates the data inside provider.
Place your Provider state at the top of the app and then you have access in all the pahes and widgets to the data that comes in on a topic via Provider.
