### ISSUE TITLE
Many data

### ISSUE THREAD

**Issue by Fianax** [shamblett/mqtt_client#320]
I have a mqtt server that sends 700 data per second, but when I print those values, not those 700 data have arrived but much less.

What is mqtt_client doing in the .updates.listen method that does not allow me such amount of information per second?

Thanks for listening.

**Comment by shamblett** [comment]
How do you know the problem is with updates.listen?

To answer your question updates is essentially this 
```
/// Stream for all subscribed topics
  final _subscriptionNotifier =
      StreamController<List<MqttReceivedMessage<MqttMessage>>>.broadcast(
          sync: true);

  /// Subscription notifier
  Stream<List<MqttReceivedMessage<MqttMessage>>> get subscriptionNotifier =>
      _subscriptionNotifier.stream;
```

i.e. a normal Dart stream.

The problem is more likely to be how quickly we are updating it, you need to turn logging on so we can see where the bottleneck is, and yes, this will slow it down a bit.

**Comment by Fianax** [comment]
What do you mean by logging in? Because I don't need to log in to the mqtt service that I have.

But yes, you may have a bottleneck somewhere but it doesn't make sense that it exists.

I have the mqtt servivor on my pc, that is, the data is created and sent from my computer, I don't have to connect to another. Therefore, when I launch the application on my computer the data flow is good, although I do not receive all the data that I should.
On the other hand, if I run it on my mobile and connect to the server (to my computer) the data flow I receive is much smaller, 4 times less, that's why I thought that the updates.listen method was saturated with so much data volume in so little weather.

CODE:

void subcribir() async {
    client.subscribe('prueba/prueba2/106/+/+', MqttQos.atLeastOnce);

    client.updates?.listen((List<MqttReceivedMessage<MqttMessage>> c) async {
      final MqttPublishMessage recMess = c[0].payload as MqttPublishMessage;
      final String msg =
          MqttPublishPayload.bytesToStringAsString(recMess.payload.message);
      
      print('-----'+c[0].topic+'---'+msg);

    });
  }


if I run this on my computer, I get 800 data approximately every 2 seconds.
On the other hand, if I run it on my mobile and connect to the server (my computer), I receive 200 data approximately every two seconds.
In fact, I have tried to run the code on other computers and mobiles and it gives the same result 200 data. That's why I thought it could be the updates.listen.

I have colleagues who do not do the same, but they do it in Visual Studio with Xamarin not with flutter.

Sorry for the inconvenience

Thanks.

**Comment by shamblett** [comment]
Not 'logging in', the client allows you to turn logging on or off, this gives you a time stamped trace file of what the client is doing, although it does add some weight. 

If the throughput is what you expect when you test locally and only slows down when you move to mobile why do suspect the client is at fault? This could be a number of things, the network, the flutter runtime etc.

The client does not regulate traffic at all, no matter where it is running.

**Comment by Fianax** [comment]
I have already solved the problem. It was on the level of Qos, had to put the level 0 instead of 1.

Thank you for helping me so quickly.
Have a nice day :)
