### ISSUE TITLE
setTrustedCertificates in SecurityContext, used for what?

### ISSUE THREAD

**Issue by thangphungverik** [shamblett/mqtt_client#321]
In the file `mqtt_server_client_secure.dart` in folder `example`, If I comment out these lines.

![Screen Shot 2021-09-14 at 23 10 08](https://user-images.githubusercontent.com/80801118/133294233-7544752c-704e-4327-92d5-a02d5ac588e1.png)

Then run the code, It works well, connects to `test.mosquitto.org` success. So, Does `setTrustedCertificates` work?

**Comment by shamblett** [comment]
It does if you have the crt file, the security context is provided by Dart, not the client, see [here](https://api.dart.dev/stable/2.14.1/dart-io/SecurityContext-class.html)

**Comment by thangphungverik** [comment]
> It does if you have the crt file, the security context is provided by Dart, not the client, see [here](https://api.dart.dev/stable/2.14.1/dart-io/SecurityContext-class.html)

Thanks for the quick reply.  I had the true crt file but I tried to set trusted a wrong crt,  then I see still connect success. I see this line `client.onBadCertificate = (dynamic a) => true;` Do I need to verify with the true crt file in here? or ignore? If I ignore it always connects success.

**Comment by shamblett** [comment]
I seem to remember that if you have used a crt file once and it has worked the OS caches it in your certificate cache and you don't need to supply it again, why it doesn't error if you supply an incorrect one I don't know. The onbadCertificate callback is just a wrapper for [this](https://api.dart.dev/stable/2.14.2/dart-io/HttpClient/badCertificateCallback.html) from the runtime.
