### ISSUE TITLE
OS Error: No address associated with hostname, errno = 7 when trying to connect to Azure

### ISSUE THREAD

**Issue by debungle-it** [shamblett/mqtt_client#323]
I connect successfully via mqtts to our hub on Azure using MQTTbox w/o generating a certificate

when I run my dart/flutter program:

```
final client = MqttServerClient('<hubname>.azure-devices.net/\$iothub/websocket', 'testdevice');
client.port = 8883;
client.secure = true;

final connMess = MqttConnectMessage()
      .authenticateAs('<hubname>.azure-devices.net/testdevice/?api-version=2018-06-30',
      'SharedAccessSignature sr=<hubname>.azure-devices.net%2Fdevices%2Ftestdevice&sig=xxxxxxx')
      .withClientIdentifier('testdevice')
      .withWillTopic('devices/testdevice/messages/events/') // If you set this you must set a will message
      .withWillMessage('My Will message')
      .startClean() // Non persistent session for testing
      .withWillQos(MqttQos.atLeastOnce);

client.connectionMessage = connMess;

try {
  await client.connect();
}
``` 

I get "SocketException: Failed host lookup: 'mqttQueue.azure-devices.net/$iothub/websocket' (OS Error: No address associated with hostname, errno = 7)"

**Comment by shamblett** [comment]
That's because 'mqttQueue.azure-devices.net/$iothub/websocket' isn't a valid hostname, it contains a '$', which is not allowed, see h[ere](https://man7.org/linux/man-pages/man7/hostname.7.html).

I reality the client doesn't do this resolution, its part of the Dart runtime, see [here](https://api.dart.dev/stable/2.14.2/dart-io/InternetAddress-class.html).

**Comment by shamblett** [comment]
There is only one client identifier used, you don't have to supply a connect message, the examples show this but it also says you can use the default one the client will generate for you. If you use the default one you can pass the client identifier on construction, if you supply your own connection message the one set in that will be used(overriding any passed on construction, unless you do pass one on construction and do not supply one in your connection message).

The client identifier is sent to the broker in the connection message as per the MQTT 3 spec, it is not used to 'complete the endpoint URL.'.

**Comment by debungle-it** [comment]
Azure documentation is incorrect. This structure works:

Future<String> mqttGetToken ({ String sessionId = <insert your session id>}) async {
  final response = await http.get(Uri.parse('https://<hubname>.azurewebsites.net/api/Token/GetMQTTToken/testdevice?sessionId=' + sessionId));
  if (response.statusCode == 200) {
    // If the server did return a 200 OK response,
    // then parse the JSON.
    debugPrint('+++ token is: ' + response.body);
    return response.body;  // returns a long string like "SharedAccessSignature sr=<hubname>.azure-devices.net%2Fdevices%2Ftestdevice&sig=<some string>&se=<some int>"

  } else {
    // If the server did not return a 200 OK response,
    // then throw an exception.
    throw Exception('Failed to obtain token');
  }
}

final client = MqttServerClient('<hubname>.azure-devices.net');
client.port = 8883;
client.secure = true;

final connMess = MqttConnectMessage()
      .withClientIdentifier('testdevice')
      .startClean() // Non persistent session for testing

client.connectionMessage = connMess; // 

password = await mqttGetToken();

try {
  await client.connect( user, password);
}
