### ISSUE TITLE
Connection to HiveMq brocker

### ISSUE THREAD

**Issue by Hasv07** [shamblett/mqtt_client#326]
I tried to connect Hivemq brocker but i failed here is connect function
```dart
Future<MqttBrowserClient> connect() async {
  MqttBrowserClient client =
      MqttBrowserClient.withPort('ws://broker.mqttdashboard.com', 'flutter7', 8000 );
  
  client.logging(on: true);
  client.keepAlivePeriod=100;
client.websocketProtocols = ['mqtt']; 
final connMessage = MqttConnectMessage()
      .authenticateAs(null,null)
      .withWillTopic('willtopic')
      .withWillMessage('Will message')
      .startClean()
      .withWillQos(MqttQos.atLeastOnce )
      .withClientIdentifier("flutter7") ;
      
  client.connectionMessage = connMessage;


  try {
    await client.connect();
  } catch (e) {
    print('Exception: $e');
    client.disconnect();
  }
```
here is log
```1-2021-09-26 11:23:11.803 -- MqttClient::connect - keep alive is enabled with a value of 100 seconds
1-2021-09-26 11:23:11.804 -- MqttConnectionKeepAlive:: Initialised with a keep alive value of 100 seconds
1-2021-09-26 11:23:11.805 -- MqttConnectionKeepAlive:: Disconnect on no ping response is disabled
1-2021-09-26 11:23:11.805 -- MqttConnectionHandlerBase::connect - server wss://broker.mqttdashboard.com, port 8000
1-2021-09-26 11:23:11.806 -- SynchronousMqttBrowserConnectionHandler::internalConnect entered
1-2021-09-26 11:23:11.806 -- SynchronousMqttBrowserConnectionHandler::internalConnect - initiating connection try 0, auto reconnect in progress false   
1-2021-09-26 11:23:11.806 -- SynchronousMqttBrowserConnectionHandler::internalConnect - calling connect
1-2021-09-26 11:23:11.807 -- MqttBrowserWsConnection::connect - entered
1-2021-09-26 11:23:11.808 -- MqttBrowserWsConnection::connect -  WS URL is wss://broker.mqttdashboard.com:8000
1-2021-09-26 11:23:11.811 -- MqttBrowserWsConnection::connect - connection is waiting
1-2021-09-26 11:23:32.187 -- MqttBrowserWsConnection::connect - websocket has erred
1-2021-09-26 11:23:32.213 -- SynchronousMqttBrowserConnectionHandler::internalConnect - connection complete
1-2021-09-26 11:23:32.214 -- SynchronousMqttBrowserConnectionHandler::internalConnect sending connect message
1-2021-09-26 11:23:32.214 -- MqttConnectionHandlerBase::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=true,
WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=false, UserNameFlag=false, KeepAlive=100
MqttConnectPayload - client identifier is : flutter7

1-2021-09-26 11:23:32.219 -- SynchronousMqttBrowserConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return  
code of noneSpecified and a disconnection origin of none
1-2021-09-26 11:23:37.275 -- SynchronousMqttBrowserConnectionHandler::internalConnect - post sleep, state = Connection status is connecting with return
code of noneSpecified and a disconnection origin of none
```
sorry i am beginner in computer field for any wrong representation of issue

**Comment by shamblett** [comment]
I can't connect to this broker on port 8000 either, even if I change the headers, you can also check your set up using mosquito, change the host to 'test.mosquitto.org' and the port to '8080', this works OK so I don't think you are doing anything wrong.

**Comment by Hasv07** [comment]
> I can't connect to this broker on port 8000 either, even if I change the headers, you can also check your set up using mosquito, change the host to 'test.mosquitto.org' and the port to '8080', this works OK so I don't think you are doing anything wrong.

I d

**Comment by Hasv07** [comment]
Thanks sir .

**Comment by kibu7** [comment]
is there a solution for this?

**Comment by shamblett** [comment]
Have you tries accessing HiveMQ on its public broker, [here](broker.hivemq.com). This should work, I have a local HiveMq broker  in a docker container I use locally for testing, out of the box this doesn't support websocket use, you have to configure it, please refer to the HiveMQ docs.

**Comment by kibu7** [comment]
Hi shamble,
thanks for your response. Im using HiveMQ Cloud but I cannot connect it using the MqttBrowserClient
`
import 'package:mqtt_client/mqtt_browser_client.dart';
import 'package:mqtt_client/mqtt_client.dart';
import 'package:mqtt_client/mqtt_server_client.dart';

const server = 'ws://*************.s1.eu.hivemq.cloud/mqtt';
const port = 8884;

class MQTTManager {
  //Singleton
  static final MQTTManager _instance = MQTTManager._internal();
  factory MQTTManager() => _instance;

  MQTTManager._internal() {
    // init things inside this
  }

  final client = MqttBrowserClient(server, 'clientIdentifier');

  MqttCurrentConnectionState connectionState = MqttCurrentConnectionState.IDLE;
  MqttSubscriptionState subscriptionState = MqttSubscriptionState.IDLE;

  void prepareMqttClient() async {
    _setupMqttClient();
    await _connectClient();
    // _subscribeToTopic('Dart/Mqtt_client/testtopic');
    _subscribeToTopic('test');
    _publishMessage('Hello');
  }

  void _subscribeToTopic(String topicName) {
    print('Subscribing to the $topicName topic');
    client.subscribe(topicName, MqttQos.atMostOnce);

    // print the message when it is received
    client.updates?.listen((List<MqttReceivedMessage<MqttMessage>> c) {
      final MqttPublishMessage recMess = c[0].payload as MqttPublishMessage;
      var message =
          MqttPublishPayload.bytesToStringAsString(recMess.payload.message);

      print('YOU GOT A NEW MESSAGE:');
      print(message);
    });
  }

  void _publishMessage(String message) {
    final MqttClientPayloadBuilder builder = MqttClientPayloadBuilder();
    builder.addString(message);

    print(
        'Publishing message "$message" to topic ${'Dart/Mqtt_client/testtopic'}');
    client.publishMessage(
        'Dart/Mqtt_client/testtopic', MqttQos.exactlyOnce, builder.payload!);
  }

  // waiting for the connection, if an error occurs, print it and disconnect
  Future<void> _connectClient() async {
    try {
      print('client connecting....');
      connectionState = MqttCurrentConnectionState.CONNECTING;
      await client.connect('user', 'password');
    } on Exception catch (e) {
      print('client exception - $e');
      connectionState = MqttCurrentConnectionState.ERROR_WHEN_CONNECTING;
      client.disconnect();
    }

    // when connected, print a confirmation, else print an error
    if (client.connectionStatus?.state == MqttConnectionState.connected) {
      connectionState = MqttCurrentConnectionState.CONNECTED;
      print('client connected');
    } else {
      print(
          'ERROR client connection failed - disconnecting, status is ${client.connectionStatus}');
      connectionState = MqttCurrentConnectionState.ERROR_WHEN_CONNECTING;
      client.disconnect();
    }
  }

  void _setupMqttClient() {
    

    client.logging(on: false);
    client.setProtocolV311();
    client.keepAlivePeriod = 60;
    client.websocketProtocols = MqttClientConstants.protocolsMultipleDefault;
    client.port = port;
    client.onDisconnected = _onDisconnected;
    client.onConnected = _onConnected;
    client.onSubscribed = _onSubscribed;
  }

  // callbacks for different events
  void _onSubscribed(String topic) {
    print('Subscription confirmed for topic $topic');
    subscriptionState = MqttSubscriptionState.SUBSCRIBED;
  }

  void _onDisconnected() {
    print('OnDisconnected client callback - Client disconnection');
    connectionState = MqttCurrentConnectionState.DISCONNECTED;
  }

  void _onConnected() {
    connectionState = MqttCurrentConnectionState.CONNECTED;
    print('OnConnected client callback - Client connection was sucessful');
  }
}

enum MqttCurrentConnectionState {
  IDLE,
  CONNECTING,
  CONNECTED,
  DISCONNECTED,
  ERROR_WHEN_CONNECTING
}

enum MqttSubscriptionState { IDLE, SUBSCRIBED }
`

**Comment by shamblett** [comment]
What log output do you get?

**Comment by shamblett** [comment]
OK, looks as though your broker is not responding, I take it the port you are using is correct? i.e.8884. You need to look at your broker logs, they should say why they are refusing the connection.

**Comment by kibu7** [comment]
thank you.
I found the problem, to connect to HiveMQ Cloud you need to have the server address:
```dart
const server = 'wss://***********.s1.eu.hivemq.cloud/mqtt';
const port = 8884;
```
