### ISSUE TITLE
Flutter Web Error :(Unsupported operation: default SecurityContext getter) 

### ISSUE THREAD

**Issue by BSBoatia** [shamblett/mqtt_client#329]
What am I missing?

I'm having the same issue as @kumarmohan7 described in [https://github.com/shamblett/mqtt_client/issues/197](https://github.com/shamblett/mqtt_client/issues/197)

However, I like to build my app for web and Android / iOS. B/c of the error described above, I introduced the following to my code

    if (kIsWeb) {
      browserClient = MqttBrowserClient(brokerAddress, '');
      _connectBrowserClient(uniqueClientId);
    } else {
      client = MqttServerClient(brokerAddress, '');
      _connect(uniqueClientId);
    }

This leads to the following error when trying to build for non web targets.

Launching lib/main.dart on AOSP on IA Emulator in debug mode...
lib/main.dart:1
: Error: Not found: 'dart:html'
package:mqtt_client/mqtt_browser_client.dart:11
import 'dart:html';
       ^

: Error: The method 'WebSocket' isn't defined for the class 'MqttBrowserWsConnection'.
../…/browser/mqtt_client_mqtt_browser_ws_connection.dart:52
- 'MqttBrowserWsConnection' is from 'package:mqtt_client/mqtt_browser_client.dart' ('../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/mqtt_client-9.6.1/lib/mqtt_browser_client.dart').
package:mqtt_client/mqtt_browser_client.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'WebSocket'.

      client = WebSocket(uriString, protocols);
               ^^^^^^^^^
: Error: The method 'WebSocket' isn't defined for the class 'MqttBrowserWsConnection'.
../…/browser/mqtt_client_mqtt_browser_ws_connection.dart:117

- 'MqttBrowserWsConnection' is from 'package:mqtt_client/mqtt_browser_client.dart' ('../../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/mqtt_client-9.6.1/lib/mqtt_browser_client.dart').
package:mqtt_client/mqtt_browser_client.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'WebSocket'.
      client = WebSocket(uriString, protocols);
               ^^^^^^^^^

: Error: 'MessageEvent' isn't a type.
../…/browser/mqtt_client_mqtt_browser_connection.dart:44
      client.onMessage.listen((MessageEvent e) {
                               ^^^^^^^^^^^^

Thanks!

**Comment by rpungin** [comment]
Instead of dealing with conditional imports, I solved this like [this](https://github.com/shamblett/mqtt_client/issues/442#issuecomment-2342619674)
