### ISSUE TITLE
Chinese can not correctly decode

### ISSUE THREAD

**Issue by jinfagang** [shamblett/mqtt_client#331]
![image](https://user-images.githubusercontent.com/21303438/139534101-118ef1a9-9891-4f22-bea8-bbba6818c7c2.png)

As you can see the text, it was `哥疼`, but decode wrongly.

```
 final MqttPublishMessage message = c[0].payload as MqttPublishMessage;
      String topic = c[0].topic;
      final payload =
          MqttPublishPayload.bytesToStringAsString(message.payload.message);
      print('************************');
      print(payload);
      var a = utf8.decode(payload.codeUnits);
      print(payload);
```

what should I do

**Comment by shamblett** [comment]
Please don'u use an image, I need to copy and paste the 'text' character string, however if you do this -
```
 print('哥疼'.codeUnits);
```
You get [21733, 30140].

Please check that your 'text' codeunits are the same.
