### ISSUE TITLE
Username & Password ?

### ISSUE THREAD

**Issue by JacoFourie** [shamblett/mqtt_client#332]
Hi. I am now at the point where I have to give my server a username & password to connect to the broker.
I do not see any samples on how to do that. I see you state that the MqttConnectMessage handles it but I do not see how to set it.

**Comment by shamblett** [comment]
You can supply them on the connect method -
```
Future<MqttClientConnectionStatus?> connect(
      [String? username, String? password])
```
 as per the API docs.

**Comment by JacoFourie** [comment]
What is this used for?

.authenticateAs(username , password)

**Comment by JacoFourie** [comment]
OK cool I have it working using the username and password on the connect method. I also had to do something to the WillTopic as the ACL on the server only allows you to publish in a certain topic branch. Now it all works again with username and password. I will close the question, just still wondering what the .authenticate is used for.
