### ISSUE TITLE
MqttClientPayloadBuilder works only for English 

### ISSUE THREAD

**Issue by guyluz11** [shamblett/mqtt_client#338]
Trying to convert using the `MqttClientPayloadBuilder();` text in Hebrew and I found out that the payload max value can be only 255.

```
final builder = MqttClientPayloadBuilder();
builder.addString('סדנאת עץ');

```

Retreves 

`[225, 5, 211, 5, 224, 5, 208, 5, 234, 5, 32, 226, 5, 229, 5] `

Where it should retrieve 

`1505 1491 1504 1488 1514 32 1506 1509`

according to [this site](https://cryptii.com/pipes/text-decimal) probably using the wrong transformation units of measurement.

When trying to use `String.fromCharCodes(message);` or  `utf8.decode(message, allowMalformed: true);` I get corrupted text with the value `áÓàÐê âå` which is not `סדנאת עץ` as I expected.

Is there a better way to convert back text from bytes that will work for all languages?.

**Comment by shamblett** [comment]
Strings in MQTT are encoded as UTF8 according to the spec, not Unicode code points, try using the addUTF8String method, you should find that utf8.decode will convert your string back. The other methods on the payload builder are supplied to allow you to build the payload in a more flexible manner if you do not want to do this, you do course have to know how to decode them yourself.

**Comment by guyluz11** [comment]
Using 
`builder.addString('סדנאת עץ');`
Worked with 
`utf8.decode(message, allowMalformed: true);`

With
`String.fromCharCodes(message);`
it does not work.

Thanks, will close now this issue.
