### ISSUE TITLE
Shadow Error

### ISSUE THREAD

**Issue by melihkara** [shamblett/mqtt_client#341]
Hello official; library shadow is not connecting to topics.
"$aws/things/Aquarium/shadow/name/ResifShadow/update"
I get the following error
But I have no problem connecting on "Aquarium/pub".
-------------------------------------------------------------------------------------------------------------------------------------------------

I/flutter ( 4792): MqttConnectPayload - client identifier is : $aws/things/Akvaryum/shadow/name/ResifShadow/update
I/flutter ( 4792): 1-2021-12-09 11:36:13.197798 -- SynchronousMqttServerConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
I/flutter ( 4792): 1-2021-12-09 11:36:13.395761 -- MqttConnection::_onData
I/flutter ( 4792): 1-2021-12-09 11:36:13.397806 -- MqttServerConnection::_onData - message received MQTTMessage of type MqttMessageType.connectAck
I/flutter ( 4792): Header: MessageType = MqttMessageType.connectAck, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 2
I/flutter ( 4792): Connect Variable Header: TopicNameCompressionResponse={0}, ReturnCode={MqttConnectReturnCode.identifierRejected}
I/flutter ( 4792): 1-2021-12-09 11:36:13.399487 -- MqttServerConnection::_onData - message available event fired
I/flutter ( 4792): 1-2021-12-09 11:36:13.401877 -- MqttConnectionHandlerBase::_connectAckProcessor
I/flutter ( 4792): 1-2021-12-09 11:36:13.403073 -- MqttConnectionHandlerBase::_connectAckProcessor connection rejected
I/flutter ( 4792): 1-2021-12-09 11:36:13.404094 -- MqttConnectionHandlerBase::_performConnectionDisconnect entered
I/flutter ( 4792): 1-2021-12-09 11:36:13.405276 -- MqttConnectionHandlerBase:: cancelling connect timer
I/flutter ( 4792): 1-2021-12-09 11:36:13.407884 -- SynchronousMqttServerConnectionHandler::internalConnect - post sleep, state = Connection status is disconnected with return code of identifierRejected and a disconnection origin of none
I/flutter ( 4792): 1-2021-12-09 11:36:13.411618 -- SynchronousMqttServerConnectionHandler::internalConnect - initiating connection try 104, auto reconnect in progress false
I/flutter ( 4792): 1-2021-12-09 11:36:13.412731 -- SynchronousMqttServerConnectionHandler::internalConnect - secure selected
I/flutter ( 4792): 1-2021-12-09 11:36:13.413819 -- SynchronousMqttServerConnectionHandler::internalConnect - calling connect
I/flutter ( 4792): 1-2021-12-09 11:36:13.415989 -- MqttSecureConnection::connect - entered
I/flutter ( 4792): 1-2021-12-09 11:36:13.739596 -- MqttConnectionBase::_onDone - calling disconnected callback

**Comment by shamblett** [comment]
Yoy have received a connect ack mesage from your broker -
```
I/flutter ( 4792): 1-2021-12-09 11:36:13.397806 -- MqttServerConnection::_onData - message received MQTTMessage of type MqttMessageType.connectAck
```
which is saying -
```
I/flutter ( 4792): 1-2021-12-09 11:36:13.407884 -- SynchronousMqttServerConnectionHandler::internalConnect - post sleep, state = Connection status is disconnected with return code of identifierRejected and a disconnection origin of none
```
Your broker is rejecting your client id by the looks of things.
