### ISSUE TITLE
After the client enters the background and returns to the foreground, it automatically reconnects, causing updates. Listen to be triggered again. How to solve this problem  

### ISSUE THREAD

**Issue by jahnli** [shamblett/mqtt_client#343]
After the client enters the background and returns to the foreground, it automatically reconnects, causing updates. Listen to be triggered again. How to solve this problem

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/146740094-e75af827-434f-4067-a67c-8d2f808f5aad.png)

**Comment by jahnli** [comment]
Results in two repeated Updates Listen

**Comment by SuYungCheng** [comment]
any idea?
I have same question.
