### ISSUE TITLE
 Ali Cloud

### ISSUE THREAD

**Issue by XiaoWei3209** [shamblett/mqtt_client#345]
Hello, how do I connect MQTT of Ali Cloud? I've been trying, but I can't connect.I hope I can get help

**Comment by shamblett** [comment]
I'm not sure we have had any other users connecting to Ali cloud, most people seem to use AWS, Azure or GCE so I'm not sure who can help you. You could start with the Ali cloud MQTT connection docs [here](https://www.alibabacloud.com/product/mqtt) I suppose.

**Comment by XiaoWei3209** [comment]
> 

thank you , see Ali cloud mqtt client sdk,i've learned.
