### ISSUE TITLE
Connecting takes way too long (5s)

### ISSUE THREAD

**Issue by cbenhagen** [shamblett/mqtt_client#35]
Connecting to a local mosquitto broker takes 5s. I wonder what takes so long..

**Comment by cbenhagen** [comment]
Well..
https://github.com/shamblett/mqtt_client/blob/e25c83ca465c7677258f93b683e4fa655447d652/lib/src/connectionhandling/mqtt_client_synchronous_mqtt_connection_handler.dart#L51-L52

**Comment by shamblett** [comment]
Yes, this was mentioned on issue 18, my initial plan was to make the wait cancellable, so when we connect we cancel and don't wait the full 5 seconds, I'll have a look at this again with your pull request.
