### ISSUE TITLE
Reading payload raw bytes into ByteBuffer/UInt8List

### ISSUE THREAD

**Issue by glanch** [shamblett/mqtt_client#350]
Currently I receive messages by listening to `client.updates`. For every message received I'd like to be able to use the payload's content as a Uint8List or a ByteBuffer. How can I achieve this?

**Comment by shamblett** [comment]
Get the received message as a published message as per the examples, use the payload wrtiteTo method to get the payload as an mqtt byte buffer -
```
 /// Writes the payload to the supplied stream.
  @override
  void writeTo(MqttByteBuffer payloadStream)
```
so it will be something like recmess.payload.writeTo(buffer), then get the underlying byte buffer from the MqttByteBuffer.

**Comment by glanch** [comment]
Must have missed the cast as stated in the examples. Thank you alot!
