### ISSUE TITLE
How to update username and password on reconnect

### ISSUE THREAD

**Issue by Jonzho** [shamblett/mqtt_client#351]
I tried to disconnect before automatic reconnection, and then manually try to connect to update the connectionMessage, but it doesn't work.
what should I do?

**Comment by shamblett** [comment]
Auto reconnect functionality wont help you here it will only attempt to re connect with the same credentials as initially supplied as per the design. Your only recourse is to turn this off on the client and do this manually from the onDisconnected callback maybe.

**Comment by Jonzho** [comment]
I tried turning off auto-reconnect and it worked. thank you

**Comment by Jonzho** [comment]
I tried turning off auto-reconnect and it worked. thank you
