### ISSUE TITLE
Change dart:html to http

### ISSUE THREAD

**Issue by pbertsch** [shamblett/mqtt_client#354]
Having a Flutter App for Web and MacOS for example can be an issue because you cannot use the MqttServerClient inside the Browser nor can you use MqttBrowserClient on MacOS because of the `dart:html` dependency which is fine if you use only one but if you aim for both platforms it's getting tricky preparing releases for both platforms without making changes to the code each time and develop the rest with that in mind.

Would it be possible to change the `dart:html` dependency to `http` in order to prevent the issue and use the same Client in both cases ?

**Comment by shamblett** [comment]
What do you mean by 'http'?  Presumably the http package, as long as its supports the socket operations the client uses now then possibly. I'll look at any pull requests for this.

**Comment by rshillington** [comment]
@pbertsch are you going to work on a PR for this?  Seems like a must have for those of us trying to reach the broadest audience.   If not I may get somebody on my team to give it a try, but no promises I can spring the resources in a timely fashion.

**Comment by shamblett** [comment]
I won't be putting together a PR for this anytime soon or in reality probably never, the testing alone would be too much for my limited bandwidth.
