### ISSUE TITLE
The broker is not responding to the connection request message correctly The return code is MqttConnectReturnCode.notAuthorized

### ISSUE THREAD

**Issue by Mawmi** [shamblett/mqtt_client#355]
Hi Goodmorning Sir! I'm new to mqtt and have tried this code
 I Got an error message  what will be the cause of this ?

```
mqtt-client::NoConnectionException: The maximum allowed connection attempts ({3}) were exceeded. The broker is not responding to the connection request message correctly The return code is MqttConnectReturnCode.notAuthorized
```

Hope to solve it! 
thankyou in advance sir!

**Comment by shamblett** [comment]
It means your not authorised, either your username/password is wrong or depending on your broker configuration it may be your client id. Please refer to the MQTT spec [here](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718032)
