### ISSUE TITLE
Backpressure Handling 

### ISSUE THREAD

**Issue by muhammadsaddamnur** [shamblett/mqtt_client#359]
Is there a way to implement backpressure handling when listen message received?

**Comment by shamblett** [comment]
If I'm understanding you correctly backpressure handling is usually implemented in the broker not the client.

The client only adds messages to the listen stream when the MQTT protocol for that message QoS level has been completed, this is event driven from message reception, the client does not add any kind of flow control other than any added by the Dart Stream implementation.

In MQTT 3.1 you have to configure your broker appropriately if you wish to rate limit etc. In MQTT 5 you can select various options in the connect message to help you with this, see section[ 3.1.2.11 CONNECT Properties](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901046) and other sections of the spec.

Note this client supports MQTT 3/3.1 only, if you need to use MQTT 5 please use the [mqtt5 client](https://pub.dev/packages/mqtt5_client)

**Comment by muhammadsaddamnur** [comment]
Thanks for your response.
okay i'm clear about that,
 
how about adding persistence db like hive on client side as backpressure handling?
does it make sense?

**Comment by shamblett** [comment]
If you have a use case for this then yes. The package itself is only for MQTT protocol handling, you don't want to tie this directly to any client side(what about the web client here BTW?) database. If you need this then you can implement it in your own code or maybe implement a hook/plugin mechanism in the client to support this.

**Comment by muhammadsaddamnur** [comment]
i just think, a local db like [hive](https://pub.dev/packages/hive) can be used on all platforms 😅
okey, I'll try your suggestion.

Thanks for created awesome package 👍
