### ISSUE TITLE
I can't connect broker

### ISSUE THREAD

**Issue by tmdwns4087** [shamblett/mqtt_client#360]
i'm using Naver IoT Core.
i can't connect iot core(broker).

SOURCE---------------------------------------------------------------------------------
Future<void>connect() async{

　  final context = SecurityContext.defaultContext;
　  final rootCA = await rootBundle.load('key/rootCaCert.pem');
　  final fullChain = await rootBundle.load('key/fullCertChain.pem');
　  final privateKey = await rootBundle.load('key/06d53a.private.pem');

　  context.setClientAuthoritiesBytes(rootCA.buffer.asUint8List());
　  context.useCertificateChainBytes(fullChain.buffer.asUint8List());
　  context.usePrivateKeyBytes(privateKey.buffer.asUint8List());

　  client.securityContext = context;
　  client.secure = true;
　  // client.setProtocolV31();
　  // client.port = 8883;
　  client.logging(on: true);
　  client.onConnected = onConnected;
　  client.onDisconnected = onDisconnected;
　  // client.onUnsubscribed = onUnsubscribed;
　  client.onSubscribed = onSubscribed;
　  client.onSubscribeFail = onSubscribeFail;
　  client.pongCallback = pong;
　  client.autoReconnect = false;
　  print('mqtt init done');
　  try {
　　    print('try');
　　    await client.connect();
　  } catch (e) {
    　　print('Exception: $e');
　　    client.disconnect();
　  }
　}

RESULT----------------------------------------------------------------
I/flutter ( 6911): 1-2022-03-17 06:32:58.112228 -- MqttClient::connect - keep alive is disabled
I/flutter ( 6911): 1-2022-03-17 06:32:58.128454 -- MqttConnectionHandlerBase::connect - server msg01.cloudiot.ntruss.com, port 8883
I/flutter ( 6911): 1-2022-03-17 06:32:58.132994 -- SynchronousMqttServerConnectionHandler::internalConnect entered
I/flutter ( 6911): 1-2022-03-17 06:32:58.133512 -- SynchronousMqttServerConnectionHandler::internalConnect - initiating connection try 0, auto reconnect in progress false
I/flutter ( 6911): 1-2022-03-17 06:32:58.134688 -- SynchronousMqttServerConnectionHandler::internalConnect - secure selected
I/flutter ( 6911): 1-2022-03-17 06:32:58.136003 -- SynchronousMqttServerConnectionHandler::internalConnect - calling connect
I/flutter ( 6911): 1-2022-03-17 06:32:58.137806 -- MqttSecureConnection::connect - entered
I/flutter ( 6911): 1-2022-03-17 06:32:58.300101 -- MqttConnectionBase::_onError - calling disconnected callback
I/flutter ( 6911): Exception: HandshakeException: Handshake error in client (OS Error: 
I/flutter ( 6911): 	CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:393))
I/flutter ( 6911): 1-2022-03-17 06:32:58.306955 -- MqttConnectionHandlerBase::disconnect - entered
I/flutter ( 6911): 1-2022-03-17 06:32:58.307622 -- MqttConnectionHandlerBase::_performConnectionDisconnect entered

Why does Exception occur?

**Comment by shamblett** [comment]
You have a certificate error -
```
I/flutter ( 6911): 1-2022-03-17 06:32:58.300101 -- MqttConnectionBase::_onError - calling disconnected callback
I/flutter ( 6911): Exception: HandshakeException: Handshake error in client (OS Error:
I/flutter ( 6911): CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:393))
```
This has come from the runtime not the client as such.

**Comment by tmdwns4087** [comment]
@shamblett denying my connection from broker?
Or is Dart displaying an error before attempting to connect? (Is there a problem with the certificate?)

**Comment by tmdwns4087** [comment]
@shamblett 
When setting to client.secure = false, the following exceptions occur:
Exception:mqtt-client::NoConnectionException: The maximum allowed connection attempts ({3}) were exceeded. The broker is not responding to the connection request message (Missing Connection Acknowledgement?

**Comment by shamblett** [comment]
I'm not sure what you are trying to do here, the exception is raised by the Dart runtime when it processes your security context, see [here](https://api.dart.dev/stable/2.16.1/dart-io/SecurityContext-class.html) its saying you have a certificate error, this is nothing to do with the client.

If you want to connect normally(not secure) you have to not pass a security context and set the port the the MQTT standard of 1883.

**Comment by tmdwns4087** [comment]
Is it possible to perform mutual authentication on Flutter?

**Comment by shamblett** [comment]
Don't know what you mean by 'mutual authentication' in the context of MQTT. You have the authentication mechanisms that MQTT 3/3.1 provide which is basically username/password. This mechanism is available for both secure and normal operation. MQTT 5 allows you to negotiate the authenticate method you require better but for that you will need the [mqtt5 ](https://pub.dev/packages/mqtt5_client)client.

If you are talking about cert handling/TLS/secure working then you are back to what is provided by settings in the Dart [security context ](https://api.dart.dev/stable/2.16.1/dart-io/SecurityContext-class.html).
