### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by SilvanFem** [shamblett/mqtt_client#362]
This plugin not working for Above Android 12 version

application crashing
showing error.
FATAL EXCEPTION: MQTT Rec:
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

**Comment by shamblett** [comment]
I have no idea what this is or where it comes from except that its not from the client, this seems to be more a platform or runtime error, if you look through the closed issues I think there was one raised about problems on Android 12
