### ISSUE TITLE
AWS connection over wss for webapp

### ISSUE THREAD

**Issue by juanjoabarca** [shamblett/mqtt_client#366]
I made a flutter web application, it works perfectly with my local broker over ws, the problem starts when I need to connect the application with AWS, I followed the instructions in this video [How to connect to AWS IOT with MQTT with AWS Signature Version 4 authentication?
](https://www.youtube.com/watch?v=XYDCAOyHD_M) to authenticate but I can't get it to work.

Could you guide me on this, thank you.

part of my code:
```
 Future<bool> initMqtt() async {
    _client = MqttBrowserClient(host!, '')
      ..port = port!
      ..logging(on: true)
      ..keepAlivePeriod = 20
      ..onConnected = onConnected
      ..onDisconnected = onDisconnected
      ..onSubscribed = onSubscribed
      ..websocketProtocols = MqttClientConstants.protocolsSingleDefault
      ..setProtocolV311();

    final mqttMsg = MqttConnectMessage()
        .withWillTopic('willtopic')
        .withWillMessage('Will message')
        .startClean()
        .withWillQos(MqttQos.atLeastOnce);
    _client.connectionMessage = mqttMsg;
    return await connectionMqtt();
  }
  ```

**Comment by shamblett** [comment]
It can be tricky to connect to AWS, there is an example in the examples directory named aws_iot.dart that may help. I don't use AWS myself but if you search through the closed issues you will find a few reports of issues connecting to AWS that were resolved.

**Comment by bmjhversteeg** [comment]
#371
