### ISSUE TITLE
Not able to subscribe topic more than 55 in aws core iot.

### ISSUE THREAD

**Issue by MurtuzaSrashtaSoft** [shamblett/mqtt_client#368]
I have 309 aws core IoT things devices. And I m trying to subscribe to all 309 things but out of 309 topics. I receive only 55 devices that are subscribed successfully. The rest of the 234 devices receive **onSubscribeFail** on onSubscribeFail I m also trying to resubscribe but the same result.

**Comment by shamblett** [comment]
Sounds as though your broker has failed the subscription requests, there can be many reasons for this, if you supply a client log of a failure I'll take a look but at the end of the day only your broker knows why it failed the subscription so you need to examine its logs also.

**Comment by MurtuzaSrashtaSoft** [comment]
how to find aws core IoT broker log? can you help me to find this!

**Comment by Yashwantbokadia** [comment]
@MurtuzaSrashtaSoft In AWS IOT, Settings option you can enable logging and check the logs. Samples are given on the below AWS link. See the below AWS screenshot for log enabling.

![image](https://user-images.githubusercontent.com/20962788/163968673-002bc57b-fea9-45eb-9520-92e5f6a48a89.png)

Hope, it will help.

AWS Documents Link: https://docs.aws.amazon.com/iot/latest/developerguide/cwl-format.html

**Comment by MurtuzaSrashtaSoft** [comment]
[log.odt](https://github.com/shamblett/mqtt_client/files/8511508/log.odt)

**Comment by MurtuzaSrashtaSoft** [comment]
{
    "timestamp": "2022-03-20 15:33:16.156",
    "logLevel": "ERROR",
    "traceId": "dfd80df2-d257-ea26-cdb9-16aaf7f1c91b",
    "accountId": "503416810272",
    "status": "Failure",
    "eventType": "Subscribe",
    "protocol": "MQTT",
    "topicName": "$aws/things/SAU2AG1_GW-001E5E0145CC-SQ610-001E5E09025D94C6/shadow/update/accepted",
    "clientId": "SAU2AG1_GW-001E5E0145CC-95828889-00bd-46af-bb0f-3b721eec5651",
    "principalId": "AROAXKNP25MQMPBP5LL5R:CognitoIdentityCredentials",
    "sourceIp": "103.192.204.240",
    "sourcePort": 46936,
    "reason": "throttled"
}

**Comment by shamblett** [comment]
I don't use AWS myself I use Google Cloud so I can't help you with any specific AWS stuff but from your error above the reason for the failure is given as 'throttled', you need to check with the AWS docs as to exactly what this means but it suggests you are sending the subscription requests to quickly for the level of service you have set your broker to,

**Comment by MurtuzaSrashtaSoft** [comment]
`I/flutter (25952): 1-2022-04-20 15:18:44.423600 -- MqttConnection::_onData
I/flutter (25952): 1-2022-04-20 15:18:44.423891 -- MqttServerConnection::_onData - message received MQTTMessage of type MqttMessageType.subscribeAck
I/flutter (25952): Header: MessageType = MqttMessageType.subscribeAck, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 3
I/flutter (25952): SubscribeAck Variable Header: MessageIdentifier={313}
I/flutter (25952): Payload: Qos grants [{1}]
I/flutter (25952): {{ Grant={MqttQos.failure} }}
I/flutter (25952): 
I/flutter (25952): 1-2022-04-20 15:18:44.424168 -- MqttServerConnection::_onData - message available event fired
I/flutter (25952): 1-2022-04-20 15:18:44.424511 -- MqttConnectionHandlerBase::messageAvailable - message type is MqttMessageType.subscribeAck
I/flutter (25952): `

**Comment by shamblett** [comment]
Not sure what you are trying to tell me, this just shows your subscription failed for a QoS 1 but we know this already don't we, do you use any other QoS levels in your subscriptions? Do they work?

**Comment by MurtuzaSrashtaSoft** [comment]
> Not sure what you are trying to tell me, this just shows your subscription failed for a QoS 1 but we know this already don't we, do you use any other QoS levels in your subscriptions? Do they work?

no, i m use only MqttQos.atLeastOnce QoS.

`  Subscription subscribe(
    String topic, [
    MqttQos qosLevel = MqttQos.atLeastOnce,
  ]) {
    return _client?.subscribe(topic, qosLevel);
  }`

**Comment by bmjhversteeg** [comment]
> below the link is the AWS IoT quota detail. but I m not able to clear which quota is restricted of the above point.
> 
> https://docs.aws.amazon.com/general/latest/gr/iot-core.html#limits_iot

It says so right in the docs, Subscriptions per connection: 50

If 50 is not enough, i would suggest playing around with wildcard subscriptions and do topic filtering of incoming messages locally

**Comment by MurtuzaSrashtaSoft** [comment]
wildcard subscriptions are not able to subscribe. not received any callback **onSubScribed**,**onSubscribeFail**

**Comment by shamblett** [comment]
You can't have a topic of '#', see this explanation -
```
The multi-level wildcard covers many topic levels. The hash symbol represents the multi-level wild card in the topic. For the broker to determine which topics match, the multi-level wildcard must be placed as the last character in the topic and preceded by a forward slash.
```
What is the client logging for this?

**Comment by MurtuzaSrashtaSoft** [comment]
@shamblett like this **$aws/things/thingName/shadow/#** ?

**Comment by shamblett** [comment]
Yes but this is a limitation of AWS isn't it? Do your AWS logs still say you are being throttled?

**Comment by MurtuzaSrashtaSoft** [comment]
received unauthorised but not received any call back in subscribefail callback.

**Comment by MurtuzaSrashtaSoft** [comment]
![Screenshot 2022-05-04 at 4 31 31 PM](https://user-images.githubusercontent.com/64843262/166674493-5fb7ce37-7d25-45b6-a618-52a766279dca.png)

i m trying above all combinations. but the full topic is received message only. but that again reaches 50 subscribe limitaion.

**Comment by shamblett** [comment]
The client can't help you here, callbacks are only triggered if a message is received, if the broker is not sending anything nothing will be triggered
