### ISSUE TITLE
mqtt_client program crashes after mqtt servece refuses to connect

### ISSUE THREAD

**Issue by qinjinze** [shamblett/mqtt_client#369]
mqtt_client: ^9.6.6
dart2.14
flutter2.5

I/flutter (25061): ---------MQTT::Mosquitto client connecting....
I/flutter (25061): ---------MQTT::ERROR Mosquitto client connection failed - disconnecting, state is MqttConnectionState.connecting
I/flutter (25061): ----------MQTT::OnDisconnected client callback - Client disconnection

**Comment by shamblett** [comment]
Can't see a crash here, looks as though your broker has refused the connection, so onDisconnected is called, looks normal to me.

**Comment by qinjinze** [comment]
"onDisconnected" will quit the app, I hope not to quit the app

**Comment by shamblett** [comment]
onDisconnected is just a callback, it does whatever you put in it, if you have an exit in there it will exit, if after this your main exits then the app will exit, this is up to you to control.

**Comment by qinjinze** [comment]
> onDisconnected 只是一个回调，它执行您放入的任何操作，如果您在其中有一个出口，它将退出，如果在此之后您的 main 退出，那么应用程序将退出，这取决于您控制。

"exit(-1)" exits the entire program

Thank you very much for your quick reply
