### ISSUE TITLE
Example code to catch subscription ack

### ISSUE THREAD

**Issue by josvos** [shamblett/mqtt_client#37]
Is it possible to get triggered when a `ckient.subscribe()` has been acknowledged by the broker? If yes, how?  If not, we need to implement it ;-).  In the code I see the pendingSubscriptions being updated and I see I can explicitly ask for the subscription status, but that's not sufficient.

**Comment by shamblett** [comment]
Ok, how do you see this, as a change notifier for subscriptions, or a callback, maybe both?

**Comment by josvos** [comment]
In other implementations (I'm using Paho MQTT for Python and I've also used the Paho JS version) there are callbacks for `subscribe()` and `unsubscribe()`.  Although using Dart's streams seem to be natural for incoming messages (other implementations use callbacks for that too), using streams doesn't sound a good idea here.  Is providing a Future similar to `connect()` an option?  Then you effectively provide the callback via `then()`.

**Comment by shamblett** [comment]
Futures are one shots, i.e. you await then move on or you go into your 'then' closure, either way to get the next subscription you would have to call the method again, this is messy in user code. Callbacks are fine though, although not as pure as it could be with Streams they are used in Dart, in fact the typedef example shows how to use a typedef to create a callback.

I'll add onSubscribed and onUnsubscribed callbacks to the client and re-publish

**Comment by shamblett** [comment]
Package updated as above, re-published at 3.3.0

**Comment by shamblett** [comment]
Believe this update is sufficient and working, closing issue.
