### ISSUE TITLE
mqtt not work in android 11 and 12

### ISSUE THREAD

**Issue by rezadevelopers2** [shamblett/mqtt_client#373]
Hi, it works properly until Android 10 version, but it does not work on Android 11 and 12. Do you know where the problem comes from?

**Comment by shamblett** [comment]
Not specifically as I don't use Android however other users have reported problems on latest Android's, look through the closed issues. I believe this was found to be a platform issue.

**Comment by sithuhein** [comment]
I am having the same issues. When I run on Emulator with Android 11, working fine. But installing APK on an Android 12 phone, It didn't connect to the MQTT server. Is there any advice will be greatly appreciated.
