### ISSUE TITLE
Keep mqtt connection live in background 

### ISSUE THREAD

**Issue by akshg05** [shamblett/mqtt_client#375]
How do we keep the mqtt connection alive in background? 
The app is not killed but in the background tray and we want to have the mqtt connection persisted while it's still in the background and not killed off.
How to achieve this?
Currently the mqtt connection is disconnected as client is not responding to pings in background.
Any help is appreciated.

**Comment by akshg05** [comment]
I am a bit confused here. So I can see that few times the connection is alive and communicating well even while the app is background. But there are times when it's aborting/disconnecting while my internet connection is steady. I do not have a reconnect flag put up yet though.
Is it normal for the client to disconnect randomly?
Worth to note I am getting this error when such disconnection happens:
SocketException: Software caused connection abort (OS Error: Software caused connection abort, errno = 103), port = 44118. Error thrown null

**Comment by shamblett** [comment]
I assume you are using flutter here, I'm not a flutter user but if you look through the closed issues background operation has come up several times, I think it was solved but you are better of asking the flutter users.

It is not normal for the client to disconnect randomly, the exception you are seeing is from the flutter runtime, your connection is being closed, the client can't really do anything about this except that you can set it to autoreconnect to automatically try to reconnect when connection is lost.

**Comment by akshg05** [comment]
Thank you. I think auto connect is the way to go.
Thank you for your time.
