### ISSUE TITLE
How to restrict number retry connects

### ISSUE THREAD

**Issue by sureace** [shamblett/mqtt_client#376]
Hi @shamblett,
                         Thank you very much for mqtt_client plugin and providing great support. Is it possible to restrict number of times for reconnect with configurable time delay. Sometimes it is trying to reconnect forever even though it is connected to broker.

Thank you,
Sureace

**Comment by shamblett** [comment]
Yes, it does try and reconnect forever this is not currently selectable I believe, there is the maxConnectionAttempts parameter, this is the number of attempts the client will try to reconnect before it gives up, defaults to 3, you could set this to 1 but once auto reconnect is triggered it doesn't stop trying till it reconnects.

**Comment by sureace** [comment]
Thanks for the prompt response @shamblett . I already configured as 2 and enabled autoReconnect as true. Sometimes it is trying auto reconnect on it's own forever without checking the current mqtt connection state. As you mentioned only way to stop auto reconnect is to call disconnect(). But in my case, mqtt_client already connected and it is trying to reconnecting...
_mqttClient = MqttServerClient.withPort(
          AppConstants.CLOUD_MQTT_URL,
          clientId,
          AppConstants.CLOUD_MQTT_PORT,
          maxConnectionAttempts: 2
      );
      _mqttClient?.autoReconnect = true;
      _mqttClient?.keepAlivePeriod = 60;
      _mqttClient?.onConnected = onConnected;
      _mqttClient?.onAutoReconnect = onAutoReconnect;
      _mqttClient?.onAutoReconnected = onAutoReconnected;
      _mqttClient?.onDisconnected = onDisconnected;
      _mqttClient?.pongCallback = pong;

**Comment by shamblett** [comment]
That shouldn't happen, I'll need a log to look at.

**Comment by sureace** [comment]
Hi @shamblett , it is a rare case scenario. In our testing we observed this. We will capture logs and share it with you. 
Thank you
