### ISSUE TITLE
[bug] broken pipe when pingRequired call

### ISSUE THREAD

**Issue by aaassseee** [shamblett/mqtt_client#377]
Hi, @shamblett. First of all, thank you for providing this library to save us lots of time.

We receive lots of crash report about the broken pipe with this library
Here's an example of non fatal crash
<img width="1231" alt="Screenshot 2022-05-06 at 4 47 50 PM" src="https://user-images.githubusercontent.com/2054978/167099292-dab58847-0519-484b-bdb2-e310923c2847.png">

This issue may stop the keepAlive flow unexpectedly because this line throws exception without try catching
https://github.com/shamblett/mqtt_client/blob/1c740d9fb071138579beda554566e63979a05f90/lib/src/connectionhandling/mqtt_client_mqtt_connection_keep_alive.dart#L88
and causing lines below the pingRequired function not getting executed
https://github.com/shamblett/mqtt_client/blob/1c740d9fb071138579beda554566e63979a05f90/lib/src/connectionhandling/mqtt_client_mqtt_connection_keep_alive.dart#L89-L122

Not executing all the lines within the pingRequired function will break the throw because this line is not getting run
https://github.com/shamblett/mqtt_client/blob/1c740d9fb071138579beda554566e63979a05f90/lib/src/connectionhandling/mqtt_client_mqtt_connection_keep_alive.dart#L96

Also the flow will not drop to noPingResponseReceived flow due to the crash without try catch

I am suggesting wrapping try catch on line
https://github.com/shamblett/mqtt_client/blob/1c740d9fb071138579beda554566e63979a05f90/lib/src/connectionhandling/mqtt_client_mqtt_connection_keep_alive.dart#L88
If it is catching any error then drop to auto reconnect flow.

Any ideas about the issue or the suggestion? If no, I can make a pull request.

**Comment by shamblett** [comment]
Yes I see what you are saying, an exception handler around the send would be a good idea. Not sure what you mean by 'drop to auto reconnect flow', if you are not in auto reconnect then there would be no flow to drop into, you would have to start the auto reconnect process from scratch, probably do this by firing an appropriate event though. 

A PR from you would allow me to understand it better, thanks.

**Comment by aaassseee** [comment]
For the meaning of 'drop to auto reconnect flow' is just directly call noPingResponseReceived when catching any socket exception
. If this solution is looks good, I can create a pull request.

**Comment by shamblett** [comment]
If you do that you will have to handle the ping timer cancelling manually in fact you would have to stop keepalive, calling stop() should do this.

**Comment by aaassseee** [comment]
Hi, @shamblett . I had created a rough solution idea about fixing the socket exception when calling sendMessage. I think the solution needs to cover both web and mobile, client and server client. What's your thought?

**Comment by shamblett** [comment]
Yes it does, I've had a quick look at the PR and it looks OK, I'll merge it and do some testing.

**Comment by aaassseee** [comment]
idk if I needs implement this solution with all sendMessage like publish function in mqtt_client_publishing_manager.dart

**Comment by shamblett** [comment]
Its OK for the moment, lets get this change in and the package released. No other users are reporting issues with the other send message calls so on the basis I don't like putting too much in one release I'm inclined to leave this for now. You could raise a separate issue for this so it can be looked at if you wish.

**Comment by shamblett** [comment]
Merged, package re released at version 9.6.8, please re test, thanks.

**Comment by aaassseee** [comment]
After the day of release, I can still observe the non fatal crash. Try catching is not working on outer layer.
