### ISSUE TITLE
QoS 2 protocol issue when sending messages fast

### ISSUE THREAD

**Issue by josvos** [shamblett/mqtt_client#38]
When the Dart client publishes 2 messages quickly after each other with QoS 2, in many cases (related to timing) the second is never fully processed and gets lost.  It happens when the broker has sent the PUBREC of the 2nd message *before* the PUBCOMP of the 1st message: then the client never sends a PUBREL for the 2nd message. This is fully reproducable.

Mosquitto broker traces (the XXXXXXXX-XXXX client is the Dart client, mosqqub/* is a `mosquitto_sub` command line client subscribed with QoS 0, that is irrelevant for the problem):

Sequence working OK (first id=48, second id=49):

```
1537369517: Received PUBLISH from 2382a99f-fe9c (d0, q2, r0, m48, 'test/topic/a', ... (504 bytes))
1537369517: Sending PUBREC to 2382a99f-fe9c (Mid: 48)
1537369517: Received PUBLISH from 2382a99f-fe9c (d0, q2, r0, m49, 'test/topic/a', ... (360 bytes))
1537369517: Received PUBREL from 2382a99f-fe9c (Mid: 48)
1537369517: Sending PUBCOMP to 2382a99f-fe9c (Mid: 48)
1537369517: Sending PUBLISH to mosqsub/12643-xos069.xo (d0, q0, r0, m0, 'test/topic/a', ... (504 bytes))
1537369517: Sending PUBREC to 2382a99f-fe9c (Mid: 49)
1537369517: Received PUBREL from 2382a99f-fe9c (Mid: 49)
1537369517: Sending PUBCOMP to 2382a99f-fe9c (Mid: 49)
1537369517: Sending PUBLISH to mosqsub/12643-xos069.xo (d0, q0, r0, m0, 'test/topic/a', ... (360 bytes))
```

Sequence working not OK (first id=4, second id=5):

```
1537369818: Received PUBLISH from 22c2105a-6926 (d0, q2, r0, m4, 'test/topic/a', ... (1175 bytes))
1537369818: Sending PUBREC to 22c2105a-6926 (Mid: 4)
1537369818: Received PUBLISH from 22c2105a-6926 (d0, q2, r0, m5, 'test/topic/a', ... (360 bytes))
1537369818: Sending PUBREC to 22c2105a-6926 (Mid: 5)
1537369818: Received PUBREL from 22c2105a-6926 (Mid: 4)
1537369818: Sending PUBCOMP to 22c2105a-6926 (Mid: 4)
1537369818: Sending PUBLISH to mosqsub/12643-xos069.xo (d0, q0, r0, m0, 'test/topic/a', ... (1175 bytes))
```

This might be related to issue #33 but I'm not sure...

**Comment by josvos** [comment]
Update: I see a similar problem arises with QoS 1.  I didn't trace it yet in Mosquitto, will try to append a trace here later today.

**Comment by shamblett** [comment]
Thanks for this, I wrote a unit test based on your findings above and found a bug in how we allocate message identifiers for higher QOS levels, could you re-test this on the latest package, 3.3.1, thanks.

**Comment by josvos** [comment]
Unfortunately it still doesn't seem to work.

**Comment by Smartauto** [comment]
Hi We have 3.3.2 version , When we send multiple payloads on the topic, Approx 3 per second, Then it misses few payloads. But if we send payload once in 2 sec then all works fine.
PS. we are creating a Flutter app.

**Comment by josvos** [comment]
In my sample app the issue already showed up when sending 2 (short) messages after each other and *that* problem has disappeared now.  I didn't test with large and/or more than two messages.
