### ISSUE TITLE
Isnt it possible to read CONNACK and its properties?

### ISSUE THREAD

**Issue by a14guguliye** [shamblett/mqtt_client#381]
Hello All,
i have been trying to read CONNACK package from MQTT which is the result of the successful submission + its properties
isnt it possible to read it if i develop web app and use MQTT_BROWSER_CLIENT?
thanks

**Comment by shamblett** [comment]
The CONNACK message is received and processed but not currently stored for later retrieval and inspection. 

It could be done by updating the mqtt_client_mqtt_connection_handler_base.dart file's  MqttConnectionHandlerBase class to store the received CONNACK and expose it to the client. The connectAckProcessor method processes the received CONNACK and could be updated to store it.

**Comment by a14guguliye** [comment]
> The CONNACK message is received and processed but not currently stored for later retrieval and inspection.
> 
> It could be done by updating the mqtt_client_mqtt_connection_handler_base.dart file's MqttConnectionHandlerBase class to store the received CONNACK and expose it to the client. The connectAckProcessor method processes the received CONNACK and could be updated to store it.

Thanks!
