### ISSUE TITLE
Updates listener stops receiving updates after multiple autoreconnects

### ISSUE THREAD

**Issue by akshg05** [shamblett/mqtt_client#382]
I am connecting to mqtt broker and setting up autoreconnect like below : 
`_client?.autoReconnect = true;`
This as expected connects my client in case the connection breaks.
I allow the library to autosubscribe to all the existing topics it did previously which it does.
I have a listener set up for updates as below: 
```
_registerUpdatesListener() {
    _client?.updates?.listen((event) {
      Logger.info(' Received data');
      Srv.handleReceivedMsg(event);
    });
  }
```
The above listener is registered only once throughout the app lifecycle on the client when it connects for the first time.
We don't call it again and I hope we don't need to as well on reconnects.
My App is a Flutter App where the auto reconnects happen often when app is left in background.
For first few reconnects, everything works fine.
However, after some, the library auto reconnects and subscribes to existing topics but doesn't receive the retained messages for the topic or in fact any messages from the topics.
Please note that it works fine and as expected for the initial reconnects.

Is there something in addition to what I state need to be taken care of?

**Comment by shamblett** [comment]
No, it should work for all auto re connects, when you say first few how many do you mean? I'll need a log of the first failure case.

**Comment by akshg05** [comment]
Hello, My bad responding late.
What kind of logs do you need? I mean I am logging everytime an mqtt message is received and my app has built UI to indicate as well. Basically it detects connected devices online status which it doesn't receive when left app is left in background for long. The time is uncertain and so is the problem but it happens. That being said, I have not tested this on a release build yet. It's evident on debug versions though. Can that be an issue? I know @shamblett  you are not into Flutter but just in case someone has a similar experience.

**Comment by sanrixue** [comment]
> Hello, My bad responding late. What kind of logs do you need? I mean I am logging everytime an mqtt message is received and my app has built UI to indicate as well. Basically it detects connected devices online status which it doesn't receive when left app is left in background for long. The time is uncertain and so is the problem but it happens. That being said, I have not tested this on a release build yet. It's evident on debug versions though. Can that be an issue? I know @shamblett you are not into Flutter but just in case someone has a similar experience.

I encountered the same problem

**Comment by shamblett** [comment]
I need a log that shows the publish messages are being received, its possible they are not queued on the listener for a number of reasons but they won't be if they are not received.
