### ISSUE TITLE
Client <unknown> disconnected due to protocol error.

### ISSUE THREAD

**Issue by a14guguliye** [shamblett/mqtt_client#383]
Hello,
I am developing a flutter web app and decided to change the broker to internally downloaded mosquitto broker.  My configuration details are as below:
````
var mq = MqttBrowserClient('ws://localhost:1883', 'clientz5tWzoydVL',
    maxConnectionAttempts: 1);

class mqttService {
  Future<MqttBrowserClient?> connectToServer() async {
    try {
      final connMess = MqttConnectMessage()
          .withClientIdentifier('clientz5tWzoydVL')
          .withWillTopic('willtopic')
          .withWillMessage('My Will message')
          .startClean() // Non persistent session for testing
          .withWillQos(MqttQos.atLeastOnce);

      mq.setProtocolV31();
      mq.port = 1883;
      mq.keepAlivePeriod = 50;
      mq.connectionMessage = connMess;

      mq.onConnected = onConnected;
      mq.onDisconnected = onDisconnected;
      mq.onSubscribed = onSubscribed;

      mq.logging(on: true);

      var status = await mq.connect();
````

however, no matter how hard i try, the connection ends with the below error:
```
1653674963: New connection from ::1:62881 on port 1883.
1653674963: Client <unknown> disconnected due to protocol error.
```
i checked the forums and etc, it says me that I need to check the mosquitto broker header properties. I really dont know where to check those
can someone please help with the isue?
regards

**Comment by shamblett** [comment]
Out of the box the port for websocket use on mosquitto is 8080 not 1883, this is the standard non-secure TCP port, please check your set up. Also you may need to specify this websocket header setting -
```
mq.websocketProtocols = MqttClientConstants.protocolsSingleDefault;

```
See the mqtt_browser_client.dart file in the examples directory.
