### ISSUE TITLE
MqttBrowserClient unsubscribe results in disconnection

### ISSUE THREAD

**Issue by BigGitWorld** [shamblett/mqtt_client#384]
Hi everyone!
I can connect to a mqtt broker from my web application (ws://) by the ``MqttBrowserClient``.
but when I want to unsubscribe from a topic, my connection is disconnected!

Note:
I have checked unsubscribe process by other clients (for example MQTT-cli by the HiveMQ) and everything works fine.
So my mqtt broker does not have any problem.

What is the problem?

**Comment by shamblett** [comment]
IIRC this can be caused by a protocol mismatch between the client and the broker, if you are using an MQTT 3.1.1 broker ensure you have this set on your client -
```
 client.setProtocolV311();
```

**Comment by BigGitWorld** [comment]
Thanks

**Comment by zozeei** [comment]
Thanks
