### ISSUE TITLE
Please try running example : mqtt_client_mosquitto_wss_browser_client.dart

### ISSUE THREAD

**Issue by Tejas-MD** [shamblett/mqtt_client#385]
This is a flutter web app run.

Here's my fail log: 

Launching MQTT_Testers\mqtt_browser_client.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:57098/9lZd-So1glg=/ws
Debug service listening on ws://127.0.0.1:57098/9lZd-So1glg=/ws
 Running with sound null safety
Connecting to VM Service at ws://127.0.0.1:57098/9lZd-So1glg=/ws
EXAMPLE::Mosquitto client connecting....
1-2022-05-30 00:33:44.427 -- MqttConnectionHandlerBase::connect - server ws://test.mosquitto.org, port 8080
1-2022-05-30 00:33:44.428 -- SynchronousMqttBrowserConnectionHandler::internalConnect entered
1-2022-05-30 00:33:44.429 -- SynchronousMqttBrowserConnectionHandler::internalConnect - initiating connection try 0, auto reconnect in progress false
1-2022-05-30 00:33:44.430 -- SynchronousMqttBrowserConnectionHandler::internalConnect - calling connect
1-2022-05-30 00:33:44.432 -- MqttBrowserWsConnection::connect - entered
1-2022-05-30 00:33:44.435 -- MqttBrowserWsConnection::connect -  WS URL is ws://test.mosquitto.org:8080
1-2022-05-30 00:33:44.445 -- MqttBrowserWsConnection::connect - connection is waiting
1-2022-05-30 00:33:44.875 -- MqttBrowserWsConnection::connect - websocket is open
1-2022-05-30 00:33:44.876 -- MqttBrowserConnection::_startListening
1-2022-05-30 00:33:44.879 -- SynchronousMqttBrowserConnectionHandler::internalConnect - connection complete
1-2022-05-30 00:33:44.879 -- SynchronousMqttBrowserConnectionHandler::internalConnect sending connect message
1-2022-05-30 00:33:44.880 -- MqttConnectionHandlerBase::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
Connect Variable Header: ProtocolName=MQTT, ProtocolVersion=4, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=true, WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=false, UserNameFlag=false, KeepAlive=0
MqttConnectPayload - client identifier is : Mqtt_MyClientUniqueId
1-2022-05-30 00:33:44.887 -- SynchronousMqttBrowserConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
1-2022-05-30 00:33:45.105 -- MqttBrowserConnection::_onData
1-2022-05-30 00:33:45.106 -- MqttBrowserConnection::_onData - message received MQTTMessage of type MqttMessageType.connectAck
Header: MessageType = MqttMessageType.connectAck, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 2
Connect Variable Header: TopicNameCompressionResponse={0}, ReturnCode={MqttConnectReturnCode.identifierRejected}
1-2022-05-30 00:33:45.107 -- MqttBrowserConnection::_onData - message available event fired
1-2022-05-30 00:33:45.109 -- MqttConnectionHandlerBase::_connectAckProcessor
1-2022-05-30 00:33:45.109 -- MqttConnectionHandlerBase::_connectAckProcessor connection rejected
1-2022-05-30 00:33:45.110 -- MqttConnectionHandlerBase::_performConnectionDisconnect entered
1-2022-05-30 00:33:45.110 -- MqttConnectionHandlerBase:: cancelling connect timer
1-2022-05-30 00:33:45.111 -- SynchronousMqttBrowserConnectionHandler::internalConnect - post sleep, state = Connection status is disconnected with return code of identifierRejected and a disconnection origin of none
1-2022-05-30 00:33:45.111 -- SynchronousMqttBrowserConnectionHandler::internalConnect - initiating connection try 1, auto reconnect in progress false
1-2022-05-30 00:33:45.111 -- SynchronousMqttBrowserConnectionHandler::internalConnect - calling connect
1-2022-05-30 00:33:45.112 -- MqttBrowserWsConnection::connect - entered
1-2022-05-30 00:33:45.112 -- MqttBrowserWsConnection::connect -  WS URL is ws://test.mosquitto.org:8080
1-2022-05-30 00:33:45.114 -- MqttBrowserWsConnection::connect - connection is waiting
1-2022-05-30 00:33:45.115 -- MqttBrowserConnection::_startListening - websocket is closed
1-2022-05-30 00:33:45.115 -- MqttConnectionBase::_onDone - calling disconnected callback
1-2022-05-30 00:33:45.566 -- MqttBrowserWsConnection::connect - websocket is open
1-2022-05-30 00:33:45.566 -- MqttBrowserConnection::_startListening
1-2022-05-30 00:33:45.567 -- SynchronousMqttBrowserConnectionHandler::internalConnect - connection complete
1-2022-05-30 00:33:45.567 -- SynchronousMqttBrowserConnectionHandler::internalConnect sending connect message
1-2022-05-30 00:33:45.567 -- MqttConnectionHandlerBase::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 61
Connect Variable Header: ProtocolName=MQTT, ProtocolVersion=4, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=true, WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=false, UserNameFlag=false, KeepAlive=0
MqttConnectPayload - client identifier is : Mqtt_MyClientUniqueId
1-2022-05-30 00:33:45.568 -- SynchronousMqttBrowserConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
1-2022-05-30 00:33:45.792 -- MqttBrowserConnection::_onData
1-2022-05-30 00:33:45.793 -- MqttBrowserConnection::_onData - message received MQTTMessage of type MqttMessageType.connectAck
Header: MessageType = MqttMessageType.connectAck, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 2
Connect Variable Header: TopicNameCompressionResponse={0}, ReturnCode={MqttConnectReturnCode.identifierRejected}
1-2022-05-30 00:33:45.793 -- MqttBrowserConnection::_onData - message available event fired
1-2022-05-30 00:33:45.794 -- MqttConnectionHandlerBase::_connectAckProcessor
1-2022-05-30 00:33:45.794 -- MqttConnectionHandlerBase::_connectAckProcessor connection rejected
1-2022-05-30 00:33:45.794 -- MqttConnectionHandlerBase::_performConnectionDisconnect entered
1-2022-05-30 00:33:45.794 -- MqttConnectionHandlerBase:: cancelling connect timer
1-2022-05-30 00:33:45.795 -- SynchronousMqttBrowserConnectionHandler::internalConnect - post sleep, state = Connection status is disconnected with return code of identifierRejected and a disconnection origin of none
1-2022-05-30 00:33:45.795 -- SynchronousMqttBrowserConnectionHandler::internalConnect - initiating connection try 2, auto reconnect in progress false
1-2022-05-30 00:33:45.795 -- SynchronousMqttBrowserConnectionHandler::internalConnect - calling connect
1-2022-05-30 00:33:45.795 -- MqttBrowserWsConnection::connect - entered
1-2022-05-30 00:33:45.796 -- MqttBrowserWsConnection::connect -  WS URL is ws://test.mosquitto.org:8080
1-2022-05-30 00:33:45.797 -- MqttBrowserWsConnection::connect - connection is waiting
1-2022-05-30 00:33:45.797 -- MqttBrowserConnection::_startListening - websocket is closed
1-2022-05-30 00:33:45.797 -- MqttConnectionBase::_onDone - calling disconnected callback
1-2022-05-30 00:33:46.233 -- MqttBrowserWsConnection::connect - websocket is open
1-2022-05-30 00:33:46.233 -- MqttBrowserConnection::_startListening
1-2022-05-30 00:33:46.234 -- SynchronousMqttBrowserConnectionHandler::internalConnect - connection complete
1-2022-05-30 00:33:46.234 -- SynchronousMqttBrowserConnectionHandler::internalConnect sending connect message
1-2022-05-30 00:33:46.234 -- MqttConnectionHandlerBase::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 61
Connect Variable Header: ProtocolName=MQTT, ProtocolVersion=4, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=true, WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=false, UserNameFlag=false, KeepAlive=0
MqttConnectPayload - client identifier is : Mqtt_MyClientUniqueId
1-2022-05-30 00:33:46.236 -- SynchronousMqttBrowserConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
1-2022-05-30 00:33:46.454 -- MqttBrowserConnection::_onData
1-2022-05-30 00:33:46.454 -- MqttBrowserConnection::_onData - message received MQTTMessage of type MqttMessageType.connectAck
Header: MessageType = MqttMessageType.connectAck, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 2
Connect Variable Header: TopicNameCompressionResponse={0}, ReturnCode={MqttConnectReturnCode.identifierRejected}
1-2022-05-30 00:33:46.455 -- MqttBrowserConnection::_onData - message available event fired
1-2022-05-30 00:33:46.455 -- MqttConnectionHandlerBase::_connectAckProcessor
1-2022-05-30 00:33:46.455 -- MqttConnectionHandlerBase::_connectAckProcessor connection rejected
1-2022-05-30 00:33:46.456 -- MqttConnectionHandlerBase::_performConnectionDisconnect entered
1-2022-05-30 00:33:46.456 -- MqttConnectionHandlerBase:: cancelling connect timer
1-2022-05-30 00:33:46.456 -- SynchronousMqttBrowserConnectionHandler::internalConnect - post sleep, state = Connection status is disconnected with return code of identifierRejected and a disconnection origin of none
1-2022-05-30 00:33:46.456 -- SynchronousMqttBrowserConnectionHandler::internalConnect failed
EXAMPLE::client exception - mqtt-client::NoConnectionException: The maximum allowed connection attempts ({3}) were exceeded. The broker is not responding to the connection request message correctly The return code is MqttConnectReturnCode.identifierRejected
1-2022-05-30 00:33:46.458 -- MqttConnectionHandlerBase::disconnect - entered
1-2022-05-30 00:33:46.459 -- MqttConnectionHandlerBase::_performConnectionDisconnect entered
EXAMPLE::OnDisconnected client callback - Client disconnection
EXAMPLE::OnDisconnected callback is solicited, this is correct
1-2022-05-30 00:33:46.461 -- MqttBrowserConnection::_startListening - websocket is closed
1-2022-05-30 00:33:46.461 -- MqttConnectionBase::_onDone - calling disconnected callback
1-2022-05-30 00:33:46.462 -- MqttClient::internalDisconnect - not invoking disconnect, no connection handler
Application finished.
Exited (sigterm)

**Comment by shamblett** [comment]
Your client identifier is being rejected -
```
1-2022-05-30 00:33:45.106 -- MqttBrowserConnection::_onData - message received MQTTMessage of type MqttMessageType.connectAck
Header: MessageType = MqttMessageType.connectAck, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 2
Connect Variable Header: TopicNameCompressionResponse={0}, ReturnCode={MqttConnectReturnCode.identifierRejected}
1-2022-05-30 00:33:45.107 -- MqttBrowserConnection::_onData - message available event fired
1-2022-05-30 00:33:45.109 -- MqttConnectionHandlerBase::_connectAckProcessor
1-2022-05-30 00:33:45.109 -- MqttConnectionHandlerBase::_connectAckProcessor connection rejected
```

**Comment by Tejas-MD** [comment]
> Your client identifier is being rejected -
> ```
> 1-2022-05-30 00:33:45.106 -- MqttBrowserConnection::_onData - message received MQTTMessage of type MqttMessageType.connectAck
> Header: MessageType = MqttMessageType.connectAck, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 2
> Connect Variable Header: TopicNameCompressionResponse={0}, ReturnCode={MqttConnectReturnCode.identifierRejected}
> 1-2022-05-30 00:33:45.107 -- MqttBrowserConnection::_onData - message available event fired
> 1-2022-05-30 00:33:45.109 -- MqttConnectionHandlerBase::_connectAckProcessor
> 1-2022-05-30 00:33:45.109 -- MqttConnectionHandlerBase::_connectAckProcessor connection rejected
> ```
> 

Yes, I did observe the same too. I tried a lot of other client identifiers but none worked. Please suggest one yourself, I'm down to try it

**Comment by shamblett** [comment]
Its really up to whatever your broker is expecting but I tend to use smallish ones like 'SJH_Client' or some such.
