### ISSUE TITLE
Can't connect to server with username and password

### ISSUE THREAD

**Issue by goat-solutions** [shamblett/mqtt_client#389]
Hello, I'm getting this error when trying to connect to a broker I created locally on my network using VerneMQ:

> MQTT: client exception - SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = 192.168.15.13, port = 53743

I'm initializing MQTT client like this:

    _client = MqttServerClient.withPort(_host!, _identifier, port);

    _client!.logging(on: false);
    _client!.setProtocolV311();
    _client!.keepAlivePeriod = 20;
    _client!.secure = true;

    _client!.onDisconnected = onDisconnected;
    _client!.onConnected = onConnected;
    _client!.onSubscribed = onSubscribed;
    _client!.onUnsubscribed = onUnsubscribed;

    final MqttConnectMessage connMess = MqttConnectMessage()
      .withClientIdentifier(_identifier)
      .startClean()
      .authenticateAs(username, password)
      .withWillQos(MqttQos.atLeastOnce);
    _client!.connectionMessage = connMess;

Where,

    host = "192.168.15.13" // IP of my MQTT server
    port = 29170
    identifier = "teste"
    username = "teste"
    password = "teste"

As you can see in the error message, the port given is 53743, but I have set it to 29170. Why is this happening?

In VerneMQ, I have certain that I've configured correctly the authentication system, based on this [documentation](https://docs.vernemq.com/configuring-vernemq/file-auth), and mainly because I've tested the same credentials (clientId, username and password) in a demo MQTT client ([MQTT Explorer](https://apps.apple.com/us/app/mqtt-explorer/id1455214828?mt=12)):

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/99085187/174437838-0dcc321d-6734-4df9-99ce-725228e00d8c.png">
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/99085187/174437883-57ff17f0-029a-4c5a-a3b7-8f4997c0164d.png">
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/99085187/174437906-9a868fdd-81b6-4466-8997-3165793858d1.png">

**Comment by shamblett** [comment]
Please turn on logging on the client and post the output.

**Comment by goat-solutions** [comment]
Thanks for the quick response!

    flutter: 1-2022-06-18 10:57:10.878644 -- MqttClient::connect - keep alive is enabled with a value of 20 seconds
    flutter: 1-2022-06-18 10:57:10.883080 -- MqttConnectionKeepAlive:: Initialised with a keep alive value of 20 seconds
    flutter: 1-2022-06-18 10:57:10.883480 -- MqttConnectionKeepAlive:: Disconnect on no ping response is disabled
    flutter: 1-2022-06-18 10:57:10.884709 -- MqttConnectionHandlerBase::connect - server 192.168.15.13, port 29170
    flutter: 1-2022-06-18 10:57:10.886267 -- SynchronousMqttServerConnectionHandler::internalConnect entered
    flutter: 1-2022-06-18 10:57:10.886715 -- SynchronousMqttServerConnectionHandler::internalConnect - initiating connection try 0, auto reconnect in progress false
    flutter: 1-2022-06-18 10:57:10.887285 -- SynchronousMqttServerConnectionHandler::internalConnect - secure selected
    flutter: 1-2022-06-18 10:57:10.888066 -- SynchronousMqttServerConnectionHandler::internalConnect - calling connect
    flutter: 1-2022-06-18 10:57:10.888922 -- MqttSecureConnection::connect - entered
    flutter: 1-2022-06-18 10:57:11.062340 -- MqttConnectionBase::_onError - calling disconnected callback
    flutter: MQTT: client exception - SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = 192.168.15.13, port = 57998
    flutter: MQTT: Disconnected
    flutter: 1-2022-06-18 10:57:11.064915 -- MqttConnectionHandlerBase::disconnect - entered
    flutter: 1-2022-06-18 10:57:11.065228 -- MqttConnectionHandlerBase::_performConnectionDisconnect entered
    flutter: 1-2022-06-18 10:57:11.066030 -- MqttConnectionKeepAlive::stop - stopping keep alive
    flutter: MQTT: Disconnection callback
    flutter: MQTT: Disconnection error callback

**Comment by shamblett** [comment]
You are connecting on port 29170, from the log -
```
flutter: 1-2022-06-18 10:57:10.884709 -- MqttConnectionHandlerBase::connect - server 192.168.15.13, port 29170
```
The port in the exception is probably the client port number allocated by the server, this exception is raised by the flutter runtime, not the package as such and is indicating it can't see your broker on the network.

I've noticed you are setting ' _client!.secure = true;' which means you want secure TLS working but you are not passing a security context to go with this so it won't work. Your first screenshot above does not have TLS selected so I guess you would be better off removing the secure setting for now and seeing what happens.

**Comment by goat-solutions** [comment]
Yea! That was it!

I set the flag to false and the connection was successful!
