### ISSUE TITLE
How could I connect to the following server with base path?

### ISSUE THREAD

**Issue by EgHubs** [shamblett/mqtt_client#392]
How could I connect to the following server with base path?

wss://xxxxxx.com:8084/mqtt
I tried the following
```
final client = MqttServerClient('wss://mqtt.xxx.xyz:8084/mqtt', '');
await client.connect();
```
and didn't pass any port like 
client.port....
but with logging, I get the following

> flutter: 3-2022-07-07 11:24:06.383576 -- MqttConnectionHandlerBase::connect - server wss://mqtt.xxx.xyz:8084/mqtt, port 1883

which Is obvious that it gives the default port with my port

**Comment by shamblett** [comment]
Remove the port from the URL string and set it on the client with client.port(or pass it on connect), you are also using web sockets so make sure you have web socket option set on the client.
