### ISSUE TITLE
no_matching_hook_found error without using webhooks

### ISSUE THREAD

**Issue by goat-solutions** [shamblett/mqtt_client#393]
Hello, I'm having a problem trying to publish a topic, causing my client to disconnect. I can successfully connect, the error only occurs when trying to publish.

I got the below error from the log which is in `/var/log/vernemq/error.log`.

> 2022-07-09 11:32:36.106 [error] <0.1050.0>@vmq_mqtt_fsm:auth_on_publish:{739,13} can't auth publish [<<>>,{[],<<"mqtt-explorer" >>},1,[<<"furnace">>],<<"1">>,false] due to no_matching_hook_found

I'm doing authentication without username and password, and I enabled the `allow_anonymous` parameter in the `vernemq.conf` file.

**Comment by shamblett** [comment]
This is a log showing your vernemq broker isnt working not the client maybe its misconfigured I cant see what this has to do with the client.

**Comment by goat-solutions** [comment]
Alright, tanks for the reply! I will try to contact the broker staff.
