### ISSUE TITLE
when using persistent session, the client cannot receive message

### ISSUE THREAD

**Issue by dikinova** [shamblett/mqtt_client#394]
Hello, when using persistent session, the client cannot receive message.

The demo code is like this.
1. the receiver make a persistent session by cleanSession=false and disconnect,
2. the sender connect and publish a message to the topic
3. the receiver reconnect again and wait incoming messages. I think the receiver should receive msg 100_20, but it never happens.

```
    println_("step 20");
    await fReceiveMsg(receiver_,
        cleanSession: false, sleepMs: 1000, disconnect: true);

    var sender = "${sender_}_100_0";
    var content = "[$runId] 100_20 hello";
    await fSendMsg(sender, content);

    var r1 = await fReceiveMsg(receiver_,
        cleanSession: false, sleepMs: 1000 * 5, disconnect: true);

    println_("step 20 should receive msg 100_20" + "!" * 5);


```

The Demo mqtt_demo1201.dart is runnable, you can test it easily.

software version:
  mqtt_client: ^9.6.8
[demo.zip](https://github.com/shamblett/mqtt_client/files/9108094/demo.zip)

**Comment by dikinova** [comment]
I just update the attachment. run 'flutter test ' can start the demo
[demo1201_project.zip](https://github.com/shamblett/mqtt_client/files/9108658/demo1201_project.zip)

**Comment by shamblett** [comment]
OK I'll have a look at this, just a couple of things from the top of my head, your setting of clean session looks OK, you can check you have a session present in the conack message by checking the session present flag -
```
Since MQTT 3.1.1, the CONNACK message from the broker contains a session present flag. This flag tells the client if a previously established session is still available on the broker. For more information on connection establishment, see [part 3 of MQTT Essentials](https://www.hivemq.com/blog/mqtt-essentials-part-3-client-broker-connection-establishment/).
```
You should be able to see this with logging turned on after you have disconnected and connected again, also note you must use exactly the same client id and persistence only works for QOS1 and QOS2 messages. Please make sure you have set the client protocol version to 3.1.1.

Which broker are you using? In my experience Mosquitto and Hive don't need any extra setup for persistence to work but others might.

**Comment by dikinova** [comment]
In the log file I cannot find the session present value in the conack message

	8-2022-07-17 13:14:15.143840 -- MqttServerConnection::_onData - message received MQTTMessage of type MqttMessageType.connectAck
	Header: MessageType = MqttMessageType.connectAck, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 2
	Connect Variable Header: TopicNameCompressionResponse={0}, ReturnCode={MqttConnectReturnCode.connectionAccepted}


config information  is in mqtt_setup_config.dart file:
	final broker_emqx = "broker-cn.emqx.io";
	var broker = broker_emqx;
	final topic = "testdt1301";
	final sender_ = "demo_dt_sender";
	final receiver_ = "demo_dt_receiver";
	final Qos = MqttQos.exactlyOnce;

protocol version is 3.1.1
  _client.setProtocolV311();

	
the broker itself works fine, I have tested it by a java mqtt client. Anyway you can change to another server to test, it doesn't matter.

**Comment by shamblett** [comment]
This seems to work for me, I was getting confused with the MQTT 5 client for the session present flag, this client doesn't actually print this in the log, I'll fix this, screenshot attached from my hivemq test broker -
 
![image](https://user-images.githubusercontent.com/270345/179393701-e73d34ce-ea3f-4956-b5d8-92245e064a77.png)

Notice the Message queue size and the session expiry parameters on the left.

Also attached is a zip file of my test project, run generator.dart, then run receiver_subscribe_nowait.dart, receive some messages, stop it and run it again, you will see that it correctly receives the messages from the generator that were queued when it was stopped. Try the same with the receiver_subscribe.dart and you will see a gap, this is caused by there not being a listener attached quickly enough in the code, you have to attach the client listener immediately so it is ready to receive incoming messages.

[persistence.zip](https://github.com/shamblett/mqtt_client/files/9127414/persistence.zip)

**Comment by dikinova** [comment]
Well, I find the line 26 is the problem. If the client sleeps a while after connect() call , it will lose messages.

receiver_subscribe.dart 

```
await MqttUtilities.asyncSleep(2);

```



```
/*
 * Package : mqtt_client
 * Author : S. Hamblett <steve.hamblett@linux.com>
 * Date   : 31/05/2017
 * Copyright :  S.Hamblett
 */

import 'dart:async';
import 'package:mqtt_client/mqtt_client.dart';
import 'package:mqtt_client/mqtt_server_client.dart';

import 'mqtt_setup_config.dart';

Future<int> main() async {
  final client = MqttServerClient.withPort(broker, 'SJHIssueRx', 1883);

  client.logging(on: false);
  client.setProtocolV311();
  const topic = 'counter';
  final connMess = MqttConnectMessage();
  client.connectionMessage = connMess;

  print('ISSUE: Connecting');
  await client.connect();

  // await MqttUtilities.asyncSleep(2);

  // Listen for the counter messages
  print('ISSUE::Listening......');
  client.updates?.listen((List<MqttReceivedMessage<MqttMessage>> c) {
    final recMess = c[0].payload as MqttPublishMessage;
    final payload = recMess.payload.message;
    if (payload != null) {
      final counterValue = payload[0];
      print('ISSUE::Change notification:: counter received is $counterValue');
    } else {
      print('ISSUE - ERROR payload is null');
    }
  });

  // Subscribe to counter, Qos 1
  client.subscribe(topic, MqttQos.atLeastOnce);
  print(
      'EXAMPLE:: Sleeping to allow the subscription acknowledges to be received....');

  await MqttUtilities.asyncSleep(10);

  print('ISSUE: Test complete');
  client.disconnect();

  return 0;
}


```

**Comment by dikinova** [comment]
maybe we could improve the api by adding a method to MqttClient, such as connectWithListener(....)

**Comment by shamblett** [comment]
Yes you must start listening before anything else (exvept connect) note thi is safe enough if you have a persistent session you dont have to resubscribe either  you can just start listening.

I know why this is and can fix it to remove this restriction from users code but for now if you want to use persistent sessions please update your code appropriately

**Comment by shamblett** [comment]
This may be why this has not been reported before I guess
