### ISSUE TITLE
Allow to set connectTimer in SynchronousMqttServerConnectionHandler class

### ISSUE THREAD

**Issue by chrislenguyen** [shamblett/mqtt_client#396]
Hi there,

I currently using your library to connect to an MQTT server, the MQTT server will then perform an authentication service which takes a little too long to respond, and before the MQTT server can respond it will try to auto-reconnect and send the authentication information again therefore I cannot get the respond from MQTT server. 

When I cloned the repository and increased the `connectTimer` variable in `SynchronousMqttServerConnectionHandler` class it gave the server a little more time to process and everything worked properly.

So can you consider the allow the ability to set the `connectTimer` so it could be more flexible on the time out

Thank you so much.

**Comment by shamblett** [comment]
OK, you can now do this -
```
client.connectTimeoutPeriod = xxxx;
```
Where xxxx is the timeout in milliseconds, minimum 1000.

Package released at version 9.7.0

**Comment by chrislenguyen** [comment]
Thank you so much, i will close this issue now
