### ISSUE TITLE
MqttEncoding::getBytes encodes the UTF-16 code units as the length instead of UTF-8

### ISSUE THREAD

**Issue by sethloco** [shamblett/mqtt_client#399]
Greetings,

I noticed in this test that the expected length of the topic was 89, but I think it should be 90
https://github.com/shamblett/mqtt_client/blob/f3eef537980101bd743a941d8316d5ac60a0c3eb/test/mqtt_client_message_test.dart#L1103

I think the issue is that the Dart string.length is what gets encoded in instead of the length of the utf8 converted bytes.
https://github.com/shamblett/mqtt_client/blob/f3eef537980101bd743a941d8316d5ac60a0c3eb/lib/src/encoding/mqtt_client_mqtt_encoding.dart#L22

BTW, this looks to be correct already in the mqtt5_client project
https://github.com/shamblett/mqtt5_client/blob/master/lib/src/encoding/mqtt_utf8_encoding.dart#L32

**Comment by shamblett** [comment]
OK thanks Ill look at this.

**Comment by shamblett** [comment]
Fixed, package re released at version 9.7.1

**Comment by sethloco** [comment]
Thanks!
