### ISSUE TITLE
Messages not received on iOS in background mode

### ISSUE THREAD

**Issue by iosephmagno** [shamblett/mqtt_client#400]
Hello,
If app is moved to background mode on iOS, messages are no longer received after a little while.

Issue doesnt occur on android (messages received in both foreground and background mode)

Is this a bug or there is an extra settings we should adopt on iOS?

Any help on this would be much appreciated!

**Comment by iosephmagno** [comment]
For clarity, app still receives messages soon after it goes from foreground to background mode.

After spending a very little time in background mode, messages no longer arrive.

**Comment by shamblett** [comment]
The package is just a Dart library, it doesn't know where its running so there is no support for any specific runtime in the code, you may be able to do something with flutter here I guess but I don't know exactly what, maybe ask the flutter guys.

**Comment by iosephmagno** [comment]
Thanks @shamblett 
Indeed it seems normal ios behaviour, we have  5sec after app moves to background.
 https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/extending_your_app_s_background_execution_time

So on iOS we should only rely on fcm notifications. User receives offline messages there and then opens app back. We can do sth with flutter to awaken app every now and then but we might not need it.
