### ISSUE TITLE
Error in pubspec.yaml when using V9.7.1

### ISSUE THREAD

**Issue by mars000** [shamblett/mqtt_client#404]
hope you can help.
When I upgrade to V9.7.1 i get following error ...
Not sure how to fix this if you can help would be much appreciated.
```
Running "flutter pub get" in flowDETECT_app...                  
Because every version of flutter_test from sdk depends on path 1.8.1 and mqtt_client >=9.6.9 depends on path ^1.8.2, flutter_test from sdk is incompatible with mqtt_client >=9.6.9.
So, because flowdetect depends on both mqtt_client ^9.7.1 and flutter_test from sdk, version solving failed.
pub get failed (1; So, because flowdetect depends on both mqtt_client ^9.7.1 and flutter_test from sdk, version solving failed.)
```

**Comment by mars000** [comment]
thank you for the reply.
flutter_test is part of core library and I'm using latest version of flutter 3.0.5
So it would seem I'm using the latest version of flutter_test ?

**Comment by mars000** [comment]
just to add when I comment out `flutter_test` from `pubspec.yaml` I get the following error:
```
Running "flutter pub get" in flowDETECT_app...                  
Because mqtt_client >=9.6.9 depends on meta ^1.8.0 and every version of flutter from sdk depends on meta 1.7.0, mqtt_client >=9.6.9 is incompatible with flutter from sdk.
So, because flowdetect depends on both flutter from sdk and mqtt_client ^9.7.1, version solving failed.
pub get failed (1; So, because flowdetect depends on both flutter from sdk and mqtt_client ^9.7.1, version solving failed.)
exit code 1
```

**Comment by shamblett** [comment]
Yes, again its showing that the flutter SDK is behind the latest version of these dependent packages.

By the looks of it the path package version changed  at version 9.6.8 so you should be OK to use version 9.6.7 of this package.

This has happened before, for some reason Google pin flutter SDK releases to certain package version, this is all very well but you have to update frequently if you are going to do this or you will get situations like this.

**Comment by JacoFourie** [comment]
Upgrade to version 3.3.0 then the error goes away.
