### ISSUE TITLE
Using plugin for multiple screen

### ISSUE THREAD

**Issue by chetan-SMRI** [shamblett/mqtt_client#406]
Actually, now I managed to run it successfully, but I just need to know how do i use it for multiple screens,
I mean when I go to different screens, I have to do connect seperately with server for different screen , but it just wastes the time of screen loader.
But I can't figure out any other solution because I need to use listener for each, in all cases however the subscription topic is the same.

Suggestions

**Comment by shamblett** [comment]
The package has no concept of 'screens' as such, its just an MQTT client that you can use as you wish. For flutter use you should only instantiate one client and share it across your app, not instantiate one every time you change screens. I'm not a flutter user so I don't know how you would do this but there are packages on pub like [this](https://pub.dev/packages/ez_mqtt_client) that may help, there may be others. Failing that ask the flutter guys how to do this.
