### ISSUE TITLE
Publish to topic1 and Listen to topic2

### ISSUE THREAD

**Issue by JohanScheepers** [shamblett/mqtt_client#407]
I have a Flutter application publishing to 'topic1' and currently listening to 'topic1'. Works 100%

I want to publish to 'topic1' and then listener to 'topic2' , is this possible?

Both topics are from the same host.

**Comment by shamblett** [comment]
Yes you can listen to any topic however you will.only re ceive whats published to.it. if no one else is publishing to it you will receive nothing. If you want to publish to it you can do of course.

**Comment by JohanScheepers** [comment]
This is what I were referring to.

```
    final String _topic1;
    final String _topic2;
```

```
          _topic1 = 'topic1',
          _topic2 = 'topic2',
```

and then

```
          _client!.publishMessage(_topic1, MqttQos.exactlyOnce, builder.payload!);
```

```
          _client!.subscribe(_topic2, MqttQos.atLeastOnce);
```

Thank you found the answer
