### ISSUE TITLE
Mqtt IOS issue

### ISSUE THREAD

**Issue by chetan-SMRI** [shamblett/mqtt_client#411]
I have a app which check currently connected devices. From my own personal server.

The problem is this, that it works just fine in android but in iOS code it doesn't connect 80% of the time.

I mean that the plugin work in iOS but it isn't so accurate like in android.

**Comment by chetan-SMRI** [comment]
[iOS testing](https://drive.google.com/file/d/1RzQGMUloHhBcUoFxPFBKBJEccPQzJ9-J/view?usp=drivesdk) 

[Android testing](https://drive.google.com/file/d/1SHUtibrF2RqbaakjRrqEJuknxeJIUgvM/view?usp=drivesdk) 



In both above testing u can see that it shows the device currently online, but in iOS it doesn't work right always, ie it is unable to connect to server sometimes.

**Comment by shamblett** [comment]
The client is just Dart code, it doesn't know where it is running, that being in the VM, a browser or a flutter runtime. If your app is working fine on Android and doesn't work in the same way on IOS this is a flutter run time issue, there's nothing the client can help you with here, it doesn't change its behaviour depending on where its running.

I suggest you contact the flutter guys at Google and see what they say.

**Comment by JacoFourie** [comment]
I have been using the client for more than a year on all platforms. It works 100% on all. You are doing something wrong.
