### ISSUE TITLE
Send separated Offline Messages

### ISSUE THREAD

**Issue by GaelleJoubert** [shamblett/mqtt_client#424]
Hello, I've looked for this topic in the previous issues for this topic, but didn't find anything about it.

Here is my situation.
I'm using MQTT to send String messages formated like json. For the exemple let say the messages are : 

`{"key":"MessageTXT1"}` , `{"key":"MessageTXT2"}` ,  ...

They each text is send in a seperate mqtt message, and it works very well.

However, when i turn off the Internet connexion, and then turn it on again, all the messages that could not be sent, are send as one big message. All the text is concatenated. For exemple if 3 messages could not have been sent  because mqtt was offline, when it is online again, one big message is send : 
`{key:"MessageTXT1"}{key:"MessageTXT2"}{key:"MessageTXT3"}`

I would actually like to send the "bufferised messages"' not at on big message, but as seperated messages, like it is the case when MQTT is online.

I didn't find out how to do that. Is that even possible ?
Thanks you for your help !

**Comment by shamblett** [comment]
I'm not sure why it should do this, all messages are turned into a byte stream for sending, like this -
```
 header!.writeTo(variableHeaderLength + payloadLength, messageStream);
    variableHeader!.writeTo(messageStream);
    payload.writeTo(messageStream);
```
The client checks if its connected before sending but there may be a lag between the internet connection being turned off and the client being told this, so some messages might get through to the socket layer buffer where they will be stored for onward transmission when the connection is restored, however they should still be separate messages as far as the MQTT broker is concerned. 

What seems to be happening to you is that the payloads are concatenated together into one message. I would be interesting to know what the MQTT header details are for this message. 

Where exactly in the transmission chain are you seeing your concatenated message exactly? Are you seeing this at the broker or the recieving MQTT client?

**Comment by GaelleJoubert** [comment]
Hello, thanks for your answer.
I see the concatenated message in my Web socket client. 
I attached bellow a screenshot of my view : the little messages are the single messages sent with internet connexion. And the Big chunck is the concatenated message send after a internet disconnexion and reconnexion. 

![image](https://user-images.githubusercontent.com/86407953/203007334-3c390087-6b6a-4083-8840-fc809e3d3ea9.png)

I'm looking for the header and will send it to you as soon as I have it.

**Comment by GaelleJoubert** [comment]
So about the Header, here is all the info about the MQTT message received which was concatenated : 

![image](https://user-images.githubusercontent.com/86407953/203042079-cdebbed8-530c-42fc-9272-0978ce446d10.png)

You can see all the details of the header.
For comparaison purpose, here is the detail of a "normal" message, sent when the app was "online", and not concatenated :  
![image](https://user-images.githubusercontent.com/86407953/203042308-ee272805-256a-4247-89f0-3f5eac58443c.png)


Let me know if you need more info. 
Thanks you very much.

**Comment by GaelleJoubert** [comment]
[ Update ] It is still not working correctly, but I got some news.
After taking a closer look I think !i was using the "builder" incorectly. 
Here is my previous "send" function :  

```
final MqttClientPayloadBuilder _builder = MqttClientPayloadBuilder();
mqttSend(String message, SendPort? sendPort, {required topicType type}) async {
  
  _builder.addString(message);
  /// Publish it
  try{
  _client.publishMessage(buildTopic(type: type), MqttQos.exactlyOnce, _builder.payload! );
  builder.clear();
  }
      catch (e){
        MqttClientConnectionStatus? _status = await _client.connectionStatus;
        print("MQTT:${_status?.state.toString()}" );
        sendPort?.send("$CODE_MQTT:${_status?.state.toString()}");
      }
}
```

This function is called each time I have new data to send (which is at least one time per second). As you can see the builder was outside of it, that's why it was "piling up" I guess.
I try to modify it by including it inside the function so it would be a new builder each time I call the function : 


```
mqttSend(String message, SendPort? sendPort, {required topicType type}) async {
  final MqttClientPayloadBuilder _builder = MqttClientPayloadBuilder();
  _builder.addString(message);
  /// Publish it

  try{
  _client.publishMessage(buildTopic(type: type), MqttQos.exactlyOnce, _builder.payload! );

  }
      catch (e){
        MqttClientConnectionStatus? _status = await _client.connectionStatus;
        print("MQTT:${_status?.state.toString()}" );
        sendPort?.send("$CODE_MQTT:${_status?.state.toString()}");
      }
}
```

But now, the result is that, if I turn off internet, and turn it on again, **all the messages that are sent in that time frame are lost** ...

So I guess I must still be something wrong, but I can't figure out what. Do you have any idea ?

**Comment by shamblett** [comment]
This makrs more sense  it is the payload that is being added to with a single header. 

The client does not store messages for you whilst disconnected. You can use the disconnected/connected/autoreconnected callbacks to control.what you do with messages in these states eg on disconnect you can stop sending or buffer yout messages on connected/autoreconnected you can start srnding again, send your buffered messages etc.

**Comment by GaelleJoubert** [comment]
But I'm not disconnecting.

I have set "autoreconnect" to true.
What I do is :
1- Connect to MQTT
2- Call my "send" function roughly 1 time/s
3- Turn off the wifi on my phone. So the MQTT state is "Connecting"
4- Turn back on the Wifi on my phone.

My understanding was that the MQTT library was abale to handle the storing and send of the message while the internet connexion was off. 
For exemple I had a look at this issue : https://github.com/shamblett/mqtt_client/issues/352
And it seems to work offline.
Or am I undertanding it wrong, and as you say, I have to handle the storing my self ?
Thanks you very much for your help.

**Comment by GaelleJoubert** [comment]
I can indeed see when I call the publishMessage, I have the following exception :
`"mqtt-client::ConnectionException: The connection must be in the Connected state in order to perform this operation. Current state is connecting"`

So there is no way of "sending" a message when the internet connexion is off, and that this message is bufferised and sent later when the connexion is back ?

**Comment by shamblett** [comment]
The broker has this capability  if someone is sending to you and you go offline the broker will store reveived messages till you comr on.line again and send them to you(if configured to do so). Your case os diffetent you are the sending client, if you go off line the broker will teceive no messages so cannoy store thrm.

MQTT doesnt specify what sending clients dhould do here for instance if you were say srnding temperature then gp.offline ehen yo.come back online you could just send the latest reading, no need to store anything. All clients will.have different requirements for this scenario

**Comment by GaelleJoubert** [comment]
Ok Ok, thanks you for the explaination !
Well in my case I am sending GPS position, so I will need all the points and not juste the last reading :) 
But I will handle that on my side. 
Thanks for the answer. 

I don't know if this is easily feasible, but that would be a cool option to add to this library.
For exemple we could set it before connecting like : `client.sendOfflineMessages= true;`

Thanks you for you work anyway :)
