### ISSUE TITLE
Subscribe to all topics

### ISSUE THREAD

**Issue by rozenrod** [shamblett/mqtt_client#426]
Is it possible to view the mqtt history and see the topics that I am not subscribed to, or subscribe to all topics?

**Comment by shamblett** [comment]
The 'subscribe' method on the client returns a 'Subscription' class, 'getSubscriptionStatus' will get you the current subscription status of a topic, this being 'doesNotExist', 'pending' or 'active'. There is no subscribe to all topics method, there is a resubscribe to all topics but this is probaly not what you want, see the API docs for details.

There is no history in the client, it doesn't keep track of subscribe/unsubscribe calls for a topic, so if you get a 'doesNotExist' returned from 'getSubscriptionStatus' it means it does not currently exist, it may have been subscribed/unsubscribed several times in the past but there is no way of knowing this unless you track it yourself of course.

**Comment by rozenrod** [comment]
I found a method to subscribe to all messages. I just need to subscribe to '#', then all messages will come to me.
