### ISSUE TITLE
[bug] resubscribe should include all pending subscription topics

### ISSUE THREAD

**Issue by aaassseee** [shamblett/mqtt_client#432]
_resubscribe function in SubscriptionsManager
https://github.com/shamblett/mqtt_client/blob/6752f6d4232027a3db8cd4a319ce4798a72fcff7/lib/src/mqtt_client_subscriptions_manager.dart#L232-L234
should include both subscriptions.value and pendingSubscriptions.value due to the pendingSubscriptions will lost in resubscribe because of network issue.

Moreover, should pendingSubscriptions also have any mechanism to resubscribe if server no responding after (n) seconds?

**Comment by shamblett** [comment]
Yes, we should do this, I'll merge the PR.

Not sure about your second comment,  I'd rather not make the client too 'smart', if the client supplied a separate resubscribePending method then the user could monitor the state of their subscriptions and call this when needed, I'd rather let the user decide what to do here. Thoughts

**Comment by aaassseee** [comment]
Hi, @shamblett. About my second comment, I think I might come up with an [XY Problem](https://xyproblem.info) solution. So hear me out, the problem that I am facing with which is.

Whenever the client subscribe a topic and the server didn't response a SUBACK to client. The topic will stay forever in pendingSubscriptions map even I resubscribe the topic. Due to these lines of code
https://github.com/shamblett/mqtt_client/blob/7e1cd4b0bd1382414d43ec4b99f23cadc42eb11a/lib/src/mqtt_client_subscriptions_manager.dart#L88-L92
, there aren't any ways or solution to bring back or resubscribe the topic which is in the pendingSubscriptions map.

So I came up with the auto resubscribe solution.

**Comment by shamblett** [comment]
Yes agreed we need to look at this, the #433 PR you submitted only works during auto reconnect, its not a general case solution which if I'm reading you correctly is what you want.

 I'm proposing we add a public method on the client that performs the complete re-subscription of confirmed and pending subscriptions that the user can call as and when needed. The criteria for when or even if to do this will vary from user to user so I don't want to build any rules for this into the client, just provide the user with the means to do it.

**Comment by shamblett** [comment]
I've created branch issue432 for future work on this issue.

**Comment by shamblett** [comment]
Merged, in releases version 9.8.0
