### ISSUE TITLE
Support MQTT v5

### ISSUE THREAD

**Issue by six-edge** [shamblett/mqtt_client#434]
Is MQTT v5 support planned?

**Comment by shamblett** [comment]
I maintain a separate client for this, [here](https://pub.dev/packages/mqtt5_client),  I will try and unify these clients eventually.

**Comment by six-edge** [comment]
Oh that's great! Thanks 👏🏻

**Comment by six-edge** [comment]
Perhaps a link to v5 in the readme at the top would be good. Would prevent people like me asking unnecessary questions 😉

**Comment by shamblett** [comment]
Yes good idea, I'm doing some updates to the client at the moment, I'll roll this in.

**Comment by shamblett** [comment]
Done.
