### ISSUE TITLE
[bug] disconnect immediately during auto reconnect in weird situation

### ISSUE THREAD

**Issue by aaassseee** [shamblett/mqtt_client#435]
Hi @shamblett. I found another weird bug when the client opened after a day, which is client got disconnect during auto reconnect with clean session on.

### Context
I don't know what is the root cause of this problem maybe didn't get the CONNACK from server. However, I found that when this problem occur, I am pretty sure that the server is holding connected a session with same client identifier but the mqtt_client is shown that the session is already disconnect. With the status of server connected client disconnected, the auto reconnect cannot disconnect the existing session due to disconnect message must be send when client status is connected
https://github.com/shamblett/mqtt_client/blob/7e1cd4b0bd1382414d43ec4b99f23cadc42eb11a/lib/src/connectionhandling/mqtt_client_mqtt_connection_handler_base.dart#L128-L133
So, when the client send connect message with clean session the server will immediately kill the session and create a new one. Because of the session is likely new create in client side, so the client socket is closed by received a tcp connect finish packet from server side. And the loop get started.

I am using EMQX here is the [documentation](https://www.emqx.io/docs/en/v4.0/advanced/hooks.html#hookpoint) ![Screenshot 2022-12-29 at 3 49 45 PM](https://user-images.githubusercontent.com/2054978/209920930-a277eea8-7ce2-4a0b-9a5a-63b7c7ae7e06.png)

### Step to reproduce:
1. connect mqtt with client id like 123
2. hold the connection and come back after one day
3. found that client call auto reconnect infinitely
4. found that server is holding the connection
5. found that server close the session by capturing packet with Wireshark ![Screenshot 2022-12-29 at 4 02 25 PM](https://user-images.githubusercontent.com/2054978/209921672-662e23ea-91c6-4c64-8c1d-ca61591b889f.png)
6. found that client didn't send disconnect message to server due to client didn't know it has connection already ref: https://github.com/shamblett/mqtt_client/blob/7e1cd4b0bd1382414d43ec4b99f23cadc42eb11a/lib/src/connectionhandling/mqtt_client_mqtt_connection_handler_base.dart#L128-L133

**Comment by shamblett** [comment]
OK, I need to look at this a bit more but initial thoughts are we can't of course assume a disconnect message will ever get to the broker, no matter what state the client thinks its in, if we are at a point where we need to send disconnect we have lost connection somewhere. Originally I put the disconnect message in as a nicety, it would be nice if we closed down as cleanly as we can, however the MQTT spec does not mandate this, so we don't have to, probably to cater for sudden network/broker failure etc.

The autoreconnect sequence should re-send the original connect message, so we should preserve whatever session state it set, we shouldn't always be sending clean session, if we are doing this we have a bug somewhere.

Note that the connected/disconnected state in the client is for the state of the TCP connection, not the state of the session, we don't actually record this.
