### ISSUE TITLE
Enqueued messages iot hub not received on connecting

### ISSUE THREAD

**Issue by Merikw** [shamblett/mqtt_client#436]
Hi,

I have a problem with enqueued messages in Azure iot hub when reconnecting with the mqtt client. I am expecting to receive the queued messages on reconnect when I have a listener on the _updates_ stream before subscribing, but the messages are not received by the listener on the stream and they disappear from the iot hub queue, so they seem to be acknowledged. Any solution for this? Thanks!

**Comment by shamblett** [comment]
The broker will only send you queued messages on re connection if you are using a persistent MQTT session, see [here](https://www.hivemq.com/blog/mqtt-essentials-part-7-persistent-session-queuing-messages/), also this only works for messages of QOS 1 and 2.

I'm no expert with Azure but [this](https://learn.microsoft.com/en-us/azure/iot-dps/iot-dps-mqtt-support) page from the MS docs does say :-

_The following is a list of DPS implementation-specific behaviors:

DPS doesn't support persistent sessions. It treats every session as non-persistent, regardless of the value of the CleanSession flag. We recommend setting CleanSession to true._

So it may be that you can't do this on Azure, please check this yourself.

**Comment by Merikw** [comment]
Thanks for the fast response! I connected with either QOS 1 or 2 and didn't set any connection message which makes it a persistent session. The MS docs are refering to the following:

_If the device connects with CleanSession flag set to 0, the subscription is persisted across different sessions. In this case, the next time the device connects with CleanSession 0 it receives any outstanding messages sent to it while disconnected._ 
https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#receiving-cloud-to-device-messages

Still, the stream isn't being fired after connecting with pending messages in the queue (which are being enqueued on connecting) with the following setup:

```
client.clientIdentifier = [identifier];
client.secure = true;
    client.setProtocolV311();
    client.port = 8883;
    client.useWebSocket = false;
    client.autoReconnect = true;
    client.manuallyAcknowledgeQos1 = true;

client.onConnected = () {
      client.updates!
          .listen((List<MqttReceivedMessage<MqttMessage?>>? messages) async {
        if (messages != null) {
            //any logic
        }

       client.subscribe(
          [device topic], MqttQos.atLeastOnce);
});

await client.connect()
```

**Comment by shamblett** [comment]
This may be a manifestation of this #412 issue, what happens if you start listening as soon as possible, i.e. start listening as soon as possible, even before doing the client connect.

**Comment by Merikw** [comment]
Unfortunatly, if I start listening to the updates before making the connection, the updates stream is null so it isn't listenable

**Comment by Merikw** [comment]
I also tried it with a manual acknowledgement, but they still disappear from the iot hub device queue (which means that they are acknowledged) without informing the updates stream.

**Comment by shamblett** [comment]
O, I'll need a client log to see what's going on, it will show what's been received, what was done and when.

**Comment by Merikw** [comment]
@shamblett Sorry for the late response. It seems like the auto reconnect connects with the clean session flag to true; 

```
I/flutter (22516): Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 267

I/flutter (22516): Connect Variable Header: ProtocolName=MQTT, ProtocolVersion=4, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=false, WillQos=MqttQos.atMostOnce, WillRetain=false, PasswordFlag=true, UserNameFlag=true, KeepAlive=0
```

**Comment by Merikw** [comment]
Fixed this issue with setting de connection message as follows:

```
var connectionMessage = MqttConnectMessage().withProtocolVersion(4).withProtocolName("MQTT");
connectionMessage.variableHeader!.connectFlags.cleanStart = false;
```
