### ISSUE TITLE
Null check operator on auto reconnect

### ISSUE THREAD

**Issue by mis-kcn** [shamblett/mqtt_client#437]
Code is failing at `mqtt_client.dart` Line 353 at `clientEventBus!`. 

Error occurs at v.9.7.2, no clear MRE at the moment.

```
void doAutoReconnect({bool force = false}) {
    if (!autoReconnect) {
      MqttLogger.log(
          'MqttClient::doAutoReconnect - auto reconnect is not set, exiting');
      return;
    }

    if (connectionStatus!.state != MqttConnectionState.connected || force) {
      // Fire a manual auto reconnect request.
      final wasConnected =
          connectionStatus!.state == MqttConnectionState.connected;
      clientEventBus!
          .fire(AutoReconnect(userRequested: true, wasConnected: wasConnected));
    }
  }
```

**Comment by shamblett** [comment]
Ok the lfile mosquito_bloc.dart isnt from this package so Im not sure what this is, you dont say what the failure is, Im guessing a null exception, on the event bus this is usually caused by the client being disconnected and closed.

Ill need a log to look any further.

**Comment by mis-kcn** [comment]
Oops sorry about that, it wasn't with the `mosquitto_bloc` that was my own bloc implementation of the whole thing. 

Error occurs at `mqtt_client.dart` at the `doAutoReconnect` function.

**Comment by jehhxuxu** [comment]
Any news on this? I have the problem as well... log from firebase

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
Bad state: Cannot add new events after calling close. Error thrown null.
_BroadcastStreamController.add (_BroadcastStreamController.java)
EventBus.fire (event_bus.dart:61)
MqttConnectionHandlerBase.autoReconnect (mqtt_client_mqtt_connection_handler_base.dart:155)
```

**Comment by shamblett** [comment]
You've closed(disconnected) the client somehow before autoreconnect starts, do you have a full log of what happened before this point?

**Comment by jehhxuxu** [comment]
Nope, crashlytics show just this piece of error... 
Sending our implementation of connect and auto reconnect just verify if our token is not null and do connect again

![Screenshot 2023-03-10 at 19 02 58](https://user-images.githubusercontent.com/27310692/224436741-4c2431ba-b937-467d-b06b-da8822e67f97.png)
![Screenshot 2023-03-10 at 19 05 02](https://user-images.githubusercontent.com/27310692/224436986-58ac1bc9-166d-4d2d-b4cd-4c4b9c0933e3.png)

**Comment by shamblett** [comment]
Whatever you are doing you have closed the event bus, hence the bad state, this being picked up in auto reconnect, its not something it has done, its something it has found. Do you have an onDisconnected callback?

**Comment by jehhxuxu** [comment]
Yes, we have an onDisconnected callback, how can I simulate the autoReconnect?

**Comment by shamblett** [comment]
You need to disconnect the broker, so kill the network connection, or the broker, or switch from GSM to wireless etc.
