### ISSUE TITLE
mqtt-client::InvalidHeaderException: The supplied header is invalid. Header must be at least 2 bytes long.

### ISSUE THREAD

**Issue by tksundar** [shamblett/mqtt_client#438]
Apologies upfront if this is a trivial issue. I am new to dart and mqtt , so bear with me

Unhandled exception:
mqtt-client::InvalidHeaderException: The supplied header is invalid. Header must be at least 2 bytes long.
#0      MqttHeader.readFrom (package:mqtt5_client/src/messages/mqtt_header.dart:69:7)
#1      new MqttHeader.fromByteBuffer (package:mqtt5_client/src/messages/mqtt_header.dart:19:5)
#2      MqttByteBuffer.isMessageAvailable (package:mqtt5_client/src/utility/mqtt_byte_buffer.dart:66:29)
#3      MqttServerConnection._onData (package:mqtt5_client/src/connectionhandling/server/mqtt_server_connection.dart:60:26)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#8      _StreamController._add (dart:async/stream_controller.dart:648:7)
#9      _StreamController.add (dart:async/stream_controller.dart:596:5)
#10     _Socket._onData (dart:io-patch/socket_patch.dart:2324:41)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#15     _StreamController._add (dart:async/stream_controller.dart:648:7)
#16     _StreamController.add (dart:async/stream_controller.dart:596:5)
#17     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1849:33)
#18     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)

I get the above exception when trying to publish a simple message. Here is the code

```
void publish(String topic, String message) {
    final builder = MqttPayloadBuilder();
    builder.addString(message);
    _client.publishMessage(topic, MqttQos.atLeastOnce, builder.payload!);
    _client.published!.listen((event) {
      print(
          'Published topic: topic is ${event.variableHeader!.topicName}, with Qos ${event.header!.qos}');
    });
  }
```

I think the exception is raised from the  `_client.publishMessage(topic, MqttQos.atLeastOnce, builder. Payload!);`

The topic is "led/state" and message is "BLINK"

Please advise if this is an issue or i am doing something wrong. There is not much help in the public domain. I lookd at the source of mqtt_client_mqtt_header.dart on github, but couldn't figure out anything.

Thanks in advance

**Comment by shamblett** [comment]
OK, from the log you are actually using the mqtt5_client package, not the mqtt_client package -
```
MqttHeader.readFrom (package:mqtt5_client/src/messages/mqtt_header.dart:69:7)
```
notice the package says mqtt5. Your observation is a known fault on this package and is being investigated now.

There are two things you can do -

1. If you do not need any MQTT version 5 features(which I'm guessing you don't) use this package, i.e. replace mqtt5_client with mqtt_client in your pubspec. This should fix your fault.

2. If you really do want to use the mqtt5_client package wrap your code in an exception handler and discard this exception, everything else should work.

**Comment by tksundar** [comment]
Thanks. You are right. I don't need any specific mqtt5 features. mqtt_client library works!
