### ISSUE TITLE
Unable to connect to a AWS MQTT Broker using Flutter

### ISSUE THREAD

**Issue by volm92** [shamblett/mqtt_client#439]
Hi all!
I really need to connect to a broker located on AWS IOT, using the session token (or other data obtained from Amplify).
The session token is obtained via amplify which is currently properly integrated in flutter. I also have AWS access key and AWS secret key available. Among others also the identity ID.

However I can't find an example to connect to the broker having this data. Could you help me?
Documentation says:

"The client has been used successfully with the MQTT brokers from several of the major cloud providers IOT/MQTT platforms, including :-

Google IOT Core
Amazon AWS
Microsoft Azure
IBM"

but how to do this?

Thank you so much!

**Comment by shamblett** [comment]
Im not an AWS user so I dont kmow a lot about this however there is an AWS example in the examples directory, it may help. Other than that search the closed issues for AWS issues if it does not help.it may give you some users to contact.
