### ISSUE TITLE
SocketException: Write failed (OS Error: Broken pipe, errno = 32) if app stays in the background for long

### ISSUE THREAD

**Issue by raphasauer** [shamblett/mqtt_client#441]
Hello! I am having a exception with the mqtt_client library that usually happen when I lock my phone's screen and keep it running on the background. 
Here are the logs:

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 192.168.1.132, port = 36690
       at _Socket.add(dart:io)
       at MqttServerConnection.send(mqtt_client_mqtt_server_connection.dart:95)
       at MqttConnectionHandlerBase.sendMessage(mqtt_client_mqtt_connection_handler_base.dart:169)
       at MqttConnectionKeepAlive.pingRequired(mqtt_client_mqtt_connection_keep_alive.dart:89)
```

I believe that the connection is being killed by Android and then the MQTT Server is not being able to ping the broker on my machine via the keep alive function (I could be totally wrong, though). 

Is there a fix for this issue? Or it's just the expected behavior of the library in this situation?

**Comment by shamblett** [comment]
This is a socket exception raised by the flutter runtime, the client has no control over this other than to report it so I guess its normal behaviour.

 I know that some users disconnect the client when background is entered and reconnect when they come out of background.
