### ISSUE TITLE
Using Server and Browser Imports at the same time

### ISSUE THREAD

**Issue by DragonSlayer88** [shamblett/mqtt_client#442]
Hey so im trying to use the same code for a desktop app and also a web app. Id like to be able to import both the browser client and the server client at the same time and have code to just use the correct one depending on the platform. Right now I get a bunch of html errors when importing the browser client and using windows. I have to comment code in order switch debugging web and desktop. Can you please integrate it where i can use both. Thanks!

Here is an old post from 3 years ago that was not really solved. I would be nice to have it integrated into the package itself. 

https://github.com/shamblett/mqtt_client/issues/167

**Comment by shamblett** [comment]
Conditional imports are used to do what you wish, look at the mqtt_client_universal example in the examples directory, the package doesn't need to do anything here this is a standard way to do this in Dart. Are you saying you are doing this and its not working?

**Comment by rpungin** [comment]
Here is the simplified code that I used to solve it.

Create a class that is used on mobile in a separate file:

```Dart
import 'package:mqtt_client/mqtt_client.dart';
import 'package:mqtt_client/mqtt_server_client.dart';

class MobileMqttClient {
 MqttClient? _mqttClient;
  
  void connect() {
    #code to get the signed URL, clientId, port etc
    _mqttClient = createMqttClient(signedUrl, clientId, port);
    #code to set the callbacks and other parameters of _mqttClient
    _mqttClient?.connect();
  }

  @protected 
  MqttClient createMqttClient(String signedUrl, String clientId, int port) {
      final mqttServerClient = MqttServerClient.withPort(
        signedUrl, clientId, port,
        maxConnectionAttempts: 2);
    mqttServerClient.useWebSocket = true;
    mqttServerClient.secure = false;
    return mqttServerClient;
  }
  
  #The rest of the code to connect, subscribe, unsubscribe etc.
}
```

Create a subclass that is used on the web in a different file with different imports and override `createMqttClient` method that instantiates `MqttBrowserClient` instead of `MqttServerClient`:

```Dart
import 'package:mqtt_client/mqtt_browser_client.dart';
import 'package:mqtt_client/mqtt_client.dart';

class WebMqttClient extends MqttClient {

  @override
  MqttClient createMqttClient(
      String signedUrl, String clientId, int port) {
    final mqttBrowserClient = MqttBrowserClient.withPort(
        signedUrl, clientId, port,
        maxConnectionAttempts: 2);
    return mqttBrowserClient;
  }
}
```

Then instantiate the appropriate class based on `kIsWeb`:

```Dart
final myMqttClient = kIsWeb ? WebMqttClient() : MobileMqttClient()
```
