### ISSUE TITLE
Deal Loop when MqttPropertyContainer.readFrom

### ISSUE THREAD

**Issue by Jayleee** [shamblett/mqtt_client#443]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/20172799/216962537-c8c16d25-21fc-4480-820e-89058d318052.png">
dead loop when length < 0

**Comment by shamblett** [comment]
You've raised this on the wrong client, this should be on the mqtt5_client, not this one. 

Please re raise this on the mqtt5_client, add more details, like what file this is in and close this issue.
