### ISSUE TITLE
Username length/Password length exceeds the max recommended in the MQTT spec.

### ISSUE THREAD

**Issue by CordMemescape** [shamblett/mqtt_client#446]
When connecting to Moquitto, I get the following in the MqttClient logs:

```
1-2023-02-23 15:38:12.839959 -- Authenticating with username '{appwrite_mqtt_server_dev}' and password '**********************'
1-2023-02-23 15:38:12.840741 -- MqttClient::checkCredentials - Username length (24) exceeds the max recommended in the MQTT spec. 
1-2023-02-23 15:38:12.840775 -- MqttClient::checkCredentials - Password length (20) exceeds the max recommended in the MQTT spec. 
```

However, when I review the MQTT spec I can see that both the username and password are 655535 bytes.

```
clientid: 23 UTF-8 encoded bytes
user name max. 655535 bytes after encoding (UTF-8 encoded)
password: 0 to 65535 bytes of binary data
message limit size: 268435455 bytes
```

Is there a reason that the lengths of 24 and 20 characters are being flagged up in the logs as non-compliant? Is this just a debug/warning message that can be safely ignored?

**Comment by shamblett** [comment]
Yes, it can be ignored, the MQTT 3.1 spec says -
```
The first UTF-encoded string. The Client Identifier (Client ID) is between 1 and 23 characters long, and uniquely identifies the client to the server. It must be unique across all clients connecting to a single server, and is the key in handling Message IDs messages with QoS levels 1 and 2. If the Client ID contains more than 23 characters, the server responds to the CONNECT message with a CONNACK return code 2: Identifier Rejected.
```

However in the 3.1. spec this has been relaxed to -
```
The Server MUST allow ClientIds which are between 1 and 23 UTF-8 encoded bytes in length, and that contain only the characters
"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" [MQTT-3.1.3-5].
The Server MAY allow ClientId’s that contain more than 23 encoded bytes. The Server MAY allow ClientId’s that contain characters not included in the list given above.
```
Since most MQTT3 brokers now don't enforce the 23 character rule I think we can remove this warning entirely.
The update will be in the next release

**Comment by CordMemescape** [comment]
Thanks for the feedback Steve, much appreciated.

I'm using 3.1.1 so it's good to know that it can be safely ignored. I've adjusted my ClientId to be 23 characters or less anyway - just in case. But I haven't changed the Username and Password lengths. So long as MqttClient is happy to use these, I'm happy to ignore any warnings.

Perhaps, rather than removing the warnings entirely, they can be version dependent? That way, they could still be displayed for 3.1 connections...

**Comment by shamblett** [comment]
Yes, I know what you are saying but in my experience MQTT 3.1 brokers seem to accept client id's of greater than 23 characters also and nowadays most people use 3.1.1. I've updated the API doc comment for the max client id constant to explain this. Leaving it in just seems to cause confusion, you are not the first to raise this issue.

**Comment by CordMemescape** [comment]
Fair enough. To avoid confusion and additional unnecessary issues, It would seem sensible to remove the warnings.
:-)

Thanks for the feedback - I'm going to close this issue as there isn't anything further.
