### ISSUE TITLE
Can getSubscriptionsStatus() be used to check wildcard topics?

### ISSUE THREAD

**Issue by CordMemescape** [shamblett/mqtt_client#447]
When I connect to Mosquitto, to avoid resubscribing to a topic that I've already subscribed to, I use getSubscriptionsStatus() to check the topic subscription status. However, I get back a response of `MqttSubscriptionStatus.doesNotExist` despite 1) knowing that I've already subscribed to the topic from this client and 2) receiving all the messages that were published while the client was offline.

The only possibility that I can think of is that the topic contains a wildcard ('v1/u/#').

**Comment by CordMemescape** [comment]
I've just tested this with a non-wildcard topic ('v1/u/2') and `getSubscriptionStatus()` still returns `MqttSubscriptionStatus.doesNotExist` even though I've previously subscribed with this topic, have not unsubscribed from it and am getting all the pending messages that happened when the client was offline.

**Comment by shamblett** [comment]
You say 'while the client was offline..', how do you do this? Do you perform the online/offline manually or do you use autoreconnect?

**Comment by CordMemescape** [comment]
So currently, there are several different clients connecting to the broker; there are many IoT clients and one 'server' client.

To conserve battery life, the IoT clients connect several times daily, pick up any queued messages and send anything they have collected since their last call home. Then they power-off off their GSM modems. This all works perfectly.

The 'server' client should theoretically be online all the time but will manually disconnect from the broker when the server it is running on is restarted or the client needs to be updated. During this offline time, the IoT clients could send messages to the broker that the 'server' client will need to pick up and process.

Currently, the 'server' client manually connects to the broker and sends a subscribe() to the broker. It feels like this step is redundant because it's not a new topic that is being subscribed to and the client does receive any published messages from the IoT clients. So what I would like to do is only subscribe once - when the 'server' client starts up for the very first time, or when the topic subscribed to has somehow been 'forgotten' by the broker.

Does that make sense?

**Comment by CordMemescape** [comment]
Brilliant. So, how would I check whether or not I should subscribe() or resubscribe() ?

My original thought was as follows:

```
client.connect(username, password);

final String topic = 'v1/u/#';

if (client.getSubscriptionsStatus(topic) != MqttSubscriptionStatus.active) {
    client.subscribe(topic);
}
else {
    client.resubscribe()
}
```

However, client.getSubscriptionsStatus(topic) always seems to return MqttSubscriptionStatus.doesNotExist.

**Comment by shamblett** [comment]
Presumably this is after you have reconnected and not before?

**Comment by CordMemescape** [comment]
Yes, correct. After connecting and setting up the updates listener.

**Comment by shamblett** [comment]
OK I need to be clear about the sequence of events here, so 

1. Your app starts up, you connect, set up the listener and subscribe, I'm assuming the subscription check works at this point.
2. Sometime later you go off line, i.e the client disconnects.
3. Sometime later again you go back online, i.e you reconnect and receive any messages sent to your subscriptions when you were offline. I'm assuming this is the point where the subscription check fails.

Also I need to know whether you disconnect/reconnect manually or use the autoreconnect functionality.

**Comment by CordMemescape** [comment]
Here's the full connection sequence minus the comments and logging

```
  Future<void> run() async {
    ProcessSignal.sigterm.watch().listen((signal) {
      _client.disconnect();
      exit(2);
    });

    ProcessSignal.sigint.watch().listen((signal) {
      _client.disconnect();
      exit(2);
    });

    try {
      await _client!.connect(username, password);

      if (_client!.connectionStatus!.state != MqttConnectionState.connected) {
        _client!.disconnect();
        exit(1);
      }

      if (onReceivedMessage != null) {
        _client!.updates?.listen((event) => onReceivedMessage(event));
      }

      if (onPublishedMessage != null) {
        _client!.published?.listen((event) => onPublishedMessage(event));
      }

      final String topic = 'v1/u/#';

      if (mqttSubscriptionStatus != MqttSubscriptionStatus.active) {
        _client!.subscribe(topic: topic);
      }
      else {
        _client!.resubscribe();
      }
    } on NoConnectionException catch (e) {
      _client!.disconnect();
      rethrow;
    } on SocketException catch (e) {
      _client!.disconnect();
      rethrow;
    }
  }
```

If the app gets shutdown by a SIGTERM or a SIGINT signal, it gracefully disconnects from Mosquitto. As the app is running on the same server as the broker, I'm not using AutoReconnect as it's unlikely that comms between the two is going to be interrupted.

The daemon is set to restart the app if it is not terminated (i.e. if it crashes). If the app has been terminated, when it restarts it follows the above flow.

**Comment by shamblett** [comment]
OK, I see what you are doing.

For this use case there is no need to check, just subscribe every time you start/restart, if while you were offline the broker failed and restarted then you will renew your subscription, if while you were offline the broker stayed alive, which is more likely, it will remember your session and send you your offline messages, when you subscribe it will just return a sub ack mesage with success as it already has the subscription.

The reason getSubscriptionsStatus doesn't work for you is because subscriptions are tracked locally in clients, there is no support in the MQTT protocol to ask the broker what subscriptions it has for a specific client, so until you subscribe the subscription will not exist locally but will on the broker.

Hope that helps,

**Comment by CordMemescape** [comment]
Ah yes, indeed, thank you - that makes it a lot clearer! I'll remove the unnecessary checks and simply subscribe each time that the client connects to the broker. Thanks again for the clarity and help, Steve, much appreciated.

I'll close this issue now.
