### ISSUE TITLE
MQTT updates not working while changing Networks

### ISSUE THREAD

**Issue by nilsorathiya** [shamblett/mqtt_client#448]
I open the application with Wifi and Mobile both ON status and so MQTT connected successfully because it's initialized in the MAIN file, and I also got messages in MQTT.UPDATES.LISTEN callbacks.

My App is in foreground mode and now I am turning off the Wifi at that time, Auto Reconnected called and also resubscribed the topic but I am not getting any response in MQTT.UPDATES.LISTEN callbacks.

**Comment by shamblett** [comment]
OK I'll need a log from the autoreconnect point onwards.

When you say you resubscribed do you have an onSubscribe callback to check if the subscription worked?

**Comment by nilsorathiya** [comment]
Thanks, @shamblett for your quick response.
Before subscribing to a topic, I am checking existing subscriptions and if a new topic does not exist then only I am subscribing.

`connectMQTT(String from) async {
    try {
      debugPrint('NEW 🦟 MQTT2 🦟 CONNECT FROM $from');
      await newMQTTclient!.connect();

      if (newMQTTclient!.connectionStatus!.state ==
          MqttConnectionState.connected) {
        debugPrint('NEW 🦟 MQTT2 🦟 CONNECTED');
      } else {
        /// Use status here rather than state if you also want the broker return code.
        debugPrint(
            'NEW 🦟 MQTT2 🦟 DISCONNECTING ${newMQTTclient!.connectionStatus}');
        newMQTTclient!.disconnect();
        exit(-1);
      }

      debugPrint('NEW 🦟 MQTT2-CHECK:: ${newMQTTclient == null}');
      debugPrint(
          'NEW 🦟 MQTT2-UPDATE CHECK:: ${newMQTTclient!.updates == null}');

      newMQTTclient!.published!.listen((MqttPublishMessage message) {
        var payload =
            MqttPublishPayload.bytesToStringAsString(message.payload.message);
        debugPrint('NEW 🦟 MQTT2 PUBLISHED:: ${payload}');
      });

      newMQTTclient!.updates!.listen(
        (List<MqttReceivedMessage<MqttMessage?>>? c) {
          debugPrint('NEW 🦟 MQTT2 ON UPDATES - {$c}');
          for (int i = 0; i < c!.length; i++) {
            final MqttPublishMessage message =
                c[i].payload as MqttPublishMessage;
            var payload = MqttPublishPayload.bytesToStringAsString(
                message.payload.message);
            debugPrint(
                "NEW 🦟 MQTT2 🦟 RESPONSE NEW  ${DateTime.now()} $payload");
            DeviceResponseUtils()
                .handleResponse(str: payload, ipAddress: "", isMqtt: true);
          }
        },
        cancelOnError: true,
        onError: (Object error) {
          debugPrint('NEW 🦟 MQTT2 ON ERROR - UPDATES');
        },
        onDone: () {
          debugPrint('NEW 🦟 MQTT2 ON DONE - UPDATES');
        },
      );
    
    } on NoConnectionException catch (e) {
      debugPrint('${DateTime.now()} NEW 🦟 MQTT2 🦟 :client exception - $e');
      newMQTTclient!.disconnect();
    } on SocketException catch (e) {
      debugPrint('${DateTime.now()} NEW 🦟 MQTT2 🦟 :socket exception - $e');
      newMQTTclient!.disconnect();
    }

    subscribeDevices();
  }`

`void subscribeDevices({String? from}) {
    await Device().fetchAllNewDevices().then((listDevice) {
      for (var device in listDevice) {
        subscribeTopics(device, from: from);
      }
    });
  }`
  
  `Future<void> subscribeTopics(DeviceResponse? deviceResponse,
      {String? from}) async {
    if (newMQTTclient != null &&
        newMQTTclient!.connectionStatus!.state ==
            MqttConnectionState.connected) {
      String topicToSubscribe =
          generateSlaveFromDeviceId(deviceId: deviceResponse!.deviceId!) +
              newMqttSubscribeTopic;
      debugPrint("NEW 🦟 MQTT2 🦟 TOPIC TO SUBSCRIBE --> $topicToSubscribe");

      debugPrint(
          "NEW 🦟 MQTT2 🦟 SUBSCRIPTIONS --> ${newMQTTclient!.subscriptionsManager!.subscriptions}");

      if (newMQTTclient!.subscriptionsManager != null &&
          newMQTTclient!.subscriptionsManager!.subscriptions
              .containsKey(topicToSubscribe)) {
        debugPrint(
            "NEW 🦟 MQTT2 🦟 SUBSCRIBE ALREADY ACTIVE--> $topicToSubscribe");
        sendDS(deviceResponse);
      } else {
        debugPrint(
            "NEW 🦟 MQTT2 🦟 CURRENT SUBSCRIPTIONS--> ${newMQTTclient!.subscriptionsManager!.subscriptions}}");

        newMQTTclient!.subscribe(topicToSubscribe, MqttQos.atMostOnce);
      }
    }
  }`

**Comment by shamblett** [comment]
OK but I still need a log as I said above, I need to see whats happening at run time.

**Comment by nilsorathiya** [comment]
Thanks for your response.

Shall I know how can I track the connection listener?

I would like to do some function when connection status becoming connecting
or disconnecting or onFaulted.

**Comment by shamblett** [comment]
I'm not unerstanding you, why can't you use the onConnected and onDisconnected callbacks? Note the API comment from  onDisconnected -
```
 /// Client disconnect callback, called on unsolicited disconnect.
  /// This will not be called even if set if [autoReconnect} is set,instead
  /// [AutoReconnectCallback] will be called.
```

**Comment by nilsorathiya** [comment]
I would like to show message to user that MQTT is connecting when MQTT
trying to reconnect and I don't know how to do that.

**Comment by shamblett** [comment]
Please have a look at the API -
```
/// Client disconnect callback, called on unsolicited disconnect.
  /// This will not be called even if set if [autoReconnect} is set,instead
  /// [AutoReconnectCallback] will be called.
  DisconnectCallback? onDisconnected;

  /// Client connect callback, called on successful connect
  ConnectCallback? onConnected;

  /// Auto reconnect callback, if auto reconnect is selected this callback will
  /// be called before auto reconnect processing is invoked to allow the user to
  /// perform any pre auto reconnect actions.
  AutoReconnectCallback? onAutoReconnect;

  /// Auto reconnected callback, if auto reconnect is selected this callback will
  /// be called after auto reconnect processing is completed to allow the user to
  /// perform any post auto reconnect actions.
  AutoReconnectCompleteCallback? onAutoReconnected;
```

If you hook these up(assuming you are using autoreconnect) then when onAutoReconnect is called then you can tell your user that they are disconnected until onAutoReconnected is called, similarly if you are not using autoreconnect for onDisconnected/onConnected.

**Comment by nilsorathiya** [comment]
Thanks for your response.

Let suppose, My MQTT client connected and suddenly internet break down, at
that time I need to show users that internet is break down and MQTT will be
up when internet is up and running.

Can you please demonstrate which callback can tell me internet break down
and mqtt is not connected for while?
