### ISSUE TITLE
how to connect mqtt secure (mqtts or wss) on brower flutter . help me

### ISSUE THREAD

**Issue by minhtritt01** [shamblett/mqtt_client#457]

**Comment by minhtritt01** [comment]
final client = MqttBrowserClient.withPort('mqtt.onskycloud.com', '', 1883);
// Certificate data
String cert = '''-----BEGIN CERTIFICATE-----
<certificate data here>
-----END CERTIFICATE-----''';
//Set up a secure WebSocket
IOWebSocketChannel channel = IOWebSocketChannel.connect(
  'wss://mqtt.onskycloud.com:8883',
  headers: {
    'Origin': 'https://mqtt.onskycloud.com',
  },
);

**Comment by shamblett** [comment]
This is incorrect, secure websockets are accessed through  'wss' not by setting secure parameters for normal secure TCP sockets. You can only use websockets in browser applications so your broker must supply a websocket endpoint or this wont work.

Please refer to the examples in the repo, specifically mqtt_browser_client.dart and read the API documents.

**Comment by shamblett** [comment]
Yes, you can only use ws or wss from browser based websockets, this is not a limitation of the package its enforced by Dart, see [here](https://api.dart.dev/stable/2.19.5/dart-html/WebSocket-class.html).

As I've already said you can't use normal or secure TCP sockets in your web browser, you have to get your broker to open a websocket endpoint and connect on that.

**Comment by izaiasemjr** [comment]
Great answer @shamblett, just to complement @minhtritt01 , I put this configs : 
```
listener 1883
listener 8080
protocol websockets
allow_anonymous true 
```
inside the file /etc/mosquitto/mosquitto.conf  and that's working for me at local mosquitto installed.
