### ISSUE TITLE
How to send a message contains utf8 characters?

### ISSUE THREAD

**Issue by zqiangliu** [shamblett/mqtt_client#46]
How to send a message contains utf8 characters?

**Comment by shamblett** [comment]
Hi,

There's no direct support for this in the client, the basic underlying data structure of payloads is a uint8 buffer from the [typed_data](https://pub.dartlang.org/packages/typed_data) package, the MqttClientPayloadBuilder class provides some utility functions to help build the payload but doesn't supply UTF8 support. You could transform your UTF8 data using the [UTF](https://pub.dartlang.org/documentation/utf/latest/utf/utf-library.html) package first then use payload builder to interface to the client.

**Comment by zqiangliu** [comment]
It's really helpful
my code works good with utf8 message
encode:
---------
MqttClientPayloadBuilder builder = new MqttClientPayloadBuilder();
var _buf = typed.Uint8Buffer();
 _buf.addAll(encodeUtf8(message));
 builder.addBuffer(_buf);

decode:
---------
final MqttPublishMessage recMess = c[0].payload as MqttPublishMessage;
String msg = decodeUtf8(recMess.payload.message);

**Comment by shamblett** [comment]
OK, closing this issue.
