### ISSUE TITLE
MQTT should AUTO CONNECT when application has internet availability

### ISSUE THREAD

**Issue by nilsorathiya** [shamblett/mqtt_client#467]
Hello @shamblett 
This package is too good and very good in terms of options are available. but from last 3 to 4 days, I am facing 1 difficulty.

Let suppose, Mobile device do not have an internet connection and I am opening the app and in the main file, also doing MQTT initialisation but in that case, I am getting obvious SocketException(because Internet not available) but I turning mobile wifi ON from status bar (without closing the app) and at that time, MQTT not trying for auto reconnect because MQTT not connected previously.

`MqttConnectionKeepAlive::pingRequired`
`MqttConnectionKeepAlive::pingRequired - NOT sending ping - not connected`
`MqttConnectionKeepAlive::pingRequired - restarting ping timer`

Can you please help me on this?

**Comment by shamblett** [comment]
Hi @nilsorathiya 

Unfortunately initialisation should only be attempted when it has a chance of working, as you have seen autoreconnect does what it says on the tin, you must have been connected to attempt to reconnects. You need to wait for a signal from your platform to tell your app the network is up before attempting initialisation, there are many ways of doing this for instance coming out of background on android, I don't use flutter so I can't help further here but there is plenty about this on both android and IOS in the closed issues.

If you want to initialise before you have a network connection you must do this yourself, i.e,. set up an initialisation loop that just retries and completes when you get an onConnection callback etc. There are lots of ways to do this.
