### ISSUE TITLE
Disconnect exactly every minute and also When publishing message

### ISSUE THREAD

**Issue by tje3d** [shamblett/mqtt_client#47]
Here is my connection code in flutter (mqtt_client: ^3.3.4):

**Code:**
```dart
...
_client = MqttClient(
  "wss://${mqttServer}/mqtt",
  clientId,
);
_client.port = 443;
_client.useWebSocket = true;
...
_client.connectionMessage = MqttConnectMessage()
  .withWillQos(MqttQos.exactlyOnce)
  .authenticateAs(id.toString(), token)
  .withClientIdentifier(clientId);
...
await _client.connect();
```

The problem is, Sometimes without any reason, i get disconnected from server also when trying to publish a message.

```dart
MqttClientPayloadBuilder builder = MqttClientPayloadBuilder();
builder.addString(
  json.encode(
    {
      "type": "msgText",
      "data": msg.data,
      "identifier": identifier,
    },
  ),
);
_client.publishMessage(topic, MqttQos.exactlyOnce, builder.payload)
```

I'm sure this is a library issue cause i have no problem with paho.mqtt.

**Edit:**

It's disconnect exactly every minute.

```text
I/flutter (23865): 2018-11-19 11:39:30.386998 -- MqttConnection::_onDone - calling disconnected callback
```

**Comment by shamblett** [comment]
Hmm, this sounds like the default keepalive period(60s), try setting this to a lower value, i.e.

 client.keepAlivePeriod = 20;

**Comment by tje3d** [comment]
@shamblett yes that's it. But it seems the behavior is wrong.

**Comment by shamblett** [comment]
Ok, in what sense, do you mean the behaviour is wrong? 60 seconds seems a fairly common value, some of this depends on your broker of course. A value of 0 disables keep alive, is this what you would prefer as a default?

**Comment by shamblett** [comment]
OK, no probs, closing
