### ISSUE TITLE
Does .addInt() of MqttClientPayloadBuilder conform to MQTT V3.1.1?

### ISSUE THREAD

**Issue by SeunghwaSong** [shamblett/mqtt_client#477]
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf
I came across this syntax while looking at MQTT V3.1.1.

##### 1.5.2 Integer data values
Integer data values are 16 bits in big-endian order: the high order byte precedes the lower order byte
This means that a 16-bit word is presented on the network as Most Significant Byte (MSB), followed by Least Significant Byte (LSB).

however
final MqttClientPayloadBuilder builder = MqttClientPayloadBuilder();
     builder. addInt(333);

If you do this, it seems to be 64-bit instead of 16-bit, and there doesn't seem to be a Big Endian setting either.
Is this something that should be fixed?

**Comment by shamblett** [comment]
The payload builder is really for building the payload in publish messages, from the MQTT 3.1.1 spec, 
```
3.3.3 Payload
The Payload contains the Application Message that is being published. The content and format of the data is application specific. The length of the payload can be calculated by subtracting the length of the variable header from the Remaining Length field that is in the Fixed Header. It is valid for a PUBLISH Packet to contain a zero length payload.
```
I believe its always been the case where the user is free to use any binary representation they want in the payload so the payload does not have to conform to other parts of the spec that use integers in packet headers etc. The payload builder also allows for the addition of half words and words if needed.
