### ISSUE TITLE
How can I pass a SecurityContext to a MqttBrowserClient client?

### ISSUE THREAD

**Issue by alecstwch** [shamblett/mqtt_client#478]
I use mosquitto configured with client certificates and I need to pass the certificate to the client in order to connect correctly.
If I use MqttServerClient + SecurityContext  then everything works well.
When I switch to MqttBrowserClient then I receive an error similar to this one:
...
Exception: Unsupported operation: default SecurityContext getter
...
MQTTClient::ERROR Mosquitto client connection failed - disconnecting, status is Connection status is disconnected with return code of noneSpecified and a disconnection origin of solicited
...

Thank you.

**Comment by shamblett** [comment]
In short you can't, the security context can only be used on the server side, not in the browser. In the browser you have to use websockets with a scheme of ws or wss.

Mosquito does support this on port 8080 maybe, see the client API focs and the mosquito docs.

**Comment by alecstwch** [comment]
Thank you. I will look into it.

**Comment by rpungin** [comment]
You need to use `MqttBrowserClient` on the web and `MqttServerClient` on mobile. I did it like [this](https://github.com/shamblett/mqtt_client/issues/442#issuecomment-2342619674).
