### ISSUE TITLE
How to mute all logs?

### ISSUE THREAD

**Issue by lucasjinreal** [shamblett/mqtt_client#481]
Hello, anyway to mute all logs?

**Comment by shamblett** [comment]
If your talking about the client itself then use the logging API -
```
/// Set logging on if needed, defaults to off
  client.logging(on: true);
```
This defaults to off so unless you have turned it on it should be off anyway.

If your talking about logging in general then you need to consult the docs about your runtime(flutter I guess) and your platform(android, ios etc.) to see how to do this.

**Comment by lucasjinreal** [comment]
@shamblett Yes, using flutter, client, is it mute default? I saw many Matt logs, don't know how to disable it.

It's helpful but  have covers all my logs hard to diagnose my own problem in app.

**Comment by shamblett** [comment]
Log output from the client looks like this as an example -
```
1-2023-08-27 08:59:29.028877 -- MqttClient::connect - Connection timeout period is 2000 milliseconds
```
It starts with the leading timestamp and somewhere in the string it will say 'Mqtt' or 'client' although this is not guaranteed. If you are not seeing this then the logging is not from this client.

See my first comment above on how to turn on/off logging for the client.
