### ISSUE TITLE
Message payload is cut off

### ISSUE THREAD

**Issue by ggirotto** [shamblett/mqtt_client#482]
I'm noticing some issue with the message formats received by MQTT. We use MQTT to receive JSON payloads from our server, and oftenly  I'm noticing that the received payload in the client differs from the one sent by the server. As an example, the server sends:

`{"status":"Open","closedReason":null,"id":"123"}`

And the client receives

`{"status":"Open","closedReason":null,"id":"}`

I can't figure it out what's happening, am I missing some configuration? We're currently using protocol v3.1.1, and here's the code we are using to decode the received JSON

```dart
sub = _client.updates?.listen((event) {
        final message = event[0].payload as MqttPublishMessage;
        final serialized = _payloadWrapper.bytesToStringAsString(message.payload.message);
        controller.add(jsonDecode(serialized) as Map<String, dynamic>);
      });
```

**Comment by shamblett** [comment]
What does 'serialized' look like? If that's OK, then look at 'message.payload.message'.

**Comment by shamblett** [comment]
It looks a little odd that the Json string has a space at the end before the closing } but not at the start, you would expect this -
'''
{"status":"Open","closedReason":null,"id":"LZ7VB90SH4QHW"}
```
not this -
```
{"status":"Open","closedReason":null,"id":"LZ7VB90SH4QHW" }
```
however it should still not cause an error with lost characters.

I need more info on whats going on here,there are several ways to do this, serialize the received publish message, i.e take your publish message and call 'writeTo' on it with a supplied ByteBuffer and dump the byte buffer, something like -
```
final bBuff = typed.Uint8Buffer();
final byteBuff = MqttByteBuffer(bBuff);
message.writeTo(byteBuff);
print(bBuff.toList());
```
and post the output, or take a local copy of the package and annotate the following method 'MqttPublishPayload.readFrom' to print the length variables -
```
void readFrom(MqttByteBuffer payloadStream) {
    // The payload of the publish message is not a string, just
    // a binary chunk of bytes.
    // The length of the bytes is the length specified in the header,
    // minus any bytes spent in the variable header.
   print( header!.messageSize);
   print( variableHeader!.length);
    final messageBytes = header!.messageSize - variableHeader!.length;
    message = payloadStream.read(messageBytes);
```

Yet another way to do this is to wireshark the incoming packets from the network and post these.
