### ISSUE TITLE
mqtt connect error HandshakeException: Handshake error in client (OS Error:         	WRONG_VERSION_NUMBER(tls_record.cc:231))

### ISSUE THREAD

**Issue by Davion705027** [shamblett/mqtt_client#489]
I can connect using the same configuration in MQTTX, but an error is reported here. Why is this?

**Comment by shamblett** [comment]
No idea, what is it you are doing? You clearly have a TLS error, remember this client sits atop the Dart runtime, this handles TLS not the client.
