### ISSUE TITLE
Is it possible to have multiple callback functions

### ISSUE THREAD

**Issue by ramanraja** [shamblett/mqtt_client#498]
This is a question about an enhancement:  I receive fairly large MQTT payloads, and I have to process them before deciding if I should handle it. Most of them are status messages, which are for information purposes only. On the other hand, if the payload contains a command, my code has to act upon it.  I cannot totally ignore the status packets also, since the user may want to see them occasionally.  I have to display the status packets only when the user's dashboard UI is active.  There are about 50 status topics and only a single command topic.
 
It would be very helpful if I can register different callback functions for command and status topics. Is this possible in the current implementation?

**Comment by shamblett** [comment]
No, callbacks are at the functional level e.g. connect/disconnect etc. not at the topic level. You could look at topic filtering, from the MqttTopicFilter API -
```
/// This class allows specific topics to be listened for. It essentially
/// acts as a bandpass filter for the topics you are interested in if
/// you subscribe to more than one topic or use wildcard topics.
/// Simply construct it, and listen to its message stream rather than
/// that of the client. Note this class will only filter valid receive topics
/// so if you filter on wildcard topics for instance, which you should only
/// subscribe to,  it  will always generate a no match.
```

You should be able to listen for your command topic and hook it straight into your own processing.

**Comment by ramanraja** [comment]
Thanks for the clarification. My use case deals with messages like  `user_id/event_type/event_id`.  I wanted to have a different callback function for each `event_type`.  I have to filter on  wild cards like `+/event_type_A/+` which, it seems,  is not currently supported. Thank you.
