### ISSUE TITLE
recMess.payload.message Failed to parse Chinese

### ISSUE THREAD

**Issue by peng093** [shamblett/mqtt_client#499]
```
_client.updates!.listen((List<MqttReceivedMessage<MqttMessage>> c) {
        final recMess = c![0].payload as MqttPublishMessage;
        final pt = MqttPublishPayload.bytesToStringAsString(recMess.payload.message);
        print('topic: ${c[0].topic}, Message: $pt');
      });
```
If the returned characters contain both Chinese and English, the Chinese part cannot be displayed normally

**Comment by shamblett** [comment]
Ok Ill have look, do have an example payload I can use?

**Comment by boborua** [comment]
> ```
> _client.updates!.listen((List<MqttReceivedMessage<MqttMessage>> c) {
>         final recMess = c![0].payload as MqttPublishMessage;
>         final pt = MqttPublishPayload.bytesToStringAsString(recMess.payload.message);
>         print('topic: ${c[0].topic}, Message: $pt');
>       });
> ```
> 
> If the returned characters contain both Chinese and English, the Chinese part cannot be displayed normally

codec should be specified when converting bytes message to string, try this:
```dart
    final recMess = c![0].payload as MqttPublishMessage;
    final pt = utf8.decode(recMess.payload.message);
```

**Comment by shamblett** [comment]
Yes this is correct, only you know what your payload contains not the client, if it contains UTF8 characters you must decode it as such,.The bytesToString method you are using is a helper method for the toString method of MqttPublishPayload not a general purpose payload decoder.
