### ISSUE TITLE
Records file import warrning 

### ISSUE THREAD

**Issue by guyluz11** [shamblett/mqtt_client#500]
```dart
Import of a library in the 'lib/src' directory of another package.
Try importing a public library that exports this library, or removing the import.dart[implementation_imports](https://dart.dev/lints/implementation_imports)
library package:mqtt_client/src/observable/src/records.dart
package:mqtt_client/src/observable/src/records.dart
```

Can we export `records.dart`?

**Comment by shamblett** [comment]
OK, I've updated linter to 3.0.0 and its now showing lots of warnings for this package which I'll fix but not this one, how are you seeing this? Note I'm also on Dart 3.2.3

**Comment by shamblett** [comment]
Analysis errors now fixed, as far as I can see we are exporting records.dart, in observable.dart -
```
export 'src/records.dart' show ChangeRecord;
```
I'm still seeing no error for this.

**Comment by guyluz11** [comment]
Closing for now, will open in case I get it again
