### ISSUE TITLE
SSL/TLS question

### ISSUE THREAD

**Issue by antonhagg** [shamblett/mqtt_client#501]
What exactly does this do? I have managed to connect to [Beebotte ](https://beebotte.com/docs/mqtt)MQTT broker  with only specifying `Client.secure = true`. In what cases do I need the code below?

`  /// Security context
  final currDir = '${path.current}${path.separator}example${path.separator}';
  final context = SecurityContext.defaultContext;
  // Note if you get a 'TlsException: Failure trusting builtin roots (OS Error:
  // 	CERT_ALREADY_IN_HASH_TABLE' error here comment out the following 2 lines
  context
      .setTrustedCertificates(currDir + path.join('pem', 'mosquitto.org.crt'));`

and

`  /// Set an on bad certificate callback, note that the parameter is needed.
  client.onBadCertificate = (Object a) => true;`

**Comment by shamblett** [comment]
Its only if you need to set up your own cert path say or use any other features in the security context, it just gives you more flexibilty in this respect. 

Usually you don't need to.do anything with this as you have discovered. Please consult the Dart API docs on this for further details.
