### ISSUE TITLE
How to enable auto reconnect, but do not reconnect when app comes back from home screen? (resume)

### ISSUE THREAD

**Issue by luohao123** [shamblett/mqtt_client#504]
I don't know if you have tested client with Flutter App, I integrated into my APP, with reconnect enabled, it will reconnect when app comes back from background, this is because my APP did not exit when homescreen button pressed, avoid reload pages, just like iOS on Android, but in this situation, it will reconnect when goes back to app from home.

I don't want it reconnect imediately after I comes back (I can detect this event)

Does there any interface control it? ( some sort of delay or something but not effect the autoreconnect feature when normal use)

**Comment by shamblett** [comment]
Have a look at autoReconnectCallback -
```
/// Auto reconnect callback, if auto reconnect is selected this callback will
  /// be called before auto reconnect processing is invoked to allow the user to
  /// perform any pre auto reconnect actions.
  AutoReconnectCallback? onAutoReconnect;
```

If you hook into this you introduce a delay if you wish or if this is a normal auto reconnect from a lost connection just let it run.

**Comment by luohao123** [comment]
@shamblett Thanks,

if I set a deplay, is that equal to I enlargered the auto reconnect time interval?

**Comment by shamblett** [comment]
You said above 'I don't want it reconnect imediately after I comes back (I can detect this event)', so you need to detect this event in the callback and delay for whatever time you want. This will delay the onset of the auto reconnect sequence, once it starts it will behave as normal, i.e it will retry until it connects with whatever other parameters you may have set, refer to the API docs here.
