### ISSUE TITLE
When using an macOS, I can only receive messages but cannot send them. What configuration is required?

### ISSUE THREAD

**Issue by orange7yz** [shamblett/mqtt_client#505]
When using an macOS, I can only receive messages but cannot send them. What configuration is required?

**Comment by shamblett** [comment]
Nothing as far as the client is concerned, the client doesn't know which OS its running on, it sits atop the Dart/flutter runtime on the host so there is no platform specific client set up to do. So your problem is probably a macOS related configuration setting of some kind.
