### ISSUE TITLE
Hot reload causes infinite MQTT connect loop 

### ISSUE THREAD

**Issue by uberchilly** [shamblett/mqtt_client#518]
This happens at least on Chrome, maybe on mobile as well. It happened on all the latest version of the library and flutter/dart sdk. Any known fix? 

![image](https://github.com/shamblett/mqtt_client/assets/5727941/1db0de74-a879-4e07-9bbd-7d18cceecba8)

**Comment by shamblett** [comment]
News to me, presumably all is ok before hot reload.

**Comment by uberchilly** [comment]
This happens when you try to reuse the same id for the client in combination with hot reload because 2 clients are fighting for the connection at the same time. When you generate new id every time it will work properly even in hot reload screnario.

**Comment by raviatri** [comment]
@uberchilly so what you suggest for a device making connection with different client id is the right approach?
