### ISSUE TITLE
Connection Lost When App Killed

### ISSUE THREAD

**Issue by JavedAtRapidTack** [shamblett/mqtt_client#519]
Hello everyone...
am using mqtt  and flutter local notifications together in my taxi booking app.  everything goes well when app is in active state.
but when user once killed the app Mqtt connection lost due to which i am unable to show local notifications .
is it possible to keep connection alive even when app is killed .

**Comment by pratamarama** [comment]
hello @shamblett, just wanna know, if broker send message to the client/app when app is killed, will the message be received as soon as it's connected again?
