### ISSUE TITLE
onConnect callback required for renewing subscriptions

### ISSUE THREAD

**Issue by elementzonline** [shamblett/mqtt_client#52]
onConnect callback feature is required when the client gets disconnected when there is network loss. This callback can be used to renew subscriptions.

**Comment by shamblett** [comment]
Yes OK I'll update the client to add one.

As a thought, the client maintains a list of subscriptions, would an option to automatically re-subscribe to these on re-connection be useful?

**Comment by drost** [comment]
On that note, how is reconnection supposed to work? If there is an error during the initial connect, I can't see that a reconnection attempt will be made.

**Comment by shamblett** [comment]
The client automatically tries to reconnect if the initial connection attempt fails, at the moment this is hard wired to 3 attempts in total, you can see this if you edit the mqtt_client.dart in the examples folder to connect to a non-existent broker and turn logging on

**Comment by shamblett** [comment]
OnConnect callback added, client re-published at 5.0.0.
