### ISSUE TITLE
MqttBrowserClient with self-signed certificate

### ISSUE THREAD

**Issue by javezbak** [shamblett/mqtt_client#525]
**Goal**

Send messages via MQTT and web socket connections encrypted with TLS/SSL using a self-signed cert (I already know an official cert would be better).

**Server-side**

I have a docker container set up to host a Mosquitto broker for both MQTT and Web Socket connections.

**Client-side**

I have a Dart app that publishes messages via MQTT using [MqttServerClient][1]. It doesn't like that I'm using a self-signed cert, but it works fine after setting the 'onBadCertificate' field to return true, circumventing the issue.

I have a Flutter web app which *tries* to send messages over wss using [MqttBrowserClient][2]. 

**Issue**

The Flutter web app is unsuccessful when it tries to connect to the broker via wss. I can use MQTTX or MQTT Explorer to successfully connect to my broker via wss, so I know it can work in Flutter. The web app can connect successfully if I try connecting via ws, and redeploy the broker to not use encryption. But as of now, the encrypted broker says nothing when I try connecting from my web app. 

This is the code I'm running:

```flutter
const scheme = 'wss';
final server = '$scheme://$host';
final randomClientId = '${defaultMqttClientId}_${Random().nextInt(1000000)}';

final client = MqttBrowserClient.withPort(server, randomClientId, port)
..setProtocolV311()
..keepAlivePeriod = 60
..logging(on: true);

final connMessage = MqttConnectMessage().startClean();
client.connectionMessage = connMessage;
client.connect()
```

This is my output (I've cut out the reconnect attempts for brevity):

```
MqttClient::connect - Connection timeout period is 5000 milliseconds
MqttClient::connect - keep alive is enabled with a value of 60 seconds
MqttConnectionKeepAlive:: Initialised with a keep alive value of 60 seconds
MqttConnectionKeepAlive:: Disconnect on no ping response is disabled
MqttConnectionHandlerBase::connect - server wss://127.0.0.1, port 9001
SynchronousMqttBrowserConnectionHandler::internalConnect entered
SynchronousMqttBrowserConnectionHandler::internalConnect - initiating connection try 0, auto reconnect in progress false
SynchronousMqttBrowserConnectionHandler::internalConnect - calling connect
MqttBrowserWsConnection::connect - entered
MqttBrowserWsConnection::connect -  WS URL is wss://127.0.0.1:9001
MqttBrowserWsConnection::connect - connection is waiting
MqttBrowserWsConnection::connect - websocket has erred
SynchronousMqttBrowserConnectionHandler::internalConnect - connection complete
SynchronousMqttBrowserConnectionHandler::internalConnect sending connect message
MqttConnectionHandlerBase::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
Connect Variable Header: ProtocolName=MQTT, ProtocolVersion=4, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=false, WillQos=MqttQos.atMostOnce, WillRetain=false, PasswordFlag=false, UserNameFlag=false, KeepAlive=60
MqttConnectPayload - client identifier is : swcfl_343410


SynchronousMqttBrowserConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
SynchronousMqttBrowserConnectionHandler::internalConnect - post sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
ynchronousMqttBrowserConnectionHandler::internalConnect failed
Network Loggy - MqttService - Connect exception: mqtt-client::NoConnectionException: The maximum allowed connection attempts ({3}) were exceeded. The broker is not responding to the connection request message (Missing Connection Acknowledgement?
Network Loggy - MqttService - disconnected
```

This is the content of my mosquitto.conf:

```
listener 8883
protocol mqtt
certfile /certs/broker/broker.crt
keyfile /certs/broker/broker.key
allow_anonymous true

listener 9001
protocol websockets
certfile /certs/broker/broker.crt
keyfile /certs/broker/broker.key
allow_anonymous true
```

I did find this [comment](https://github.com/shamblett/mqtt_client/issues/487#issuecomment-1793604799) from a similar issue. Is this true? Am I just out of luck with regards to getting this to work with a self-signed cert? Any help would be greatly appreciated. Thanks.

  [1]: https://pub.dev/documentation/mqtt_client/latest/mqtt_server_client/MqttServerClient-class.html
  [2]: https://pub.dev/documentation/mqtt_client/latest/mqtt_browser_client/MqttBrowserClient-class.html

**Comment by shamblett** [comment]
Yes I believe the comment is correct, server side secure sockets behave differently to web side websockets. There is no SecurityContext available to the web client, the client simply sanitises the url passed to it and instantiates a [WebSocket](https://api.dart.dev/stable/3.3.3/dart-html/WebSocket-class.html) , it has no control over what happens next, this is purely a function of the Dart runtime.

I'm not saying its impossible to do what you are trying to do just that as far as I know there is no solution to this for self signed certs. The comment does say -
```
... because the [self-signed certificates are not trusted by browsers](https://stackoverflow.com/questions/54285172/how-to-solve-flutter-certificate-verify-failed-error-while-performing-a-post-req)  (unless you manually add your cert, but that's tough in prod)
```

Maybe you could try doing this, either way the client can't help you with any of this.
