### ISSUE TITLE
How to add proxy to see content in proxy tools like Charles/Proxyman?

### ISSUE THREAD

**Issue by opsenes** [shamblett/mqtt_client#526]
Is there any option to provide a proxy for MqttServerClient?

In HttpClient we provide proxy as HttpOverrides.global.

```
  @override
  HttpClient createHttpClient(SecurityContext? context) {
    return super.createHttpClient(context)
      ..findProxy = (uri) {
        return "PROXY $customProxy;";
      }
      ..badCertificateCallback = (cert, host, port) => true;
  }
  ```

**Comment by shamblett** [comment]
No not as such. MQTT is not a HTTP based protocol, the client opens a socket and transmits/receives binary data to/from the broker as per the MQTT protocol spec. 

There are tools such as [this](https://blog.nviso.eu/2020/07/06/introducing-ioxy-an-open-source-mqtt-intercepting-proxy/) which are intercepting proxies if tis is what you mean.
