### ISSUE TITLE
retain:true publishing issue (using IoT Core)

### ISSUE THREAD

**Issue by SRoseZano** [shamblett/mqtt_client#527]
When running:
   
  ```
  final MqttPayloadBuilder builder1 = MqttPayloadBuilder();
    builder1.addString('test');
    var test = client!.publishMessage(topic, MqttQos.atLeastOnce, builder1.payload!,retain:false);
```
    
I can see the message within the IoT core test client and I actively receive it  with my listener in my flutter code.
   
However changing retain to true

  `   var test = client!.publishMessage(topic, MqttQos.atLeastOnce, builder1.payload!,retain:true);`
     
The message is no longer published, I am unable to see the message within my IoT test client nor through my active flutter listener.

I know that IoT core supports retained messages and that they are accessible within my flutter subscription as I have manually sent a retained message using the IoT test client that I am able to then see when I subscribe to the topic in flutter. It seems to be an issue with the publish method? Would really appreciate some clarification

**Comment by shamblett** [comment]
Interesting, setting the retained flag shouldn't stop publishing of course. Do you get a message identifier returned in your 'test' variable in both  cases i.e. with and without retained.

Also is it possible to supply a log, i.e. turn on logging on the client and try your test, I only need the retained true output.

**Comment by SRoseZano** [comment]
Looking at the logs it would appear that you have to specifically allow for retain publishing permissions within your IoT policy for this to work and the one I was using only had publish permissions.... I noticed in the logs that it claimed "unauthorized" and investigated further. After correcting my policy and using a clean connection everything is working as expected.

Sorry for wasting your time.

**Comment by shamblett** [comment]
No problem, although the package is some 6 years old now its surprising what users still find hidden in the weeds, also your solution to this may be of use to other users.
