### ISSUE TITLE
Differences in automatic reconnection between IOS and Android

### ISSUE THREAD

**Issue by Zqiang12345** [shamblett/mqtt_client#529]
In IOS. When the wifi is disconnected and reconnected, mqtt can connect normally, but Android cannot

**Comment by shamblett** [comment]
Yes this is a well known phenomena, please look through the closed issues for the many raised in this area and the solutions proposed.

In short there is nothing the client can do about this, it simply responds to events raised by the Dart/flutter runtime, android it seems needs more external management of network change events than IOS does.
