### ISSUE TITLE
AWS IoT Certificate - Use .bks file certificate

### ISSUE THREAD

**Issue by pratamarama** [shamblett/mqtt_client#537]
Hello, I have implemented mqtt client in native android and I want to implement mqtt client on flutter. But, in android i used `.bks` file for the [keystore/certificate](https://docs.amplify.aws/gen1/android/sdk/pubsub/working-api/), while in the example of this package we used `.pem`, `.cert` and `.key` for the certificate.

is there another way to import the certificate for the connections with `.bks` file?

**Comment by shamblett** [comment]
The client relies on the Security Context class from dart:io to configure secure socket working, reference for this is [here](https://api.dart.dev/stable/3.4.2/dart-io/SecurityContext-class.html) as such you can only configure whatever this class allows. It doesn't seem to support .bks files hence the client doesn't support this.
