### ISSUE TITLE
How can i subscribe multi topic?

### ISSUE THREAD

**Issue by quanganh050998** [shamblett/mqtt_client#549]
Hello! First off, thank you for making such an epic library!
How can I subscribe to multiple topics at the same time after I have already connected with MqttServerClient?

**Comment by shamblett** [comment]
Just use the subscribe() method on the client, you can only subscribe to one topic at a time but this can of course be a wildcard topic.

**Comment by quanganh050998** [comment]
But i have multi topic. Can i sub below code:
```

      mqttClient?.subscribe('MI/02', MqttQos.atLeastOnce);
      
      mqttClient?.subscribe('MI/05', MqttQos.atLeastOnce);
```

**Comment by quanganh050998** [comment]
Thanks for support me
