### ISSUE TITLE
Unhandled Exception: Bad state: Cannot add new events after calling close (similar to #516)

### ISSUE THREAD

**Issue by Vera-Spoettl** [shamblett/mqtt_client#558]
Hi there,
I have the same error message as mentioned in [https://github.com/shamblett/mqtt_client/issues/516](url) but with the following stack trace:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      EventBus.fire (package:event_bus/event_bus.dart:61:22)
#2      MqttConnectionHandlerBase.autoReconnect (package:mqtt_client/src/connectionhandling/mqtt_client_mqtt_connection_handler_base.dart:157:23)

```

It seems, that there is a problem after an auto reconnect. Do I have to do anything after reconnecting that I'm missing?

Thanks for your help!

**Comment by shamblett** [comment]
I need a full client log of your autoreconect sequence and just afterwards, are you calling disconnect() after a successful autoreconnect sequence?

**Comment by Vera-Spoettl** [comment]
I have some problems with the hardware at the moment that makes it hard to reproduce this. Please give me some more time to attach a full log ...

**Comment by Vera-Spoettl** [comment]
As I can't reproduce it at the moment, I would like to close this one. I'll raise it again if/when I can reproduce (then with log, ...). 

Thanks for your help! 👍
