### ISSUE TITLE
How to clear retained message?

### ISSUE THREAD

**Issue by function2000** [shamblett/mqtt_client#563]
How to clear retained message on broker via this client?
Thanks for reply!

**Comment by shamblett** [comment]
There is no way to delete retained messages via the client as MQTT doesnt support this you can just receive the message and check the retained flag and ignore it, reconnect with the clean session flag set to true or publish an empty message to the topic with the retained flag set, this has the effevt of clearing the retained message. Note you must do this before you subscribe.

**Comment by function2000** [comment]
Thanks for the reply.  Please close the issue.
