### ISSUE TITLE
How to set will message

### ISSUE THREAD

**Issue by function2000** [shamblett/mqtt_client#564]
Please guide how to set will message. 
I try to do like below, but after that, I even cannot connect to broker:
    final connMess = MqttConnectMessage()
        .withClientIdentifier('nxxii_${DateTime.now().millisecondsSinceEpoch}')
        .startClean()
        .withUserProperties([property])
        .will()
        .withWillTopic('test/disconnected/lol')
        .withWillPayload(builder.payload!)
        .withWillRetain()
        .withWillQos(MqttQos.atMostOnce)
    ;

Better to give an example.  Appreciated!

**Comment by shamblett** [comment]
Will messages are very specific to what you need in this area, the client just provides you with the means to set these fields also brokers differ with what they will support as you have seen just setting all of them can lead to connection refusal(what was the returned error code BTW?).

Please refer to the 3.1 CONNECT – Connection Request message in the MQTT5 [specification](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901033) for details and check what your broker supports.

If in doubt and you don't need to use the will message then leave the connect message defaulted, examples are in the example directory.

**Comment by function2000** [comment]
Thanks for reply, I use MQTT mosquitto server. It support V5.
here below is the log:
flutter: 2024-09-25 16:48:34.478213 -- MqttConnectionHandlerBase::sendMessage - sending message started >>> -> MQTTMessage of type MqttMessageType.connect
MessageType = MqttMessageType.connect Duplicate = false Retain = false Qos = atMostOnce Size = 0
ProtocolName = MQTT
ProtocolVersion = 5
ConnectFlags = CleanStart=true, WillFlag=true, WillQos=atLeastOnce, WillRetain=true, PasswordFlag=false, UserNameFlag=false
KeepAlive = 0
Properties = No properties setWill topic = nxxii/disconnected/lol
User name = not set
Password = not set

flutter: 2024-09-25 16:48:34.495166 -- MqttConnectionHandlerBase::sendMessage - sending message ended >>>
flutter: 2024-09-25 16:48:34.496223 -- MqttSynchronousServerConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of notSet and a disconnection origin of none
flutter: 2024-09-25 16:48:34.504223 -- MqttConnectionBase::_onDone - calling disconnected callback
flutter: 2024-09-25 16:48:36.118576 -- MqttConnectionHandlerBase::disconnect
flutter: 2024-09-25 16:48:36.118805 -- MqttConnectionHandlerBase::_performConnectionDisconnect entered

**Comment by shamblett** [comment]
Mosquitto supports V5 but it may not support the combination of will flags you are sending, you need to consult the MQTT5 spec  and your broker docs as I've said above. As you can see from your log the broker is rejecting the connect message, this is nothing to do with the client as such.

**Comment by function2000** [comment]
Thanks for the comments.
