### ISSUE TITLE
Flutter client just dose not work.

### ISSUE THREAD

**Issue by uwejan** [shamblett/mqtt_client#57]
Hello there,
I just download the repo to test the flutter example, it just dose not seem to work, many error my ide detected, `Undefined class mqtt.ConnectionState, Too many positional arguments every where, can not even get it start to debug`.
Off course enabled dart '2', and got all dependencies.
Thank you.

**Comment by uwejan** [comment]
Hey @shamblett , almost there, 
what about this one, says 4 provided 3 expected 
[void _sendMessage() {
    final mqtt.MqttClientPayloadBuilder builder =
        mqtt.MqttClientPayloadBuilder();

    builder.addString(_messageContent);
    widget.client.publishMessage(
      _topicContent,
      mqtt.MqttQos.values[_qosValue],
      builder.payload,
      _retainValue,
    );
    Navigator.pop(context);
  }](url)

**Comment by shamblett** [comment]
Try 'retain:_retainValue' as per the API for the publishMessage method

**Comment by uwejan** [comment]
Hi, using the example from pub website, i wish to run the method on main file of my flutter, and have the result of incoming notifications accessed from other classes, how can i do that please.
```
  client.updates.listen((List<MqttReceivedMessage<MqttMessage>> c) {
    final MqttPublishMessage recMess = c[0].payload;
    final String pt =
        MqttPublishPayload.bytesToStringAsString(recMess.payload.message);

    /// The above may seem a little convoluted for users only interested in the
    /// payload, some users however may be interested in the received publish message,
    /// lets not constrain ourselves yet until the package has been in the wild
    /// for a while.
    /// The payload is a byte buffer, this will be specific to the topic
    print(
        'EXAMPLE::Change notification:: topic is <${c[0].topic}>, payload is <-- $pt -->');
    print('');
  });
```
i want pt , to be accessed from other classes, so i have only one connection on my main, and want client, to be accessed to so i can pub from other classes, what would be the way to do this please.
