### ISSUE TITLE
Error: mqtt-client::NoConnectionException: The maximum allowed connection attempts ({3}) were exceeded. The broker is not responding to the connection request message (Missing Connection Acknowledgement?

### ISSUE THREAD

**Issue by XlashDev** [shamblett/mqtt_client#570]
`
import 'package:mqtt_client/mqtt_client.dart';
import 'package:mqtt_client/mqtt_server_client.dart';
import 'package:logger/logger.dart';

var logger = Logger();

class MQTTClientService {
  final String broker = '192.168.0.109';
  final String clientId = 'client_main';
  final int port = 1883;
  MqttServerClient? client;

  List<String> deviceTopics = [
    'topics/subtopics1',
     'topics/subtopics2',
  ];

  Future<void> initializeMQTTClient() async {
    client = MqttServerClient(broker, clientId)
      ..port = port
      ..logging(on: true)
      ..keepAlivePeriod = 20
      ..secure = false
      ..onConnected = onConnected
      ..onDisconnected = onDisconnected
      ..onSubscribed = onSubscribed
      ..onSubscribeFail = onSubscribeFail
      ..setProtocolV311()
      ..onUnsubscribed = onUnsubscribed;

    client!.connectionMessage = MqttConnectMessage()
        .withClientIdentifier(clientId)
        .startClean()
        .withWillQos(MqttQos.atLeastOnce);

    await connect();
  }

  Future<void> connect() async {
    try {
      await client!.connect();
    } on Exception catch (e) {
      logger.e('Error: $e');
      await reconnect();
    }

    if (client!.connectionStatus!.state == MqttConnectionState.connected) {
      // Subscribe to all topics after a successful connection
      for (var topic in deviceTopics) {
        logger.i('Subscribing to $topic...');
        client!.subscribe(topic, MqttQos.atMostOnce);
      }
    } else {
      logger.i('Failed to connect, retrying...');
      await reconnect();
    }
  }

  // Reconnection logic
  Future<void> reconnect() async {
    logger.i('Attempting to reconnect...');
    await Future.delayed(const Duration(seconds: 5));
    if (client!.connectionStatus!.state != MqttConnectionState.connected) {
      await connect();
    }
  }

  // Callbacks
  void onConnected() {
    logger.i('Connected to MQTT broker');
  }

  void onDisconnected() {
    logger.i('Disconnected from MQTT broker');
  }

  void onSubscribed(String topic) {
    logger.i('Subscribed to $topic');
  }

  void onSubscribeFail(String topic) {
    logger.i('Failed to subscribe to $topic');
  }

  void onUnsubscribed(String? topic) {
    logger.i('Unsubscribed from $topic');
  }

  void disconnect() {
    client?.disconnect();
  }
}

void main() async {
  final mqttService = MQTTClientService();
  await mqttService.initializeMQTTClient();
}

`

I have same issue here https://github.com/shamblett/mqtt_client/issues/513 but cant resolve using secure to false and it set to false by default.

`Error: mqtt-client::NoConnectionException: The maximum allowed connection attempts ({3}) were exceeded. The broker is not responding to the connection request message (Missing Connection Acknowledgement?`

This is what the mosquitto logs shows

`1730865437: New connection from 127.0.0.1:48590 on port 1883.

1730865437: Client <unknown> disconnected due to protocol error.

1730865442: New connection from 127.0.0.1:58468 on port 1883.

1730865442: Client <unknown> disconnected due to protocol error.

1730865452: New connection from 127.0.0.1:49546 on port 1883.

1730865452: Client <unknown> disconnected due to protocol error.
`

**Comment by shamblett** [comment]
Your getting a protocol error, please look at your connect message. I don't think you can set a will QoS without setting the other will properties either remove the line or use one like this from the examples -
```
final connMess = MqttConnectMessage()
      .withClientIdentifier('Mqtt_MyClientUniqueId')
      .withWillTopic('willtopic') // If you set this you must set a will message
      .withWillMessage('My Will message')
      .startClean() // Non persistent session for testing
      .withWillQos(MqttQos.atLeastOnce);
```

**Comment by XlashDev** [comment]
Thank you @shamblett Been going back and forth with the code, logs and configs with no luck so I opened an issue and you knew the cause of issue right away! Thank you and awesome work with this library!
