### ISSUE TITLE
How to get know the client received the message?

### ISSUE THREAD

**Issue by function2000** [shamblett/mqtt_client#573]
Dear expert,
I want to use MQTT to develop a chat app, I want to store the offline message to server database.  But I have a question, how to get know if the user is offline, as user can be offline in an abnormal way.  So I want to get the ack feedback to make sure user received the message, otherwise, I will consider the user is offline, then store the message to server database. 
Thanks a lot for the advice!

**Comment by shamblett** [comment]
I think you are talking about this -
```
 /// Published message stream. A publish message is added to this
  /// stream on completion of the message publishing protocol for a Qos level.
  /// Attach listeners only after connect has been called.
  Stream<MqttPublishMessage>? get published =>
      publishingManager?.published.stream;
```
When you send a message to the broker at QoS level 1 or 2 a handshake protocol with the broker is started, when the handshake is complete the message you have just sent appears on this stream so you know it has been delivered. If it doesn't appear then it has not been delivered. There is no separate ack message as such.

Note you should really only use QoS 2 for this if you want full resilience, see the MQTT spec for further details.

**Comment by function2000** [comment]
Appreciate your answer, even it is not exactly the same as I expected.  But I have alternative solution.  Thanks all the same.
