### ISSUE TITLE
Handle failed subcriptions

### ISSUE THREAD

**Issue by mrm** [shamblett/mqtt_client#60]
When trying to subscribe to a topic you're not allowed to, the client will crash:
```dart
RangeError (index): Invalid value: Not in range 0..3, inclusive: 128
#0      List.[] (dart:core/runtime/libarray.dart:137:52)
#1      MqttSubscribeAckPayload.readFrom (...mqtt_client-5.1.0/lib/src/messages/subscribeack/mqtt_client_mqtt_subscribe_ack_payload.dart:45:45)
```
As it will try to create a QoS grant with value 0x80 which denotes a failure according to the spec:
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Figure_3.26_-

Perhaps a `success` `bool` should be passed to the `onSubscribed`, or an `onSubscriptionFailed`?

**Comment by mrm** [comment]
I only allow certain topics for certain users, e.g. house/aaa1111/status but tried to connect to aaa1111/status (using vernemq).

**Comment by shamblett** [comment]
Ok, updated at release 5.2.0, this should work now. Iv'e added an onSusbcribeFail callback to trap subscription failure errors, please retest.

**Comment by shamblett** [comment]
Assumed no more work on this is needed, closing
