### ISSUE TITLE
Is QoS lost when the application is closed?

### ISSUE THREAD

**Issue by natezhengbne** [shamblett/mqtt_client#61]
If the QoS message likes MqttQos.atLeastOnce or MqttQos.exactlyOnce only save in Map at the memory.
Could I think the QoS message will be fade away when the application closed?

**Comment by natezhengbne** [comment]
Yes, you get my point.
So that I should storage the message greater than QoS-0 and check whether the QoS requirement is implemented. 
For example, I send a message in QoS-1, I should check and resend until received the ack from the MQTT server.

**Comment by shamblett** [comment]
No need to do this, the client performs the handshake for you, see the Qos examples in the examples directory, however you don't get a notification if this has worked or not, is this what you are asking for?

**Comment by natezhengbne** [comment]
In your example, the code likes these:
`
     client.publishMessage(topic2, MqttQos.atLeastOnce, builder2.payload);
`
If the client crashed after the message has published successfully but it didn't received the ack from server.
What will be happen? Will the message be losed?
So that what I mean is how to make the message persistence.

**Comment by shamblett** [comment]
Well, if the client crashes its likely to bring the whole Dart VM down with it so any persistence outside the client would be gone anyway. 

However, you'll notice that the 'publishMessage' method on the client returns the message id of the published message, you could store this with your QoS message, then when the client has published the message it could fire an OnPublished callback from the code above, passing the message id as a parameter, you could then remove this message from your persistence queue, would this be OK?

**Comment by natezhengbne** [comment]
My business scenario is that GPS Locator constantly generates data and stores in SQLite.
So I think it will be stored well when application down or offline.
I think your solution will work, but the issue is how do I resend the message save in the map "publishedMessages", likes a retry mechanism.

**Comment by shamblett** [comment]
OK, I see, so how do you mark a message as being sent? You can't rely on the client for this as like you say it may crash so do you update sqlite with a 'sent' marker, or remove the message or some other mechanism. I'm backing away from the idea of a callback for this now, I don't want to tie the client into to much external processing on publish, there may be a lot of traffic here. 

I can add a getter for the 'publishedMessages' map on the client if you wish if this will help you.

**Comment by natezhengbne** [comment]
I will save every message in SQLite with UUID and status.
I think you can put the event in the stream that is it may be a choice?

**Comment by natezhengbne** [comment]
Great to hear that.
Thank you very much.
