### ISSUE TITLE
Unicode ( Arabic, Emoji ) Problem

### ISSUE THREAD

**Issue by tje3d** [shamblett/mqtt_client#62]
There is a weird problem with arabic and emoji characters.
For example if you send something like `سلام`, What broker receives is: `3D'E`.

Same for emojis: `😁`, Result: `=\u0001`

**Comment by shamblett** [comment]
Ok I'll have a look, in the meantime have you tried the 'addUTF16String' method on the payload builder class to add your characters?

**Comment by tje3d** [comment]
@shamblett Not works, It seems builder makes invalid payload:

1:
```dart
MqttClientPayloadBuilder builder = MqttClientPayloadBuilder();
builder.addUTF16String("این یک پیام تستی هستش");
builder.payload; // [39, 6, 4294967244, 6]
```

2:
```dart
MqttClientPayloadBuilder builder = MqttClientPayloadBuilder();
builder.addUTF16String(
    json.encode(
        {
            "type": "msgText",
            "data": "این یک پیام تست هستش",
        },
    ),
);
builder.payload; // Payload: [123, 0, 34, 0]
```

**Comment by shamblett** [comment]
Yes, I'll look at this, note that at the moment example 2 would never work, the builder would expect the data string only, not the whole json string.

**Comment by noordawod** [comment]
I suggest to encode your message with Base64 and decode it on the client, @tje3d.

**Comment by tje3d** [comment]
@noordawod Thanks good idea, but in my case, i'm working with a public production broker.

**Comment by tje3d** [comment]
I just ported Paho StringToUTF8 logic and got problem fixed. Will make a pull request soon.

**Comment by tje3d** [comment]
@shamblett Just updated to 5.3.0, and issue still exists. Now `سلام` turn's to `3 D ' E` ( note spaces ).
