### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by littlesalt** [shamblett/mqtt_client#65]
Garbled characters when the content is Chinese！
Partial code：
final mqtt.MqttPublishMessage recMess =
    event[0].payload as mqtt.MqttPublishMessage;
    final String message =
    mqtt.MqttPublishPayload.bytesToStringAsString(recMess.payload.message);
   
when MqttPublishMessageis chinese , message is garbled.
example:
你好  -》  `}

**Comment by littlesalt** [comment]
OK.There is no known method, do I need to customize it?

**Comment by shamblett** [comment]
Yes, the client does supply a utility class for building payloads from Dart types but not for decoding, there are many ways users can encode payload data, no one library will encompass all of them so this is left to the user.
