### ISSUE TITLE
Fallback to websockets

### ISSUE THREAD

**Issue by Niek** [shamblett/mqtt_client#71]
It would be great if it'd be possible to fall back to WS/WSS in case that the MQTT connection is not working/blocked.

Maybe a constructor that allows to pass in a list of servers that are tried in waterfall order?

**Comment by shamblett** [comment]
OK, your use case here is possible, so do you mean you want a client that given a list of connections(assume all the same for now i.e. ws/wss) it tries the first one, if it fails it tries the second and so on, when one connects that's the on you use, until some time in the future it fails, then you try the next and so on, or when the first connection succeeds that's the one you want, if it fails it fails as it does now.

Either way this won't be in the client as such, I'm introducing some management classes to perform stuff like this and [topic filtering](https://github.com/shamblett/mqtt_client/issues/69) etc. This allows users to chose what they want to use without bloating the client itself, some users may want to do all their own management.

**Comment by shamblett** [comment]
Its in library scope, sorry if I wasn't clear, but not in the client scope, as in a constructor on MqttClient class, it would be say in some management class say MqttClientMonitor class or something that will use the MqttClient so it will be in the library.

If you wish to have a go at this feel free, pull requests gladly accepted, if your willing to wait I will do this but it may be a couple of weeks.
