### ISSUE TITLE
MqttConnectionState.connected

### ISSUE THREAD

**Issue by uwejan** [shamblett/mqtt_client#74]
Hello, i do not know if this is normal behavior or not, so, if i disconnect internet from my client and have a button to make a check against the connection status, i always keep getting connected, is not should return disconnected? btw, what would be the ideal way to avoid such issues on production, make a check on timer and try to reconnect till i get connected?

**Comment by shamblett** [comment]
You need to hook into the onDisconnected callback, see the API docs/examples for more details. The client calls this on disconnect, either by the user calling the disconnect method or from the broker on unsolicited disconnect. For the scenario you describe the disconnect is triggered from the onDone callback of whatever socket you are using to connect to the broker, if this is not happening for whatever reason the client will still show as connected.

Other users use this callback to do tidy up processing, trigger a reconnect etc.

**Comment by uwejan** [comment]
Not quit there. I am basically connected to a broker over tcp. So in case of internet disconnectivity there is no way for the client  to detect it?
I was thinking of sth like On.client.Disconnected fun that automatically detects there is no ping/pong between client and the broker and that of course as result of internet disconnictivity client side in my case.

**Comment by shamblett** [comment]
OK, easiest way to do this is to add a callback to the client that's invoked when a ping response is received from the broker, then the user can say increment a count and check this is being incremented, if not it can take whatever action it wants. Its more complex to build this into the client, firstly how many failed responses do you count before triggering fail, then what do you do? Disconenct? some users may not want this, other scenarios are alos possible. This is a candidate for en external management function, I'm looking at these for other issues.

**Comment by uwejan** [comment]
that is sth, can not do for some reason, will keep this issue open, to track in case you had it.
I have read on the specifications, that the client will keep sending ping, to the server hey am there, and the server say back pong, i know you are there. in theory if there would be a fuc that check there is no ping/pong going on, so do whatever you want then. could be try to reconnect.

**Comment by shamblett** [comment]
Callback added on ping response received, client re-published at version 5.5.0
