### ISSUE TITLE
Isolates.

### ISSUE THREAD

**Issue by uwejan** [shamblett/mqtt_client#76]
Hi, i was wondering, is there a way to run the client on isolates, taking advantage using threads, and multiple CPU cores.

**Comment by shamblett** [comment]
Can't see why not, there's nothing special about the client that I'm aware of that means it can't be instantiated multiple times whether this be in a single isolate or multiple ones.

**Comment by uwejan** [comment]
Is it possible to ask for an example running on multiple isolates?
