### ISSUE TITLE
Validate if topic exists

### ISSUE THREAD

**Issue by BitKnitting** [shamblett/mqtt_client#78]
Prior to subscribing, I'd like to ask the broker for a list of existing topics.  Then validate if the topic being passed in already exists on the broker.  I did not find an obvious way to do this with the mqtt_client.  What am I missing?  Thank you.

**Comment by shamblett** [comment]
Unfortunately MQTT doesn't really allow this, an explanation and possible workarounds can be found [here](https://stackoverflow.com/questions/43221929/how-to-check-if-topic-exists-in-mqtt). If your broker supports a topic that gives you a list of existing topics you could subscribe to this but this is not part of the MQTT spec.

**Comment by shamblett** [comment]
Closing this as not a client issue
