### ISSUE TITLE
Flutter to Adafruit IO example

### ISSUE THREAD

**Issue by BitKnitting** [shamblett/mqtt_client#79]
This isn't an issue...but rather I was able to get a flutter app to publish/subscribe to Adafruit IO.  I wanted to thank you for all your help.  Here is the repo: [https://github.com/BitKnitting/flutter_adafruit_mqtt](url)

**Comment by shamblett** [comment]
OK great, another broker the client has been tested against. I think I'll update the README to more properly list the brokers I know it works against and in the case where there are examples like this one add a link to the example. I'll leave this issue open for now as a reminder to do this.

**Comment by shamblett** [comment]
README updated with link to above example in client 5.5.0, closing
