### ISSUE TITLE
How to Solve CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate

### ISSUE THREAD

**Issue by ycads** [shamblett/mqtt_client#80]
Hi All, 
    When I was using ssl, I prompted CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate to make a mistake. Is there anyone who can help me? Thank you!
Final SecurityContext context = SecurityContext. defaultContext;
Context. setTrusted Certificates ("/storage/emulated/0/roots.pem");
Also tried to add passwords, the same prompt error.

@shamblett 

Thanks!

**Comment by shamblett** [comment]
If you are using flutter there is some info [here](https://github.com/flutter/flutter/issues/21218), you could also try [this](https://stackoverflow.com/questions/54285172/how-to-solve-flutter-certificate-verify-failed-error-while-performing-a-post-req). I doubt this is anything to do with the client per se.

**Comment by ycads** [comment]
> this
@shamblett Thank you very much for your reply.
Yes, I using flutter, I know this: 
 client. badCertificate Callback = ((X509 Certificate Cert, String host, int port) => true);
 but I can't modify your code. Must I modify the source code to solve this problem?

Thank you!

**Comment by ycads** [comment]
Hello @shamblett , 
    I have solved this bug and need to adjust mqtt_client_mqtt_secure-connection to add X509 Certificate verification. 
Thank you very much!

**Comment by shamblett** [comment]
Great, thanks for doing the research into this. Is it possible to share your code update? If you have encountered this others may do also, it would be good to put a fix in the client.

**Comment by merliandrea** [comment]
Please leave the code if you can @shamblett @ycads 
Thanks

**Comment by ExzaSolutions** [comment]
Hi how did you solve this?

**Comment by shamblett** [comment]
I didn't, may be better contacting @ycads directly

**Comment by w4-sglim** [comment]
FYI: I created PR #127 to support this issue.
