### ISSUE TITLE
why the mqtt conncet disconnected,should I connect the serve in the disconnected callback?

### ISSUE THREAD

**Issue by zhaoxiafeigithub** [shamblett/mqtt_client#86]

**Comment by shamblett** [comment]
The disconnected callback is there to indicate a disconnection if you need to know this. Disconnections are either solicited(you have called the disconnect() method on the client) or unsolicited(the broker has closed the connection). You can then take appropriate action. Some users do reconnect in the disconnect callback but I think a better method is to just set a flag to say disconnection has occurred and use a timed watchdog task to perform the reconnection.
