### ISSUE TITLE
flutter assets errors

### ISSUE THREAD

**Issue by SarahKaren4** [shamblett/mqtt_client#91]
Lost connection to device.
Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
Error writing "build/flutter_assets/packages/font_awesome_flutter/lib/fonts/fa-regular-400.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
Error writing "build/flutter_assets/packages/font_awesome_flutter/lib/fonts/fa-brands-400.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
Error writing "build/flutter_assets/packages/font_awesome_flutter/lib/fonts/fa-solid-900.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
Error writing "build/flutter_assets/packages/rich_alert/assets/success.png" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
Error writing "build/flutter_assets/AssetManifest.json" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
Error writing "build/flutter_assets/FontManifest.json" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
Error writing "build/flutter_assets/LICENSE" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
Error writing "build/flutter_assets/packages/rich_alert/assets/error.png" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
Error writing "build/flutter_assets/packages/rich_alert/assets/warning.png" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
Error writing "build/flutter_assets/packages/material_design_icons_flutter/lib/fonts/materialdesignicons-webfont.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
Error writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
Error writing "build/flutter_assets/assets/catalog.png" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/

**Comment by shamblett** [comment]
Can't see what this has to do with the mqtt_client, looks more like a flutter runtime error of some kind, maybe ask on the flutter dev lists

**Comment by bhanuka96** [comment]
> Lost connection to device.
> Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
> Error writing "build/flutter_assets/packages/font_awesome_flutter/lib/fonts/fa-regular-400.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
> Error writing "build/flutter_assets/packages/font_awesome_flutter/lib/fonts/fa-brands-400.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
> Error writing "build/flutter_assets/packages/font_awesome_flutter/lib/fonts/fa-solid-900.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
> Error writing "build/flutter_assets/packages/rich_alert/assets/success.png" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
> Error writing "build/flutter_assets/AssetManifest.json" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
> Error writing "build/flutter_assets/FontManifest.json" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
> Error writing "build/flutter_assets/LICENSE" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
> Error writing "build/flutter_assets/packages/rich_alert/assets/error.png" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
> Error writing "build/flutter_assets/packages/rich_alert/assets/warning.png" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
> Error writing "build/flutter_assets/packages/material_design_icons_flutter/lib/fonts/materialdesignicons-webfont.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
> Error writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/
> Error writing "build/flutter_assets/assets/catalog.png" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49701/

Do you solve this error?

**Comment by bttcJ** [comment]
Do you solve this error?

**Comment by SarahKaren4** [comment]
No my flutter app is still stopping whe I add assets

**Comment by xhidnoda** [comment]
This, problem happen to me one time, and don't really know if related...but when i management in the correct way the MQTT connection, the error is disappear.
