### ISSUE TITLE
Trying to connect to an appsync subscription...

### ISSUE THREAD

**Issue by bobwiller** [shamblett/mqtt_client#92]
Trying to spike some code to connect to an AppSync Subscription websocket at "wss://a307xxxxxxxxx0-ats.iot.us-east-1.amazonaws.com/mqtt" but it seems no matter what i have tried i get a WebSocketException that Conection to '' was not upgraded to websocket.  

I am assuming this is because the Connection and Upgrade headers need to be set, but not sure how to do this?  Has anyone else been successful connecting to an AppSync  subscription in Dart or Flutter?
Thanks,
Bob

**Comment by shamblett** [comment]
We have lots of users using ws and wss, if you look through the closed issues you'll see a number of things were found and fixed for the websocket implementation. The websocket upgrading is not done by the client per se but by the Dart runtime however there are a couple of things you can try -

1. Change the protocols string sent in the ws header using the websocketProtocols setter, see the API docs.
2. Try setting useAlternateWebSocketImplementation, this was added by a user who was having probs with IIRC Amazon specifically. 

I don't know what an AppSync Subscription is but if it conforms to standard websocket protocol it should work.

From your log extract above the 'connection to' string should print the URL, it seems not to.

**Comment by marwfair** [comment]
@bobwiller Were you able to make this work?

**Comment by bobwiller** [comment]
@marwfair gist here: [https://gist.github.com/bobwiller/b669f3476fcd2805b4f25b96243d859a](url)

**Comment by marwfair** [comment]
@bobwiller Thank you! That was just what I was needing.
