### ISSUE TITLE
MQTT connection problem with local broker

### ISSUE THREAD

**Issue by DhavalRKansara** [shamblett/mqtt_client#93]
I am trying to connect to a local broker on MQTT and getting the following exception, could you please check and tell if there is some error from my side?

**My Code**
final MqttClient client = MqttClient('172.16.4.231', '');

  Future setUpMQTT() async {
    client.logging(on: true);
    client.onDisconnected = onDisconnected;
    client.onConnected = onConnected;
    client.keepAlivePeriod = 20;
    client.onSubscribed = onSubscribed;
    client.pongCallback = pong;
    client.port = 8083;
    client.secure = false;

    final MqttConnectMessage connMess = await MqttConnectMessage()
 .withClientIdentifier('rayWebSocketClient_123456_33f7423c-a3b7-46b1-8a1a-26937e4a071f')
.authenticateAs('username', 'some-password')
.withWillTopic('willtopic') 
.withWillMessage('My Will message')
.keepAliveFor(20)
.startClean()
.withWillQos(MqttQos.atLeastOnce);
print(' Mosquitto client connecting....');

client.connectionMessage = connMess;

    try {
      await client.connect();
    } on Exception catch (e) {
      print('client Connection exception - $e');
    }

**Below is the error log:**
flutter: 2019-05-01 11:22:36.729330 -- MqttConnectPayload::Client id exceeds spec value of 23
flutter:  Mosquitto client connecting....
flutter: 2019-05-01 11:22:36.742334 -- Authenticating with username '{websocketuser}' and password '{wbcGH+2qTEe.78U}'
flutter: 2019-05-01 11:22:36.742541 -- Username length (13) exceeds the max recommended in the MQTT spec.
flutter: 2019-05-01 11:22:36.742669 -- Password length (15) exceeds the max recommended in the MQTT spec.
flutter: 2019-05-01 11:22:36.762969 -- SynchronousMqttConnectionHandler::internalConnect entered
flutter: 2019-05-01 11:22:36.763185 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 0
flutter: 2019-05-01 11:22:36.763537 -- SynchronousMqttConnectionHandler::internalConnect - insecure TCP selected
flutter: 2019-05-01 11:22:36.799096 -- MqttConnection::_startListening
flutter: 2019-05-01 11:22:36.802701 -- SynchronousMqttConnectionHandler::internalConnect sending connect message
flutter: 2019-05-01 11:22:36.804895 -- MqttConnectionHandler::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=true, WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=true, UserNameFlag=true, KeepAlive=20
Instance of 'MqttConnectPayload'
flutter: 2019-05-01 11:22:36.825418 -- SynchronousMqttConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code noneSpecified
flutter: 2019-05-01 11:22:36.829865 -- MqttConnection::_onData
flutter: 2019-05-01 11:22:36.846529 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.publishAck
Header: MessageType = MqttMessageType.publishAck, Duplicate = true, Retain = false, Qos = MqttQos.atMostOnce, Size = 84
PublishAck Variable Header: MessageIdentifier={21584}
flutter: 2019-05-01 11:22:36.848664 -- MqttConnection::_onData - message processed
flutter: 2019-05-01 11:22:36.849021 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.publishAck
Header: MessageType = MqttMessageType.publishAck, Duplicate = false, Retain = true, Qos = MqttQos.atLeastOnce, Size = 111
PublishAck Variable Header: MessageIdentifier={28276}
flutter: 2019-05-01 11:22:36.849354 -- MqttConnection::_onData - message processed
flutter: 2019-05-01 11:22:36.850142 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.publishRelease
Header: MessageType = MqttMessageType.publishRelease, Duplicate = true, Retain = false, Qos = MqttQos.atMostOnce, Size = 101
PublishRelease Variable Header: MessageIdentifier={24932}
flutter: 2019-05-01 11:22:36.850372 -- MqttConnection::_onData - message processed
flutter: 2019-05-01 11:22:36.851599 -- MqttConnection::_ondata - message is not valid
flutter: 2019-05-01 11:22:36.851811 -- MqttConnection::_ondata - exception is mqtt-client::InvalidMessageException: The data provided in the message stream was not a valid MQTT Message, exception is mqtt-client::InvalidMessageException: Available bytes is less than the message size, bytestream is null or empty
flutter: 2019-05-01 11:22:36.863666 -- MqttConnection::_onDone - calling disconnected callback
Syncing files to device iPhone Xʀ...
flutter: 2019-05-01 11:22:41.830794 -- SynchronousMqttConnectionHandler::internalConnect - post sleep, state = Connection status is connecting with return code noneSpecified
flutter: 2019-05-01 11:22:41.830967 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 1
flutter: 2019-05-01 11:22:41.831063 -- SynchronousMqttConnectionHandler::internalConnect - insecure TCP selected
flutter: 2019-05-01 11:22:41.841657 -- MqttConnection::_startListening
flutter: 2019-05-01 11:22:41.842110 -- SynchronousMqttConnectionHandler::internalConnect sending connect message
flutter: 2019-05-01 11:22:41.842302 -- MqttConnectionHandler::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 137
Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=true, WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=true, UserNameFlag=true, KeepAlive=20
Instance of 'MqttConnectPayload'
flutter: 2019-05-01 11:22:41.842933 -- SynchronousMqttConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code noneSpecified
flutter: 2019-05-01 11:22:41.848356 -- MqttConnection::_onData
flutter: 2019-05-01 11:22:41.848915 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.publishAck
Header: MessageType = MqttMessageType.publishAck, Duplicate = true, Retain = false, Qos = MqttQos.atMostOnce, Size = 84
PublishAck Variable Header: MessageIdentifier={21584}
flutter: 2019-05-01 11:22:41.849100 -- MqttConnection::_onData - message processed
flutter: 2019-05-01 11:22:41.849352 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.publishAck
Header: MessageType = MqttMessageType.publishAck, Duplicate = false, Retain = true, Qos = MqttQos.atLeastOnce, Size = 111
PublishAck Variable Header: MessageIdentifier={28276}
flutter: 2019-05-01 11:22:41.849496 -- MqttConnection::_onData - message processed
flutter: 2019-05-01 11:22:41.849751 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.publishRelease
Header: MessageType = MqttMessageType.publishRelease, Duplicate = true, Retain = false, Qos = MqttQos.atMostOnce, Size = 101
PublishRelease Variable Header: MessageIdentifier={24932}
flutter: 2019-05-01 11:22:41.849900 -- MqttConnection::_onData - message processed
flutter: 2019-05-01 11:22:41.850077 -- MqttConnection::_ondata - message is not valid
flutter: 2019-05-01 11:22:41.850217 -- MqttConnection::_ondata - exception is mqtt-client::InvalidMessageException: The data provided in the message stream was not a valid MQTT Message, exception is mqtt-client::InvalidMessageException: Available bytes is less than the message size, bytestream is null or empty
flutter: 2019-05-01 11:22:41.850777 -- MqttConnection::_onDone - calling disconnected callback
flutter: 2019-05-01 11:22:46.849276 -- SynchronousMqttConnectionHandler::internalConnect - post sleep, state = Connection status is connecting with return code noneSpecified
flutter: 2019-05-01 11:22:46.849430 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 2
flutter: 2019-05-01 11:22:46.849544 -- SynchronousMqttConnectionHandler::internalConnect - insecure TCP selected
flutter: 2019-05-01 11:22:46.855218 -- MqttConnection::_startListening
flutter: 2019-05-01 11:22:46.855454 -- SynchronousMqttConnectionHandler::internalConnect sending connect message
flutter: 2019-05-01 11:22:46.855596 -- MqttConnectionHandler::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 137
Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=true, WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=true, UserNameFlag=true, KeepAlive=20
Instance of 'MqttConnectPayload'
flutter: 2019-05-01 11:22:46.856126 -- SynchronousMqttConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code noneSpecified
flutter: 2019-05-01 11:22:46.859729 -- MqttConnection::_onData
flutter: 2019-05-01 11:22:46.859939 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.publishAck
Header: MessageType = MqttMessageType.publishAck, Duplicate = true, Retain = false, Qos = MqttQos.atMostOnce, Size = 84
PublishAck Variable Header: MessageIdentifier={21584}
flutter: 2019-05-01 11:22:46.860237 -- MqttConnection::_onData - message processed
flutter: 2019-05-01 11:22:46.860500 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.publishAck
Header: MessageType = MqttMessageType.publishAck, Duplicate = false, Retain = true, Qos = MqttQos.atLeastOnce, Size = 111
PublishAck Variable Header: MessageIdentifier={28276}
flutter: 2019-05-01 11:22:46.860666 -- MqttConnection::_onData - message processed
flutter: 2019-05-01 11:22:46.860874 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.publishRelease
Header: MessageType = MqttMessageType.publishRelease, Duplicate = true, Retain = false, Qos = MqttQos.atMostOnce, Size = 101
PublishRelease Variable Header: MessageIdentifier={24932}
flutter: 2019-05-01 11:22:46.861005 -- MqttConnection::_onData - message processed
flutter: 2019-05-01 11:22:46.861200 -- MqttConnection::_ondata - message is not valid
flutter: 2019-05-01 11:22:46.861318 -- MqttConnection::_ondata - exception is mqtt-client::InvalidMessageException: The data provided in the message stream was not a valid MQTT Message, exception is mqtt-client::InvalidMessageException: Available bytes is less than the message size, bytestream is null or empty
flutter: 2019-05-01 11:22:46.861647 -- MqttConnection::_onDone - calling disconnected callback
flutter: 2019-05-01 11:22:51.863195 -- SynchronousMqttConnectionHandler::internalConnect - post sleep, state = Connection status is connecting with return code noneSpecified
flutter: 2019-05-01 11:22:51.863351 -- SynchronousMqttConnectionHandler::internalConnect failed
flutter: client Connection exception - mqtt-client::NoConnectionException: The maximum allowed connection attempts ({3}) were exceeded. The broker is not responding to the connection request message (Missing Connection Acknowledgement

**Screeenshot of webclient with successful connection**
<img width="800" alt="Screenshot 2019-05-01 at 11 20 03 AM" src="https://user-images.githubusercontent.com/44993081/57007311-49c82300-6c05-11e9-97d3-0592f67bf8c1.png">

**Comment by shamblett** [comment]
OK, couple of things, the first message the client expects from the broker is a connack, we are not getting this we are getting 

flutter: 2019-05-01 11:22:36.846529 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.publishAck

or what it thinks is a publish ack, followed by some other messages, finally failing with a

client::InvalidMessageException: The data provided in the message stream was not a valid MQTT Message, 

without a connack we time out and retry which is what you are seeing.

Also looking at your creds i.e your username is websocketuser, are you intending to use websockets? If so you need to set the websocket flag on the client and prefix your hostname with 'ws://'

**Comment by DhavalRKansara** [comment]
Thanks for your quick response.

Firstly, I am not connecting over a websocket, but over a tcp connection. I tried sending the username and password in the parameters of connect method, but still got the notAuthorized error. I am pasting the new flutter log below, kindly provide assistance.

```
flutter: 2019-05-01 12:55:20.991767 -- SynchronousMqttConnectionHandler::internalConnect - insecure TCP selected
flutter: 2019-05-01 12:55:21.090370 -- MqttConnection::_startListening
flutter: 2019-05-01 12:55:21.105326 -- SynchronousMqttConnectionHandler::internalConnect sending connect message
flutter: 2019-05-01 12:55:21.109374 -- MqttConnectionHandler::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=true, WillQos=MqttQos.atLeastOnce, WillRetain=true, PasswordFlag=true, UserNameFlag=true, KeepAlive=30
Instance of ‘MqttConnectPayload’
flutter: 2019-05-01 12:55:21.138968 -- SynchronousMqttConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code noneSpecified
flutter: 2019-05-01 12:55:21.167553 -- MqttConnection::_onData
flutter: 2019-05-01 12:55:21.183077 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.connectAck
Header: MessageType = MqttMessageType.connectAck, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 2
Connect Variable Header: TopicNameCompressionResponse={0}, ReturnCode={MqttConnectReturnCode.notAuthorized}
flutter: 2019-05-01 12:55:21.186179 -- MqttConnection::_onData - message processed
flutter: 2019-05-01 12:55:21.191909 -- SynchronousMqttConnectionHandler::_connectAckProcessor
flutter: 2019-05-01 12:55:21.192697 -- SynchronousMqttConnectionHandler::_connectAckProcessor connection rejected
flutter: 2019-05-01 12:55:21.197137 -- SynchronousMqttConnectionHandler:: cancelling connect timer
flutter: 2019-05-01 12:55:21.198718 -- SynchronousMqttConnectionHandler::internalConnect - post sleep, state = Connection status is disconnected with return code notAuthorized
```

**Comment by shamblett** [comment]
OK, this usually means you are in fact not authed, could you supply all of the log, i.e. from 

flutter: Mosquitto client connecting...

so I can see the connection string.

**Comment by DhavalRKansara** [comment]
I am not connecting to mosquitto client, but to a local client, below is the log you asked for:

```
flutter: 2019-05-01 13:12:00.922727 -- MqttConnectPayload::Client id exceeds spec value of 23
flutter: MQTT client connecting....
flutter: 2019-05-01 13:12:00.931695 -- Authenticating with username '{websocketuser}' and password '{wbcGH+2qTEe.78U}'
flutter: 2019-05-01 13:12:00.933444 -- Username length (13) exceeds the max recommended in the MQTT spec.
flutter: 2019-05-01 13:12:00.933836 -- Password length (15) exceeds the max recommended in the MQTT spec.
flutter: 2019-05-01 13:12:00.947334 -- SynchronousMqttConnectionHandler::internalConnect entered
flutter: 2019-05-01 13:12:00.947677 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 0
flutter: 2019-05-01 13:12:00.948514 -- SynchronousMqttConnectionHandler::internalConnect - insecure TCP selected
flutter: 2019-05-01 13:12:00.978042 -- MqttConnection::_startListening
flutter: 2019-05-01 13:12:00.988437 -- SynchronousMqttConnectionHandler::internalConnect sending connect message
flutter: 2019-05-01 13:12:00.990425 -- MqttConnectionHandler::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=true, WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=true, UserNameFlag=true, KeepAlive=30
Instance of 'MqttConnectPayload'
flutter: 2019-05-01 13:12:00.999684 -- SynchronousMqttConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code noneSpecified
flutter: 2019-05-01 13:12:01.029721 -- MqttConnection::_onError - calling disconnected callback
flutter: 2019-05-01 13:12:01.032345 -- MqttConnection::_onDone - calling disconnected callback
flutter: 2019-05-01 13:12:06.004493 -- SynchronousMqttConnectionHandler::internalConnect - post sleep, state = Connection status is connecting with return code noneSpecified
flutter: 2019-05-01 13:12:06.004902 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 1
flutter: 2019-05-01 13:12:06.005163 -- SynchronousMqttConnectionHandler::internalConnect - insecure TCP selected
flutter: 2019-05-01 13:12:06.017858 -- MqttConnection::_startListening
flutter: 2019-05-01 13:12:06.018321 -- SynchronousMqttConnectionHandler::internalConnect sending connect message
flutter: 2019-05-01 13:12:06.018709 -- MqttConnectionHandler::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 136
Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=true, WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=true, UserNameFlag=true, KeepAlive=30
Instance of 'MqttConnectPayload'
flutter: 2019-05-01 13:12:06.020268 -- SynchronousMqttConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code noneSpecified
flutter: 2019-05-01 13:12:06.035068 -- MqttConnection::_onData
flutter: 2019-05-01 13:12:06.039434 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.connectAck
Header: MessageType = MqttMessageType.connectAck, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 2
Connect Variable Header: TopicNameCompressionResponse={0}, ReturnCode={MqttConnectReturnCode.notAuthorized}
flutter: 2019-05-01 13:12:06.041268 -- MqttConnection::_onData - message processed
flutter: 2019-05-01 13:12:06.043791 -- SynchronousMqttConnectionHandler::_connectAckProcessor
flutter: 2019-05-01 13:12:06.044032 -- SynchronousMqttConnectionHandler::_connectAckProcessor connection rejected
flutter: 2019-05-01 13:12:06.044436 -- SynchronousMqttConnectionHandler:: cancelling connect timer
flutter: 2019-05-01 13:12:06.045009 -- SynchronousMqttConnectionHandler::_connectAckProcessor
flutter: 2019-05-01 13:12:06.045302 -- SynchronousMqttConnectionHandler::_connectAckProcessor connection rejected
flutter: 2019-05-01 13:12:06.045548 -- SynchronousMqttConnectionHandler:: cancelling connect timer
flutter: 2019-05-01 13:12:06.045838 -- SynchronousMqttConnectionHandler::internalConnect - post sleep, state = Connection status is disconnected with return code notAuthorized
```

**Comment by shamblett** [comment]
OK,

Looks as though for these credentials 

Authenticating with username '{websocketuser}' and password '{wbcGH+2qTEe.78U}'

You are not authorized, the broker is returning this in the connack message, I can't see any other errors.

**Comment by DhavalRKansara** [comment]
My broker has a local IP 172.16.4.231 with port 1883, I am able to connect to the broker via a web MQTT client, MQTTLens (Chrome plugin). Is there any special change I would need to make in order to make it work on a local IP? If it was unauthorized, I would get the same message on the web client as well.

**Comment by shamblett** [comment]
Your connection is OK, you are receiving a valid connack message, the broker is saying you are not authorized for some reason, could you maybe turn authentication off and then try it, or maybe look at your local broker logs, it may say why its not happy.

**Comment by DhavalRKansara** [comment]
Hi @shamblett 
I changed a few properties in my code as below:
- Removed withWillTopic
- Removed withWillMessage
- Removed withWillRetain
- Set withWillQos(MqttQos.atMostOnce)

After these changes in my code setup started working.
Thank you for your help.
I am closing this issue.

**Comment by pankajmotiyar** [comment]
> Hi @shamblett I changed a few properties in my code as below:
> 
> * Removed withWillTopic
> * Removed withWillMessage
> * Removed withWillRetain
> * Set withWillQos(MqttQos.atMostOnce)
> 
> After these changes in my code setup started working. Thank you for your help. I am closing this issue.

working for me.
