### ISSUE TITLE
Why I connect to server through TCP

### ISSUE THREAD

**Issue by SunLongbri** [shamblett/mqtt_client#94]
I/flutter ( 5825): 2019-05-06 18:19:00.679666 -- Authenticating with username '{wbpwjaso}' and password '{eO-kjpnhyvrI}'
I/flutter ( 5825): 2019-05-06 18:19:00.681352 -- SynchronousMqttConnectionHandler::internalConnect entered
I/flutter ( 5825): 2019-05-06 18:19:00.681805 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 0
I/flutter ( 5825): 2019-05-06 18:19:00.681949 -- SynchronousMqttConnectionHandler::internalConnect - insecure TCP selected
I/flutter ( 5825): 2019-05-06 18:19:42.773435 -- MqttConnection::_onError - calling disconnected callback
I/flutter ( 5825): SocketException: Failed host lookup: 'tcp://192.168.1.129' (OS Error: No address associated with hostname, errno = 7)
I/flutter ( 5825): 2019-05-06 18:19:42.776705 -- SynchronousMqttConnectionHandler::disconnect
I/flutter ( 5825): 2019-05-06 18:19:42.778262 -- MqttConnectionHandler::sendMessage - MQTTMessage of type MqttMessageType.disconnect
I/flutter ( 5825): Header: MessageType = MqttMessageType.disconnect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
I/flutter ( 5825): 2019-05-06 18:19:42.779627 -- MqttConnectionHandler::sendMessage - not connected
E/flutter ( 5825): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'cancel' was called on null.

**Comment by shamblett** [comment]
Failing on this line 👎 
SocketException: Failed host lookup: 'tcp://192.168.1.129' (OS Error: No address associated with hostname, errno = 7)

Your IP address doesn't seem to exist

**Comment by SunLongbri** [comment]
I should use wss ,and I use this way ,connected is successful.
