### ISSUE TITLE
I posted a new Topic on Communications Cat's website, and other devices received it, but nothing was printed on my phone. If the log in the framework is set to false, the buffer can be printed out. I don't know if I didn't listen to this topic.

### ISSUE THREAD

**Issue by SunLongbri** [shamblett/mqtt_client#95]
Future<int> connect() async {

    final MqttClient client = MqttClient('ws://192.168.1.129', '');

    client.useWebSocket = true;
    client.port = 8084;
    client.logging(on: false);
    client.keepAlivePeriod = 30;
    
    client.onDisconnected = onDisconnected;
    
    final MqttConnectMessage connMess = MqttConnectMessage()
        .withClientIdentifier('Mqtt_MyClientUniqueIdWildcard')
        .keepAliveFor(30) // Must agree with the keep alive set above or not set
        .withWillTopic(
            'willtopic') // If you set this you must set a will message
        .withWillMessage('My Will message')
        .startClean() // Non persistent session for testing
        .withWillQos(MqttQos.atLeastOnce);
    print('EXAMPLE::Mosquitto client connecting....');
    client.connectionMessage = connMess;
    try {
      await client.connect();
    } on Exception catch (e) {
      print('EXAMPLE::client exception - $e');
      client.disconnect();
    }

    if (client.connectionStatus.state == MqttConnectionState.connected) {
      print('EXAMPLE::Mosquitto client connected');
    } else {
      print(
          'EXAMPLE::ERROR Mosquitto client connection failed - disconnecting, state is ${client.connectionStatus.state}');
      client.disconnect();
//      exit(-1);
    }

    print('开始订阅 test/# subscription');

    /// Ok, lets try a subscription or two, note these may change/cease to exist on the broker
    const String topic = 'test/#'; // Wildcard topic
    client.subscribe(topic, MqttQos.atMostOnce);
//    const String topic1 = 'ebcon/#'; // Wildcard topic
//    client.subscribe(topic1, MqttQos.atMostOnce);
    print('订阅完成: test/# subscription');

    client.updates.listen((List<MqttReceivedMessage<MqttMessage>> c) {
      print('监听获取到的数据:${c.toString()}');
      final MqttPublishMessage recMess = c[0].payload;
      final String pt =
          MqttPublishPayload.bytesToStringAsString(recMess.payload.message);
      print(
          'EXAMPLE::Change notification:: topic is <${c[0].topic}>, payload is <-- $pt -->');
      print('');
    });
    
  }

**Comment by SunLongbri** [comment]
![image](https://user-images.githubusercontent.com/26838223/57277691-40dcc300-70d7-11e9-88af-abca2c460f2f.png)

**Comment by SunLongbri** [comment]
sorry , I have soved this problems ,but I also have other problem: I send a topic by chinese ,but I receive is other language .
![image](https://user-images.githubusercontent.com/26838223/57279165-e2b1df00-70da-11e9-8f79-d3c5c37de4b9.png)

**Comment by shamblett** [comment]
Not sure what you mean, the topic you have received is test/lol, this is not Chinese, the red underline above is the contents of the payload as a byte dump, it doesn't expect any formatting here, Chinese or otherwise, its up to you to decode the payload you recieve as you see fit. If your are expecting Chinese characters in your payload its up to you to decode it.

**Comment by SunLongbri** [comment]
I means : I publish a new topic '我终于接收到数据了'，but I receive data is : '  ç» äº æ ¥ æ ¶ å° äº ° æ',I should encoded by myself?

**Comment by shamblett** [comment]
Yes, your receive data is in the payload, only you know what your payload contains, the client can't possibly know what to do with every payload it can possibly receive, its up to you to interpret your payload as you see fit, the log just shows you as a byte dump what was received, not what it means to you.

**Comment by SunLongbri** [comment]
Thanks，I understand what should I do.
